<?php

declare(strict_types=1);

// This file is generated by tools/generate.php from resources/specs/core.json. Do not edit.

namespace GoSuccess\Bunny\Core\Model;

use GoSuccess\Bunny\Model\Cast;
use GoSuccess\Bunny\Model\ResponseModel;

/** Schema: BillingAffiliateDetailsModel */
final readonly class AffiliateDetails implements ResponseModel
{
    public function __construct(
        /** The amount of affiliate credits on the account */
        public float $affiliateBalance = 0.0,
        /** The affiliate URL for the currently authenticated user */
        public ?string $affiliateUrl = null,
        /** The bonus percentage given when claiming affiliate balance as bunny credits */
        public float $claimBonusPercentage = 0.0,
        /** The minimum amount required to request affiliate credits external payout */
        public float $minimumPayoutAmount = 0.0,
        /**
         * The constructed affiliate click history chart data
         *
         * @var array<array-key, int>
         */
        public array $affiliateClicksChart = [],
        /**
         * The constructed affiliate signup history chart data
         *
         * @var array<array-key, int>
         */
        public array $affiliateSignupsChart = [],
        /**
         * The constructed affiliate conversion history chart data
         *
         * @var array<array-key, int>
         */
        public array $affiliateConversionsChart = [],
    ) {}

    public static function fromArray(array $data): static
    {
        return new self(
            affiliateBalance: Cast::float($data['AffiliateBalance'] ?? null) ?? 0.0,
            affiliateUrl: Cast::string($data['AffiliateUrl'] ?? null),
            claimBonusPercentage: Cast::float($data['ClaimBonusPercentage'] ?? null) ?? 0.0,
            minimumPayoutAmount: Cast::float($data['MinimumPayoutAmount'] ?? null) ?? 0.0,
            affiliateClicksChart: Cast::mapOf($data['AffiliateClicksChart'] ?? null, Cast::int(...)),
            affiliateSignupsChart: Cast::mapOf($data['AffiliateSignupsChart'] ?? null, Cast::int(...)),
            affiliateConversionsChart: Cast::mapOf($data['AffiliateConversionsChart'] ?? null, Cast::int(...)),
        );
    }
}
