<?php

declare(strict_types=1);

// This file is generated by tools/generate.php from resources/specs/core.json. Do not edit.

namespace GoSuccess\Bunny\Core\Model;

use GoSuccess\Bunny\Model\Cast;
use GoSuccess\Bunny\Model\ResponseModel;

/** Schema: BillingSummaryItem */
final readonly class BillingSummaryItem implements ResponseModel
{
    public function __construct(
        /** The ID of the pull zone */
        public int $pullZoneId = 0,
        /** The total credit amount used in this month by the Pull Zone */
        public float $monthlyUsage = 0.0,
        /** The total monthly bandwidth used by the pull zone */
        public int $monthlyBandwidthUsed = 0,
    ) {}

    public static function fromArray(array $data): static
    {
        return new self(
            pullZoneId: Cast::int($data['PullZoneId'] ?? null) ?? 0,
            monthlyUsage: Cast::float($data['MonthlyUsage'] ?? null) ?? 0.0,
            monthlyBandwidthUsed: Cast::int($data['MonthlyBandwidthUsed'] ?? null) ?? 0,
        );
    }
}
