<?php

declare(strict_types=1);

// This file is generated by tools/generate.php from resources/specs/core.json. Do not edit.

namespace GoSuccess\Bunny\Core\Model;

use GoSuccess\Bunny\Model\Cast;
use GoSuccess\Bunny\Model\ResponseModel;

/** Schema: BillingSavedPaymentMethod */
final readonly class BillingSavedPaymentMethod implements ResponseModel
{
    public function __construct(
        public ?string $token = null,
        public ?string $imageUrl = null,
        public ?string $expirationDate = null,
        public ?string $lastFour = null,
        public ?string $email = null,
    ) {}

    public static function fromArray(array $data): static
    {
        return new self(
            token: Cast::string($data['Token'] ?? null),
            imageUrl: Cast::string($data['ImageUrl'] ?? null),
            expirationDate: Cast::string($data['ExpirationDate'] ?? null),
            lastFour: Cast::string($data['LastFour'] ?? null),
            email: Cast::string($data['Email'] ?? null),
        );
    }
}
