<?php

declare(strict_types=1);

// This file is generated by tools/generate.php from resources/specs/core.json. Do not edit.

namespace GoSuccess\Bunny\Core\Model;

use DateTimeImmutable;
use GoSuccess\Bunny\Core\Enum\BillingRecordType;
use GoSuccess\Bunny\Model\Cast;
use GoSuccess\Bunny\Model\ResponseModel;

/** Schema: BillingRecordModel */
final readonly class BillingRecord implements ResponseModel
{
    public function __construct(
        /** The ID of the billing record */
        public int $id = 0,
        /** The external ID of the payment */
        public ?string $paymentId = null,
        /** The amount linked to the record model */
        public float $amount = 0.0,
        /** The payer reference that sent the payment */
        public ?string $payer = null,
        /** The date and time when the billing record was created */
        public ?DateTimeImmutable $timestamp = null,
        /** The type of the billing record. */
        public ?BillingRecordType $type = null,
        /** Determines if an invoice is available */
        public bool $invoiceAvailable = false,
        /** The URL where the invoice or document can be downloaded. Null if this is not available. */
        public ?string $documentDownloadUrl = null,
        /**
         * The URL where the document with product usage breakdown can be downloaded. Null if this is not available.
         */
        public ?string $detailedDocumentDownloadUrl = null,
    ) {}

    public static function fromArray(array $data): static
    {
        return new self(
            id: Cast::int($data['Id'] ?? null) ?? 0,
            paymentId: Cast::string($data['PaymentId'] ?? null),
            amount: Cast::float($data['Amount'] ?? null) ?? 0.0,
            payer: Cast::string($data['Payer'] ?? null),
            timestamp: Cast::dateTime($data['Timestamp'] ?? null),
            type: Cast::intEnum(BillingRecordType::class, $data['Type'] ?? null),
            invoiceAvailable: Cast::bool($data['InvoiceAvailable'] ?? null) ?? false,
            documentDownloadUrl: Cast::string($data['DocumentDownloadUrl'] ?? null),
            detailedDocumentDownloadUrl: Cast::string($data['DetailedDocumentDownloadUrl'] ?? null),
        );
    }
}
