<?php

declare(strict_types=1);

// This file is generated by tools/generate.php from resources/specs/core.json. Do not edit.

namespace GoSuccess\Bunny\Core\Model;

use GoSuccess\Bunny\Model\Cast;
use GoSuccess\Bunny\Model\ResponseModel;

/** Schema: BillingModel */
final readonly class BillingDetails implements ResponseModel
{
    public function __construct(
        /** The current account balance */
        public float $balance = 0.0,
        /** The current account charges of the running month */
        public float $thisMonthCharges = 0.0,
        /** Last recharge amount balance */
        public float $lastRechargeBalance = 0.0,
        /** The current account balance plus available (unexpired) coupon credit */
        public float $availableBalance = 0.0,
        /** All available (unexpired) coupon money on the account */
        public float $couponBalance = 0.0,
        /** The total coupon credit used this month across all services */
        public float $monthlyCouponUsage = 0.0,
        /**
         * The list of billing records for this account
         *
         * @var list<BillingRecord>
         */
        public array $billingRecords = [],
        /**
         * The constructed billing history chart data
         *
         * @var array<array-key, int>
         */
        public array $billingHistoryChart = [],
        /** The total charges this month paid for European traffic */
        public float $monthlyChargesEUTraffic = 0.0,
        /** The total charges this month paid for North American traffic */
        public float $monthlyChargesUSTraffic = 0.0,
        /** The total charges this month paid for Asian and Oceanian traffic */
        public float $monthlyChargesASIATraffic = 0.0,
        /** The total charges this month paid for African traffic */
        public float $monthlyChargesAFTraffic = 0.0,
        /** The total charges this month paid for South American traffic */
        public float $monthlyChargesSATraffic = 0.0,
        /** The total charges this month paid for Edge Storage */
        public float $monthlyChargesStorage = 0.0,
        /** The total monthly charges for Bunny DNS */
        public float $monthlyChargesDNS = 0.0,
        /** The monthly charges caused by optimizer. */
        public float $monthlyChargesOptimizer = 0.0,
        /** The total monthly charges for Bunny Stream Transcribe */
        public float $monthlyChargesTranscribe = 0.0,
        /** The total monthly charges for Bunny Stream Premium Encoding */
        public float $monthlyChargesPremiumEncoding = 0.0,
        /** The monthly charges caused by extra pull zones. */
        public float $monthlyChargesExtraPullZones = 0.0,
        /** The monthly charges caused by extra storage zones. */
        public float $monthlyChargesExtraStorageZones = 0.0,
        /** The monthly charges caused by extra DNS zones. */
        public float $monthlyChargesExtraDnsZones = 0.0,
        /** The monthly charges caused by extra video libraries. */
        public float $monthlyChargesExtraVideoLibraries = 0.0,
        /** The total monthly charges for Bunny Edge Scripting */
        public float $monthlyChargesScripting = 0.0,
        /** The total monthly charges for Bunny Edge Scripting Requests */
        public float $monthlyChargesScriptingRequests = 0.0,
        /** The total monthly charges for Bunny Edge Scripting CPU usage */
        public float $monthlyChargesScriptingCpu = 0.0,
        /** The total monthly charges for DRM */
        public float $monthlyChargesDrm = 0.0,
        /** The total monthly charges for Magic Containers */
        public float $monthlyChargesMagicContainers = 0.0,
        /** The monthly charges and usage for Magic Containers CPU */
        public ?UsageBreakdown $monthlyMcCpu = null,
        /** The monthly charges and usage for Magic Containers Memory */
        public ?UsageBreakdown $monthlyMcMemory = null,
        /** The monthly charges and usage for Magic Containers Anycast IP */
        public ?UsageBreakdown $monthlyMcIp = null,
        /** The monthly charges and usage for Magic Containers Ingress Traffic */
        public ?UsageBreakdown $monthlyMcIngressTraffic = null,
        /** The monthly charges and usage for Magic Containers Egress Traffic */
        public ?UsageBreakdown $monthlyMcEgressTraffic = null,
        /** The monthly charges and usage for Magic Containers Persistent Volumes */
        public ?UsageBreakdown $monthlyMcVolumes = null,
        /** The total monthly charges for Shield */
        public float $monthlyChargesShield = 0.0,
        /** The total monthly charges for Taxes */
        public float $monthlyChargesTaxes = 0.0,
        /** The total monthly charges for WebSockets */
        public float $monthlyChargesWebSockets = 0.0,
        /** The total monthly charges for DB */
        public float $monthlyChargesDB = 0.0,
        /** The total monthly charges for Load Balancer */
        public float $monthlyChargesLoadBalancer = 0.0,
        /** The monthly charges and usage for BunnyDB row writes */
        public ?UsageBreakdown $monthlyDBWrites = null,
        /** The monthly charges and usage for BunnyDB row reads */
        public ?UsageBreakdown $monthlyDBReads = null,
        /** The monthly charges and usage for BunnyDB storage */
        public ?UsageBreakdown $monthlyDBStorage = null,
        /** The monthly charges and usage for BunnyDB replica storage */
        public ?UsageBreakdown $monthlyDBReplica = null,
        /** The total monthly charges for AI Gateway */
        public float $monthlyChargesAiGateway = 0.0,
        /** The monthly charges and usage for AI Gateway input tokens */
        public ?UsageBreakdown $monthlyAiGatewayInputTokens = null,
        /** The monthly charges and usage for AI Gateway output tokens */
        public ?UsageBreakdown $monthlyAiGatewayOutputTokens = null,
        /** The monthly charges and usage for AI Gateway cached tokens */
        public ?UsageBreakdown $monthlyAiGatewayCachedTokens = null,
        /** Total bandwidth used by the account during this month. */
        public int $monthlyBandwidthUsed = 0,
        /** Total number of Bunny DNS smart queries served this month. */
        public int $monthlyDnsSmartQueriesServed = 0,
        /** Total number of Bunny DNS normal queries served this month. */
        public int $monthlyDnsNormalQueriesServed = 0,
        /** Total minutes used for Bunny Stream Transcribe this month. */
        public int $monthlyTranscriptionMinutes = 0,
        /** Total billable minutes used for Bunny Stream Premium Encoding this month. */
        public int $monthlyPremiumEncodingBillableMinutes = 0,
        /** DRM (enterprise) licenses issued this month. */
        public int $monthlyDRMLicensesIssued = 0,
        /** Total number of edge script requests this month. */
        public int $monthlyScriptingRequests = 0,
        /** Total edge script CPU time (milliseconds) used this month. */
        public int $monthlyScriptingCpuTime = 0,
        /** Determines if billing is currently enabled for this user. */
        public bool $billingEnabled = false,
        /** Determines the minimum monthly commit of the user. */
        public float $minimumMonthlyCommit = 0.0,
        /** The VAT rate for the user's account. */
        public float $vatRate = 0.0,
        /** Next month VAT rate for the user's account. */
        public float $nextMonthVATRate = 0.0,
        /** If an automatic payment method is configured, this will contain the image url of the payment method */
        public ?string $automaticPaymentImageUrl = null,
        /**
         * If an automatic payment method is configured with a credit card, this will contain the name of the payment credit card
         */
        public ?string $automaticPaymentCardType = null,
        /**
         * If an automatic payment method is configured, this will contain the identifier of the payment method
         */
        public ?string $automaticPaymentIdentifier = null,
        /**
         * If an automatic payments are configured, this contains the payment amount that will be made during an automatic recharge
         */
        public float $automaticPaymentAmount = 0.0,
        /**
         * If an automatic payments are configured, this contains the account balance amount that will trigger an automatic recharge
         */
        public float $automaticRechargeTreshold = 0.0,
        /** Determines if automatic recharge is currently enabled. */
        public bool $automaticRechargeEnabled = false,
        /**
         * Determines the number of failed automatic recharges that the system made since the last successful payment.
         */
        public int $automaticPaymentFailureCount = 0,
        /**
         * Contains the list of saved payment methods on the user's account
         *
         * @var list<BillingSavedPaymentMethod>
         */
        public array $savedPaymentMethods = [],
        /** The account wide pricing discount for EU and US region. */
        public int $euusDiscount = 0,
        /** The account wide pricing discount for South America region. */
        public int $southAmericaDiscount = 0,
        /** The account wide pricing discount for Africa region. */
        public int $africaDiscount = 0,
        /** The account wide pricing discount for Asia & Oceania region. */
        public int $asiaOceaniaDiscount = 0,
        /** Optimizer monthly price per pull zone for this account (unless overridden on pull zone level). */
        public float $optimizerMonthlyPrice = 0.0,
        /** DRM (Enterprise) base monthly price per video library. */
        public float $drmBaseMonthlyPrice = 0.0,
        /** DRM (Enterprise) cost per license or default pricing tier applied if null. */
        public ?float $drmCostPerLicense = null,
    ) {}

    public static function fromArray(array $data): static
    {
        return new self(
            balance: Cast::float($data['Balance'] ?? null) ?? 0.0,
            thisMonthCharges: Cast::float($data['ThisMonthCharges'] ?? null) ?? 0.0,
            lastRechargeBalance: Cast::float($data['LastRechargeBalance'] ?? null) ?? 0.0,
            availableBalance: Cast::float($data['AvailableBalance'] ?? null) ?? 0.0,
            couponBalance: Cast::float($data['CouponBalance'] ?? null) ?? 0.0,
            monthlyCouponUsage: Cast::float($data['MonthlyCouponUsage'] ?? null) ?? 0.0,
            billingRecords: Cast::modelList(BillingRecord::class, $data['BillingRecords'] ?? null),
            billingHistoryChart: Cast::mapOf($data['BillingHistoryChart'] ?? null, Cast::int(...)),
            monthlyChargesEUTraffic: Cast::float($data['MonthlyChargesEUTraffic'] ?? null) ?? 0.0,
            monthlyChargesUSTraffic: Cast::float($data['MonthlyChargesUSTraffic'] ?? null) ?? 0.0,
            monthlyChargesASIATraffic: Cast::float($data['MonthlyChargesASIATraffic'] ?? null) ?? 0.0,
            monthlyChargesAFTraffic: Cast::float($data['MonthlyChargesAFTraffic'] ?? null) ?? 0.0,
            monthlyChargesSATraffic: Cast::float($data['MonthlyChargesSATraffic'] ?? null) ?? 0.0,
            monthlyChargesStorage: Cast::float($data['MonthlyChargesStorage'] ?? null) ?? 0.0,
            monthlyChargesDNS: Cast::float($data['MonthlyChargesDNS'] ?? null) ?? 0.0,
            monthlyChargesOptimizer: Cast::float($data['MonthlyChargesOptimizer'] ?? null) ?? 0.0,
            monthlyChargesTranscribe: Cast::float($data['MonthlyChargesTranscribe'] ?? null) ?? 0.0,
            monthlyChargesPremiumEncoding: Cast::float($data['MonthlyChargesPremiumEncoding'] ?? null) ?? 0.0,
            monthlyChargesExtraPullZones: Cast::float($data['MonthlyChargesExtraPullZones'] ?? null) ?? 0.0,
            monthlyChargesExtraStorageZones: Cast::float($data['MonthlyChargesExtraStorageZones'] ?? null) ?? 0.0,
            monthlyChargesExtraDnsZones: Cast::float($data['MonthlyChargesExtraDnsZones'] ?? null) ?? 0.0,
            monthlyChargesExtraVideoLibraries: Cast::float($data['MonthlyChargesExtraVideoLibraries'] ?? null) ?? 0.0,
            monthlyChargesScripting: Cast::float($data['MonthlyChargesScripting'] ?? null) ?? 0.0,
            monthlyChargesScriptingRequests: Cast::float($data['MonthlyChargesScriptingRequests'] ?? null) ?? 0.0,
            monthlyChargesScriptingCpu: Cast::float($data['MonthlyChargesScriptingCpu'] ?? null) ?? 0.0,
            monthlyChargesDrm: Cast::float($data['MonthlyChargesDrm'] ?? null) ?? 0.0,
            monthlyChargesMagicContainers: Cast::float($data['MonthlyChargesMagicContainers'] ?? null) ?? 0.0,
            monthlyMcCpu: Cast::model(UsageBreakdown::class, $data['MonthlyMcCpu'] ?? null),
            monthlyMcMemory: Cast::model(UsageBreakdown::class, $data['MonthlyMcMemory'] ?? null),
            monthlyMcIp: Cast::model(UsageBreakdown::class, $data['MonthlyMcIp'] ?? null),
            monthlyMcIngressTraffic: Cast::model(UsageBreakdown::class, $data['MonthlyMcIngressTraffic'] ?? null),
            monthlyMcEgressTraffic: Cast::model(UsageBreakdown::class, $data['MonthlyMcEgressTraffic'] ?? null),
            monthlyMcVolumes: Cast::model(UsageBreakdown::class, $data['MonthlyMcVolumes'] ?? null),
            monthlyChargesShield: Cast::float($data['MonthlyChargesShield'] ?? null) ?? 0.0,
            monthlyChargesTaxes: Cast::float($data['MonthlyChargesTaxes'] ?? null) ?? 0.0,
            monthlyChargesWebSockets: Cast::float($data['MonthlyChargesWebSockets'] ?? null) ?? 0.0,
            monthlyChargesDB: Cast::float($data['MonthlyChargesDB'] ?? null) ?? 0.0,
            monthlyChargesLoadBalancer: Cast::float($data['MonthlyChargesLoadBalancer'] ?? null) ?? 0.0,
            monthlyDBWrites: Cast::model(UsageBreakdown::class, $data['MonthlyDBWrites'] ?? null),
            monthlyDBReads: Cast::model(UsageBreakdown::class, $data['MonthlyDBReads'] ?? null),
            monthlyDBStorage: Cast::model(UsageBreakdown::class, $data['MonthlyDBStorage'] ?? null),
            monthlyDBReplica: Cast::model(UsageBreakdown::class, $data['MonthlyDBReplica'] ?? null),
            monthlyChargesAiGateway: Cast::float($data['MonthlyChargesAiGateway'] ?? null) ?? 0.0,
            monthlyAiGatewayInputTokens: Cast::model(UsageBreakdown::class, $data['MonthlyAiGatewayInputTokens'] ?? null),
            monthlyAiGatewayOutputTokens: Cast::model(UsageBreakdown::class, $data['MonthlyAiGatewayOutputTokens'] ?? null),
            monthlyAiGatewayCachedTokens: Cast::model(UsageBreakdown::class, $data['MonthlyAiGatewayCachedTokens'] ?? null),
            monthlyBandwidthUsed: Cast::int($data['MonthlyBandwidthUsed'] ?? null) ?? 0,
            monthlyDnsSmartQueriesServed: Cast::int($data['MonthlyDnsSmartQueriesServed'] ?? null) ?? 0,
            monthlyDnsNormalQueriesServed: Cast::int($data['MonthlyDnsNormalQueriesServed'] ?? null) ?? 0,
            monthlyTranscriptionMinutes: Cast::int($data['MonthlyTranscriptionMinutes'] ?? null) ?? 0,
            monthlyPremiumEncodingBillableMinutes: Cast::int($data['MonthlyPremiumEncodingBillableMinutes'] ?? null) ?? 0,
            monthlyDRMLicensesIssued: Cast::int($data['MonthlyDRMLicensesIssued'] ?? null) ?? 0,
            monthlyScriptingRequests: Cast::int($data['MonthlyScriptingRequests'] ?? null) ?? 0,
            monthlyScriptingCpuTime: Cast::int($data['MonthlyScriptingCpuTime'] ?? null) ?? 0,
            billingEnabled: Cast::bool($data['BillingEnabled'] ?? null) ?? false,
            minimumMonthlyCommit: Cast::float($data['MinimumMonthlyCommit'] ?? null) ?? 0.0,
            vatRate: Cast::float($data['VATRate'] ?? null) ?? 0.0,
            nextMonthVATRate: Cast::float($data['NextMonthVATRate'] ?? null) ?? 0.0,
            automaticPaymentImageUrl: Cast::string($data['AutomaticPaymentImageUrl'] ?? null),
            automaticPaymentCardType: Cast::string($data['AutomaticPaymentCardType'] ?? null),
            automaticPaymentIdentifier: Cast::string($data['AutomaticPaymentIdentifier'] ?? null),
            automaticPaymentAmount: Cast::float($data['AutomaticPaymentAmount'] ?? null) ?? 0.0,
            automaticRechargeTreshold: Cast::float($data['AutomaticRechargeTreshold'] ?? null) ?? 0.0,
            automaticRechargeEnabled: Cast::bool($data['AutomaticRechargeEnabled'] ?? null) ?? false,
            automaticPaymentFailureCount: Cast::int($data['AutomaticPaymentFailureCount'] ?? null) ?? 0,
            savedPaymentMethods: Cast::modelList(BillingSavedPaymentMethod::class, $data['SavedPaymentMethods'] ?? null),
            euusDiscount: Cast::int($data['EUUSDiscount'] ?? null) ?? 0,
            southAmericaDiscount: Cast::int($data['SouthAmericaDiscount'] ?? null) ?? 0,
            africaDiscount: Cast::int($data['AfricaDiscount'] ?? null) ?? 0,
            asiaOceaniaDiscount: Cast::int($data['AsiaOceaniaDiscount'] ?? null) ?? 0,
            optimizerMonthlyPrice: Cast::float($data['OptimizerMonthlyPrice'] ?? null) ?? 0.0,
            drmBaseMonthlyPrice: Cast::float($data['DrmBaseMonthlyPrice'] ?? null) ?? 0.0,
            drmCostPerLicense: Cast::float($data['DrmCostPerLicense'] ?? null),
        );
    }
}
