<?php

declare(strict_types=1);

// This file is generated by tools/generate.php from resources/specs/core.json. Do not edit.

namespace GoSuccess\Bunny\Core\Model;

use GoSuccess\Bunny\Model\Cast;
use GoSuccess\Bunny\Model\Json;
use GoSuccess\Bunny\Model\RequestModel;
use GoSuccess\Bunny\Model\ResponseModel;
use GoSuccess\Bunny\Model\Undefined;

/** Schema: BunnyAiImageBlueprintModel */
final readonly class BunnyAiImageBlueprint implements RequestModel, ResponseModel
{
    public ?string $name;

    /** @var array<array-key, string> */
    public array $properties;

    /**
     * Payload keys the caller provided; toArray() sends exactly these.
     *
     * @var array<string, true>
     */
    private array $provided;

    /** @param array<array-key, string>|Undefined $properties */
    public function __construct(
        string|Undefined|null $name = Undefined::Value,
        array|Undefined $properties = Undefined::Value,
    ) {
        $this->name = $name instanceof Undefined ? null : $name;
        $this->properties = $properties instanceof Undefined ? [] : $properties;
        $this->provided = array_filter([
            'Name' => !$name instanceof Undefined,
            'Properties' => !$properties instanceof Undefined,
        ]);
    }

    public static function fromArray(array $data): static
    {
        return new self(
            name: Cast::string($data['Name'] ?? null) ?? Undefined::Value,
            properties: Cast::mapOf($data['Properties'] ?? null, Cast::string(...)) ?: Undefined::Value,
        );
    }

    public function toArray(): array
    {
        $data = [];

        if (isset($this->provided['Name'])) {
            $data['Name'] = $this->name;
        }

        if (isset($this->provided['Properties'])) {
            $data['Properties'] = Json::map($this->properties);
        }

        return $data;
    }
}
