<?php

declare(strict_types=1);

// This file is generated by tools/generate.php from resources/specs/core.json. Do not edit.

namespace GoSuccess\Bunny\Core\Model;

use GoSuccess\Bunny\Core\Enum\DnsZoneDiscoveredRecordType;
use GoSuccess\Bunny\Model\Cast;
use GoSuccess\Bunny\Model\ResponseModel;

/** Schema: DnsZoneDiscoveredRecordModel */
final readonly class DiscoveredDnsRecord implements ResponseModel
{
    public function __construct(
        /** Record name relative to the zone. '@' represents apex. */
        public ?string $name = null,
        /**
         * 0 = A
         * 1 = AAAA
         * 2 = CNAME
         * 3 = TXT
         * 4 = MX
         * 8 = SRV
         * 9 = CAA
         * 10 = PTR
         * 12 = NS
         * 13 = Svcb
         * 14 = HTTPS
         * 15 = TLSA
         * 16 = SOA
         */
        public ?DnsZoneDiscoveredRecordType $type = null,
        public ?int $ttl = null,
        public ?string $value = null,
        public ?int $priority = null,
        public ?int $weight = null,
        public ?int $port = null,
        public bool $isProxied = false,
    ) {}

    public static function fromArray(array $data): static
    {
        return new self(
            name: Cast::string($data['Name'] ?? null),
            type: Cast::intEnum(DnsZoneDiscoveredRecordType::class, $data['Type'] ?? null),
            ttl: Cast::int($data['Ttl'] ?? null),
            value: Cast::string($data['Value'] ?? null),
            priority: Cast::int($data['Priority'] ?? null),
            weight: Cast::int($data['Weight'] ?? null),
            port: Cast::int($data['Port'] ?? null),
            isProxied: Cast::bool($data['IsProxied'] ?? null) ?? false,
        );
    }
}
