<?php

declare(strict_types=1);

// This file is generated by tools/generate.php from resources/specs/core.json. Do not edit.

namespace GoSuccess\Bunny\Core\Model;

use GoSuccess\Bunny\Core\Enum\DnsMonitoringType;
use GoSuccess\Bunny\Core\Enum\DnsRecordType;
use GoSuccess\Bunny\Core\Enum\DnsSmartRoutingType;
use GoSuccess\Bunny\Model\RequestModel;
use GoSuccess\Bunny\Model\Undefined;

/** Schema: AddDnsRecordModel */
final readonly class DnsRecordCreate implements RequestModel
{
    public function __construct(
        /**
         * 0 = A
         * 1 = AAAA
         * 2 = CNAME
         * 3 = TXT
         * 4 = MX
         * 5 = Redirect
         * 6 = Flatten
         * 7 = PullZone
         * 8 = SRV
         * 9 = CAA
         * 10 = PTR
         * 11 = Script
         * 12 = NS
         * 13 = SVCB
         * 14 = HTTPS
         * 15 = TLSA
         */
        public DnsRecordType|Undefined|null $type = Undefined::Value,
        public int|Undefined|null $ttl = Undefined::Value,
        public string|Undefined|null $value = Undefined::Value,
        public string|Undefined|null $name = Undefined::Value,
        public int|Undefined|null $weight = Undefined::Value,
        public int|Undefined|null $priority = Undefined::Value,
        public int|Undefined|null $flags = Undefined::Value,
        public string|Undefined|null $tag = Undefined::Value,
        public int|Undefined|null $port = Undefined::Value,
        public int|Undefined|null $pullZoneId = Undefined::Value,
        public int|Undefined|null $scriptId = Undefined::Value,
        public bool|Undefined|null $accelerated = Undefined::Value,
        /**
         * 0 = None
         * 1 = Ping
         * 2 = Http
         * 3 = Monitor
         */
        public DnsMonitoringType|Undefined|null $monitorType = Undefined::Value,
        public float|Undefined|null $geolocationLatitude = Undefined::Value,
        public float|Undefined|null $geolocationLongitude = Undefined::Value,
        public string|Undefined|null $latencyZone = Undefined::Value,
        /**
         * 0 = None
         * 1 = Latency
         * 2 = Geolocation
         */
        public DnsSmartRoutingType|Undefined|null $smartRoutingType = Undefined::Value,
        public bool|Undefined|null $disabled = Undefined::Value,
        /** @var list<DnsRecordEnvironmentVariable>|Undefined */
        public array|Undefined $enviromentalVariables = Undefined::Value,
        public string|Undefined|null $comment = Undefined::Value,
        public bool|Undefined|null $autoSslIssuance = Undefined::Value,
    ) {}

    public function toArray(): array
    {
        $data = [];

        if (!$this->type instanceof Undefined) {
            $data['Type'] = $this->type?->value;
        }

        if (!$this->ttl instanceof Undefined) {
            $data['Ttl'] = $this->ttl;
        }

        if (!$this->value instanceof Undefined) {
            $data['Value'] = $this->value;
        }

        if (!$this->name instanceof Undefined) {
            $data['Name'] = $this->name;
        }

        if (!$this->weight instanceof Undefined) {
            $data['Weight'] = $this->weight;
        }

        if (!$this->priority instanceof Undefined) {
            $data['Priority'] = $this->priority;
        }

        if (!$this->flags instanceof Undefined) {
            $data['Flags'] = $this->flags;
        }

        if (!$this->tag instanceof Undefined) {
            $data['Tag'] = $this->tag;
        }

        if (!$this->port instanceof Undefined) {
            $data['Port'] = $this->port;
        }

        if (!$this->pullZoneId instanceof Undefined) {
            $data['PullZoneId'] = $this->pullZoneId;
        }

        if (!$this->scriptId instanceof Undefined) {
            $data['ScriptId'] = $this->scriptId;
        }

        if (!$this->accelerated instanceof Undefined) {
            $data['Accelerated'] = $this->accelerated;
        }

        if (!$this->monitorType instanceof Undefined) {
            $data['MonitorType'] = $this->monitorType?->value;
        }

        if (!$this->geolocationLatitude instanceof Undefined) {
            $data['GeolocationLatitude'] = $this->geolocationLatitude;
        }

        if (!$this->geolocationLongitude instanceof Undefined) {
            $data['GeolocationLongitude'] = $this->geolocationLongitude;
        }

        if (!$this->latencyZone instanceof Undefined) {
            $data['LatencyZone'] = $this->latencyZone;
        }

        if (!$this->smartRoutingType instanceof Undefined) {
            $data['SmartRoutingType'] = $this->smartRoutingType?->value;
        }

        if (!$this->disabled instanceof Undefined) {
            $data['Disabled'] = $this->disabled;
        }

        if (!$this->enviromentalVariables instanceof Undefined) {
            $data['EnviromentalVariables'] = array_map(static fn(DnsRecordEnvironmentVariable $item): array => $item->toArray(), $this->enviromentalVariables);
        }

        if (!$this->comment instanceof Undefined) {
            $data['Comment'] = $this->comment;
        }

        if (!$this->autoSslIssuance instanceof Undefined) {
            $data['AutoSslIssuance'] = $this->autoSslIssuance;
        }

        return $data;
    }
}
