<?php

declare(strict_types=1);

// This file is generated by tools/generate.php from resources/specs/core.json. Do not edit.

namespace GoSuccess\Bunny\Core\Model;

use DateTimeImmutable;
use GoSuccess\Bunny\Core\Enum\LogAnonymizationType;
use GoSuccess\Bunny\Core\Enum\PrivateKeyType;
use GoSuccess\Bunny\Model\Cast;
use GoSuccess\Bunny\Model\ResponseModel;

/** Schema: DnsZoneModel */
final readonly class DnsZone implements ResponseModel
{
    public function __construct(
        public int $id = 0,
        public ?string $domain = null,
        /** @var list<DnsRecord> */
        public array $records = [],
        public ?DateTimeImmutable $dateModified = null,
        public ?DateTimeImmutable $dateCreated = null,
        public bool $nameserversDetected = false,
        public bool $customNameserversEnabled = false,
        public ?string $nameserver1 = null,
        public ?string $nameserver2 = null,
        public ?string $soaEmail = null,
        public ?DateTimeImmutable $nameserversNextCheck = null,
        public bool $loggingEnabled = false,
        /** Determines if the TLS 1 is enabled on the DNS Zone */
        public bool $loggingIPAnonymizationEnabled = false,
        /** Sets the log anonymization type for this zone */
        public ?LogAnonymizationType $logAnonymizationType = null,
        /** Determines if DNSSEC is enabled for this DNS Zone */
        public bool $dnsSecEnabled = false,
        /** The private key type to use for automatic certificates */
        public ?PrivateKeyType $certificateKeyType = null,
    ) {}

    public static function fromArray(array $data): static
    {
        return new self(
            id: Cast::int($data['Id'] ?? null) ?? 0,
            domain: Cast::string($data['Domain'] ?? null),
            records: Cast::modelList(DnsRecord::class, $data['Records'] ?? null),
            dateModified: Cast::dateTime($data['DateModified'] ?? null),
            dateCreated: Cast::dateTime($data['DateCreated'] ?? null),
            nameserversDetected: Cast::bool($data['NameserversDetected'] ?? null) ?? false,
            customNameserversEnabled: Cast::bool($data['CustomNameserversEnabled'] ?? null) ?? false,
            nameserver1: Cast::string($data['Nameserver1'] ?? null),
            nameserver2: Cast::string($data['Nameserver2'] ?? null),
            soaEmail: Cast::string($data['SoaEmail'] ?? null),
            nameserversNextCheck: Cast::dateTime($data['NameserversNextCheck'] ?? null),
            loggingEnabled: Cast::bool($data['LoggingEnabled'] ?? null) ?? false,
            loggingIPAnonymizationEnabled: Cast::bool($data['LoggingIPAnonymizationEnabled'] ?? null) ?? false,
            logAnonymizationType: Cast::intEnum(LogAnonymizationType::class, $data['LogAnonymizationType'] ?? null),
            dnsSecEnabled: Cast::bool($data['DnsSecEnabled'] ?? null) ?? false,
            certificateKeyType: Cast::intEnum(PrivateKeyType::class, $data['CertificateKeyType'] ?? null),
        );
    }
}
