<?php

declare(strict_types=1);

// This file is generated by tools/generate.php from resources/specs/core.json. Do not edit.

namespace GoSuccess\Bunny\Core\Model;

use GoSuccess\Bunny\Core\Enum\LogAnonymizationType;
use GoSuccess\Bunny\Core\Enum\PrivateKeyType;
use GoSuccess\Bunny\Model\RequestModel;
use GoSuccess\Bunny\Model\Undefined;

/** Schema: UpdateDnsZoneModel */
final readonly class DnsZoneUpdate implements RequestModel
{
    public function __construct(
        public bool|Undefined|null $customNameserversEnabled = Undefined::Value,
        public string|Undefined|null $nameserver1 = Undefined::Value,
        public string|Undefined|null $nameserver2 = Undefined::Value,
        public string|Undefined|null $soaEmail = Undefined::Value,
        public bool|Undefined|null $loggingEnabled = Undefined::Value,
        /** Gets the log anonymization type for this zone */
        public LogAnonymizationType|Undefined|null $logAnonymizationType = Undefined::Value,
        /** Sets the certificate private key type for wildcard certificates for this zone */
        public PrivateKeyType|Undefined|null $certificateKeyType = Undefined::Value,
        /** Determines if the log anonoymization should be enabled */
        public bool|Undefined|null $loggingIPAnonymizationEnabled = Undefined::Value,
    ) {}

    public function toArray(): array
    {
        $data = [];

        if (!$this->customNameserversEnabled instanceof Undefined) {
            $data['CustomNameserversEnabled'] = $this->customNameserversEnabled;
        }

        if (!$this->nameserver1 instanceof Undefined) {
            $data['Nameserver1'] = $this->nameserver1;
        }

        if (!$this->nameserver2 instanceof Undefined) {
            $data['Nameserver2'] = $this->nameserver2;
        }

        if (!$this->soaEmail instanceof Undefined) {
            $data['SoaEmail'] = $this->soaEmail;
        }

        if (!$this->loggingEnabled instanceof Undefined) {
            $data['LoggingEnabled'] = $this->loggingEnabled;
        }

        if (!$this->logAnonymizationType instanceof Undefined) {
            $data['LogAnonymizationType'] = $this->logAnonymizationType?->value;
        }

        if (!$this->certificateKeyType instanceof Undefined) {
            $data['CertificateKeyType'] = $this->certificateKeyType?->value;
        }

        if (!$this->loggingIPAnonymizationEnabled instanceof Undefined) {
            $data['LoggingIPAnonymizationEnabled'] = $this->loggingIPAnonymizationEnabled;
        }

        return $data;
    }
}
