<?php

declare(strict_types=1);

// This file is generated by tools/generate.php from resources/specs/core.json. Do not edit.

namespace GoSuccess\Bunny\Core\Model;

use GoSuccess\Bunny\Model\Cast;
use GoSuccess\Bunny\Model\ResponseModel;

/** Schema: DnsZoneStatisticsModel */
final readonly class DnsZoneStatistics implements ResponseModel
{
    public function __construct(
        public int $totalQueriesServed = 0,
        /** @var array<array-key, float> */
        public array $queriesServedChart = [],
        /** @var array<array-key, float> */
        public array $normalQueriesServedChart = [],
        /** @var array<array-key, float> */
        public array $smartQueriesServedChart = [],
        /** @var array<array-key, int> */
        public array $queriesByTypeChart = [],
    ) {}

    public static function fromArray(array $data): static
    {
        return new self(
            totalQueriesServed: Cast::int($data['TotalQueriesServed'] ?? null) ?? 0,
            queriesServedChart: Cast::mapOf($data['QueriesServedChart'] ?? null, Cast::float(...)),
            normalQueriesServedChart: Cast::mapOf($data['NormalQueriesServedChart'] ?? null, Cast::float(...)),
            smartQueriesServedChart: Cast::mapOf($data['SmartQueriesServedChart'] ?? null, Cast::float(...)),
            queriesByTypeChart: Cast::mapOf($data['QueriesByTypeChart'] ?? null, Cast::int(...)),
        );
    }
}
