<?php

declare(strict_types=1);

// This file is generated by tools/generate.php from resources/specs/core.json. Do not edit.

namespace GoSuccess\Bunny\Core\Model;

use GoSuccess\Bunny\Core\Enum\EdgeRuleActionType;
use GoSuccess\Bunny\Core\Enum\TriggerMatchingType;
use GoSuccess\Bunny\Model\Cast;
use GoSuccess\Bunny\Model\RequestModel;
use GoSuccess\Bunny\Model\ResponseModel;
use GoSuccess\Bunny\Model\Undefined;

/** Schema: EdgeRuleV2Model */
final readonly class EdgeRule implements RequestModel, ResponseModel
{
    /** The unique GUID of the edge rule */
    public ?string $guid;

    /** The action type of the edge rule. */
    public ?EdgeRuleActionType $actionType;

    /** The Action parameter 1. The value depends on other parameters of the edge rule. */
    public ?string $actionParameter1;

    /** The Action parameter 2. The value depends on other parameters of the edge rule. */
    public ?string $actionParameter2;

    /** The Action parameter 3. The value depends on other parameters of the edge rule. */
    public ?string $actionParameter3;

    /** @var list<EdgeRuleTrigger> */
    public array $triggers;

    /** @var list<EdgeRuleAction> */
    public array $extraActions;

    /** The trigger matching type. */
    public ?TriggerMatchingType $triggerMatchingType;

    /** The description of the edge rule */
    public ?string $description;

    /** Determines if the edge rule is currently enabled or not */
    public bool $enabled;

    /** The index of the edge rule in the list of execution priority */
    public int $orderIndex;

    /** Determines if the edge rule is read-only and cannot be modified or deleted */
    public bool $readOnly;

    /**
     * Payload keys the caller provided; toArray() sends exactly these.
     *
     * @var array<string, true>
     */
    private array $provided;

    /**
     * @param list<EdgeRuleTrigger>|Undefined $triggers
     * @param list<EdgeRuleAction>|Undefined $extraActions
     */
    public function __construct(
        string|Undefined|null $guid = Undefined::Value,
        EdgeRuleActionType|Undefined $actionType = Undefined::Value,
        string|Undefined|null $actionParameter1 = Undefined::Value,
        string|Undefined|null $actionParameter2 = Undefined::Value,
        string|Undefined|null $actionParameter3 = Undefined::Value,
        array|Undefined $triggers = Undefined::Value,
        array|Undefined $extraActions = Undefined::Value,
        TriggerMatchingType|Undefined $triggerMatchingType = Undefined::Value,
        string|Undefined|null $description = Undefined::Value,
        bool|Undefined $enabled = Undefined::Value,
        int|Undefined $orderIndex = Undefined::Value,
        bool|Undefined $readOnly = Undefined::Value,
    ) {
        $this->guid = $guid instanceof Undefined ? null : $guid;
        $this->actionType = $actionType instanceof Undefined ? null : $actionType;
        $this->actionParameter1 = $actionParameter1 instanceof Undefined ? null : $actionParameter1;
        $this->actionParameter2 = $actionParameter2 instanceof Undefined ? null : $actionParameter2;
        $this->actionParameter3 = $actionParameter3 instanceof Undefined ? null : $actionParameter3;
        $this->triggers = $triggers instanceof Undefined ? [] : $triggers;
        $this->extraActions = $extraActions instanceof Undefined ? [] : $extraActions;
        $this->triggerMatchingType = $triggerMatchingType instanceof Undefined ? null : $triggerMatchingType;
        $this->description = $description instanceof Undefined ? null : $description;
        $this->enabled = $enabled instanceof Undefined ? false : $enabled;
        $this->orderIndex = $orderIndex instanceof Undefined ? 0 : $orderIndex;
        $this->readOnly = $readOnly instanceof Undefined ? false : $readOnly;
        $this->provided = array_filter([
            'Guid' => !$guid instanceof Undefined,
            'ActionType' => !$actionType instanceof Undefined,
            'ActionParameter1' => !$actionParameter1 instanceof Undefined,
            'ActionParameter2' => !$actionParameter2 instanceof Undefined,
            'ActionParameter3' => !$actionParameter3 instanceof Undefined,
            'Triggers' => !$triggers instanceof Undefined,
            'ExtraActions' => !$extraActions instanceof Undefined,
            'TriggerMatchingType' => !$triggerMatchingType instanceof Undefined,
            'Description' => !$description instanceof Undefined,
            'Enabled' => !$enabled instanceof Undefined,
            'OrderIndex' => !$orderIndex instanceof Undefined,
            'ReadOnly' => !$readOnly instanceof Undefined,
        ]);
    }

    public static function fromArray(array $data): static
    {
        return new self(
            guid: Cast::string($data['Guid'] ?? null) ?? Undefined::Value,
            actionType: Cast::intEnum(EdgeRuleActionType::class, $data['ActionType'] ?? null) ?? Undefined::Value,
            actionParameter1: Cast::string($data['ActionParameter1'] ?? null) ?? Undefined::Value,
            actionParameter2: Cast::string($data['ActionParameter2'] ?? null) ?? Undefined::Value,
            actionParameter3: Cast::string($data['ActionParameter3'] ?? null) ?? Undefined::Value,
            triggers: Cast::modelList(EdgeRuleTrigger::class, $data['Triggers'] ?? null) ?: Undefined::Value,
            extraActions: Cast::modelList(EdgeRuleAction::class, $data['ExtraActions'] ?? null) ?: Undefined::Value,
            triggerMatchingType: Cast::intEnum(TriggerMatchingType::class, $data['TriggerMatchingType'] ?? null) ?? Undefined::Value,
            description: Cast::string($data['Description'] ?? null) ?? Undefined::Value,
            enabled: Cast::bool($data['Enabled'] ?? null) ?? Undefined::Value,
            orderIndex: Cast::int($data['OrderIndex'] ?? null) ?? Undefined::Value,
            readOnly: Cast::bool($data['ReadOnly'] ?? null) ?? Undefined::Value,
        );
    }

    public function toArray(): array
    {
        $data = [];

        if (isset($this->provided['Guid'])) {
            $data['Guid'] = $this->guid;
        }

        if (isset($this->provided['ActionType'])) {
            $data['ActionType'] = $this->actionType?->value;
        }

        if (isset($this->provided['ActionParameter1'])) {
            $data['ActionParameter1'] = $this->actionParameter1;
        }

        if (isset($this->provided['ActionParameter2'])) {
            $data['ActionParameter2'] = $this->actionParameter2;
        }

        if (isset($this->provided['ActionParameter3'])) {
            $data['ActionParameter3'] = $this->actionParameter3;
        }

        if (isset($this->provided['Triggers'])) {
            $data['Triggers'] = array_map(static fn(EdgeRuleTrigger $item): array => $item->toArray(), $this->triggers);
        }

        if (isset($this->provided['ExtraActions'])) {
            $data['ExtraActions'] = array_map(static fn(EdgeRuleAction $item): array => $item->toArray(), $this->extraActions);
        }

        if (isset($this->provided['TriggerMatchingType'])) {
            $data['TriggerMatchingType'] = $this->triggerMatchingType?->value;
        }

        if (isset($this->provided['Description'])) {
            $data['Description'] = $this->description;
        }

        if (isset($this->provided['Enabled'])) {
            $data['Enabled'] = $this->enabled;
        }

        if (isset($this->provided['OrderIndex'])) {
            $data['OrderIndex'] = $this->orderIndex;
        }

        if (isset($this->provided['ReadOnly'])) {
            $data['ReadOnly'] = $this->readOnly;
        }

        return $data;
    }
}
