<?php

declare(strict_types=1);

// This file is generated by tools/generate.php from resources/specs/core.json. Do not edit.

namespace GoSuccess\Bunny\Core\Model;

use GoSuccess\Bunny\Model\Cast;
use GoSuccess\Bunny\Model\ResponseModel;

/** Schema: GeoDnsLocationModel */
final readonly class GeoDnsLocation implements ResponseModel
{
    public function __construct(
        /** The ISO country code of the location */
        public ?string $countryCode = null,
        /** The name of the country of the location */
        public ?string $country = null,
        /** The ASN of the IP organization */
        public int $asn = 0,
        /** The mame of the organization that owns the IP */
        public ?string $organizationName = null,
        /** The name of the city of the location */
        public ?string $city = null,
    ) {}

    public static function fromArray(array $data): static
    {
        return new self(
            countryCode: Cast::string($data['CountryCode'] ?? null),
            country: Cast::string($data['Country'] ?? null),
            asn: Cast::int($data['ASN'] ?? null) ?? 0,
            organizationName: Cast::string($data['OrganizationName'] ?? null),
            city: Cast::string($data['City'] ?? null),
        );
    }
}
