<?php

declare(strict_types=1);

// This file is generated by tools/generate.php from resources/specs/core.json. Do not edit.

namespace GoSuccess\Bunny\Core\Model;

use GoSuccess\Bunny\Core\Enum\WidevineMinClientSecurityLevel;
use GoSuccess\Bunny\Model\RequestModel;
use GoSuccess\Bunny\Model\Undefined;

/** Schema: GoogleWidevineDrmUpdateModel */
final readonly class GoogleWidevineDrmUpdate implements RequestModel
{
    public function __construct(
        /** (Optional) Enables or disables Google Widevine Enterprise DRM */
        public bool|Undefined|null $enabled = Undefined::Value,
        /** (Optional) Only allow audio and SD access to Widevine L3 clients */
        public bool|Undefined|null $sdOnlyForL3 = Undefined::Value,
        /** (Optional) Minimum Client Security Level (1 being most secure, 3 least secure and is default) */
        public WidevineMinClientSecurityLevel|Undefined|null $minClientSecurityLevel = Undefined::Value,
    ) {}

    public function toArray(): array
    {
        $data = [];

        if (!$this->enabled instanceof Undefined) {
            $data['Enabled'] = $this->enabled;
        }

        if (!$this->sdOnlyForL3 instanceof Undefined) {
            $data['SdOnlyForL3'] = $this->sdOnlyForL3;
        }

        if (!$this->minClientSecurityLevel instanceof Undefined) {
            $data['MinClientSecurityLevel'] = $this->minClientSecurityLevel?->value;
        }

        return $data;
    }
}
