<?php

declare(strict_types=1);

// This file is generated by tools/generate.php from resources/specs/core.json. Do not edit.

namespace GoSuccess\Bunny\Core\Model;

use GoSuccess\Bunny\Core\Enum\CertificateProvisionType;
use GoSuccess\Bunny\Core\Enum\PrivateKeyType;
use GoSuccess\Bunny\Model\Cast;
use GoSuccess\Bunny\Model\ResponseModel;

/** Schema: HostnameModel */
final readonly class Hostname implements ResponseModel
{
    public function __construct(
        /** The unique ID of the hostname */
        public int $id = 0,
        /** The hostname value for the domain name */
        public ?string $value = null,
        /** Determines if the Force SSL feature is enabled */
        public bool $forceSSL = false,
        /** Determines if this is a system hostname controlled by bunny.net */
        public bool $isSystemHostname = false,
        /** Determines if this is a managed hostname controlled by bunny.net */
        public bool $isManagedHostname = false,
        /** Determines if the hostname has an SSL certificate configured */
        public bool $hasCertificate = false,
        /** Contains the Base64Url encoded certificate for the hostname */
        public ?string $certificate = null,
        /** Contains the Base64Url encoded certificate key for the hostname */
        public ?string $certificateKey = null,
        /** The private key type to use for automatic certificates */
        public ?PrivateKeyType $certificateKeyType = null,
        /** The provisioned certificate type */
        public ?CertificateProvisionType $certificateProvisionType = null,
    ) {}

    public static function fromArray(array $data): static
    {
        return new self(
            id: Cast::int($data['Id'] ?? null) ?? 0,
            value: Cast::string($data['Value'] ?? null),
            forceSSL: Cast::bool($data['ForceSSL'] ?? null) ?? false,
            isSystemHostname: Cast::bool($data['IsSystemHostname'] ?? null) ?? false,
            isManagedHostname: Cast::bool($data['IsManagedHostname'] ?? null) ?? false,
            hasCertificate: Cast::bool($data['HasCertificate'] ?? null) ?? false,
            certificate: Cast::string($data['Certificate'] ?? null),
            certificateKey: Cast::string($data['CertificateKey'] ?? null),
            certificateKeyType: Cast::intEnum(PrivateKeyType::class, $data['CertificateKeyType'] ?? null),
            certificateProvisionType: Cast::intEnum(CertificateProvisionType::class, $data['CertificateProvisionType'] ?? null),
        );
    }
}
