<?php

declare(strict_types=1);

// This file is generated by tools/generate.php from resources/specs/core.json. Do not edit.

namespace GoSuccess\Bunny\Core\Model;

use GoSuccess\Bunny\Model\Cast;
use GoSuccess\Bunny\Model\ResponseModel;

/** Schema: LoadBalancerOriginRequestsSeriesModel */
final readonly class LoadBalancerOriginRequestsSeries implements ResponseModel
{
    public function __construct(
        public int $originId = 0,
        public ?string $originName = null,
        /** @var array<array-key, float> */
        public array $values = [],
    ) {}

    public static function fromArray(array $data): static
    {
        return new self(
            originId: Cast::int($data['OriginId'] ?? null) ?? 0,
            originName: Cast::string($data['OriginName'] ?? null),
            values: Cast::mapOf($data['Values'] ?? null, Cast::float(...)),
        );
    }
}
