<?php

declare(strict_types=1);

// This file is generated by tools/generate.php from resources/specs/core.json. Do not edit.

namespace GoSuccess\Bunny\Core\Model;

use GoSuccess\Bunny\Model\Cast;
use GoSuccess\Bunny\Model\ResponseModel;

/** Schema: LoadBalancerStatisticsModel */
final readonly class LoadBalancerStatistics implements ResponseModel
{
    public function __construct(
        public ?LoadBalancerStatisticsSummary $summary = null,
        /** @var list<LoadBalancerOriginRequestsSeries> */
        public array $requestsByOrigin = [],
        /** @var list<LoadBalancerOriginGroupRequestsSeries> */
        public array $requestsByOriginGroup = [],
        /** @var list<LoadBalancerOriginRequestsSeries> */
        public array $trafficByOrigin = [],
        /** @var list<LoadBalancerOriginLatencySeries> */
        public array $originLatency = [],
        /** @var list<LoadBalancerOriginFailuresSeries> */
        public array $originFailures = [],
    ) {}

    public static function fromArray(array $data): static
    {
        return new self(
            summary: Cast::model(LoadBalancerStatisticsSummary::class, $data['Summary'] ?? null),
            requestsByOrigin: Cast::modelList(LoadBalancerOriginRequestsSeries::class, $data['RequestsByOrigin'] ?? null),
            requestsByOriginGroup: Cast::modelList(LoadBalancerOriginGroupRequestsSeries::class, $data['RequestsByOriginGroup'] ?? null),
            trafficByOrigin: Cast::modelList(LoadBalancerOriginRequestsSeries::class, $data['TrafficByOrigin'] ?? null),
            originLatency: Cast::modelList(LoadBalancerOriginLatencySeries::class, $data['OriginLatency'] ?? null),
            originFailures: Cast::modelList(LoadBalancerOriginFailuresSeries::class, $data['OriginFailures'] ?? null),
        );
    }
}
