<?php

declare(strict_types=1);

// This file is generated by tools/generate.php from resources/specs/core.json. Do not edit.

namespace GoSuccess\Bunny\Core\Model;

use GoSuccess\Bunny\Model\Cast;
use GoSuccess\Bunny\Model\ResponseModel;

/** Schema: LoadBalancerAccountSummaryModel */
final readonly class LoadBalancerAccountSummary implements ResponseModel
{
    public function __construct(
        public int $loadBalancerId = 0,
        public float $totalRequests = 0.0,
        public float $totalTraffic = 0.0,
        public int $attachedPullZoneCount = 0,
    ) {}

    public static function fromArray(array $data): static
    {
        return new self(
            loadBalancerId: Cast::int($data['LoadBalancerId'] ?? null) ?? 0,
            totalRequests: Cast::float($data['TotalRequests'] ?? null) ?? 0.0,
            totalTraffic: Cast::float($data['TotalTraffic'] ?? null) ?? 0.0,
            attachedPullZoneCount: Cast::int($data['AttachedPullZoneCount'] ?? null) ?? 0,
        );
    }
}
