<?php

declare(strict_types=1);

// This file is generated by tools/generate.php from resources/specs/core.json. Do not edit.

namespace GoSuccess\Bunny\Core\Model;

use GoSuccess\Bunny\Model\Cast;
use GoSuccess\Bunny\Model\ResponseModel;

/** Schema: LoadBalancerPricingTierModel */
final readonly class LoadBalancerPricingTier implements ResponseModel
{
    public function __construct(
        public int $thresholdFromMillions = 0,
        public ?int $thresholdToMillions = null,
        public float $pricePerMillion = 0.0,
    ) {}

    public static function fromArray(array $data): static
    {
        return new self(
            thresholdFromMillions: Cast::int($data['ThresholdFromMillions'] ?? null) ?? 0,
            thresholdToMillions: Cast::int($data['ThresholdToMillions'] ?? null),
            pricePerMillion: Cast::float($data['PricePerMillion'] ?? null) ?? 0.0,
        );
    }
}
