<?php

declare(strict_types=1);

// This file is generated by tools/generate.php from resources/specs/core.json. Do not edit.

namespace GoSuccess\Bunny\Core\Model;

use GoSuccess\Bunny\Model\Cast;
use GoSuccess\Bunny\Model\ResponseModel;

/** Schema: OriginShieldConcurrencyStatisticsModel */
final readonly class OriginShieldConcurrencyStatistics implements ResponseModel
{
    public function __construct(
        /**
         * The constructed chart of origin shield concurrent requests
         *
         * @var array<array-key, int>
         */
        public array $concurrentRequestsChart = [],
        /**
         * The constructed chart of origin shield requests chart
         *
         * @var array<array-key, int>
         */
        public array $queuedRequestsChart = [],
    ) {}

    public static function fromArray(array $data): static
    {
        return new self(
            concurrentRequestsChart: Cast::mapOf($data['ConcurrentRequestsChart'] ?? null, Cast::int(...)),
            queuedRequestsChart: Cast::mapOf($data['QueuedRequestsChart'] ?? null, Cast::int(...)),
        );
    }
}
