<?php

declare(strict_types=1);

// This file is generated by tools/generate.php from resources/specs/core.json. Do not edit.

namespace GoSuccess\Bunny\Core\Model;

use DateTimeImmutable;
use GoSuccess\Bunny\Model\Cast;
use GoSuccess\Bunny\Model\ResponseModel;

/** Schema: PaymentRequestModel */
final readonly class PaymentRequest implements ResponseModel
{
    public function __construct(
        public int $id = 0,
        public float $amount = 0.0,
        public ?DateTimeImmutable $dateGenerated = null,
        public ?DateTimeImmutable $dateDue = null,
        public ?string $description = null,
        public bool $paid = false,
        public ?DateTimeImmutable $datePaid = null,
        public ?int $billingInvoiceId = null,
        public ?string $billingInvoiceDownloadLink = null,
        public ?string $bankTransferReference = null,
        public float $taxRate = 0.0,
        public float $taxedAmount = 0.0,
    ) {}

    public static function fromArray(array $data): static
    {
        return new self(
            id: Cast::int($data['Id'] ?? null) ?? 0,
            amount: Cast::float($data['Amount'] ?? null) ?? 0.0,
            dateGenerated: Cast::dateTime($data['DateGenerated'] ?? null),
            dateDue: Cast::dateTime($data['DateDue'] ?? null),
            description: Cast::string($data['Description'] ?? null),
            paid: Cast::bool($data['Paid'] ?? null) ?? false,
            datePaid: Cast::dateTime($data['DatePaid'] ?? null),
            billingInvoiceId: Cast::int($data['BillingInvoiceId'] ?? null),
            billingInvoiceDownloadLink: Cast::string($data['BillingInvoiceDownloadLink'] ?? null),
            bankTransferReference: Cast::string($data['BankTransferReference'] ?? null),
            taxRate: Cast::float($data['TaxRate'] ?? null) ?? 0.0,
            taxedAmount: Cast::float($data['TaxedAmount'] ?? null) ?? 0.0,
        );
    }
}
