<?php

declare(strict_types=1);

// This file is generated by tools/generate.php from resources/specs/core.json. Do not edit.

namespace GoSuccess\Bunny\Core\Model;

use GoSuccess\Bunny\Core\Enum\AppliedPricingType;
use GoSuccess\Bunny\Model\Cast;
use GoSuccess\Bunny\Model\ResponseModel;

/** Schema: PriceEstimationModel */
final readonly class PriceEstimation implements ResponseModel
{
    public function __construct(
        /**
         * 0 = ListPrice
         * 1 = UserOverride
         * 2 = ResourceOverride
         */
        public ?AppliedPricingType $pricingType = null,
        public float $pricePerUnit = 0.0,
        public ?string $unitDescription = null,
        public ?float $estimatedCost = null,
        /** @var list<PriceEstimationBreakdownLine> */
        public array $breakdown = [],
    ) {}

    public static function fromArray(array $data): static
    {
        return new self(
            pricingType: Cast::intEnum(AppliedPricingType::class, $data['PricingType'] ?? null),
            pricePerUnit: Cast::float($data['PricePerUnit'] ?? null) ?? 0.0,
            unitDescription: Cast::string($data['UnitDescription'] ?? null),
            estimatedCost: Cast::float($data['EstimatedCost'] ?? null),
            breakdown: Cast::modelList(PriceEstimationBreakdownLine::class, $data['Breakdown'] ?? null),
        );
    }
}
