<?php

declare(strict_types=1);

// This file is generated by tools/generate.php from resources/specs/core.json. Do not edit.

namespace GoSuccess\Bunny\Core\Model;

use GoSuccess\Bunny\Model\Cast;
use GoSuccess\Bunny\Model\ResponseModel;

/** Schema: PriceEstimationBreakdownLine */
final readonly class PriceEstimationBreakdownLine implements ResponseModel
{
    public function __construct(
        public ?string $description = null,
        public int $units = 0,
        public float $pricePerUnit = 0.0,
        public float $cost = 0.0,
    ) {}

    public static function fromArray(array $data): static
    {
        return new self(
            description: Cast::string($data['Description'] ?? null),
            units: Cast::int($data['Units'] ?? null) ?? 0,
            pricePerUnit: Cast::float($data['PricePerUnit'] ?? null) ?? 0.0,
            cost: Cast::float($data['Cost'] ?? null) ?? 0.0,
        );
    }
}
