<?php

declare(strict_types=1);

// This file is generated by tools/generate.php from resources/specs/core.json. Do not edit.

namespace GoSuccess\Bunny\Core\Model;

use GoSuccess\Bunny\Core\Enum\ExecutionPhase;
use GoSuccess\Bunny\Core\Enum\IpFamilyPolicy;
use GoSuccess\Bunny\Core\Enum\LogAnonymizationType;
use GoSuccess\Bunny\Core\Enum\OptimizerHtmlToMarkdownType;
use GoSuccess\Bunny\Core\Enum\OptimizerWatermarkPosition;
use GoSuccess\Bunny\Core\Enum\PermaCacheType;
use GoSuccess\Bunny\Core\Enum\PreloadingScreenTheme;
use GoSuccess\Bunny\Core\Enum\PullZoneLogFormat;
use GoSuccess\Bunny\Core\Enum\PullZoneLogForwarderProtocolType;
use GoSuccess\Bunny\Core\Enum\PullZoneOriginType;
use GoSuccess\Bunny\Core\Enum\PullZoneType;
use GoSuccess\Bunny\Core\Enum\ShieldDDosProtectionType;
use GoSuccess\Bunny\Core\Enum\StickySessionType;
use GoSuccess\Bunny\Core\Enum\TlsSecurityLevelType;
use GoSuccess\Bunny\Model\RequestModel;
use GoSuccess\Bunny\Model\Undefined;

/** Schema: PullZoneSettingsModel */
final readonly class PullZoneUpdate implements RequestModel
{
    public function __construct(
        /** Sets the origin URL of the Pull Zone */
        public string|Undefined|null $originUrl = Undefined::Value,
        /**
         * Sets the list of referrer hostnames that are allowed to access the pull zone. Requests containing the header Referer: hostname that is not on the list will be rejected. If empty, all the referrers are allowed
         *
         * @var list<string>|Undefined
         */
        public array|Undefined $allowedReferrers = Undefined::Value,
        /**
         * Sets the list of referrer hostnames that are blocked from accessing the pull zone.
         *
         * @var list<string>|Undefined
         */
        public array|Undefined $blockedReferrers = Undefined::Value,
        public bool|Undefined|null $blockNoneReferrer = Undefined::Value,
        /**
         * Sets the list of IPs that are blocked from accessing the pull zone. Requests coming from the following IPs will be rejected. If empty, all the IPs will be allowed
         *
         * @var list<string>|Undefined
         */
        public array|Undefined $blockedIps = Undefined::Value,
        /** Determines if the delivery from the North America region should be enabled for this pull zone */
        public bool|Undefined|null $enableGeoZoneUS = Undefined::Value,
        /** Determines if the delivery from the Europe region should be enabled for this pull zone */
        public bool|Undefined|null $enableGeoZoneEU = Undefined::Value,
        /** Determines if the delivery from the Asia / Oceania regions should be enabled for this pull zone */
        public bool|Undefined|null $enableGeoZoneASIA = Undefined::Value,
        /** Determines if the delivery from the South America region should be enabled for this pull zone */
        public bool|Undefined|null $enableGeoZoneSA = Undefined::Value,
        /** Determines if the delivery from the Africa region should be enabled for this pull zone */
        public bool|Undefined|null $enableGeoZoneAF = Undefined::Value,
        /**
         * Address-family policy: 0=IPv4Only, 1=DualStack (default, best latency and compatibility), 2=DualStackPreferIPv6, 3=IPv6Only.
         */
        public IpFamilyPolicy|Undefined|null $ipFamilyPolicy = Undefined::Value,
        /** Determines if the zone should block requests to the root of the zone. */
        public bool|Undefined|null $blockRootPathAccess = Undefined::Value,
        /** Determines if the POST requests to this zone should be rejected. */
        public bool|Undefined|null $blockPostRequests = Undefined::Value,
        /** Determines if the query string ordering should be enabled. */
        public bool|Undefined|null $enableQueryStringOrdering = Undefined::Value,
        /** Determines if the WebP Vary feature should be enabled. */
        public bool|Undefined|null $enableWebpVary = Undefined::Value,
        /** Determines if the AVIF Vary feature should be enabled. */
        public bool|Undefined|null $enableAvifVary = Undefined::Value,
        /** Determines if the Mobile Vary feature is enabled. */
        public bool|Undefined|null $enableMobileVary = Undefined::Value,
        /** Determines if the Country Code Vary feature should be enabled. */
        public bool|Undefined|null $enableCountryCodeVary = Undefined::Value,
        /** Determines if the Country State Code Vary feature should be enabled. */
        public bool|Undefined|null $enableCountryStateCodeVary = Undefined::Value,
        /** Determines if the Hostname Vary feature should be enabled. */
        public bool|Undefined|null $enableHostnameVary = Undefined::Value,
        /** Determines if cache slicing (Optimize for video) should be enabled for this zone */
        public bool|Undefined|null $enableCacheSlice = Undefined::Value,
        /** Determines if the zone token authentication security should be enabled */
        public bool|Undefined|null $zoneSecurityEnabled = Undefined::Value,
        /** Determines if the token authentication IP validation should be enabled */
        public bool|Undefined|null $zoneSecurityIncludeHashRemoteIP = Undefined::Value,
        /**
         * Determines if the Pull Zone should ignore query strings when serving cached objects (Vary by Query String)
         */
        public bool|Undefined|null $ignoreQueryStrings = Undefined::Value,
        /** Sets the monthly limit of bandwidth in bytes that the pullzone is allowed to use */
        public int|Undefined|null $monthlyBandwidthLimit = Undefined::Value,
        /**
         * Sets the list of extensions that will return the CORS headers
         *
         * @var list<string>|Undefined
         */
        public array|Undefined $accessControlOriginHeaderExtensions = Undefined::Value,
        /** Determines if CORS headers should be enabled */
        public bool|Undefined|null $enableAccessControlOriginHeader = Undefined::Value,
        /** Determines if the Pull Zone should automatically remove cookies from the responses */
        public bool|Undefined|null $disableCookies = Undefined::Value,
        /**
         * Sets the list of two letter Alpha2 country codes that will be redirected to the cheapest possible region
         *
         * @var list<string>|Undefined
         */
        public array|Undefined $budgetRedirectedCountries = Undefined::Value,
        /**
         * Sets the list of two letter Alpha2 country codes that will be blocked from accessing the zone
         *
         * @var list<string>|Undefined
         */
        public array|Undefined $blockedCountries = Undefined::Value,
        /** Sets the cache control override setting for this zone */
        public int|Undefined|null $cacheControlMaxAgeOverride = Undefined::Value,
        /** Sets the browser cache control override setting for this zone */
        public int|Undefined|null $cacheControlPublicMaxAgeOverride = Undefined::Value,
        /** (Deprecated) Sets the browser cache control override setting for this zone */
        public int|Undefined|null $cacheControlBrowserMaxAgeOverride = Undefined::Value,
        /** Determines if the zone should forward the requested host header to the origin */
        public bool|Undefined|null $addHostHeader = Undefined::Value,
        /** Determines if the canonical header should be added by this zone */
        public bool|Undefined|null $addCanonicalHeader = Undefined::Value,
        /** Determines if the logging should be enabled for this zone */
        public bool|Undefined|null $enableLogging = Undefined::Value,
        /** Determines if the log anonoymization should be enabled */
        public bool|Undefined|null $loggingIPAnonymizationEnabled = Undefined::Value,
        /** The ID of the storage zone that should be used as the Perma-Cache */
        public int|Undefined|null $permaCacheStorageZoneId = Undefined::Value,
        /** Determines Perma-Cache behavior */
        public PermaCacheType|Undefined|null $permaCacheType = Undefined::Value,
        /** Determines if the AWS signing should be enabled or not */
        public bool|Undefined|null $awsSigningEnabled = Undefined::Value,
        /** Sets the AWS signing key */
        public string|Undefined|null $awsSigningKey = Undefined::Value,
        /** Sets the AWS signing region name */
        public string|Undefined|null $awsSigningRegionName = Undefined::Value,
        /** Sets the AWS signing secret key */
        public string|Undefined|null $awsSigningSecret = Undefined::Value,
        /** Determines if the origin shield should be enabled */
        public bool|Undefined|null $enableOriginShield = Undefined::Value,
        /** Determines the zone code where the origin shield should be set up */
        public string|Undefined|null $originShieldZoneCode = Undefined::Value,
        /** Determines if the TLS 1 should be enabled on this zone */
        public bool|Undefined|null $enableTLS1 = Undefined::Value,
        /** Determines if the TLS 1.1 should be enabled on this zone */
        public bool|Undefined|null $enableTLS11 = Undefined::Value,
        /** The minimum TLS security level enforced on this zone (Legacy = 0, Compatible = 1, ModernOnly = 2) */
        public TlsSecurityLevelType|Undefined|null $tlsSecurityLevel = Undefined::Value,
        /** Determines if the cache error responses should be enabled on the zone */
        public bool|Undefined|null $cacheErrorResponses = Undefined::Value,
        /** Determines if the SSL certificate should be verified when connecting to the origin */
        public bool|Undefined|null $verifyOriginSSL = Undefined::Value,
        /** Sets the log forwarding token for the zone */
        public bool|Undefined|null $logForwardingEnabled = Undefined::Value,
        /** Sets the log forwarding destination hostname for the zone */
        public string|Undefined|null $logForwardingHostname = Undefined::Value,
        /** Sets the log forwarding port for the zone */
        public int|Undefined|null $logForwardingPort = Undefined::Value,
        /** Sets the log forwarding token for the zone */
        public string|Undefined|null $logForwardingToken = Undefined::Value,
        /** Sets the log forwarding protocol type */
        public PullZoneLogForwarderProtocolType|Undefined|null $logForwardingProtocol = Undefined::Value,
        /** Determines if the logging permanent storage should be enabled */
        public bool|Undefined|null $loggingSaveToStorage = Undefined::Value,
        /** Sets the Storage Zone id that should contain the logs from this Pull Zone */
        public int|Undefined|null $loggingStorageZoneId = Undefined::Value,
        /** Determines if the zone should follow redirects return by the oprigin and cache the response */
        public bool|Undefined|null $followRedirects = Undefined::Value,
        /**
         * Determines the maximum number of connections per IP that will be allowed to connect to this Pull Zone
         */
        public int|Undefined|null $connectionLimitPerIPCount = Undefined::Value,
        /**
         * Determines the maximum number of requests per second that will be allowed to connect to this Pull Zone
         */
        public int|Undefined|null $requestLimit = Undefined::Value,
        /** Determines the amount of traffic transferred before the client is limited */
        public float|Undefined|null $limitRateAfter = Undefined::Value,
        /** Determines the maximum number of requests per second coming from a single IP before it is blocked. */
        public int|Undefined|null $limitRatePerSecond = Undefined::Value,
        /** Determines the maximum burst requests before an IP is blocked */
        public int|Undefined|null $burstSize = Undefined::Value,
        /** Determines if custom error page code should be enabled. */
        public bool|Undefined|null $errorPageEnableCustomCode = Undefined::Value,
        /** Contains the custom error page code that will be returned */
        public string|Undefined|null $errorPageCustomCode = Undefined::Value,
        /** Determines if the statuspage widget should be displayed on the error pages */
        public bool|Undefined|null $errorPageEnableStatuspageWidget = Undefined::Value,
        /** The statuspage code that will be used to build the status widget */
        public string|Undefined|null $errorPageStatuspageCode = Undefined::Value,
        /** Determines if the error pages should be whitelabel or not */
        public bool|Undefined|null $errorPageWhitelabel = Undefined::Value,
        /** Determines if the optimizer should be enabled for this zone */
        public bool|Undefined|null $optimizerEnabled = Undefined::Value,
        /** Determines if the optimizer origin tunnel system should be enabled for this zone */
        public bool|Undefined|null $optimizerTunnelEnabled = Undefined::Value,
        /** Determines if the optimizer tunnel system active probing should be enabled for this zone */
        public bool|Undefined|null $optimizerTunnelActiveProbingEnabled = Undefined::Value,
        /** Determines the maximum automatic image size for desktop clients */
        public int|Undefined|null $optimizerDesktopMaxWidth = Undefined::Value,
        /** Determines the maximum automatic image size for mobile clients */
        public int|Undefined|null $optimizerMobileMaxWidth = Undefined::Value,
        /** Determines the image quality for desktop clients */
        public int|Undefined|null $optimizerImageQuality = Undefined::Value,
        /** Determines the image quality for mobile clients */
        public int|Undefined|null $optimizerMobileImageQuality = Undefined::Value,
        /** Determines if the WebP optimization should be enabled */
        public bool|Undefined|null $optimizerEnableWebP = Undefined::Value,
        /** Determines if the SEO HTML prerender should be enabled */
        public bool|Undefined|null $optimizerPrerenderHtml = Undefined::Value,
        /** Determines if Markdown automatic generation for AI systems is enabled and which pipeline to use */
        public OptimizerHtmlToMarkdownType|Undefined|null $optimizerHtmlToMarkdown = Undefined::Value,
        /** Determines if the llms.txt file can be generated and served by the Optimizer */
        public bool|Undefined|null $optimizerLlmsTxt = Undefined::Value,
        /** Determines the image manipulation should be enabled */
        public bool|Undefined|null $optimizerEnableManipulationEngine = Undefined::Value,
        /** Determines if the CSS minifcation should be enabled */
        public bool|Undefined|null $optimizerMinifyCSS = Undefined::Value,
        /** Determines if the JavaScript minifcation should be enabled */
        public bool|Undefined|null $optimizerMinifyJavaScript = Undefined::Value,
        /** Determines if image watermarking should be enabled */
        public bool|Undefined|null $optimizerWatermarkEnabled = Undefined::Value,
        /** Sets the URL of the watermark image */
        public string|Undefined|null $optimizerWatermarkUrl = Undefined::Value,
        /** Sets the position of the watermark image */
        public OptimizerWatermarkPosition|Undefined|null $optimizerWatermarkPosition = Undefined::Value,
        /** Sets the offset of the watermark image */
        public float|Undefined|null $optimizerWatermarkOffset = Undefined::Value,
        /** Sets the minimum image size to which the watermark will be added */
        public int|Undefined|null $optimizerWatermarkMinImageSize = Undefined::Value,
        /** Determines if the automatic image optimization should be enabled */
        public bool|Undefined|null $optimizerAutomaticOptimizationEnabled = Undefined::Value,
        /**
         * Determines the list of optimizer classes
         *
         * @var list<OptimizerClassInput>|Undefined
         */
        public array|Undefined $optimizerClasses = Undefined::Value,
        /** Determines if the optimizer classes should be forced */
        public bool|Undefined|null $optimizerForceClasses = Undefined::Value,
        /** Determines whether optimizer static html feature enabled */
        public bool|Undefined|null $optimizerStaticHtmlEnabled = Undefined::Value,
        /** Wordpress html path which should be bypassed by permacache in edge rule */
        public string|Undefined|null $optimizerStaticHtmlWordPressPath = Undefined::Value,
        /** Wordpress cookie which should be bypassed by permacache in edge rule */
        public string|Undefined|null $optimizerStaticHtmlWordPressBypassCookie = Undefined::Value,
        /** The type of the pull zone. */
        public PullZoneType|Undefined|null $type = Undefined::Value,
        /** The number of retries to the origin server */
        public int|Undefined|null $originRetries = Undefined::Value,
        /**
         * The amount of seconds to wait when connecting to the origin. Otherwise the request will fail or retry.
         */
        public int|Undefined|null $originConnectTimeout = Undefined::Value,
        /**
         * The amount of seconds to wait when waiting for the origin reply. Otherwise the request will fail or retry.
         */
        public int|Undefined|null $originResponseTimeout = Undefined::Value,
        /** Determines if we should use stale cache while cache is updating */
        public bool|Undefined|null $useStaleWhileUpdating = Undefined::Value,
        /** Determines if we should use stale cache while the origin is offline */
        public bool|Undefined|null $useStaleWhileOffline = Undefined::Value,
        /** Determines if we should retry the request in case of a 5XX response. */
        public bool|Undefined|null $originRetry5XXResponses = Undefined::Value,
        /** Determines if we should retry the request in case of a connection timeout. */
        public bool|Undefined|null $originRetryConnectionTimeout = Undefined::Value,
        /** Determines if we should retry the request in case of a response timeout. */
        public bool|Undefined|null $originRetryResponseTimeout = Undefined::Value,
        /** Determines the amount of time that the CDN should wait before retrying an origin request. */
        public int|Undefined|null $originRetryDelay = Undefined::Value,
        /** Determines the origin port of the pull zone. */
        public int|Undefined|null $dnsOriginPort = Undefined::Value,
        /** Determines the origin scheme of the pull zone. */
        public string|Undefined|null $dnsOriginScheme = Undefined::Value,
        /**
         * Contains the list of vary parameters that will be used for vary cache by query string. Only alphanumeric characters, dashes and underscores are allowed (values that contain other characters are ignorred). If empty, all parameters will be used to construct the key.
         *
         * @var list<string>|Undefined
         */
        public array|Undefined $queryStringVaryParameters = Undefined::Value,
        /** Determines if the origin shield concurrency limit is enabled. */
        public bool|Undefined|null $originShieldEnableConcurrencyLimit = Undefined::Value,
        /** Determines the number of maximum concurrent requests allowed to the origin. */
        public int|Undefined|null $originShieldMaxConcurrentRequests = Undefined::Value,
        /** Determines if the Cookie Vary feature is enabled. */
        public bool|Undefined|null $enableCookieVary = Undefined::Value,
        /**
         * Contains the list of vary parameters that will be used for vary cache by cookie string.Only alphanumeric characters, dashes and underscores are allowed (values that contain other characters are ignorred). If empty, cookie vary will not be used.
         *
         * @var list<string>|Undefined
         */
        public array|Undefined $cookieVaryParameters = Undefined::Value,
        public bool|Undefined|null $enableSafeHop = Undefined::Value,
        /** Determines the max queue wait time */
        public int|Undefined|null $originShieldQueueMaxWaitTime = Undefined::Value,
        /** Determines the max number of origin requests that will remain in the queue */
        public int|Undefined|null $originShieldMaxQueuedRequests = Undefined::Value,
        /** Determines if cache update is performed in the background. */
        public bool|Undefined|null $useBackgroundUpdate = Undefined::Value,
        /** If set to true, any hostnames added to this Pull Zone will automatically enable SSL. */
        public bool|Undefined|null $enableAutoSSL = Undefined::Value,
        /** Sets the log anonymization type for this pull zone */
        public LogAnonymizationType|Undefined|null $logAnonymizationType = Undefined::Value,
        /** The ID of the storage zone that will be used as the origin */
        public int|Undefined|null $storageZoneId = Undefined::Value,
        /** The ID of the edge script that will be used as the origin */
        public int|Undefined|null $edgeScriptId = Undefined::Value,
        /** The ID of the middleware script */
        public int|Undefined|null $middlewareScriptId = Undefined::Value,
        /** The execution phase of the edge script */
        public ExecutionPhase|Undefined|null $edgeScriptExecutionPhase = Undefined::Value,
        /** Determine the type of the origin for this Pull Zone */
        public PullZoneOriginType|Undefined|null $originType = Undefined::Value,
        public string|Undefined|null $magicContainersAppId = Undefined::Value,
        public string|Undefined|null $magicContainersEndpointId = Undefined::Value,
        /**
         * 0 = Plain
         * 1 = JSON
         */
        public PullZoneLogFormat|Undefined|null $logFormat = Undefined::Value,
        /**
         * 0 = Plain
         * 1 = JSON
         */
        public PullZoneLogFormat|Undefined|null $logForwardingFormat = Undefined::Value,
        /**
         * 0 = DetectOnly
         * 1 = ActiveStandard
         * 2 = ActiveAggressive
         */
        public ShieldDDosProtectionType|Undefined|null $shieldDDosProtectionType = Undefined::Value,
        public bool|Undefined|null $shieldDDosProtectionEnabled = Undefined::Value,
        /** Sets the host header that will be sent to the origin */
        public string|Undefined|null $originHostHeader = Undefined::Value,
        public bool|Undefined|null $enableSmartCache = Undefined::Value,
        /** Determines if request coalescing is currently enabled. */
        public bool|Undefined|null $enableRequestCoalescing = Undefined::Value,
        /** Determines the lock time for coalesced requests. */
        public int|Undefined|null $requestCoalescingTimeout = Undefined::Value,
        /** If set to true, the built-in let's encrypt will be disabled and requests are passed to the origin. */
        public bool|Undefined|null $disableLetsEncrypt = Undefined::Value,
        public bool|Undefined|null $enableBunnyImageAi = Undefined::Value,
        /** @var list<BunnyAiImageBlueprint>|Undefined */
        public array|Undefined $bunnyAiImageBlueprints = Undefined::Value,
        /** Determines if the preloading screen is currently enabled */
        public bool|Undefined|null $preloadingScreenEnabled = Undefined::Value,
        /** The custom preloading screen coed */
        public string|Undefined|null $preloadingScreenCode = Undefined::Value,
        /** The preloading screen logo URL */
        public string|Undefined|null $preloadingScreenLogoUrl = Undefined::Value,
        /** Determines if the preloading screen is shown on the first load from a user. */
        public bool|Undefined $preloadingScreenShowOnFirstVisit = Undefined::Value,
        /** The currently configured preloading screem theme. (0 - Light, 1 - Dark) */
        public PreloadingScreenTheme|Undefined|null $preloadingScreenTheme = Undefined::Value,
        /** Determines if the custom preloader screen should be enabled */
        public bool|Undefined|null $preloadingScreenCodeEnabled = Undefined::Value,
        /** The delay in miliseconds after which the preloading screen will be displayed (0 - 10000ms) */
        public int|Undefined|null $preloadingScreenDelay = Undefined::Value,
        /**
         * The list of routing filters enabled for this zone
         *
         * @var list<string>|Undefined
         */
        public array|Undefined $routingFilters = Undefined::Value,
        /** Whether to use a Sticky Session mechanism for this pull zone */
        public StickySessionType|Undefined|null $stickySessionType = Undefined::Value,
        /** Sticky Session Cookie Name */
        public string|Undefined|null $stickySessionCookieName = Undefined::Value,
        /** A set of comma-separated header names used to identify clients */
        public string|Undefined|null $stickySessionClientHeaders = Undefined::Value,
        /** Determines if Optimizer is allowed to upscale images */
        public bool|Undefined|null $optimizerEnableUpscaling = Undefined::Value,
        /** Determines if WebSocket connections are allowed for this Pull Zone. */
        public bool|Undefined|null $enableWebSockets = Undefined::Value,
        /**
         * The maximum global simultaneous WebSocket connections allowed for this Pull Zone. Allowed tiers: 500, 1,000, 2,500, 5,000, 10,000, 25,000. If you send a non-tier value, the value is rounded up to the next tier. Values over 25,000 are rejected, please contact sales if required.
         */
        public int|Undefined|null $maxWebSocketConnections = Undefined::Value,
        /** Vary Cache by Request Headers (comma delimited) */
        public string|Undefined|null $cacheKeyHeaders = Undefined::Value,
        /** If using a load balancer origin, the ID of the load balancer to use */
        public int|Undefined|null $loadBalancerId = Undefined::Value,
    ) {}

    public function toArray(): array
    {
        $data = [];

        if (!$this->originUrl instanceof Undefined) {
            $data['OriginUrl'] = $this->originUrl;
        }

        if (!$this->allowedReferrers instanceof Undefined) {
            $data['AllowedReferrers'] = $this->allowedReferrers;
        }

        if (!$this->blockedReferrers instanceof Undefined) {
            $data['BlockedReferrers'] = $this->blockedReferrers;
        }

        if (!$this->blockNoneReferrer instanceof Undefined) {
            $data['BlockNoneReferrer'] = $this->blockNoneReferrer;
        }

        if (!$this->blockedIps instanceof Undefined) {
            $data['BlockedIps'] = $this->blockedIps;
        }

        if (!$this->enableGeoZoneUS instanceof Undefined) {
            $data['EnableGeoZoneUS'] = $this->enableGeoZoneUS;
        }

        if (!$this->enableGeoZoneEU instanceof Undefined) {
            $data['EnableGeoZoneEU'] = $this->enableGeoZoneEU;
        }

        if (!$this->enableGeoZoneASIA instanceof Undefined) {
            $data['EnableGeoZoneASIA'] = $this->enableGeoZoneASIA;
        }

        if (!$this->enableGeoZoneSA instanceof Undefined) {
            $data['EnableGeoZoneSA'] = $this->enableGeoZoneSA;
        }

        if (!$this->enableGeoZoneAF instanceof Undefined) {
            $data['EnableGeoZoneAF'] = $this->enableGeoZoneAF;
        }

        if (!$this->ipFamilyPolicy instanceof Undefined) {
            $data['IpFamilyPolicy'] = $this->ipFamilyPolicy?->value;
        }

        if (!$this->blockRootPathAccess instanceof Undefined) {
            $data['BlockRootPathAccess'] = $this->blockRootPathAccess;
        }

        if (!$this->blockPostRequests instanceof Undefined) {
            $data['BlockPostRequests'] = $this->blockPostRequests;
        }

        if (!$this->enableQueryStringOrdering instanceof Undefined) {
            $data['EnableQueryStringOrdering'] = $this->enableQueryStringOrdering;
        }

        if (!$this->enableWebpVary instanceof Undefined) {
            $data['EnableWebpVary'] = $this->enableWebpVary;
        }

        if (!$this->enableAvifVary instanceof Undefined) {
            $data['EnableAvifVary'] = $this->enableAvifVary;
        }

        if (!$this->enableMobileVary instanceof Undefined) {
            $data['EnableMobileVary'] = $this->enableMobileVary;
        }

        if (!$this->enableCountryCodeVary instanceof Undefined) {
            $data['EnableCountryCodeVary'] = $this->enableCountryCodeVary;
        }

        if (!$this->enableCountryStateCodeVary instanceof Undefined) {
            $data['EnableCountryStateCodeVary'] = $this->enableCountryStateCodeVary;
        }

        if (!$this->enableHostnameVary instanceof Undefined) {
            $data['EnableHostnameVary'] = $this->enableHostnameVary;
        }

        if (!$this->enableCacheSlice instanceof Undefined) {
            $data['EnableCacheSlice'] = $this->enableCacheSlice;
        }

        if (!$this->zoneSecurityEnabled instanceof Undefined) {
            $data['ZoneSecurityEnabled'] = $this->zoneSecurityEnabled;
        }

        if (!$this->zoneSecurityIncludeHashRemoteIP instanceof Undefined) {
            $data['ZoneSecurityIncludeHashRemoteIP'] = $this->zoneSecurityIncludeHashRemoteIP;
        }

        if (!$this->ignoreQueryStrings instanceof Undefined) {
            $data['IgnoreQueryStrings'] = $this->ignoreQueryStrings;
        }

        if (!$this->monthlyBandwidthLimit instanceof Undefined) {
            $data['MonthlyBandwidthLimit'] = $this->monthlyBandwidthLimit;
        }

        if (!$this->accessControlOriginHeaderExtensions instanceof Undefined) {
            $data['AccessControlOriginHeaderExtensions'] = $this->accessControlOriginHeaderExtensions;
        }

        if (!$this->enableAccessControlOriginHeader instanceof Undefined) {
            $data['EnableAccessControlOriginHeader'] = $this->enableAccessControlOriginHeader;
        }

        if (!$this->disableCookies instanceof Undefined) {
            $data['DisableCookies'] = $this->disableCookies;
        }

        if (!$this->budgetRedirectedCountries instanceof Undefined) {
            $data['BudgetRedirectedCountries'] = $this->budgetRedirectedCountries;
        }

        if (!$this->blockedCountries instanceof Undefined) {
            $data['BlockedCountries'] = $this->blockedCountries;
        }

        if (!$this->cacheControlMaxAgeOverride instanceof Undefined) {
            $data['CacheControlMaxAgeOverride'] = $this->cacheControlMaxAgeOverride;
        }

        if (!$this->cacheControlPublicMaxAgeOverride instanceof Undefined) {
            $data['CacheControlPublicMaxAgeOverride'] = $this->cacheControlPublicMaxAgeOverride;
        }

        if (!$this->cacheControlBrowserMaxAgeOverride instanceof Undefined) {
            $data['CacheControlBrowserMaxAgeOverride'] = $this->cacheControlBrowserMaxAgeOverride;
        }

        if (!$this->addHostHeader instanceof Undefined) {
            $data['AddHostHeader'] = $this->addHostHeader;
        }

        if (!$this->addCanonicalHeader instanceof Undefined) {
            $data['AddCanonicalHeader'] = $this->addCanonicalHeader;
        }

        if (!$this->enableLogging instanceof Undefined) {
            $data['EnableLogging'] = $this->enableLogging;
        }

        if (!$this->loggingIPAnonymizationEnabled instanceof Undefined) {
            $data['LoggingIPAnonymizationEnabled'] = $this->loggingIPAnonymizationEnabled;
        }

        if (!$this->permaCacheStorageZoneId instanceof Undefined) {
            $data['PermaCacheStorageZoneId'] = $this->permaCacheStorageZoneId;
        }

        if (!$this->permaCacheType instanceof Undefined) {
            $data['PermaCacheType'] = $this->permaCacheType?->value;
        }

        if (!$this->awsSigningEnabled instanceof Undefined) {
            $data['AWSSigningEnabled'] = $this->awsSigningEnabled;
        }

        if (!$this->awsSigningKey instanceof Undefined) {
            $data['AWSSigningKey'] = $this->awsSigningKey;
        }

        if (!$this->awsSigningRegionName instanceof Undefined) {
            $data['AWSSigningRegionName'] = $this->awsSigningRegionName;
        }

        if (!$this->awsSigningSecret instanceof Undefined) {
            $data['AWSSigningSecret'] = $this->awsSigningSecret;
        }

        if (!$this->enableOriginShield instanceof Undefined) {
            $data['EnableOriginShield'] = $this->enableOriginShield;
        }

        if (!$this->originShieldZoneCode instanceof Undefined) {
            $data['OriginShieldZoneCode'] = $this->originShieldZoneCode;
        }

        if (!$this->enableTLS1 instanceof Undefined) {
            $data['EnableTLS1'] = $this->enableTLS1;
        }

        if (!$this->enableTLS11 instanceof Undefined) {
            $data['EnableTLS1_1'] = $this->enableTLS11;
        }

        if (!$this->tlsSecurityLevel instanceof Undefined) {
            $data['TlsSecurityLevel'] = $this->tlsSecurityLevel?->value;
        }

        if (!$this->cacheErrorResponses instanceof Undefined) {
            $data['CacheErrorResponses'] = $this->cacheErrorResponses;
        }

        if (!$this->verifyOriginSSL instanceof Undefined) {
            $data['VerifyOriginSSL'] = $this->verifyOriginSSL;
        }

        if (!$this->logForwardingEnabled instanceof Undefined) {
            $data['LogForwardingEnabled'] = $this->logForwardingEnabled;
        }

        if (!$this->logForwardingHostname instanceof Undefined) {
            $data['LogForwardingHostname'] = $this->logForwardingHostname;
        }

        if (!$this->logForwardingPort instanceof Undefined) {
            $data['LogForwardingPort'] = $this->logForwardingPort;
        }

        if (!$this->logForwardingToken instanceof Undefined) {
            $data['LogForwardingToken'] = $this->logForwardingToken;
        }

        if (!$this->logForwardingProtocol instanceof Undefined) {
            $data['LogForwardingProtocol'] = $this->logForwardingProtocol?->value;
        }

        if (!$this->loggingSaveToStorage instanceof Undefined) {
            $data['LoggingSaveToStorage'] = $this->loggingSaveToStorage;
        }

        if (!$this->loggingStorageZoneId instanceof Undefined) {
            $data['LoggingStorageZoneId'] = $this->loggingStorageZoneId;
        }

        if (!$this->followRedirects instanceof Undefined) {
            $data['FollowRedirects'] = $this->followRedirects;
        }

        if (!$this->connectionLimitPerIPCount instanceof Undefined) {
            $data['ConnectionLimitPerIPCount'] = $this->connectionLimitPerIPCount;
        }

        if (!$this->requestLimit instanceof Undefined) {
            $data['RequestLimit'] = $this->requestLimit;
        }

        if (!$this->limitRateAfter instanceof Undefined) {
            $data['LimitRateAfter'] = $this->limitRateAfter;
        }

        if (!$this->limitRatePerSecond instanceof Undefined) {
            $data['LimitRatePerSecond'] = $this->limitRatePerSecond;
        }

        if (!$this->burstSize instanceof Undefined) {
            $data['BurstSize'] = $this->burstSize;
        }

        if (!$this->errorPageEnableCustomCode instanceof Undefined) {
            $data['ErrorPageEnableCustomCode'] = $this->errorPageEnableCustomCode;
        }

        if (!$this->errorPageCustomCode instanceof Undefined) {
            $data['ErrorPageCustomCode'] = $this->errorPageCustomCode;
        }

        if (!$this->errorPageEnableStatuspageWidget instanceof Undefined) {
            $data['ErrorPageEnableStatuspageWidget'] = $this->errorPageEnableStatuspageWidget;
        }

        if (!$this->errorPageStatuspageCode instanceof Undefined) {
            $data['ErrorPageStatuspageCode'] = $this->errorPageStatuspageCode;
        }

        if (!$this->errorPageWhitelabel instanceof Undefined) {
            $data['ErrorPageWhitelabel'] = $this->errorPageWhitelabel;
        }

        if (!$this->optimizerEnabled instanceof Undefined) {
            $data['OptimizerEnabled'] = $this->optimizerEnabled;
        }

        if (!$this->optimizerTunnelEnabled instanceof Undefined) {
            $data['OptimizerTunnelEnabled'] = $this->optimizerTunnelEnabled;
        }

        if (!$this->optimizerTunnelActiveProbingEnabled instanceof Undefined) {
            $data['OptimizerTunnelActiveProbingEnabled'] = $this->optimizerTunnelActiveProbingEnabled;
        }

        if (!$this->optimizerDesktopMaxWidth instanceof Undefined) {
            $data['OptimizerDesktopMaxWidth'] = $this->optimizerDesktopMaxWidth;
        }

        if (!$this->optimizerMobileMaxWidth instanceof Undefined) {
            $data['OptimizerMobileMaxWidth'] = $this->optimizerMobileMaxWidth;
        }

        if (!$this->optimizerImageQuality instanceof Undefined) {
            $data['OptimizerImageQuality'] = $this->optimizerImageQuality;
        }

        if (!$this->optimizerMobileImageQuality instanceof Undefined) {
            $data['OptimizerMobileImageQuality'] = $this->optimizerMobileImageQuality;
        }

        if (!$this->optimizerEnableWebP instanceof Undefined) {
            $data['OptimizerEnableWebP'] = $this->optimizerEnableWebP;
        }

        if (!$this->optimizerPrerenderHtml instanceof Undefined) {
            $data['OptimizerPrerenderHtml'] = $this->optimizerPrerenderHtml;
        }

        if (!$this->optimizerHtmlToMarkdown instanceof Undefined) {
            $data['OptimizerHtmlToMarkdown'] = $this->optimizerHtmlToMarkdown?->value;
        }

        if (!$this->optimizerLlmsTxt instanceof Undefined) {
            $data['OptimizerLlmsTxt'] = $this->optimizerLlmsTxt;
        }

        if (!$this->optimizerEnableManipulationEngine instanceof Undefined) {
            $data['OptimizerEnableManipulationEngine'] = $this->optimizerEnableManipulationEngine;
        }

        if (!$this->optimizerMinifyCSS instanceof Undefined) {
            $data['OptimizerMinifyCSS'] = $this->optimizerMinifyCSS;
        }

        if (!$this->optimizerMinifyJavaScript instanceof Undefined) {
            $data['OptimizerMinifyJavaScript'] = $this->optimizerMinifyJavaScript;
        }

        if (!$this->optimizerWatermarkEnabled instanceof Undefined) {
            $data['OptimizerWatermarkEnabled'] = $this->optimizerWatermarkEnabled;
        }

        if (!$this->optimizerWatermarkUrl instanceof Undefined) {
            $data['OptimizerWatermarkUrl'] = $this->optimizerWatermarkUrl;
        }

        if (!$this->optimizerWatermarkPosition instanceof Undefined) {
            $data['OptimizerWatermarkPosition'] = $this->optimizerWatermarkPosition?->value;
        }

        if (!$this->optimizerWatermarkOffset instanceof Undefined) {
            $data['OptimizerWatermarkOffset'] = $this->optimizerWatermarkOffset;
        }

        if (!$this->optimizerWatermarkMinImageSize instanceof Undefined) {
            $data['OptimizerWatermarkMinImageSize'] = $this->optimizerWatermarkMinImageSize;
        }

        if (!$this->optimizerAutomaticOptimizationEnabled instanceof Undefined) {
            $data['OptimizerAutomaticOptimizationEnabled'] = $this->optimizerAutomaticOptimizationEnabled;
        }

        if (!$this->optimizerClasses instanceof Undefined) {
            $data['OptimizerClasses'] = array_map(static fn(OptimizerClassInput $item): array => $item->toArray(), $this->optimizerClasses);
        }

        if (!$this->optimizerForceClasses instanceof Undefined) {
            $data['OptimizerForceClasses'] = $this->optimizerForceClasses;
        }

        if (!$this->optimizerStaticHtmlEnabled instanceof Undefined) {
            $data['OptimizerStaticHtmlEnabled'] = $this->optimizerStaticHtmlEnabled;
        }

        if (!$this->optimizerStaticHtmlWordPressPath instanceof Undefined) {
            $data['OptimizerStaticHtmlWordPressPath'] = $this->optimizerStaticHtmlWordPressPath;
        }

        if (!$this->optimizerStaticHtmlWordPressBypassCookie instanceof Undefined) {
            $data['OptimizerStaticHtmlWordPressBypassCookie'] = $this->optimizerStaticHtmlWordPressBypassCookie;
        }

        if (!$this->type instanceof Undefined) {
            $data['Type'] = $this->type?->value;
        }

        if (!$this->originRetries instanceof Undefined) {
            $data['OriginRetries'] = $this->originRetries;
        }

        if (!$this->originConnectTimeout instanceof Undefined) {
            $data['OriginConnectTimeout'] = $this->originConnectTimeout;
        }

        if (!$this->originResponseTimeout instanceof Undefined) {
            $data['OriginResponseTimeout'] = $this->originResponseTimeout;
        }

        if (!$this->useStaleWhileUpdating instanceof Undefined) {
            $data['UseStaleWhileUpdating'] = $this->useStaleWhileUpdating;
        }

        if (!$this->useStaleWhileOffline instanceof Undefined) {
            $data['UseStaleWhileOffline'] = $this->useStaleWhileOffline;
        }

        if (!$this->originRetry5XXResponses instanceof Undefined) {
            $data['OriginRetry5XXResponses'] = $this->originRetry5XXResponses;
        }

        if (!$this->originRetryConnectionTimeout instanceof Undefined) {
            $data['OriginRetryConnectionTimeout'] = $this->originRetryConnectionTimeout;
        }

        if (!$this->originRetryResponseTimeout instanceof Undefined) {
            $data['OriginRetryResponseTimeout'] = $this->originRetryResponseTimeout;
        }

        if (!$this->originRetryDelay instanceof Undefined) {
            $data['OriginRetryDelay'] = $this->originRetryDelay;
        }

        if (!$this->dnsOriginPort instanceof Undefined) {
            $data['DnsOriginPort'] = $this->dnsOriginPort;
        }

        if (!$this->dnsOriginScheme instanceof Undefined) {
            $data['DnsOriginScheme'] = $this->dnsOriginScheme;
        }

        if (!$this->queryStringVaryParameters instanceof Undefined) {
            $data['QueryStringVaryParameters'] = $this->queryStringVaryParameters;
        }

        if (!$this->originShieldEnableConcurrencyLimit instanceof Undefined) {
            $data['OriginShieldEnableConcurrencyLimit'] = $this->originShieldEnableConcurrencyLimit;
        }

        if (!$this->originShieldMaxConcurrentRequests instanceof Undefined) {
            $data['OriginShieldMaxConcurrentRequests'] = $this->originShieldMaxConcurrentRequests;
        }

        if (!$this->enableCookieVary instanceof Undefined) {
            $data['EnableCookieVary'] = $this->enableCookieVary;
        }

        if (!$this->cookieVaryParameters instanceof Undefined) {
            $data['CookieVaryParameters'] = $this->cookieVaryParameters;
        }

        if (!$this->enableSafeHop instanceof Undefined) {
            $data['EnableSafeHop'] = $this->enableSafeHop;
        }

        if (!$this->originShieldQueueMaxWaitTime instanceof Undefined) {
            $data['OriginShieldQueueMaxWaitTime'] = $this->originShieldQueueMaxWaitTime;
        }

        if (!$this->originShieldMaxQueuedRequests instanceof Undefined) {
            $data['OriginShieldMaxQueuedRequests'] = $this->originShieldMaxQueuedRequests;
        }

        if (!$this->useBackgroundUpdate instanceof Undefined) {
            $data['UseBackgroundUpdate'] = $this->useBackgroundUpdate;
        }

        if (!$this->enableAutoSSL instanceof Undefined) {
            $data['EnableAutoSSL'] = $this->enableAutoSSL;
        }

        if (!$this->logAnonymizationType instanceof Undefined) {
            $data['LogAnonymizationType'] = $this->logAnonymizationType?->value;
        }

        if (!$this->storageZoneId instanceof Undefined) {
            $data['StorageZoneId'] = $this->storageZoneId;
        }

        if (!$this->edgeScriptId instanceof Undefined) {
            $data['EdgeScriptId'] = $this->edgeScriptId;
        }

        if (!$this->middlewareScriptId instanceof Undefined) {
            $data['MiddlewareScriptId'] = $this->middlewareScriptId;
        }

        if (!$this->edgeScriptExecutionPhase instanceof Undefined) {
            $data['EdgeScriptExecutionPhase'] = $this->edgeScriptExecutionPhase?->value;
        }

        if (!$this->originType instanceof Undefined) {
            $data['OriginType'] = $this->originType?->value;
        }

        if (!$this->magicContainersAppId instanceof Undefined) {
            $data['MagicContainersAppId'] = $this->magicContainersAppId;
        }

        if (!$this->magicContainersEndpointId instanceof Undefined) {
            $data['MagicContainersEndpointId'] = $this->magicContainersEndpointId;
        }

        if (!$this->logFormat instanceof Undefined) {
            $data['LogFormat'] = $this->logFormat?->value;
        }

        if (!$this->logForwardingFormat instanceof Undefined) {
            $data['LogForwardingFormat'] = $this->logForwardingFormat?->value;
        }

        if (!$this->shieldDDosProtectionType instanceof Undefined) {
            $data['ShieldDDosProtectionType'] = $this->shieldDDosProtectionType?->value;
        }

        if (!$this->shieldDDosProtectionEnabled instanceof Undefined) {
            $data['ShieldDDosProtectionEnabled'] = $this->shieldDDosProtectionEnabled;
        }

        if (!$this->originHostHeader instanceof Undefined) {
            $data['OriginHostHeader'] = $this->originHostHeader;
        }

        if (!$this->enableSmartCache instanceof Undefined) {
            $data['EnableSmartCache'] = $this->enableSmartCache;
        }

        if (!$this->enableRequestCoalescing instanceof Undefined) {
            $data['EnableRequestCoalescing'] = $this->enableRequestCoalescing;
        }

        if (!$this->requestCoalescingTimeout instanceof Undefined) {
            $data['RequestCoalescingTimeout'] = $this->requestCoalescingTimeout;
        }

        if (!$this->disableLetsEncrypt instanceof Undefined) {
            $data['DisableLetsEncrypt'] = $this->disableLetsEncrypt;
        }

        if (!$this->enableBunnyImageAi instanceof Undefined) {
            $data['EnableBunnyImageAi'] = $this->enableBunnyImageAi;
        }

        if (!$this->bunnyAiImageBlueprints instanceof Undefined) {
            $data['BunnyAiImageBlueprints'] = array_map(static fn(BunnyAiImageBlueprint $item): array => $item->toArray(), $this->bunnyAiImageBlueprints);
        }

        if (!$this->preloadingScreenEnabled instanceof Undefined) {
            $data['PreloadingScreenEnabled'] = $this->preloadingScreenEnabled;
        }

        if (!$this->preloadingScreenCode instanceof Undefined) {
            $data['PreloadingScreenCode'] = $this->preloadingScreenCode;
        }

        if (!$this->preloadingScreenLogoUrl instanceof Undefined) {
            $data['PreloadingScreenLogoUrl'] = $this->preloadingScreenLogoUrl;
        }

        if (!$this->preloadingScreenShowOnFirstVisit instanceof Undefined) {
            $data['PreloadingScreenShowOnFirstVisit'] = $this->preloadingScreenShowOnFirstVisit;
        }

        if (!$this->preloadingScreenTheme instanceof Undefined) {
            $data['PreloadingScreenTheme'] = $this->preloadingScreenTheme?->value;
        }

        if (!$this->preloadingScreenCodeEnabled instanceof Undefined) {
            $data['PreloadingScreenCodeEnabled'] = $this->preloadingScreenCodeEnabled;
        }

        if (!$this->preloadingScreenDelay instanceof Undefined) {
            $data['PreloadingScreenDelay'] = $this->preloadingScreenDelay;
        }

        if (!$this->routingFilters instanceof Undefined) {
            $data['RoutingFilters'] = $this->routingFilters;
        }

        if (!$this->stickySessionType instanceof Undefined) {
            $data['StickySessionType'] = $this->stickySessionType?->value;
        }

        if (!$this->stickySessionCookieName instanceof Undefined) {
            $data['StickySessionCookieName'] = $this->stickySessionCookieName;
        }

        if (!$this->stickySessionClientHeaders instanceof Undefined) {
            $data['StickySessionClientHeaders'] = $this->stickySessionClientHeaders;
        }

        if (!$this->optimizerEnableUpscaling instanceof Undefined) {
            $data['OptimizerEnableUpscaling'] = $this->optimizerEnableUpscaling;
        }

        if (!$this->enableWebSockets instanceof Undefined) {
            $data['EnableWebSockets'] = $this->enableWebSockets;
        }

        if (!$this->maxWebSocketConnections instanceof Undefined) {
            $data['MaxWebSocketConnections'] = $this->maxWebSocketConnections;
        }

        if (!$this->cacheKeyHeaders instanceof Undefined) {
            $data['CacheKeyHeaders'] = $this->cacheKeyHeaders;
        }

        if (!$this->loadBalancerId instanceof Undefined) {
            $data['LoadBalancerId'] = $this->loadBalancerId;
        }

        return $data;
    }
}
