<?php

declare(strict_types=1);

// This file is generated by tools/generate.php from resources/specs/core.json. Do not edit.

namespace GoSuccess\Bunny\Core\Model;

use GoSuccess\Bunny\Core\Enum\ExecutionPhase;
use GoSuccess\Bunny\Core\Enum\IpFamilyPolicy;
use GoSuccess\Bunny\Core\Enum\LogAnonymizationType;
use GoSuccess\Bunny\Core\Enum\OptimizerHtmlToMarkdownType;
use GoSuccess\Bunny\Core\Enum\OptimizerWatermarkPosition;
use GoSuccess\Bunny\Core\Enum\PermaCacheType;
use GoSuccess\Bunny\Core\Enum\PreloadingScreenTheme;
use GoSuccess\Bunny\Core\Enum\PullZoneLogFormat;
use GoSuccess\Bunny\Core\Enum\PullZoneLogForwarderProtocolType;
use GoSuccess\Bunny\Core\Enum\PullZoneOriginType;
use GoSuccess\Bunny\Core\Enum\PullZoneType;
use GoSuccess\Bunny\Core\Enum\ShieldDDosProtectionType;
use GoSuccess\Bunny\Core\Enum\StickySessionType;
use GoSuccess\Bunny\Core\Enum\TlsSecurityLevelType;
use GoSuccess\Bunny\Model\Cast;
use GoSuccess\Bunny\Model\ResponseModel;

/** Schema: PullZoneModel */
final readonly class PullZone implements ResponseModel
{
    public function __construct(
        /** The unique ID of the pull zone. */
        public int $id = 0,
        /** The name of the pull zone. */
        public ?string $name = null,
        /** The origin URL of the pull zone where the files are fetched from. */
        public ?string $originUrl = null,
        /** True unless reached resource limits or account owning it ran out of funds. */
        public bool $enabled = false,
        public bool $suspended = false,
        /**
         * The list of hostnames linked to this Pull Zone
         *
         * @var list<Hostname>
         */
        public array $hostnames = [],
        /** The ID of the storage zone that the pull zone is linked to */
        public int $storageZoneId = 0,
        /** The ID of the edge script that the pull zone is linked to */
        public int $edgeScriptId = 0,
        /** The phase of the request where the script will be executed */
        public ?ExecutionPhase $edgeScriptExecutionPhase = null,
        public ?int $middlewareScriptId = null,
        /** The ID of the Magic Container application the pull zone is linked to */
        public ?string $magicContainersAppId = null,
        /** The ID of the Magic Container Endpoint the pull zone is linked to */
        public ?string $magicContainersEndpointId = null,
        /**
         * The list of referrer hostnames that are allowed to access the pull zone.Requests containing the header Referer: hostname that is not on the list will be rejected.If empty, all the referrers are allowed
         *
         * @var list<string>
         */
        public array $allowedReferrers = [],
        /**
         * The list of referrer hostnames that are allowed to access the pull zone. Requests containing the header Referer: hostname that is not on the list will be rejected. If empty, all the referrers are allowed
         *
         * @var list<string>
         */
        public array $blockedReferrers = [],
        /**
         * The list of IPs that are blocked from accessing the pull zone. Requests coming from the following IPs will be rejected. If empty, all the IPs will be allowed
         *
         * @var list<string>
         */
        public array $blockedIps = [],
        /** Determines if the delivery from the North American region is enabled for this pull zone */
        public bool $enableGeoZoneUS = false,
        /** Determines if the delivery from the European region is enabled for this pull zone */
        public bool $enableGeoZoneEU = false,
        /** Determines if the delivery from the Asian / Oceanian region is enabled for this pull zone */
        public bool $enableGeoZoneASIA = false,
        /** Determines if the delivery from the South American region is enabled for this pull zone */
        public bool $enableGeoZoneSA = false,
        /** Determines if the delivery from the Africa region is enabled for this pull zone */
        public bool $enableGeoZoneAF = false,
        /** Address-family policy: 0=IPv4Only, 1=DualStack, 2=DualStackPreferIPv6, 3=IPv6Only. */
        public ?IpFamilyPolicy $ipFamilyPolicy = null,
        /** True if the URL secure token authentication security is enabled */
        public bool $zoneSecurityEnabled = false,
        /** The security key used for secure URL token authentication */
        public ?string $zoneSecurityKey = null,
        /** True if the zone security hash should include the remote IP */
        public bool $zoneSecurityIncludeHashRemoteIP = false,
        /** True if the Pull Zone is ignoring query strings when serving cached objects */
        public bool $ignoreQueryStrings = false,
        /** The monthly limit of bandwidth in bytes that the pullzone is allowed to use */
        public int $monthlyBandwidthLimit = 0,
        /** The amount of bandwidth in bytes that the pull zone used this month */
        public int $monthlyBandwidthUsed = 0,
        /** The total monthly charges for this so zone so far */
        public float $monthlyCharges = 0.0,
        /** Determines if the Pull Zone should forward the current hostname to the origin */
        public bool $addHostHeader = false,
        /** Determines the host header that will be sent to the origin */
        public ?string $originHostHeader = null,
        /** The type of the pull zone. */
        public ?PullZoneType $type = null,
        /**
         * The list of extensions that will return the CORS headers
         *
         * @var list<string>
         */
        public array $accessControlOriginHeaderExtensions = [],
        /** Determines if the CORS headers should be enabled */
        public bool $enableAccessControlOriginHeader = false,
        /** Determines if the cookies are disabled for the pull zone */
        public bool $disableCookies = false,
        /**
         * The list of budget redirected countries with the two-letter Alpha2 ISO codes
         *
         * @var list<string>
         */
        public array $budgetRedirectedCountries = [],
        /**
         * The list of blocked countries with the two-letter Alpha2 ISO codes
         *
         * @var list<string>
         */
        public array $blockedCountries = [],
        /** If true the server will use the origin shield feature */
        public bool $enableOriginShield = false,
        /** The override cache time for the pull zone */
        public int $cacheControlMaxAgeOverride = 0,
        /** The override cache time for the pull zone for the end client */
        public int $cacheControlPublicMaxAgeOverride = 0,
        /** Excessive requests are delayed until their number exceeds the maximum burst size. */
        public int $burstSize = 0,
        /** Max number of requests per IP per second */
        public int $requestLimit = 0,
        /** If true, access to root path will return a 403 error */
        public bool $blockRootPathAccess = false,
        /** If true, POST requests to the zone will be blocked */
        public bool $blockPostRequests = false,
        /** The maximum rate at which the zone will transfer data in kb/s. 0 for unlimited */
        public float $limitRatePerSecond = 0.0,
        /** The amount of data after the rate limit will be activated */
        public float $limitRateAfter = 0.0,
        /** The number of connections limited per IP for this zone */
        public int $connectionLimitPerIPCount = 0,
        /** The custom price override for this zone. Unit is $/Byte. */
        public float $priceOverride = 0.0,
        /** Monthly pricing for Bunny Optimizer for this pull zone */
        public float $optimizerPricing = 0.0,
        /** Determines if the Add Canonical Header is enabled for this Pull Zone */
        public bool $addCanonicalHeader = false,
        /** Determines if the logging is enabled for this Pull Zone */
        public bool $enableLogging = false,
        /** Determines if the cache slice (Optimize for video) feature is enabled for the Pull Zone */
        public bool $enableCacheSlice = false,
        /** Determines if smart caching is enabled for this zone */
        public bool $enableSmartCache = false,
        /**
         * The list of edge rules on this Pull Zone
         *
         * @var list<EdgeRule>
         */
        public array $edgeRules = [],
        /** Determines if the WebP Vary feature is enabled. */
        public bool $enableWebPVary = false,
        /** Determines if the AVIF Vary feature is enabled. */
        public bool $enableAvifVary = false,
        /** Determines if the Country Code Vary feature is enabled. */
        public bool $enableCountryCodeVary = false,
        /** Determines if the Country State Code Vary feature should be enabled. */
        public bool $enableCountryStateCodeVary = false,
        /** Determines if the Mobile Vary feature is enabled. */
        public bool $enableMobileVary = false,
        /** Determines if the Cookie Vary feature is enabled. */
        public bool $enableCookieVary = false,
        /**
         * Contains the list of vary parameters that will be used for vary cache by cookie string. If empty, cookie vary will not be used.
         *
         * @var list<string>
         */
        public array $cookieVaryParameters = [],
        /** Determines if the Hostname Vary feature is enabled. */
        public bool $enableHostnameVary = false,
        /** The CNAME domain of the pull zone for setting up custom hostnames */
        public ?string $cnameDomain = null,
        /** Determines if the AWS Signing is enabled */
        public bool $awsSigningEnabled = false,
        /** The AWS Signing region key */
        public ?string $awsSigningKey = null,
        /** The AWS Signing region secret */
        public ?string $awsSigningSecret = null,
        /** The AWS Signing region name */
        public ?string $awsSigningRegionName = null,
        /** Determines if the TLS 1 is enabled on the Pull Zone */
        public bool $loggingIPAnonymizationEnabled = false,
        /** Determines if the TLS 1 is enabled on the Pull Zone */
        public bool $enableTLS1 = false,
        /** Determines if the TLS 1.1 is enabled on the Pull Zone */
        public bool $enableTLS11 = false,
        /**
         * The minimum TLS security level enforced on the Pull Zone (Legacy = 0, Compatible = 1, ModernOnly = 2)
         */
        public ?TlsSecurityLevelType $tlsSecurityLevel = null,
        /** Determines if the Pull Zone should verify the origin SSL certificate */
        public bool $verifyOriginSSL = false,
        /** Determines if custom error page code should be enabled. */
        public bool $errorPageEnableCustomCode = false,
        /** Contains the custom error page code that will be returned */
        public ?string $errorPageCustomCode = null,
        /** Determines if the statuspage widget should be displayed on the error pages */
        public bool $errorPageEnableStatuspageWidget = false,
        /** The statuspage code that will be used to build the status widget */
        public ?string $errorPageStatuspageCode = null,
        /** Determines if the error pages should be whitelabel or not */
        public bool $errorPageWhitelabel = false,
        /** The zone code of the origin shield */
        public ?string $originShieldZoneCode = null,
        /** Determines if the log forawrding is enabled */
        public bool $logForwardingEnabled = false,
        /** The log forwarding hostname */
        public ?string $logForwardingHostname = null,
        /** The log forwarding port */
        public int $logForwardingPort = 0,
        /** The log forwarding token value */
        public ?string $logForwardingToken = null,
        /** Determines the log forwarding protocol type */
        public ?PullZoneLogForwarderProtocolType $logForwardingProtocol = null,
        /** Determines if the permanent logging feature is enabled */
        public bool $loggingSaveToStorage = false,
        /** The ID of the logging storage zone that is configured for this Pull Zone */
        public int $loggingStorageZoneId = 0,
        /** Determines if the zone will follow origin redirects */
        public bool $followRedirects = false,
        /** The ID of the video library that the zone is linked to */
        public int $videoLibraryId = 0,
        /** The ID of the DNS record tied to this pull zone */
        public int $dnsRecordId = 0,
        /** The ID of the DNS zone tied to this pull zone */
        public int $dnsZoneId = 0,
        /** The cached version of the DNS record value */
        public ?string $dnsRecordValue = null,
        /** Determines if the optimizer should be enabled for this zone */
        public bool $optimizerEnabled = false,
        /** Determines if the optimizer origin tunnel system is enabled for this zone */
        public bool $optimizerTunnelEnabled = false,
        /** Determines if the optimizer tunnel system active probing should be enabled for this zone */
        public bool $optimizerTunnelActiveProbingEnabled = false,
        /** Determines the maximum automatic image size for desktop clients */
        public int $optimizerDesktopMaxWidth = 0,
        /** Determines the maximum automatic image size for mobile clients */
        public int $optimizerMobileMaxWidth = 0,
        /** Determines the image quality for desktop clients */
        public int $optimizerImageQuality = 0,
        /** Determines the image quality for mobile clients */
        public int $optimizerMobileImageQuality = 0,
        /** Determines if the WebP optimization should be enabled */
        public bool $optimizerEnableWebP = false,
        /** Determines if the SEO HTML prerender is enabled */
        public bool $optimizerPrerenderHtml = false,
        /** Determines if Markdown automatic generation for AI systems is enabled and which pipeline to use */
        public ?OptimizerHtmlToMarkdownType $optimizerHtmlToMarkdown = null,
        /** Determines if the llms.txt file can be generated and served by the Optimizer */
        public bool $optimizerLlmsTxt = false,
        /** Determines the image manipulation should be enabled */
        public bool $optimizerEnableManipulationEngine = false,
        /** Determines if the CSS minifcation should be enabled */
        public bool $optimizerMinifyCSS = false,
        /** Determines if the JavaScript minifcation should be enabled */
        public bool $optimizerMinifyJavaScript = false,
        /** Determines if image watermarking should be enabled */
        public bool $optimizerWatermarkEnabled = false,
        /** Sets the URL of the watermark image */
        public ?string $optimizerWatermarkUrl = null,
        /** Sets the position of the watermark image */
        public ?OptimizerWatermarkPosition $optimizerWatermarkPosition = null,
        /** Sets the offset of the watermark image */
        public float $optimizerWatermarkOffset = 0.0,
        /** Sets the minimum image size to which the watermark will be added */
        public int $optimizerWatermarkMinImageSize = 0,
        /** Determines if the automatic image optimization should be enabled */
        public bool $optimizerAutomaticOptimizationEnabled = false,
        /** The IP of the storage zone used for Perma-Cache */
        public int $permaCacheStorageZoneId = 0,
        /** Determines Perma-Cache behavior */
        public ?PermaCacheType $permaCacheType = null,
        /** The number of retries to the origin server */
        public int $originRetries = 0,
        /**
         * The amount of seconds to wait when connecting to the origin. Otherwise the request will fail or retry.
         */
        public int $originConnectTimeout = 0,
        /**
         * The amount of seconds to wait when waiting for the origin reply. Otherwise the request will fail or retry.
         */
        public int $originResponseTimeout = 0,
        /** Determines if we should use stale cache while cache is updating */
        public bool $useStaleWhileUpdating = false,
        /** Determines if we should use stale cache while the origin is offline */
        public bool $useStaleWhileOffline = false,
        /** Determines if we should retry the request in case of a 5XX response. */
        public bool $originRetry5XXResponses = false,
        /** Determines if we should retry the request in case of a connection timeout. */
        public bool $originRetryConnectionTimeout = false,
        /** Determines if we should retry the request in case of a response timeout. */
        public bool $originRetryResponseTimeout = false,
        /** Determines the amount of time that the CDN should wait before retrying an origin request. */
        public int $originRetryDelay = 0,
        /**
         * Contains the list of vary parameters that will be used for vary cache by query string. If empty, all parameters will be used to construct the key
         *
         * @var list<string>
         */
        public array $queryStringVaryParameters = [],
        /** Determines if the origin shield concurrency limit is enabled. */
        public bool $originShieldEnableConcurrencyLimit = false,
        /** Determines the number of maximum concurrent requests allowed to the origin. */
        public int $originShieldMaxConcurrentRequests = 0,
        public bool $enableSafeHop = false,
        /** Determines if bunny.net should be caching error responses */
        public bool $cacheErrorResponses = false,
        /** Determines the max queue wait time */
        public int $originShieldQueueMaxWaitTime = 0,
        /** Determines the max number of origin requests that will remain in the queu */
        public int $originShieldMaxQueuedRequests = 0,
        /**
         * Contains the list of optimizer classes
         *
         * @var list<OptimizerClass>
         */
        public array $optimizerClasses = [],
        /** Determines if the optimizer class list should be enforced */
        public bool $optimizerForceClasses = false,
        /** Determines whether optimizer static html feature enabled */
        public bool $optimizerStaticHtmlEnabled = false,
        /** Wordpress html path which should be bypassed by permacache in edge rule */
        public ?string $optimizerStaticHtmlWordPressPath = null,
        /** Wordpress cookie which should be bypassed by permacache in edge rule */
        public ?string $optimizerStaticHtmlWordPressBypassCookie = null,
        /** Determines if cache update is performed in the background. */
        public bool $useBackgroundUpdate = false,
        /** If set to true, any hostnames added to this Pull Zone will automatically enable SSL. */
        public bool $enableAutoSSL = false,
        /** If set to true the query string ordering property is enabled. */
        public bool $enableQueryStringOrdering = false,
        /** Gets the log anonymization type for this pull zone */
        public ?LogAnonymizationType $logAnonymizationType = null,
        /**
         * 0 = Plain
         * 1 = JSON
         */
        public ?PullZoneLogFormat $logFormat = null,
        /**
         * 0 = Plain
         * 1 = JSON
         */
        public ?PullZoneLogFormat $logForwardingFormat = null,
        /**
         * 0 = DetectOnly
         * 1 = ActiveStandard
         * 2 = ActiveAggressive
         */
        public ?ShieldDDosProtectionType $shieldDDosProtectionType = null,
        public bool $shieldDDosProtectionEnabled = false,
        /** The type of the origin for this Pull Zone */
        public ?PullZoneOriginType $originType = null,
        /** Determines if request coalescing is currently enabled. */
        public bool $enableRequestCoalescing = false,
        /** Determines the lock time for coalesced requests. */
        public int $requestCoalescingTimeout = 0,
        /** Returns the link short preview value for the pull zone origin connection. */
        public ?string $originLinkValue = null,
        /** If true, the built-in let's encrypt is disabled and requests are passed to the origin. */
        public bool $disableLetsEncrypt = false,
        public bool $enableBunnyImageAi = false,
        /** @var list<BunnyAiImageBlueprint> */
        public array $bunnyAiImageBlueprints = [],
        /** Determines if the preloading screen is currently enabled */
        public bool $preloadingScreenEnabled = false,
        /** Determines if the preloading screen is shown on the first load from a user. */
        public bool $preloadingScreenShowOnFirstVisit = false,
        /** The custom preloading screen code */
        public ?string $preloadingScreenCode = null,
        /** The preloading screen logo URL */
        public ?string $preloadingScreenLogoUrl = null,
        /** Determines if the custom preloader screen is enabled */
        public bool $preloadingScreenCodeEnabled = false,
        /** The currently configured preloading screem theme. (0 - Light, 1 - Dark) */
        public ?PreloadingScreenTheme $preloadingScreenTheme = null,
        /** The delay in miliseconds after which the preloading screen will be desplayed */
        public int $preloadingScreenDelay = 0,
        /** The Pull Zone specific pricing discount for EU and US region. */
        public int $euusDiscount = 0,
        /** The Pull Zone specific pricing discount for South America region. */
        public int $southAmericaDiscount = 0,
        /** The Pull Zone specific pricing discount for Africa region. */
        public int $africaDiscount = 0,
        /** The Pull Zone specific pricing discount for Asia & Oceania region. */
        public int $asiaOceaniaDiscount = 0,
        /**
         * The list of routing filters enabled for this zone
         *
         * @var list<string>
         */
        public array $routingFilters = [],
        /** Determines if direct access to files will be blocked if not coming from allowed referrers */
        public bool $blockNoneReferrer = false,
        /** Whether to use a Sticky Session mechanism for this pull zone */
        public ?StickySessionType $stickySessionType = null,
        /** Sticky Session Cookie Name */
        public ?string $stickySessionCookieName = null,
        /** A set of comma-separated header names used to identify clients */
        public ?string $stickySessionClientHeaders = null,
        /** The ID of the Load Balancer profile used as the origin when OriginType is LoadBalancer */
        public ?int $loadBalancerId = null,
        /** User Id of the pull zone owner */
        public ?string $userId = null,
        public int $cacheVersion = 0,
        /** Determines if Optimizer is allowed to upscale images */
        public bool $optimizerEnableUpscaling = false,
        /** Determines if WebSocket connections are allowed for this Pull Zone. */
        public bool $enableWebSockets = false,
        /** The maximum global simultaneous WebSocket connections allowed for this Pull Zone. */
        public int $maxWebSocketConnections = 0,
        /** Determines if extended logging with additional details is enabled for this Pull Zone. */
        public bool $enableExtendedLogging = false,
        /** Vary Cache by Request Headers (comma delimited) */
        public ?string $cacheKeyHeaders = null,
    ) {}

    public static function fromArray(array $data): static
    {
        return new self(
            id: Cast::int($data['Id'] ?? null) ?? 0,
            name: Cast::string($data['Name'] ?? null),
            originUrl: Cast::string($data['OriginUrl'] ?? null),
            enabled: Cast::bool($data['Enabled'] ?? null) ?? false,
            suspended: Cast::bool($data['Suspended'] ?? null) ?? false,
            hostnames: Cast::modelList(Hostname::class, $data['Hostnames'] ?? null),
            storageZoneId: Cast::int($data['StorageZoneId'] ?? null) ?? 0,
            edgeScriptId: Cast::int($data['EdgeScriptId'] ?? null) ?? 0,
            edgeScriptExecutionPhase: Cast::intEnum(ExecutionPhase::class, $data['EdgeScriptExecutionPhase'] ?? null),
            middlewareScriptId: Cast::int($data['MiddlewareScriptId'] ?? null),
            magicContainersAppId: Cast::string($data['MagicContainersAppId'] ?? null),
            magicContainersEndpointId: Cast::string($data['MagicContainersEndpointId'] ?? null),
            allowedReferrers: Cast::listOf($data['AllowedReferrers'] ?? null, Cast::string(...)),
            blockedReferrers: Cast::listOf($data['BlockedReferrers'] ?? null, Cast::string(...)),
            blockedIps: Cast::listOf($data['BlockedIps'] ?? null, Cast::string(...)),
            enableGeoZoneUS: Cast::bool($data['EnableGeoZoneUS'] ?? null) ?? false,
            enableGeoZoneEU: Cast::bool($data['EnableGeoZoneEU'] ?? null) ?? false,
            enableGeoZoneASIA: Cast::bool($data['EnableGeoZoneASIA'] ?? null) ?? false,
            enableGeoZoneSA: Cast::bool($data['EnableGeoZoneSA'] ?? null) ?? false,
            enableGeoZoneAF: Cast::bool($data['EnableGeoZoneAF'] ?? null) ?? false,
            ipFamilyPolicy: Cast::intEnum(IpFamilyPolicy::class, $data['IpFamilyPolicy'] ?? null),
            zoneSecurityEnabled: Cast::bool($data['ZoneSecurityEnabled'] ?? null) ?? false,
            zoneSecurityKey: Cast::string($data['ZoneSecurityKey'] ?? null),
            zoneSecurityIncludeHashRemoteIP: Cast::bool($data['ZoneSecurityIncludeHashRemoteIP'] ?? null) ?? false,
            ignoreQueryStrings: Cast::bool($data['IgnoreQueryStrings'] ?? null) ?? false,
            monthlyBandwidthLimit: Cast::int($data['MonthlyBandwidthLimit'] ?? null) ?? 0,
            monthlyBandwidthUsed: Cast::int($data['MonthlyBandwidthUsed'] ?? null) ?? 0,
            monthlyCharges: Cast::float($data['MonthlyCharges'] ?? null) ?? 0.0,
            addHostHeader: Cast::bool($data['AddHostHeader'] ?? null) ?? false,
            originHostHeader: Cast::string($data['OriginHostHeader'] ?? null),
            type: Cast::intEnum(PullZoneType::class, $data['Type'] ?? null),
            accessControlOriginHeaderExtensions: Cast::listOf($data['AccessControlOriginHeaderExtensions'] ?? null, Cast::string(...)),
            enableAccessControlOriginHeader: Cast::bool($data['EnableAccessControlOriginHeader'] ?? null) ?? false,
            disableCookies: Cast::bool($data['DisableCookies'] ?? null) ?? false,
            budgetRedirectedCountries: Cast::listOf($data['BudgetRedirectedCountries'] ?? null, Cast::string(...)),
            blockedCountries: Cast::listOf($data['BlockedCountries'] ?? null, Cast::string(...)),
            enableOriginShield: Cast::bool($data['EnableOriginShield'] ?? null) ?? false,
            cacheControlMaxAgeOverride: Cast::int($data['CacheControlMaxAgeOverride'] ?? null) ?? 0,
            cacheControlPublicMaxAgeOverride: Cast::int($data['CacheControlPublicMaxAgeOverride'] ?? null) ?? 0,
            burstSize: Cast::int($data['BurstSize'] ?? null) ?? 0,
            requestLimit: Cast::int($data['RequestLimit'] ?? null) ?? 0,
            blockRootPathAccess: Cast::bool($data['BlockRootPathAccess'] ?? null) ?? false,
            blockPostRequests: Cast::bool($data['BlockPostRequests'] ?? null) ?? false,
            limitRatePerSecond: Cast::float($data['LimitRatePerSecond'] ?? null) ?? 0.0,
            limitRateAfter: Cast::float($data['LimitRateAfter'] ?? null) ?? 0.0,
            connectionLimitPerIPCount: Cast::int($data['ConnectionLimitPerIPCount'] ?? null) ?? 0,
            priceOverride: Cast::float($data['PriceOverride'] ?? null) ?? 0.0,
            optimizerPricing: Cast::float($data['OptimizerPricing'] ?? null) ?? 0.0,
            addCanonicalHeader: Cast::bool($data['AddCanonicalHeader'] ?? null) ?? false,
            enableLogging: Cast::bool($data['EnableLogging'] ?? null) ?? false,
            enableCacheSlice: Cast::bool($data['EnableCacheSlice'] ?? null) ?? false,
            enableSmartCache: Cast::bool($data['EnableSmartCache'] ?? null) ?? false,
            edgeRules: Cast::modelList(EdgeRule::class, $data['EdgeRules'] ?? null),
            enableWebPVary: Cast::bool($data['EnableWebPVary'] ?? null) ?? false,
            enableAvifVary: Cast::bool($data['EnableAvifVary'] ?? null) ?? false,
            enableCountryCodeVary: Cast::bool($data['EnableCountryCodeVary'] ?? null) ?? false,
            enableCountryStateCodeVary: Cast::bool($data['EnableCountryStateCodeVary'] ?? null) ?? false,
            enableMobileVary: Cast::bool($data['EnableMobileVary'] ?? null) ?? false,
            enableCookieVary: Cast::bool($data['EnableCookieVary'] ?? null) ?? false,
            cookieVaryParameters: Cast::listOf($data['CookieVaryParameters'] ?? null, Cast::string(...)),
            enableHostnameVary: Cast::bool($data['EnableHostnameVary'] ?? null) ?? false,
            cnameDomain: Cast::string($data['CnameDomain'] ?? null),
            awsSigningEnabled: Cast::bool($data['AWSSigningEnabled'] ?? null) ?? false,
            awsSigningKey: Cast::string($data['AWSSigningKey'] ?? null),
            awsSigningSecret: Cast::string($data['AWSSigningSecret'] ?? null),
            awsSigningRegionName: Cast::string($data['AWSSigningRegionName'] ?? null),
            loggingIPAnonymizationEnabled: Cast::bool($data['LoggingIPAnonymizationEnabled'] ?? null) ?? false,
            enableTLS1: Cast::bool($data['EnableTLS1'] ?? null) ?? false,
            enableTLS11: Cast::bool($data['EnableTLS1_1'] ?? null) ?? false,
            tlsSecurityLevel: Cast::intEnum(TlsSecurityLevelType::class, $data['TlsSecurityLevel'] ?? null),
            verifyOriginSSL: Cast::bool($data['VerifyOriginSSL'] ?? null) ?? false,
            errorPageEnableCustomCode: Cast::bool($data['ErrorPageEnableCustomCode'] ?? null) ?? false,
            errorPageCustomCode: Cast::string($data['ErrorPageCustomCode'] ?? null),
            errorPageEnableStatuspageWidget: Cast::bool($data['ErrorPageEnableStatuspageWidget'] ?? null) ?? false,
            errorPageStatuspageCode: Cast::string($data['ErrorPageStatuspageCode'] ?? null),
            errorPageWhitelabel: Cast::bool($data['ErrorPageWhitelabel'] ?? null) ?? false,
            originShieldZoneCode: Cast::string($data['OriginShieldZoneCode'] ?? null),
            logForwardingEnabled: Cast::bool($data['LogForwardingEnabled'] ?? null) ?? false,
            logForwardingHostname: Cast::string($data['LogForwardingHostname'] ?? null),
            logForwardingPort: Cast::int($data['LogForwardingPort'] ?? null) ?? 0,
            logForwardingToken: Cast::string($data['LogForwardingToken'] ?? null),
            logForwardingProtocol: Cast::intEnum(PullZoneLogForwarderProtocolType::class, $data['LogForwardingProtocol'] ?? null),
            loggingSaveToStorage: Cast::bool($data['LoggingSaveToStorage'] ?? null) ?? false,
            loggingStorageZoneId: Cast::int($data['LoggingStorageZoneId'] ?? null) ?? 0,
            followRedirects: Cast::bool($data['FollowRedirects'] ?? null) ?? false,
            videoLibraryId: Cast::int($data['VideoLibraryId'] ?? null) ?? 0,
            dnsRecordId: Cast::int($data['DnsRecordId'] ?? null) ?? 0,
            dnsZoneId: Cast::int($data['DnsZoneId'] ?? null) ?? 0,
            dnsRecordValue: Cast::string($data['DnsRecordValue'] ?? null),
            optimizerEnabled: Cast::bool($data['OptimizerEnabled'] ?? null) ?? false,
            optimizerTunnelEnabled: Cast::bool($data['OptimizerTunnelEnabled'] ?? null) ?? false,
            optimizerTunnelActiveProbingEnabled: Cast::bool($data['OptimizerTunnelActiveProbingEnabled'] ?? null) ?? false,
            optimizerDesktopMaxWidth: Cast::int($data['OptimizerDesktopMaxWidth'] ?? null) ?? 0,
            optimizerMobileMaxWidth: Cast::int($data['OptimizerMobileMaxWidth'] ?? null) ?? 0,
            optimizerImageQuality: Cast::int($data['OptimizerImageQuality'] ?? null) ?? 0,
            optimizerMobileImageQuality: Cast::int($data['OptimizerMobileImageQuality'] ?? null) ?? 0,
            optimizerEnableWebP: Cast::bool($data['OptimizerEnableWebP'] ?? null) ?? false,
            optimizerPrerenderHtml: Cast::bool($data['OptimizerPrerenderHtml'] ?? null) ?? false,
            optimizerHtmlToMarkdown: Cast::intEnum(OptimizerHtmlToMarkdownType::class, $data['OptimizerHtmlToMarkdown'] ?? null),
            optimizerLlmsTxt: Cast::bool($data['OptimizerLlmsTxt'] ?? null) ?? false,
            optimizerEnableManipulationEngine: Cast::bool($data['OptimizerEnableManipulationEngine'] ?? null) ?? false,
            optimizerMinifyCSS: Cast::bool($data['OptimizerMinifyCSS'] ?? null) ?? false,
            optimizerMinifyJavaScript: Cast::bool($data['OptimizerMinifyJavaScript'] ?? null) ?? false,
            optimizerWatermarkEnabled: Cast::bool($data['OptimizerWatermarkEnabled'] ?? null) ?? false,
            optimizerWatermarkUrl: Cast::string($data['OptimizerWatermarkUrl'] ?? null),
            optimizerWatermarkPosition: Cast::intEnum(OptimizerWatermarkPosition::class, $data['OptimizerWatermarkPosition'] ?? null),
            optimizerWatermarkOffset: Cast::float($data['OptimizerWatermarkOffset'] ?? null) ?? 0.0,
            optimizerWatermarkMinImageSize: Cast::int($data['OptimizerWatermarkMinImageSize'] ?? null) ?? 0,
            optimizerAutomaticOptimizationEnabled: Cast::bool($data['OptimizerAutomaticOptimizationEnabled'] ?? null) ?? false,
            permaCacheStorageZoneId: Cast::int($data['PermaCacheStorageZoneId'] ?? null) ?? 0,
            permaCacheType: Cast::intEnum(PermaCacheType::class, $data['PermaCacheType'] ?? null),
            originRetries: Cast::int($data['OriginRetries'] ?? null) ?? 0,
            originConnectTimeout: Cast::int($data['OriginConnectTimeout'] ?? null) ?? 0,
            originResponseTimeout: Cast::int($data['OriginResponseTimeout'] ?? null) ?? 0,
            useStaleWhileUpdating: Cast::bool($data['UseStaleWhileUpdating'] ?? null) ?? false,
            useStaleWhileOffline: Cast::bool($data['UseStaleWhileOffline'] ?? null) ?? false,
            originRetry5XXResponses: Cast::bool($data['OriginRetry5XXResponses'] ?? null) ?? false,
            originRetryConnectionTimeout: Cast::bool($data['OriginRetryConnectionTimeout'] ?? null) ?? false,
            originRetryResponseTimeout: Cast::bool($data['OriginRetryResponseTimeout'] ?? null) ?? false,
            originRetryDelay: Cast::int($data['OriginRetryDelay'] ?? null) ?? 0,
            queryStringVaryParameters: Cast::listOf($data['QueryStringVaryParameters'] ?? null, Cast::string(...)),
            originShieldEnableConcurrencyLimit: Cast::bool($data['OriginShieldEnableConcurrencyLimit'] ?? null) ?? false,
            originShieldMaxConcurrentRequests: Cast::int($data['OriginShieldMaxConcurrentRequests'] ?? null) ?? 0,
            enableSafeHop: Cast::bool($data['EnableSafeHop'] ?? null) ?? false,
            cacheErrorResponses: Cast::bool($data['CacheErrorResponses'] ?? null) ?? false,
            originShieldQueueMaxWaitTime: Cast::int($data['OriginShieldQueueMaxWaitTime'] ?? null) ?? 0,
            originShieldMaxQueuedRequests: Cast::int($data['OriginShieldMaxQueuedRequests'] ?? null) ?? 0,
            optimizerClasses: Cast::modelList(OptimizerClass::class, $data['OptimizerClasses'] ?? null),
            optimizerForceClasses: Cast::bool($data['OptimizerForceClasses'] ?? null) ?? false,
            optimizerStaticHtmlEnabled: Cast::bool($data['OptimizerStaticHtmlEnabled'] ?? null) ?? false,
            optimizerStaticHtmlWordPressPath: Cast::string($data['OptimizerStaticHtmlWordPressPath'] ?? null),
            optimizerStaticHtmlWordPressBypassCookie: Cast::string($data['OptimizerStaticHtmlWordPressBypassCookie'] ?? null),
            useBackgroundUpdate: Cast::bool($data['UseBackgroundUpdate'] ?? null) ?? false,
            enableAutoSSL: Cast::bool($data['EnableAutoSSL'] ?? null) ?? false,
            enableQueryStringOrdering: Cast::bool($data['EnableQueryStringOrdering'] ?? null) ?? false,
            logAnonymizationType: Cast::intEnum(LogAnonymizationType::class, $data['LogAnonymizationType'] ?? null),
            logFormat: Cast::intEnum(PullZoneLogFormat::class, $data['LogFormat'] ?? null),
            logForwardingFormat: Cast::intEnum(PullZoneLogFormat::class, $data['LogForwardingFormat'] ?? null),
            shieldDDosProtectionType: Cast::intEnum(ShieldDDosProtectionType::class, $data['ShieldDDosProtectionType'] ?? null),
            shieldDDosProtectionEnabled: Cast::bool($data['ShieldDDosProtectionEnabled'] ?? null) ?? false,
            originType: Cast::intEnum(PullZoneOriginType::class, $data['OriginType'] ?? null),
            enableRequestCoalescing: Cast::bool($data['EnableRequestCoalescing'] ?? null) ?? false,
            requestCoalescingTimeout: Cast::int($data['RequestCoalescingTimeout'] ?? null) ?? 0,
            originLinkValue: Cast::string($data['OriginLinkValue'] ?? null),
            disableLetsEncrypt: Cast::bool($data['DisableLetsEncrypt'] ?? null) ?? false,
            enableBunnyImageAi: Cast::bool($data['EnableBunnyImageAi'] ?? null) ?? false,
            bunnyAiImageBlueprints: Cast::modelList(BunnyAiImageBlueprint::class, $data['BunnyAiImageBlueprints'] ?? null),
            preloadingScreenEnabled: Cast::bool($data['PreloadingScreenEnabled'] ?? null) ?? false,
            preloadingScreenShowOnFirstVisit: Cast::bool($data['PreloadingScreenShowOnFirstVisit'] ?? null) ?? false,
            preloadingScreenCode: Cast::string($data['PreloadingScreenCode'] ?? null),
            preloadingScreenLogoUrl: Cast::string($data['PreloadingScreenLogoUrl'] ?? null),
            preloadingScreenCodeEnabled: Cast::bool($data['PreloadingScreenCodeEnabled'] ?? null) ?? false,
            preloadingScreenTheme: Cast::intEnum(PreloadingScreenTheme::class, $data['PreloadingScreenTheme'] ?? null),
            preloadingScreenDelay: Cast::int($data['PreloadingScreenDelay'] ?? null) ?? 0,
            euusDiscount: Cast::int($data['EUUSDiscount'] ?? null) ?? 0,
            southAmericaDiscount: Cast::int($data['SouthAmericaDiscount'] ?? null) ?? 0,
            africaDiscount: Cast::int($data['AfricaDiscount'] ?? null) ?? 0,
            asiaOceaniaDiscount: Cast::int($data['AsiaOceaniaDiscount'] ?? null) ?? 0,
            routingFilters: Cast::listOf($data['RoutingFilters'] ?? null, Cast::string(...)),
            blockNoneReferrer: Cast::bool($data['BlockNoneReferrer'] ?? null) ?? false,
            stickySessionType: Cast::intEnum(StickySessionType::class, $data['StickySessionType'] ?? null),
            stickySessionCookieName: Cast::string($data['StickySessionCookieName'] ?? null),
            stickySessionClientHeaders: Cast::string($data['StickySessionClientHeaders'] ?? null),
            loadBalancerId: Cast::int($data['LoadBalancerId'] ?? null),
            userId: Cast::string($data['UserId'] ?? null),
            cacheVersion: Cast::int($data['CacheVersion'] ?? null) ?? 0,
            optimizerEnableUpscaling: Cast::bool($data['OptimizerEnableUpscaling'] ?? null) ?? false,
            enableWebSockets: Cast::bool($data['EnableWebSockets'] ?? null) ?? false,
            maxWebSocketConnections: Cast::int($data['MaxWebSocketConnections'] ?? null) ?? 0,
            enableExtendedLogging: Cast::bool($data['EnableExtendedLogging'] ?? null) ?? false,
            cacheKeyHeaders: Cast::string($data['CacheKeyHeaders'] ?? null),
        );
    }
}
