<?php

declare(strict_types=1);

// This file is generated by tools/generate.php from resources/specs/core.json. Do not edit.

namespace GoSuccess\Bunny\Core\Model;

use GoSuccess\Bunny\Model\Cast;
use GoSuccess\Bunny\Model\ResponseModel;

/** Schema: SearchResultItemModel */
final readonly class SearchResult implements ResponseModel
{
    public function __construct(
        /** The type of the search result item. Possible values: cdn, storage, dns, script, stream */
        public ?string $type = null,
        /** The ID of the search result item linked object */
        public int $id = 0,
        /** The name of the object found */
        public ?string $name = null,
    ) {}

    public static function fromArray(array $data): static
    {
        return new self(
            type: Cast::string($data['Type'] ?? null),
            id: Cast::int($data['Id'] ?? null) ?? 0,
            name: Cast::string($data['Name'] ?? null),
        );
    }
}
