<?php

declare(strict_types=1);

// This file is generated by tools/generate.php from resources/specs/core.json. Do not edit.

namespace GoSuccess\Bunny\Core\Model;

use GoSuccess\Bunny\Model\Cast;
use GoSuccess\Bunny\Model\ResponseModel;

/** Schema: StatisticsModel */
final readonly class Statistics implements ResponseModel
{
    public function __construct(
        /** The total bandwidth used by the response in the given time range */
        public int $totalBandwidthUsed = 0,
        /** The total amount of traffic received from the origin */
        public int $totalOriginTraffic = 0,
        /** The median response time origin */
        public int $averageOriginResponseTime = 0,
        /**
         * The constructed origin response time chart data
         *
         * @var array<array-key, float>
         */
        public array $originResponseTimeChart = [],
        /** The total requests served by the response in the given time range */
        public int $totalRequestsServed = 0,
        /** The average cache hit rate in the response in the given time range */
        public float $cacheHitRate = 0.0,
        /**
         * The constructed bandwdidth used chart data
         *
         * @var array<array-key, float>
         */
        public array $bandwidthUsedChart = [],
        /**
         * The constructed cached bandwdidth used chart data
         *
         * @var array<array-key, float>
         */
        public array $bandwidthCachedChart = [],
        /**
         * The constructed cache hit rate chart data
         *
         * @var array<array-key, float>
         */
        public array $cacheHitRateChart = [],
        /**
         * The constructed requests served chart data
         *
         * @var array<array-key, float>
         */
        public array $requestsServedChart = [],
        /**
         * The constructed uncached requests served chart data
         *
         * @var array<array-key, float>
         */
        public array $pullRequestsPulledChart = [],
        /**
         * The constructed origin shield bandwdidth used chart data
         *
         * @var array<array-key, float>
         */
        public array $originShieldBandwidthUsedChart = [],
        /**
         * The constructed origin shield internal bandwdidth used chart data
         *
         * @var array<array-key, float>
         */
        public array $originShieldInternalBandwidthUsedChart = [],
        /**
         * The constructed origin traffic used chart data
         *
         * @var array<array-key, float>
         */
        public array $originTrafficChart = [],
        /**
         * The constructed user balance history chart data
         *
         * @var array<array-key, float>
         */
        public array $userBalanceHistoryChart = [],
        /**
         * The geo traffic distribution data
         *
         * @var array<array-key, int>
         */
        public array $geoTrafficDistribution = [],
        /**
         * The constructed 3XX error responses chart data
         *
         * @var array<array-key, float>
         */
        public array $error3xxChart = [],
        /**
         * The constructed 4XX error responses chart data
         *
         * @var array<array-key, float>
         */
        public array $error4xxChart = [],
        /**
         * The constructed 5XX error responses chart data
         *
         * @var array<array-key, float>
         */
        public array $error5xxChart = [],
    ) {}

    public static function fromArray(array $data): static
    {
        return new self(
            totalBandwidthUsed: Cast::int($data['TotalBandwidthUsed'] ?? null) ?? 0,
            totalOriginTraffic: Cast::int($data['TotalOriginTraffic'] ?? null) ?? 0,
            averageOriginResponseTime: Cast::int($data['AverageOriginResponseTime'] ?? null) ?? 0,
            originResponseTimeChart: Cast::mapOf($data['OriginResponseTimeChart'] ?? null, Cast::float(...)),
            totalRequestsServed: Cast::int($data['TotalRequestsServed'] ?? null) ?? 0,
            cacheHitRate: Cast::float($data['CacheHitRate'] ?? null) ?? 0.0,
            bandwidthUsedChart: Cast::mapOf($data['BandwidthUsedChart'] ?? null, Cast::float(...)),
            bandwidthCachedChart: Cast::mapOf($data['BandwidthCachedChart'] ?? null, Cast::float(...)),
            cacheHitRateChart: Cast::mapOf($data['CacheHitRateChart'] ?? null, Cast::float(...)),
            requestsServedChart: Cast::mapOf($data['RequestsServedChart'] ?? null, Cast::float(...)),
            pullRequestsPulledChart: Cast::mapOf($data['PullRequestsPulledChart'] ?? null, Cast::float(...)),
            originShieldBandwidthUsedChart: Cast::mapOf($data['OriginShieldBandwidthUsedChart'] ?? null, Cast::float(...)),
            originShieldInternalBandwidthUsedChart: Cast::mapOf($data['OriginShieldInternalBandwidthUsedChart'] ?? null, Cast::float(...)),
            originTrafficChart: Cast::mapOf($data['OriginTrafficChart'] ?? null, Cast::float(...)),
            userBalanceHistoryChart: Cast::mapOf($data['UserBalanceHistoryChart'] ?? null, Cast::float(...)),
            geoTrafficDistribution: Cast::mapOf($data['GeoTrafficDistribution'] ?? null, Cast::int(...)),
            error3xxChart: Cast::mapOf($data['Error3xxChart'] ?? null, Cast::float(...)),
            error4xxChart: Cast::mapOf($data['Error4xxChart'] ?? null, Cast::float(...)),
            error5xxChart: Cast::mapOf($data['Error5xxChart'] ?? null, Cast::float(...)),
        );
    }
}
