<?php

declare(strict_types=1);

// This file is generated by tools/generate.php from resources/specs/core.json. Do not edit.

namespace GoSuccess\Bunny\Core\Model;

use GoSuccess\Bunny\Model\RequestModel;
use GoSuccess\Bunny\Model\Undefined;

/** Schema: StorageZoneSettingsModel */
final readonly class StorageZoneUpdate implements RequestModel
{
    public function __construct(
        /**
         * The list of replication zones enabld for the storage zone
         *
         * @var list<string>|Undefined
         */
        public array|Undefined $replicationZones = Undefined::Value,
        /** The origin URL of the storage zone */
        public string|Undefined|null $originUrl = Undefined::Value,
        /** The path to the custom file that will be returned in a case of 404 */
        public string|Undefined|null $custom404FilePath = Undefined::Value,
        /** Rewrite 404 status code to 200 for URLs without extension */
        public bool|Undefined|null $rewrite404To200 = Undefined::Value,
    ) {}

    public function toArray(): array
    {
        $data = [];

        if (!$this->replicationZones instanceof Undefined) {
            $data['ReplicationZones'] = $this->replicationZones;
        }

        if (!$this->originUrl instanceof Undefined) {
            $data['OriginUrl'] = $this->originUrl;
        }

        if (!$this->custom404FilePath instanceof Undefined) {
            $data['Custom404FilePath'] = $this->custom404FilePath;
        }

        if (!$this->rewrite404To200 instanceof Undefined) {
            $data['Rewrite404To200'] = $this->rewrite404To200;
        }

        return $data;
    }
}
