<?php

declare(strict_types=1);

// This file is generated by tools/generate.php from resources/specs/core.json. Do not edit.

namespace GoSuccess\Bunny\Core\Model;

use GoSuccess\Bunny\Model\Cast;
use GoSuccess\Bunny\Model\ResponseModel;

/** Schema: StorageZoneEgressStatisticsModel */
final readonly class StorageZoneEgressStatistics implements ResponseModel
{
    public function __construct(
        /**
         * Download traffic served over HTTP
         *
         * @var array<array-key, int>
         */
        public array $httpEgressChart = [],
        /**
         * Download traffic served over S3
         *
         * @var array<array-key, int>
         */
        public array $s3EgressChart = [],
        /**
         * Download traffic served over presigned S3 URLs
         *
         * @var array<array-key, int>
         */
        public array $s3PresignedEgressChart = [],
        /**
         * Download traffic served over FTP
         *
         * @var array<array-key, int>
         */
        public array $ftpEgressChart = [],
        /**
         * Download traffic served over SFTP
         *
         * @var array<array-key, int>
         */
        public array $sftpEgressChart = [],
        /**
         * Total download traffic across all protocols
         *
         * @var array<array-key, int>
         */
        public array $totalEgressChart = [],
        /** Total download traffic over HTTP */
        public int $httpEgressTotal = 0,
        /** Total download traffic over S3 */
        public int $s3EgressTotal = 0,
        /** Total download traffic over presigned S3 URLs */
        public int $s3PresignedEgressTotal = 0,
        /** Total download traffic over FTP */
        public int $ftpEgressTotal = 0,
        /** Total download traffic over SFTP */
        public int $sftpEgressTotal = 0,
        /** Total download traffic across all protocols */
        public int $totalEgress = 0,
    ) {}

    public static function fromArray(array $data): static
    {
        return new self(
            httpEgressChart: Cast::mapOf($data['HttpEgressChart'] ?? null, Cast::int(...)),
            s3EgressChart: Cast::mapOf($data['S3EgressChart'] ?? null, Cast::int(...)),
            s3PresignedEgressChart: Cast::mapOf($data['S3PresignedEgressChart'] ?? null, Cast::int(...)),
            ftpEgressChart: Cast::mapOf($data['FtpEgressChart'] ?? null, Cast::int(...)),
            sftpEgressChart: Cast::mapOf($data['SftpEgressChart'] ?? null, Cast::int(...)),
            totalEgressChart: Cast::mapOf($data['TotalEgressChart'] ?? null, Cast::int(...)),
            httpEgressTotal: Cast::int($data['HttpEgressTotal'] ?? null) ?? 0,
            s3EgressTotal: Cast::int($data['S3EgressTotal'] ?? null) ?? 0,
            s3PresignedEgressTotal: Cast::int($data['S3PresignedEgressTotal'] ?? null) ?? 0,
            ftpEgressTotal: Cast::int($data['FtpEgressTotal'] ?? null) ?? 0,
            sftpEgressTotal: Cast::int($data['SftpEgressTotal'] ?? null) ?? 0,
            totalEgress: Cast::int($data['TotalEgress'] ?? null) ?? 0,
        );
    }
}
