<?php

declare(strict_types=1);

// This file is generated by tools/generate.php from resources/specs/core.json. Do not edit.

namespace GoSuccess\Bunny\Core\Model;

use GoSuccess\Bunny\Model\Cast;
use GoSuccess\Bunny\Model\ResponseModel;

/** Schema: StorageZoneStatisticsModel */
final readonly class StorageZoneStatistics implements ResponseModel
{
    public function __construct(
        /**
         * The constructed chart of the storage used by day
         *
         * @var array<array-key, int>
         */
        public array $storageUsedChart = [],
        /**
         * The constructed chart of requests stored
         *
         * @var array<array-key, int>
         */
        public array $fileCountChart = [],
    ) {}

    public static function fromArray(array $data): static
    {
        return new self(
            storageUsedChart: Cast::mapOf($data['StorageUsedChart'] ?? null, Cast::int(...)),
            fileCountChart: Cast::mapOf($data['FileCountChart'] ?? null, Cast::int(...)),
        );
    }
}
