<?php

declare(strict_types=1);

// This file is generated by tools/generate.php from resources/specs/core.json. Do not edit.

namespace GoSuccess\Bunny\Core\Model;

use GoSuccess\Bunny\Model\Cast;
use GoSuccess\Bunny\Model\ResponseModel;

/** Schema: UsageBreakdown */
final readonly class UsageBreakdown implements ResponseModel
{
    public function __construct(
        /** The usage based charge in USD */
        public float $usage = 0.0,
        /** The billed quantity for the related product */
        public int $totalUnits = 0,
        /** Measuring Unit for TotalUnits (e.g. Rows, GB, Seconds, Bytes, Block-seconds) */
        public ?string $measuringUnit = null,
    ) {}

    public static function fromArray(array $data): static
    {
        return new self(
            usage: Cast::float($data['Usage'] ?? null) ?? 0.0,
            totalUnits: Cast::int($data['TotalUnits'] ?? null) ?? 0,
            measuringUnit: Cast::string($data['MeasuringUnit'] ?? null),
        );
    }
}
