<?php

declare(strict_types=1);

// This file is generated by tools/generate.php from resources/specs/core.json. Do not edit.

namespace GoSuccess\Bunny\Core\Model;

use GoSuccess\Bunny\Model\Cast;
use GoSuccess\Bunny\Model\ResponseModel;

/** Schema: VideoLibraryDrmStatisticsModel */
final readonly class VideoLibraryDrmStatistics implements ResponseModel
{
    public function __construct(
        public int $totalLicensesIssued = 0,
        /** @var array<array-key, float> */
        public array $licensesIssuedChart = [],
    ) {}

    public static function fromArray(array $data): static
    {
        return new self(
            totalLicensesIssued: Cast::int($data['TotalLicensesIssued'] ?? null) ?? 0,
            licensesIssuedChart: Cast::mapOf($data['LicensesIssuedChart'] ?? null, Cast::float(...)),
        );
    }
}
