<?php

declare(strict_types=1);

// This file is generated by tools/generate.php from resources/specs/core.json. Do not edit.

namespace GoSuccess\Bunny\Core\Model;

use GoSuccess\Bunny\Core\Enum\EncodingTier;
use GoSuccess\Bunny\Model\RequestModel;
use GoSuccess\Bunny\Model\Undefined;

/** Schema: VideoLibraryCreateModel */
final readonly class VideoLibraryCreate implements RequestModel
{
    public function __construct(
        /** The name of the Video Library. */
        public string $name,
        /**
         * The geo-replication regions of the underlying storage zone
         *
         * @var list<string>|Undefined
         */
        public array|Undefined $replicationRegions = Undefined::Value,
        /** (Optional) Sets player version used for this library */
        public int|Undefined|null $playerVersion = Undefined::Value,
        /**
         * (Optional) Defines encoding tier. Premium is a paid tier that offers prioritized encoding and extra codec support.
         */
        public EncodingTier|Undefined|null $encodingTier = Undefined::Value,
        /**
         * (Optional) Determines whether JIT encoding should be used for the library. Supported in premium encoding only.
         */
        public bool|Undefined|null $jitEncodingEnabled = Undefined::Value,
        /**
         * (Optional) Specifies which video codecs are used for encoding, provided as a comma-separated (CSV) string. Free encoding tier supports only x264. A premium encoding tier adds support for vp9, hevc, and av1.
         */
        public string|Undefined|null $outputCodecs = Undefined::Value,
        /**
         * (Optional) Sets the enabled resolutions for the transcoding. At least one resolution should be enabled. Possible values: 240p, 360p, 480p, 720p, 1080p, 1440p, 2160p
         */
        public string|Undefined|null $enabledResolutions = Undefined::Value,
        /** (Optional) Determines if requests without a referer should be blocked. */
        public bool|Undefined|null $blockNoneReferrer = Undefined::Value,
        /** (Optional) Determines if MP4 fallback should be enabled for this library. */
        public bool|Undefined|null $enableMP4Fallback = Undefined::Value,
        /** (Optional) Determines if the original file should be kept after the video is processed. */
        public bool|Undefined|null $keepOriginalFiles = Undefined::Value,
        /** (Optional) Determines if direct play URLs should be enabled for the library */
        public bool|Undefined|null $allowDirectPlay = Undefined::Value,
        /** (Optional) Determines if multiple output audio track support is enabled on video library. */
        public bool|Undefined|null $enableMultiAudioTrackSupport = Undefined::Value,
        /** (Optional) Enables automatic audio transcribing for this library. */
        public bool|Undefined|null $enableTranscribing = Undefined::Value,
        /**
         * (Optional) Languages that captions will be automatically transcribed to.
         *
         * @var list<string>|Undefined
         */
        public array|Undefined $transcribingCaptionLanguages = Undefined::Value,
        /**
         * (Optional) Determines if automatic transcribing title generation is enabled for this library. Enabling any smart generation feature turns on transcribing automatically.
         */
        public bool|Undefined|null $enableTranscribingTitleGeneration = Undefined::Value,
        /**
         * (Optional) Determines if automatic transcribing description generation is enabled for this library. Enabling any smart generation feature turns on transcribing automatically.
         */
        public bool|Undefined|null $enableTranscribingDescriptionGeneration = Undefined::Value,
        /**
         * (Optional) Determines if automatic transcribing chapters generation is enabled for this library. Enabling any smart generation feature turns on transcribing automatically.
         */
        public bool|Undefined|null $enableTranscribingChaptersGeneration = Undefined::Value,
        /**
         * (Optional) Determines if automatic transcribing moments generation is enabled for this library. Enabling any smart generation feature turns on transcribing automatically.
         */
        public bool|Undefined|null $enableTranscribingMomentsGeneration = Undefined::Value,
        /**
         * (Optional) Enables Early Play. Enabling this also exposes originals via CDN settings consistent with the video library update API.
         */
        public bool|Undefined|null $allowEarlyPlay = Undefined::Value,
    ) {}

    public function toArray(): array
    {
        $data = [];
        $data['Name'] = $this->name;

        if (!$this->replicationRegions instanceof Undefined) {
            $data['ReplicationRegions'] = $this->replicationRegions;
        }

        if (!$this->playerVersion instanceof Undefined) {
            $data['PlayerVersion'] = $this->playerVersion;
        }

        if (!$this->encodingTier instanceof Undefined) {
            $data['EncodingTier'] = $this->encodingTier?->value;
        }

        if (!$this->jitEncodingEnabled instanceof Undefined) {
            $data['JitEncodingEnabled'] = $this->jitEncodingEnabled;
        }

        if (!$this->outputCodecs instanceof Undefined) {
            $data['OutputCodecs'] = $this->outputCodecs;
        }

        if (!$this->enabledResolutions instanceof Undefined) {
            $data['EnabledResolutions'] = $this->enabledResolutions;
        }

        if (!$this->blockNoneReferrer instanceof Undefined) {
            $data['BlockNoneReferrer'] = $this->blockNoneReferrer;
        }

        if (!$this->enableMP4Fallback instanceof Undefined) {
            $data['EnableMP4Fallback'] = $this->enableMP4Fallback;
        }

        if (!$this->keepOriginalFiles instanceof Undefined) {
            $data['KeepOriginalFiles'] = $this->keepOriginalFiles;
        }

        if (!$this->allowDirectPlay instanceof Undefined) {
            $data['AllowDirectPlay'] = $this->allowDirectPlay;
        }

        if (!$this->enableMultiAudioTrackSupport instanceof Undefined) {
            $data['EnableMultiAudioTrackSupport'] = $this->enableMultiAudioTrackSupport;
        }

        if (!$this->enableTranscribing instanceof Undefined) {
            $data['EnableTranscribing'] = $this->enableTranscribing;
        }

        if (!$this->transcribingCaptionLanguages instanceof Undefined) {
            $data['TranscribingCaptionLanguages'] = $this->transcribingCaptionLanguages;
        }

        if (!$this->enableTranscribingTitleGeneration instanceof Undefined) {
            $data['EnableTranscribingTitleGeneration'] = $this->enableTranscribingTitleGeneration;
        }

        if (!$this->enableTranscribingDescriptionGeneration instanceof Undefined) {
            $data['EnableTranscribingDescriptionGeneration'] = $this->enableTranscribingDescriptionGeneration;
        }

        if (!$this->enableTranscribingChaptersGeneration instanceof Undefined) {
            $data['EnableTranscribingChaptersGeneration'] = $this->enableTranscribingChaptersGeneration;
        }

        if (!$this->enableTranscribingMomentsGeneration instanceof Undefined) {
            $data['EnableTranscribingMomentsGeneration'] = $this->enableTranscribingMomentsGeneration;
        }

        if (!$this->allowEarlyPlay instanceof Undefined) {
            $data['AllowEarlyPlay'] = $this->allowEarlyPlay;
        }

        return $data;
    }
}
