<?php

declare(strict_types=1);

// This file is generated by tools/generate.php from resources/specs/logging.json. Do not edit.

namespace GoSuccess\Bunny\Logging;

use GoSuccess\Bunny\ClientOptions;
use GoSuccess\Bunny\Http\Connection;
use GoSuccess\Bunny\Http\CurlHttpClient;
use GoSuccess\Bunny\Http\HttpClient;
use GoSuccess\Bunny\Logging\Resource\LogResource;
use GoSuccess\Bunny\RateLimit\NullRateLimiter;
use GoSuccess\Bunny\RateLimit\RateLimiter;
use SensitiveParameter;

/**
 * Client for the bunny.net CDN Logging API (`https://logging.bunnycdn.com`).
 *
 * Resources are created on first access, so unused ones cost nothing.
 */
final class LoggingClient
{
    public const string DEFAULT_BASE_URI = 'https://logging.bunnycdn.com';

    /** Raw CDN request logs of the last 3 days. */
    public private(set) LogResource $logs {
        get => $this->logs ??= new LogResource($this->connection);
    }

    private readonly Connection $connection;

    /**
     * @param string          $apiKey      The account API key (bunny.net dashboard → Account settings → API key).
     * @param ClientOptions   $options     Timeouts, retries and user agent.
     * @param HttpClient|null $httpClient  Custom transport; defaults to the built-in cURL transport.
     * @param RateLimiter     $rateLimiter Client-side throttling; disabled by default.
     * @param string          $baseUri     Base URI of the API.
     */
    public function __construct(
        #[SensitiveParameter]
        string $apiKey,
        ClientOptions $options = new ClientOptions(),
        ?HttpClient $httpClient = null,
        RateLimiter $rateLimiter = new NullRateLimiter(),
        string $baseUri = self::DEFAULT_BASE_URI,
    ) {
        $this->connection = new Connection(
            $baseUri,
            $apiKey,
            $options,
            $httpClient ?? new CurlHttpClient($options->timeout, $options->connectTimeout),
            $rateLimiter,
        );
    }
}
