<?php

declare(strict_types=1);

// This file is generated by tools/generate.php from resources/specs/edge-scripting.json. Do not edit.

namespace GoSuccess\Bunny\EdgeScripting\Resource;

use GoSuccess\Bunny\Core\Pagination;
use GoSuccess\Bunny\EdgeScripting\Model\EdgeScriptRelease;
use GoSuccess\Bunny\Http\Method;
use GoSuccess\Bunny\Model\Cast;
use GoSuccess\Bunny\Pagination\Page;
use GoSuccess\Bunny\Pagination\Paginator;
use GoSuccess\Bunny\Resource\AbstractResource;

/** Releases of edge scripts: the published versions of their code. */
final class ReleaseResource extends AbstractResource
{
    /**
     * Get Releases
     *
     * `GET /compute/script/{id}/releases`
     *
     * @param int $scriptId The ID of the script for which published releases would be returned
     * @param int $page     The page to return, starting at 1.
     * @param int $perPage  The number of items per page.
     *
     * @return Page<EdgeScriptRelease>
     */
    public function list(int $scriptId, int $page = 1, int $perPage = 100): Page
    {
        $data = self::expectObject($this->connection->json(Method::Get, "compute/script/{$scriptId}/releases", [
            'page' => $page,
            'perPage' => $perPage,
        ]));

        return Pagination::page($data, Cast::modelList(EdgeScriptRelease::class, $data['Items'] ?? null));
    }

    /**
     * Iterate lazily over every item of list(), across all pages.
     *
     * `GET /compute/script/{id}/releases`
     *
     * @param int $scriptId The ID of the script for which published releases would be returned
     * @param int $perPage  The number of items per page.
     *
     * @return Paginator<EdgeScriptRelease>
     */
    public function all(int $scriptId, int $perPage = 1000): Paginator
    {
        return new Paginator(fn(int|string|null $position): Page => $this->list(
            scriptId: $scriptId,
            page: \is_int($position) ? $position : 1,
            perPage: $perPage,
        ));
    }

    /**
     * Get Active Release
     *
     * `GET /compute/script/{id}/releases/active`
     *
     * @param int $scriptId The ID of the script for which active release would be returned
     */
    public function active(int $scriptId): EdgeScriptRelease
    {
        $data = $this->connection->json(Method::Get, "compute/script/{$scriptId}/releases/active");

        return self::toModel(EdgeScriptRelease::class, $data);
    }

    /**
     * Publish Release
     *
     * `POST /compute/script/{id}/publish`
     *
     * @param int         $scriptId Publishes the current code as a release
     * @param string|null $note
     */
    public function publish(int $scriptId, ?string $note = null): void
    {
        $body = [];

        if ($note !== null) {
            $body['Note'] = $note;
        }

        $this->connection->json(Method::Post, "compute/script/{$scriptId}/publish", body: $body);
    }

    /**
     * Publish Release
     *
     * `POST /compute/script/{id}/publish/{uuid}`
     *
     * @param int         $scriptId Publishes the current code as a release
     * @param string      $uuid     The UUID of the script release that will be published
     * @param string|null $note
     */
    public function publishRelease(int $scriptId, string $uuid, ?string $note = null): void
    {
        $body = [];

        if ($note !== null) {
            $body['Note'] = $note;
        }

        $this->connection->json(Method::Post, "compute/script/{$scriptId}/publish/{$this->segment($uuid)}", body: $body);
    }
}
