<?php

declare(strict_types=1);

// This file is generated by tools/generate.php from resources/specs/edge-scripting.json. Do not edit.

namespace GoSuccess\Bunny\EdgeScripting\Resource;

use GoSuccess\Bunny\EdgeScripting\Model\EdgeScriptSecret;
use GoSuccess\Bunny\Http\Method;
use GoSuccess\Bunny\Model\Cast;
use GoSuccess\Bunny\Resource\AbstractResource;

/** Secrets of edge scripts; their values can be written, never read. */
final class SecretResource extends AbstractResource
{
    /**
     * List Secrets
     *
     * `GET /compute/script/{id}/secrets`
     *
     * @param int $scriptId The ID of the script to list secrets
     *
     * @return list<EdgeScriptSecret>
     */
    public function list(int $scriptId): array
    {
        $data = $this->connection->json(Method::Get, "compute/script/{$scriptId}/secrets");

        return Cast::modelList(EdgeScriptSecret::class, self::expectObject($data)['Secrets'] ?? null);
    }

    /**
     * Add Secret
     *
     * `POST /compute/script/{id}/secrets`
     *
     * @param int    $scriptId The ID of the script that will have the secret added
     * @param string $name
     * @param string $secret
     */
    public function create(int $scriptId, string $name, string $secret): EdgeScriptSecret
    {
        $body = [
            'Name' => $name,
            'Secret' => $secret,
        ];

        $data = $this->connection->json(Method::Post, "compute/script/{$scriptId}/secrets", body: $body);

        return self::toModel(EdgeScriptSecret::class, $data);
    }

    /**
     * Update Secret
     *
     * `POST /compute/script/{id}/secrets/{secretId}`
     *
     * @param int    $scriptId The ID of the script that will have the secret updated
     * @param int    $secretId The ID of the secret that will be updated
     * @param string $secret
     */
    public function update(int $scriptId, int $secretId, string $secret): EdgeScriptSecret
    {
        $body = [
            'Secret' => $secret,
        ];

        $data = $this->connection->json(Method::Post, "compute/script/{$scriptId}/secrets/{$secretId}", body: $body);

        return self::toModel(EdgeScriptSecret::class, $data);
    }

    /**
     * Upsert Secret
     *
     * Returns the secret if it was created, and null if an existing secret was updated (204 No Content).
     *
     * `PUT /compute/script/{id}/secrets`
     *
     * @param int    $scriptId The ID of the script that will have the secret upserted
     * @param string $name
     * @param string $secret
     */
    public function upsert(int $scriptId, string $name, string $secret): ?EdgeScriptSecret
    {
        $body = [
            'Name' => $name,
            'Secret' => $secret,
        ];

        $data = $this->connection->json(Method::Put, "compute/script/{$scriptId}/secrets", body: $body);

        return $data === null ? null : self::toModel(EdgeScriptSecret::class, $data);
    }

    /**
     * Delete Secret
     *
     * `DELETE /compute/script/{id}/secrets/{secretId}`
     *
     * @param int $scriptId The ID of the script that contains the secret
     * @param int $secretId The ID of the secret that should be deleted
     */
    public function delete(int $scriptId, int $secretId): void
    {
        $this->connection->json(Method::Delete, "compute/script/{$scriptId}/secrets/{$secretId}");
    }
}
