<?php

declare(strict_types=1);

// This file is generated by tools/generate.php from resources/specs/core.json. Do not edit.

namespace GoSuccess\Bunny\Core\Resource;

use GoSuccess\Bunny\Core\Model\CloseAccountResult;
use GoSuccess\Bunny\Http\Method;
use GoSuccess\Bunny\Resource\AbstractResource;

/** Account-level operations. */
final class AccountResource extends AbstractResource
{
    /**
     * Close the account
     *
     * Close the current user account
     *
     * Irreversible: this closes the whole bunny.net account.
     *
     * `POST /user/closeaccount`
     *
     * @param string|null $password
     * @param string|null $reason
     */
    public function close(?string $password = null, ?string $reason = null): CloseAccountResult
    {
        $body = [];

        if ($password !== null) {
            $body['Password'] = $password;
        }

        if ($reason !== null) {
            $body['Reason'] = $reason;
        }

        $data = $this->connection->json(Method::Post, 'user/closeaccount', body: $body);

        return self::toModel(CloseAccountResult::class, $data);
    }
}
