<?php

declare(strict_types=1);

// This file is generated by tools/generate.php from resources/specs/core.json. Do not edit.

namespace GoSuccess\Bunny\Core\Resource;

use GoSuccess\Bunny\Core\Model\AffiliateDetails;
use GoSuccess\Bunny\Core\Model\BillingDetails;
use GoSuccess\Bunny\Core\Model\BillingSummaryItem;
use GoSuccess\Bunny\Core\Model\PaymentRequest;
use GoSuccess\Bunny\Core\Resource\Handwritten\BillingOperations;
use GoSuccess\Bunny\Http\Method;
use GoSuccess\Bunny\Resource\AbstractResource;

/** Billing details, summaries, payment requests and invoices. */
final class BillingResource extends AbstractResource
{
    use BillingOperations;

    /**
     * Get Billing Details
     *
     * Get the billing status details
     *
     * `GET /billing`
     */
    public function details(): BillingDetails
    {
        $data = $this->connection->json(Method::Get, 'billing');

        return self::toModel(BillingDetails::class, $data);
    }

    /**
     * Get Billing Summary
     *
     * `GET /billing/summary`
     *
     * @return list<BillingSummaryItem>
     */
    public function summary(): array
    {
        $data = $this->connection->json(Method::Get, 'billing/summary');

        return self::toModelList(BillingSummaryItem::class, $data);
    }

    /**
     * Get Pending Payment Requests
     *
     * `GET /billing/payment-requests`
     *
     * @return list<PaymentRequest>
     */
    public function paymentRequests(): array
    {
        $data = $this->connection->json(Method::Get, 'billing/payment-requests');

        return self::toModelList(PaymentRequest::class, $data);
    }

    /**
     * Get affiliate details
     *
     * `GET /billing/affiliate`
     */
    public function affiliate(): AffiliateDetails
    {
        $data = $this->connection->json(Method::Get, 'billing/affiliate');

        return self::toModel(AffiliateDetails::class, $data);
    }
}
