<?php

declare(strict_types=1);

// This file is generated by tools/generate.php from resources/specs/core.json. Do not edit.

namespace GoSuccess\Bunny\Core\Resource;

use GoSuccess\Bunny\Core\Model\Country;
use GoSuccess\Bunny\Http\Method;
use GoSuccess\Bunny\Resource\AbstractResource;

/** The countries known to bunny.net, e.g. for geo blocking. */
final class CountryResource extends AbstractResource
{
    /**
     * Get Country List
     *
     * `GET /country`
     *
     * @return list<Country>
     */
    public function list(): array
    {
        $data = $this->connection->json(Method::Get, 'country');

        return self::toModelList(Country::class, $data);
    }
}
