<?php

declare(strict_types=1);

// This file is generated by tools/generate.php from resources/specs/core.json. Do not edit.

namespace GoSuccess\Bunny\Core\Resource;

use GoSuccess\Bunny\Core\Enum\DnsRecordType;
use GoSuccess\Bunny\Core\Model\DnsRecord;
use GoSuccess\Bunny\Core\Model\DnsRecordCreate;
use GoSuccess\Bunny\Core\Model\DnsRecordUpdate;
use GoSuccess\Bunny\Core\Pagination;
use GoSuccess\Bunny\Http\Method;
use GoSuccess\Bunny\Model\Cast;
use GoSuccess\Bunny\Pagination\Page;
use GoSuccess\Bunny\Pagination\Paginator;
use GoSuccess\Bunny\Resource\AbstractResource;

/** DNS records of a zone. */
final class DnsRecordResource extends AbstractResource
{
    /**
     * List DNS Zone Records
     *
     * `GET /dnszone/{zoneId}/records`
     *
     * @param int                $zoneId  The ID of the DNS Zone
     * @param int                $page    The page to return, starting at 1.
     * @param int                $perPage The number of items per page.
     * @param DnsRecordType|null $type    The type of DNS Record
     * @param string|null        $search
     *
     * @return Page<DnsRecord>
     */
    public function list(
        int $zoneId,
        int $page = 1,
        int $perPage = 100,
        ?DnsRecordType $type = null,
        ?string $search = null,
    ): Page {
        $data = self::expectObject($this->connection->json(Method::Get, "dnszone/{$zoneId}/records", [
            'page' => $page,
            'perPage' => $perPage,
            'type' => $type,
            'search' => $search,
        ]));

        return Pagination::page($data, Cast::modelList(DnsRecord::class, $data['Items'] ?? null));
    }

    /**
     * Iterate lazily over every item of list(), across all pages.
     *
     * `GET /dnszone/{zoneId}/records`
     *
     * @param int                $zoneId  The ID of the DNS Zone
     * @param DnsRecordType|null $type    The type of DNS Record
     * @param string|null        $search
     * @param int                $perPage The number of items per page.
     *
     * @return Paginator<DnsRecord>
     */
    public function all(
        int $zoneId,
        ?DnsRecordType $type = null,
        ?string $search = null,
        int $perPage = 1000,
    ): Paginator {
        return new Paginator(fn(int|string|null $position): Page => $this->list(
            zoneId: $zoneId,
            page: \is_int($position) ? $position : 1,
            perPage: $perPage,
            type: $type,
            search: $search,
        ));
    }

    /**
     * Add DNS Record
     *
     * `PUT /dnszone/{zoneId}/records`
     *
     * @param int             $zoneId The DNS Zone ID to which the record will be added.
     * @param DnsRecordCreate $record
     */
    public function create(int $zoneId, DnsRecordCreate $record): DnsRecord
    {
        $data = $this->connection->json(Method::Put, "dnszone/{$zoneId}/records", body: $record->toArray());

        return self::toModel(DnsRecord::class, $data);
    }

    /**
     * Update DNS Record
     *
     * `POST /dnszone/{zoneId}/records/{id}`
     *
     * @param int             $zoneId  The DNS Zone ID that contains the record.
     * @param int             $id      The ID of the DNS record that will be updated.
     * @param DnsRecordUpdate $changes
     */
    public function update(int $zoneId, int $id, DnsRecordUpdate $changes): void
    {
        $this->connection->json(Method::Post, "dnszone/{$zoneId}/records/{$id}", body: $changes->toArray());
    }

    /**
     * Delete DNS Record
     *
     * `DELETE /dnszone/{zoneId}/records/{id}`
     *
     * @param int $zoneId The DNS Zone ID that contains the record.
     * @param int $id     The ID of the DNS record that will be deleted.
     */
    public function delete(int $zoneId, int $id): void
    {
        $this->connection->json(Method::Delete, "dnszone/{$zoneId}/records/{$id}");
    }
}
