<?php

declare(strict_types=1);

// This file is generated by tools/generate.php from resources/specs/core.json. Do not edit.

namespace GoSuccess\Bunny\Core\Resource;

use GoSuccess\Bunny\Core\Model\EdgeRule;
use GoSuccess\Bunny\Core\Resource\Handwritten\EdgeRuleOperations;
use GoSuccess\Bunny\Http\Method;
use GoSuccess\Bunny\Resource\AbstractResource;

/** Edge rules of pull zones. */
final class EdgeRuleResource extends AbstractResource
{
    use EdgeRuleOperations;

    /**
     * Add/Update Edge Rule
     *
     * `POST /pullzone/{pullZoneId}/edgerules/addOrUpdate`
     *
     * @param int      $pullZoneId The ID of the Pull Zone where the Edge Rule will be created
     * @param EdgeRule $edgeRule
     */
    public function addOrUpdate(int $pullZoneId, EdgeRule $edgeRule): EdgeRule
    {
        $data = $this->connection->json(Method::Post, "pullzone/{$pullZoneId}/edgerules/addOrUpdate", body: $edgeRule->toArray());

        return self::toModel(EdgeRule::class, $data);
    }

    /**
     * Delete Edge Rule
     *
     * `DELETE /pullzone/{pullZoneId}/edgerules/{edgeRuleId}`
     *
     * @param int    $pullZoneId The ID of the Pull Zone that contains the Edge Rule
     * @param string $edgeRuleId The ID of the Edge Rule that should be deleted
     */
    public function delete(int $pullZoneId, string $edgeRuleId): void
    {
        $this->connection->json(Method::Delete, "pullzone/{$pullZoneId}/edgerules/{$this->segment($edgeRuleId)}");
    }
}
