<?php

declare(strict_types=1);

// This file is generated by tools/generate.php from resources/specs/core.json. Do not edit.

namespace GoSuccess\Bunny\Core\Resource;

use DateTimeInterface;
use GoSuccess\Bunny\Core\Model\LoadBalancerAccountSummary;
use GoSuccess\Bunny\Core\Model\LoadBalancerAttachedZone;
use GoSuccess\Bunny\Core\Model\LoadBalancerStatistics;
use GoSuccess\Bunny\Core\Model\LoadBalancerUsage;
use GoSuccess\Bunny\Http\Method;
use GoSuccess\Bunny\Resource\AbstractResource;

/** Load balancer statistics and usage. */
final class LoadBalancerResource extends AbstractResource
{
    /**
     * Get Load Balancer statistics
     *
     * `GET /loadbalancer/{loadBalancerId}/statistics`
     *
     * @param int                    $loadBalancerId
     * @param DateTimeInterface|null $from           (Optional) The start date of the statistics. If no value is passed, the last 24 hours will be returned. Rounded to full-day boundaries unless hourly=true and exactRange=true.
     * @param DateTimeInterface|null $to             (Optional) The end date of the statistics. Rounded to full-day boundaries unless hourly=true and exactRange=true.
     * @param bool|null              $hourly         (Optional) If true, the statistics will be returned in hourly grouping. Hourly statistics are available for the last 30 days only.
     * @param bool|null              $exactRange     (Optional) If true and hourly=true, the exact hour components of from and to will be preserved instead of rounding to full-day boundaries.
     */
    public function statistics(
        int $loadBalancerId,
        ?DateTimeInterface $from = null,
        ?DateTimeInterface $to = null,
        ?bool $hourly = null,
        ?bool $exactRange = null,
    ): LoadBalancerStatistics {
        $data = $this->connection->json(Method::Get, "loadbalancer/{$loadBalancerId}/statistics", [
            'from' => $from,
            'to' => $to,
            'hourly' => $hourly,
            'exactRange' => $exactRange,
        ]);

        return self::toModel(LoadBalancerStatistics::class, $data);
    }

    /**
     * Get the pull zones attached to a Load Balancer
     *
     * `GET /loadbalancer/{loadBalancerId}/pullzones`
     *
     * @param int                    $loadBalancerId
     * @param DateTimeInterface|null $from
     * @param DateTimeInterface|null $to
     *
     * @return list<LoadBalancerAttachedZone>
     */
    public function attachedPullZones(
        int $loadBalancerId,
        ?DateTimeInterface $from = null,
        ?DateTimeInterface $to = null,
    ): array {
        $data = $this->connection->json(Method::Get, "loadbalancer/{$loadBalancerId}/pullzones", [
            'from' => $from,
            'to' => $to,
        ]);

        return self::toModelList(LoadBalancerAttachedZone::class, $data);
    }

    /**
     * Get statistics roll-ups for all Load Balancers on the account
     *
     * `GET /loadbalancer/statistics`
     *
     * @param DateTimeInterface|null $from
     * @param DateTimeInterface|null $to
     *
     * @return list<LoadBalancerAccountSummary>
     */
    public function accountStatistics(?DateTimeInterface $from = null, ?DateTimeInterface $to = null): array
    {
        $data = $this->connection->json(Method::Get, 'loadbalancer/statistics', [
            'from' => $from,
            'to' => $to,
        ]);

        return self::toModelList(LoadBalancerAccountSummary::class, $data);
    }

    /**
     * Get current-period request usage and pricing for a Load Balancer
     *
     * `GET /loadbalancer/{loadBalancerId}/usage`
     *
     * @param int      $loadBalancerId
     * @param int|null $year           Year of the usage month (UTC). Defaults to the current year; supply together with month.
     * @param int|null $month          Month of the usage month, 1-12 (UTC). Defaults to the current month; supply together with year.
     */
    public function usage(int $loadBalancerId, ?int $year = null, ?int $month = null): LoadBalancerUsage
    {
        $data = $this->connection->json(Method::Get, "loadbalancer/{$loadBalancerId}/usage", [
            'year' => $year,
            'month' => $month,
        ]);

        return self::toModel(LoadBalancerUsage::class, $data);
    }
}
