<?php

declare(strict_types=1);

// This file is generated by tools/generate.php from resources/specs/core.json. Do not edit.

namespace GoSuccess\Bunny\Core\Resource;

use GoSuccess\Bunny\Core\Enum\PricingEstimationSource;
use GoSuccess\Bunny\Core\Model\PriceEstimation;
use GoSuccess\Bunny\Http\Method;
use GoSuccess\Bunny\Resource\AbstractResource;

/** Price estimations. */
final class PricingResource extends AbstractResource
{
    /**
     * Get active price for a resource and optionally cost estimate if usage amount provided
     *
     * `GET /v1/pricing/{source}/{resourceId}`
     *
     * @param PricingEstimationSource $source     The billing source to estimate pricing for
     * @param int                     $resourceId The ID of the resource (pull zone, storage zone, video library, or edge script)
     * @param int|null                $units      Optional number of units to calculate estimated total cost
     */
    public function estimate(PricingEstimationSource $source, int $resourceId, ?int $units = null): PriceEstimation
    {
        $data = $this->connection->json(Method::Get, "v1/pricing/{$this->segment($source)}/{$resourceId}", [
            'units' => $units,
        ]);

        return self::toModel(PriceEstimation::class, $data);
    }
}
