<?php

declare(strict_types=1);

// This file is generated by tools/generate.php from resources/specs/core.json. Do not edit.

namespace GoSuccess\Bunny\Core\Resource;

use GoSuccess\Bunny\Core\Model\SearchResults;
use GoSuccess\Bunny\Http\Method;
use GoSuccess\Bunny\Resource\AbstractResource;

/** Global search across the resources of the account. */
final class SearchResource extends AbstractResource
{
    /**
     * Global Search
     *
     * `GET /search`
     *
     * @param string|null $search
     * @param int|null    $from
     * @param int|null    $size
     */
    public function query(?string $search = null, ?int $from = null, ?int $size = null): SearchResults
    {
        $data = $this->connection->json(Method::Get, 'search', [
            'search' => $search,
            'from' => $from,
            'size' => $size,
        ]);

        return self::toModel(SearchResults::class, $data);
    }
}
