<?php

declare(strict_types=1);

// This file is generated by tools/generate.php from resources/specs/core.json. Do not edit.

namespace GoSuccess\Bunny\Core\Resource;

use DateTimeInterface;
use GoSuccess\Bunny\Core\Model\VideoLibrary;
use GoSuccess\Bunny\Core\Model\VideoLibraryCreate;
use GoSuccess\Bunny\Core\Model\VideoLibraryDrmStatistics;
use GoSuccess\Bunny\Core\Model\VideoLibraryLanguage;
use GoSuccess\Bunny\Core\Model\VideoLibraryTranscriptionStatistics;
use GoSuccess\Bunny\Core\Model\VideoLibraryUpdate;
use GoSuccess\Bunny\Core\Pagination;
use GoSuccess\Bunny\Core\Resource\Handwritten\VideoLibraryOperations;
use GoSuccess\Bunny\Http\Method;
use GoSuccess\Bunny\Model\Cast;
use GoSuccess\Bunny\Pagination\Page;
use GoSuccess\Bunny\Pagination\Paginator;
use GoSuccess\Bunny\Resource\AbstractResource;

/**
 * Stream video libraries: settings, API keys, referrer rules, watermarks and statistics. Videos are handled by the Stream API.
 */
final class VideoLibraryResource extends AbstractResource
{
    use VideoLibraryOperations;

    /**
     * List Video Libraries
     *
     * `GET /videolibrary`
     *
     * @param int         $page    The page to return, starting at 1.
     * @param int         $perPage The number of items per page.
     * @param string|null $search  The search term that will be used to filter the results
     *
     * @return Page<VideoLibrary>
     */
    public function list(int $page = 1, int $perPage = 100, ?string $search = null): Page
    {
        $data = self::expectObject($this->connection->json(Method::Get, 'videolibrary', [
            'page' => $page,
            'perPage' => $perPage,
            'search' => $search,
        ]));

        return Pagination::page($data, Cast::modelList(VideoLibrary::class, $data['Items'] ?? null));
    }

    /**
     * Iterate lazily over every item of list(), across all pages.
     *
     * `GET /videolibrary`
     *
     * @param string|null $search  The search term that will be used to filter the results
     * @param int         $perPage The number of items per page.
     *
     * @return Paginator<VideoLibrary>
     */
    public function all(?string $search = null, int $perPage = 1000): Paginator
    {
        return new Paginator(fn(int|string|null $position): Page => $this->list(
            page: \is_int($position) ? $position : 1,
            perPage: $perPage,
            search: $search,
        ));
    }

    /**
     * Get Video Library
     *
     * `GET /videolibrary/{id}`
     *
     * @param int $id The ID of the Video Library that will be returned
     */
    public function get(int $id): VideoLibrary
    {
        $data = $this->connection->json(Method::Get, "videolibrary/{$id}");

        return self::toModel(VideoLibrary::class, $data);
    }

    /**
     * Add Video Library
     *
     * `POST /videolibrary`
     *
     * @param VideoLibraryCreate $library
     */
    public function create(VideoLibraryCreate $library): VideoLibrary
    {
        $data = $this->connection->json(Method::Post, 'videolibrary', body: $library->toArray());

        return self::toModel(VideoLibrary::class, $data);
    }

    /**
     * Update Video Library
     *
     * `POST /videolibrary/{id}`
     *
     * @param int                $id      The ID of the Video Library to update
     * @param VideoLibraryUpdate $changes
     */
    public function update(int $id, VideoLibraryUpdate $changes): VideoLibrary
    {
        $data = $this->connection->json(Method::Post, "videolibrary/{$id}", body: $changes->toArray());

        return self::toModel(VideoLibrary::class, $data);
    }

    /**
     * Delete Video Library
     *
     * `DELETE /videolibrary/{id}`
     *
     * @param int $id The ID of the Video Library that should be deleted
     */
    public function delete(int $id): void
    {
        $this->connection->json(Method::Delete, "videolibrary/{$id}");
    }

    /**
     * Get Languages
     *
     * `GET /videolibrary/languages`
     *
     * @return list<VideoLibraryLanguage>
     */
    public function languages(): array
    {
        $data = $this->connection->json(Method::Get, 'videolibrary/languages');

        return self::toModelList(VideoLibraryLanguage::class, $data);
    }

    /**
     * Reset API Key
     *
     * `POST /videolibrary/{id}/resetApiKey`
     *
     * @param int $id The ID of the video library that should have the API key reset
     */
    public function resetApiKey(int $id): void
    {
        $this->connection->json(Method::Post, "videolibrary/{$id}/resetApiKey");
    }

    /**
     * Reset Read Only API Key
     *
     * `POST /videolibrary/{id}/resetReadOnlyApiKey`
     *
     * @param int $id The ID of the video library that should have the read only API key reset
     */
    public function resetReadOnlyApiKey(int $id): void
    {
        $this->connection->json(Method::Post, "videolibrary/{$id}/resetReadOnlyApiKey");
    }

    /**
     * Add Allowed Referer
     *
     * `POST /videolibrary/{id}/addAllowedReferrer`
     *
     * @param int    $id       The ID of the requested Video Library
     * @param string $hostname The hostname that will be added as an allowed referer
     */
    public function addAllowedReferrer(int $id, string $hostname): void
    {
        $body = [
            'Hostname' => $hostname,
        ];

        $this->connection->json(Method::Post, "videolibrary/{$id}/addAllowedReferrer", body: $body);
    }

    /**
     * Remove Allowed Referer
     *
     * `POST /videolibrary/{id}/removeAllowedReferrer`
     *
     * @param int    $id       The ID of the requested Video Library
     * @param string $hostname The hostname that will be removed as an allowed referer
     */
    public function removeAllowedReferrer(int $id, string $hostname): void
    {
        $body = [
            'Hostname' => $hostname,
        ];

        $this->connection->json(Method::Post, "videolibrary/{$id}/removeAllowedReferrer", body: $body);
    }

    /**
     * Add Blocked Referer
     *
     * `POST /videolibrary/{id}/addBlockedReferrer`
     *
     * @param int    $id       The ID of the requested Video Library
     * @param string $hostname The hostname that will be added as a blocked referer
     */
    public function addBlockedReferrer(int $id, string $hostname): void
    {
        $body = [
            'Hostname' => $hostname,
        ];

        $this->connection->json(Method::Post, "videolibrary/{$id}/addBlockedReferrer", body: $body);
    }

    /**
     * Remove Blocked Referer
     *
     * `POST /videolibrary/{id}/removeBlockedReferrer`
     *
     * @param int    $id       The ID of the requested Video Library
     * @param string $hostname The hostname that will be removed as a blocked referer
     */
    public function removeBlockedReferrer(int $id, string $hostname): void
    {
        $body = [
            'Hostname' => $hostname,
        ];

        $this->connection->json(Method::Post, "videolibrary/{$id}/removeBlockedReferrer", body: $body);
    }

    /**
     * Delete Watermark
     *
     * `DELETE /videolibrary/{id}/watermark`
     *
     * @param int $id The ID of the requested Video Library
     */
    public function deleteWatermark(int $id): void
    {
        $this->connection->json(Method::Delete, "videolibrary/{$id}/watermark");
    }

    /**
     * Delete Live Thumbnail
     *
     * `DELETE /videolibrary/{id}/live/thumbnail`
     *
     * @param int $id The ID of the requested Video Library
     */
    public function deleteLiveThumbnail(int $id): void
    {
        $this->connection->json(Method::Delete, "videolibrary/{$id}/live/thumbnail");
    }

    /**
     * Delete Live Watermark
     *
     * `DELETE /videolibrary/{id}/live/watermark`
     *
     * @param int $id The ID of the requested Video Library
     */
    public function deleteLiveWatermark(int $id): void
    {
        $this->connection->json(Method::Delete, "videolibrary/{$id}/live/watermark");
    }

    /**
     * Get Video Library Transcribing Statistics
     *
     * `GET /videolibrary/{id}/transcribing/statistics`
     *
     * @param int                    $id       The ID of the video library for which the transcribing statistics will be returned
     * @param DateTimeInterface|null $dateFrom (Optional) The start date of the statistics. If no value is passed, the last 14 days will be returned
     * @param DateTimeInterface|null $dateTo   (Optional) The end date of the statistics. If no value is passed, current date will be used
     */
    public function transcribingStatistics(int $id, ?DateTimeInterface $dateFrom = null, ?DateTimeInterface $dateTo = null): VideoLibraryTranscriptionStatistics
    {
        $data = $this->connection->json(Method::Get, "videolibrary/{$id}/transcribing/statistics", [
            'dateFrom' => $dateFrom,
            'dateTo' => $dateTo,
        ]);

        return self::toModel(VideoLibraryTranscriptionStatistics::class, $data);
    }

    /**
     * Get Video Library DRM Statistics
     *
     * `GET /videolibrary/{id}/drm/statistics`
     *
     * @param int                    $id       The ID of the video library for which the DRM statistics will be returned
     * @param DateTimeInterface|null $dateFrom (Optional) The start date of the statistics. If no value is passed, the last 14 days will be returned
     * @param DateTimeInterface|null $dateTo   (Optional) The end date of the statistics. If no value is passed, current date will be used
     */
    public function drmStatistics(int $id, ?DateTimeInterface $dateFrom = null, ?DateTimeInterface $dateTo = null): VideoLibraryDrmStatistics
    {
        $data = $this->connection->json(Method::Get, "videolibrary/{$id}/drm/statistics", [
            'dateFrom' => $dateFrom,
            'dateTo' => $dateTo,
        ]);

        return self::toModel(VideoLibraryDrmStatistics::class, $data);
    }
}
