<?php

declare(strict_types=1);

// This file is generated by tools/generate.php from resources/specs/stream.json. Do not edit.

namespace GoSuccess\Bunny\Stream\Resource;

use DateTimeInterface;
use GoSuccess\Bunny\Http\Connection;
use GoSuccess\Bunny\Http\Method;
use GoSuccess\Bunny\Resource\AbstractResource;
use GoSuccess\Bunny\Stream\Model\VideoStatistics;

/** View and watch time statistics of the library or of one video. */
final class StatisticsResource extends AbstractResource
{
    /**
     * @internal Created by the client.
     */
    public function __construct(Connection $connection, private readonly int $libraryId)
    {
        parent::__construct($connection);
    }

    /**
     * Get Video Statistics
     *
     * Returns time-series views and watch time, plus country-level aggregates, at the library level or for a specific video. Control the time window with dateFrom/dateTo and the granularity with hourly. Basic safeguards prevent spam and bot inflation by de-duplicating sessions and ignoring obviously invalid events.
     *
     * `GET /library/{libraryId}/statistics`
     *
     * @param DateTimeInterface|null $dateFrom  Optional start of the time range (UTC). If omitted or invalid, the last 30 days are returned.
     * @param DateTimeInterface|null $dateTo    Optional end of the time range (UTC). If omitted with a valid start, defaults to now; otherwise the last 30 days are returned.
     * @param bool|null              $hourly    Optional. If true, returns hourly data; otherwise daily (UTC). Default is daily.
     * @param string|null            $videoGuid Optional video GUID to filter results. When omitted, returns library-level aggregates.
     */
    public function get(
        ?DateTimeInterface $dateFrom = null,
        ?DateTimeInterface $dateTo = null,
        ?bool $hourly = null,
        ?string $videoGuid = null,
    ): VideoStatistics {
        $data = $this->connection->json(Method::Get, "library/{$this->libraryId}/statistics", [
            'dateFrom' => $dateFrom,
            'dateTo' => $dateTo,
            'hourly' => $hourly,
            'videoGuid' => $videoGuid,
        ]);

        return self::toModel(VideoStatistics::class, $data);
    }
}
