<?php

declare(strict_types=1);

// This file is generated by tools/generate.php from resources/specs/stream.json. Do not edit.

namespace GoSuccess\Bunny\Stream\Model;

use GoSuccess\Bunny\Model\Cast;
use GoSuccess\Bunny\Model\ResponseModel;

/** Schema: CaptionValidationModel */
final readonly class CaptionValidation implements ResponseModel
{
    public function __construct(
        /** Denotes whether uploaded captions file was valid */
        public bool $valid = false,
        /**
         * When uploaded file was invalid, will contain errors found
         *
         * @var list<string>
         */
        public array $errorList = [],
        /**
         * When uploaded file was valid but non-breaking issues were found, will contain issues found
         *
         * @var list<string>
         */
        public array $warningList = [],
        /** UI-friendly summary of warnings found in the uploaded captions file */
        public ?string $warningMessage = null,
    ) {}

    public static function fromArray(array $data): static
    {
        return new self(
            valid: Cast::bool($data['valid'] ?? null) ?? false,
            errorList: Cast::listOf($data['errorList'] ?? null, Cast::string(...)),
            warningList: Cast::listOf($data['warningList'] ?? null, Cast::string(...)),
            warningMessage: Cast::string($data['warningMessage'] ?? null),
        );
    }
}
