<?php

declare(strict_types=1);

// This file is generated by tools/generate.php from resources/specs/stream.json. Do not edit.

namespace GoSuccess\Bunny\Stream\Model;

use GoSuccess\Bunny\Model\Cast;
use GoSuccess\Bunny\Model\RequestModel;
use GoSuccess\Bunny\Model\ResponseModel;
use GoSuccess\Bunny\Model\Undefined;

/** Schema: ChapterModel */
final readonly class Chapter implements RequestModel, ResponseModel
{
    /** The title of the chapter, up to 255 characters. */
    public string $title;

    /**
     * The start time of the chapter in seconds. Must be less than End and within the video's duration; chapters must not overlap each other.
     */
    public int $start;

    /**
     * The end time of the chapter in seconds. Must be greater than Start and within the video's duration; chapters must not overlap each other.
     */
    public int $end;

    /**
     * Payload keys the caller provided; toArray() sends exactly these.
     *
     * @var array<string, true>
     */
    private array $provided;

    public function __construct(
        string|Undefined $title = Undefined::Value,
        int|Undefined $start = Undefined::Value,
        int|Undefined $end = Undefined::Value,
    ) {
        $this->title = $title instanceof Undefined ? '' : $title;
        $this->start = $start instanceof Undefined ? 0 : $start;
        $this->end = $end instanceof Undefined ? 0 : $end;
        $this->provided = array_filter([
            'title' => !$title instanceof Undefined,
            'start' => !$start instanceof Undefined,
            'end' => !$end instanceof Undefined,
        ]);
    }

    public static function fromArray(array $data): static
    {
        return new self(
            title: Cast::string($data['title'] ?? null) ?? Undefined::Value,
            start: Cast::int($data['start'] ?? null) ?? Undefined::Value,
            end: Cast::int($data['end'] ?? null) ?? Undefined::Value,
        );
    }

    public function toArray(): array
    {
        $data = [];

        if (isset($this->provided['title'])) {
            $data['title'] = $this->title;
        }

        if (isset($this->provided['start'])) {
            $data['start'] = $this->start;
        }

        if (isset($this->provided['end'])) {
            $data['end'] = $this->end;
        }

        return $data;
    }
}
