<?php

declare(strict_types=1);

// This file is generated by tools/generate.php from resources/specs/stream.json. Do not edit.

namespace GoSuccess\Bunny\Stream\Model;

use GoSuccess\Bunny\Model\Cast;
use GoSuccess\Bunny\Model\RequestModel;
use GoSuccess\Bunny\Model\ResponseModel;
use GoSuccess\Bunny\Model\Undefined;

/** Schema: MetaTagModel */
final readonly class MetaTag implements RequestModel, ResponseModel
{
    /**
     * The meta tag key. Must match ^[A-Za-z0-9._:'"-]+$. Setting a tag with the property "description" also updates the video's Description field.
     */
    public ?string $property;

    /** The meta tag value. HTML/markup is stripped and the value is stored as plain text. */
    public ?string $value;

    /**
     * Payload keys the caller provided; toArray() sends exactly these.
     *
     * @var array<string, true>
     */
    private array $provided;

    public function __construct(
        string|Undefined|null $property = Undefined::Value,
        string|Undefined|null $value = Undefined::Value,
    ) {
        $this->property = $property instanceof Undefined ? null : $property;
        $this->value = $value instanceof Undefined ? null : $value;
        $this->provided = array_filter([
            'property' => !$property instanceof Undefined,
            'value' => !$value instanceof Undefined,
        ]);
    }

    public static function fromArray(array $data): static
    {
        return new self(
            property: Cast::string($data['property'] ?? null) ?? Undefined::Value,
            value: Cast::string($data['value'] ?? null) ?? Undefined::Value,
        );
    }

    public function toArray(): array
    {
        $data = [];

        if (isset($this->provided['property'])) {
            $data['property'] = $this->property;
        }

        if (isset($this->provided['value'])) {
            $data['value'] = $this->value;
        }

        return $data;
    }
}
