<?php

declare(strict_types=1);

// This file is generated by tools/generate.php from resources/specs/stream.json. Do not edit.

namespace GoSuccess\Bunny\Stream\Model;

use GoSuccess\Bunny\Model\Cast;
use GoSuccess\Bunny\Model\ResponseModel;

/** Schema: ResolutionsCleanupModel */
final readonly class ResolutionsCleanup implements ResponseModel
{
    public function __construct(
        /** The GUID of the video. */
        public ?string $videoId = null,
        /** The ID of the video library. */
        public int $videoLibraryId = 0,
        /**
         * Resolutions selected for removal as part of this cleanup, across the HLS playlist, object storage, and MP4 fallback set. Populated even when dryRun is true or an individual deletion fails — see UpdatedAvailableResolutions/ModifiedPlaylist/DeletedStorageObjects for what was actually changed.
         *
         * @var list<string>
         */
        public array $resolutionsToDelete = [],
        /**
         * Resolutions selected for removal from the HLS master playlist. Populated even when dryRun is true.
         *
         * @var list<string>
         */
        public array $resolutionsToDeleteFromPlaylist = [],
        /**
         * Resolutions selected for removal from object storage. Populated even when dryRun is true or an individual deletion fails.
         *
         * @var list<string>
         */
        public array $resolutionsToDeleteFromStorage = [],
        /**
         * Resolutions selected for removal from the MP4 fallback set. Populated even when dryRun is true.
         *
         * @var list<string>
         */
        public array $resolutionsToDeleteFromMp4 = [],
        /**
         * Storage object paths selected for deletion as part of this cleanup. These are candidates, not confirmations: the list is populated even when dryRun is true or when an individual deletion fails — see DeletedStorageObjects for whether at least one deletion actually succeeded.
         *
         * @var list<string>
         */
        public array $storageObjectsToDelete = [],
        /**
         * The video's available resolutions after this cleanup.
         *
         * @var list<string>
         */
        public array $availableResolutionsAfter = [],
        /** Whether the video's AvailableResolutions field was rewritten as part of this cleanup. */
        public bool $updatedAvailableResolutions = false,
        /** Whether the HLS master playlist was rewritten to remove the deleted resolutions. */
        public bool $modifiedPlaylist = false,
        /**
         * Whether at least one of the storage objects in StorageObjectsToDelete was actually deleted (always false when dryRun is true). Individual objects can still have failed to delete — their failures are logged and do not clear this flag — so this confirms the cleanup did something, not that it removed everything listed.
         */
        public bool $deletedStorageObjects = false,
        /** Whether the original uploaded source file was deleted from storage as part of this operation. */
        public bool $deletedOriginal = false,
    ) {}

    public static function fromArray(array $data): static
    {
        return new self(
            videoId: Cast::string($data['videoId'] ?? null),
            videoLibraryId: Cast::int($data['videoLibraryId'] ?? null) ?? 0,
            resolutionsToDelete: Cast::listOf($data['resolutionsToDelete'] ?? null, Cast::string(...)),
            resolutionsToDeleteFromPlaylist: Cast::listOf($data['resolutionsToDeleteFromPlaylist'] ?? null, Cast::string(...)),
            resolutionsToDeleteFromStorage: Cast::listOf($data['resolutionsToDeleteFromStorage'] ?? null, Cast::string(...)),
            resolutionsToDeleteFromMp4: Cast::listOf($data['resolutionsToDeleteFromMp4'] ?? null, Cast::string(...)),
            storageObjectsToDelete: Cast::listOf($data['storageObjectsToDelete'] ?? null, Cast::string(...)),
            availableResolutionsAfter: Cast::listOf($data['availableResolutionsAfter'] ?? null, Cast::string(...)),
            updatedAvailableResolutions: Cast::bool($data['updatedAvailableResolutions'] ?? null) ?? false,
            modifiedPlaylist: Cast::bool($data['modifiedPlaylist'] ?? null) ?? false,
            deletedStorageObjects: Cast::bool($data['deletedStorageObjects'] ?? null) ?? false,
            deletedOriginal: Cast::bool($data['deletedOriginal'] ?? null) ?? false,
        );
    }
}
