<?php

declare(strict_types=1);

// This file is generated by tools/generate.php from resources/specs/stream.json. Do not edit.

namespace GoSuccess\Bunny\Stream\Model;

use GoSuccess\Bunny\Model\Cast;
use GoSuccess\Bunny\Model\ResponseModel;
use GoSuccess\Bunny\Stream\Enum\SmartGenerateStatus;

/** Schema: SmartGenerateFeaturesStatusModel */
final readonly class SmartGenerateFeaturesStatus implements ResponseModel
{
    public function __construct(
        /** Smart generate status for the video title, when applicable. */
        public ?SmartGenerateStatus $title = null,
        /** Smart generate status for the video description, when applicable. */
        public ?SmartGenerateStatus $description = null,
        /** Smart generate status for chapters, when applicable. */
        public ?SmartGenerateStatus $chapters = null,
        /** Smart generate status for moments, when applicable. */
        public ?SmartGenerateStatus $moments = null,
    ) {}

    public static function fromArray(array $data): static
    {
        return new self(
            title: Cast::intEnum(SmartGenerateStatus::class, $data['title'] ?? null),
            description: Cast::intEnum(SmartGenerateStatus::class, $data['description'] ?? null),
            chapters: Cast::intEnum(SmartGenerateStatus::class, $data['chapters'] ?? null),
            moments: Cast::intEnum(SmartGenerateStatus::class, $data['moments'] ?? null),
        );
    }
}
