<?php

declare(strict_types=1);

// This file is generated by tools/generate.php from resources/specs/stream.json. Do not edit.

namespace GoSuccess\Bunny\Stream\Model;

use DateTimeImmutable;
use GoSuccess\Bunny\Model\Cast;
use GoSuccess\Bunny\Model\ResponseModel;
use GoSuccess\Bunny\Stream\Enum\TranscodingIssue;
use GoSuccess\Bunny\Stream\Enum\TranscodingSeverity;

/** Schema: TranscodingMessageModel */
final readonly class TranscodingMessage implements ResponseModel
{
    public function __construct(
        /** Date and time when this message was added (UTC). */
        public ?DateTimeImmutable $timeStamp = null,
        /** Message severity. See Severity. */
        public ?TranscodingSeverity $level = null,
        /** Issue code identifying the specific transcoding problem. See IssueCodes. */
        public ?TranscodingIssue $issueCode = null,
        /** Human-readable description of the issue. */
        public ?string $message = null,
        /** Additional context value for the issue, if applicable; otherwise empty. */
        public ?string $value = null,
    ) {}

    public static function fromArray(array $data): static
    {
        return new self(
            timeStamp: Cast::dateTime($data['timeStamp'] ?? null),
            level: Cast::intEnum(TranscodingSeverity::class, $data['level'] ?? null),
            issueCode: Cast::intEnum(TranscodingIssue::class, $data['issueCode'] ?? null),
            message: Cast::string($data['message'] ?? null),
            value: Cast::string($data['value'] ?? null),
        );
    }
}
