<?php

declare(strict_types=1);

// This file is generated by tools/generate.php from resources/specs/stream.json. Do not edit.

namespace GoSuccess\Bunny\Stream\Model;

use DateTimeImmutable;
use GoSuccess\Bunny\Model\Cast;
use GoSuccess\Bunny\Model\ResponseModel;

/** Schema: VideoStorageSizeModel */
final readonly class VideoStorageSize implements ResponseModel
{
    public function __construct(
        /**
         * Size in bytes of each encoded rendition, keyed by "{resolution}-{codec}" (e.g. "720p-h264"). Videos encoded before the current storage layout can also report legacy "{width}x{height}" resolutions, e.g. "1920x1080-h264".
         *
         * @var array<array-key, CodecRenditionSize>
         */
        public array $encoded = [],
        /** Size in bytes of the video's JPEG thumbnails. */
        public int $thumbnails = 0,
        /** Size in bytes of the video's GIF and WEBP previews. */
        public int $previews = 0,
        /** Size in bytes of the original uploaded video file. */
        public int $originals = 0,
        /** Size in bytes of the MP4 fallback rendition. */
        public int $mp4Fallback = 0,
        /** Size in bytes of everything else: playlists, manifests, captions, audio extracts, etc. */
        public int $miscellaneous = 0,
        /** Timestamp when this storage size was calculated (UTC). */
        public ?DateTimeImmutable $calculatedAt = null,
    ) {}

    public static function fromArray(array $data): static
    {
        return new self(
            encoded: Cast::mapOf($data['encoded'] ?? null, static fn(mixed $value): ?CodecRenditionSize => Cast::model(CodecRenditionSize::class, $value)),
            thumbnails: Cast::int($data['thumbnails'] ?? null) ?? 0,
            previews: Cast::int($data['previews'] ?? null) ?? 0,
            originals: Cast::int($data['originals'] ?? null) ?? 0,
            mp4Fallback: Cast::int($data['mp4Fallback'] ?? null) ?? 0,
            miscellaneous: Cast::int($data['miscellaneous'] ?? null) ?? 0,
            calculatedAt: Cast::dateTime($data['calculatedAt'] ?? null),
        );
    }
}
