<?php

declare(strict_types=1);

// This file is generated by tools/generate.php from resources/specs/stream.json. Do not edit.

namespace GoSuccess\Bunny\Stream\Model;

use GoSuccess\Bunny\Model\RequestModel;
use GoSuccess\Bunny\Model\Undefined;

/** Schema: UpdateVideoModel */
final readonly class VideoUpdate implements RequestModel
{
    public function __construct(
        /** The title of the video */
        public string|Undefined|null $title = Undefined::Value,
        /**
         * The ID of the collection where the video belongs. Omit/null to leave the current collection unchanged; send an empty string to remove the video from its collection.
         */
        public string|Undefined|null $collectionId = Undefined::Value,
        /**
         * The list of chapters available for the video, up to 200. Omit/null to leave existing chapters unchanged; providing a list, including an empty one, fully replaces all existing chapters.
         *
         * @var list<Chapter>|Undefined
         */
        public array|Undefined $chapters = Undefined::Value,
        /**
         * The list of moments available for the video, up to 200. Omit/null to leave existing moments unchanged; providing a list, including an empty one, fully replaces all existing moments.
         *
         * @var list<Moment>|Undefined
         */
        public array|Undefined $moments = Undefined::Value,
        /**
         * The meta tags added to the video, up to 50. Omit/null to leave existing tags unchanged; providing a list, including an empty one, fully replaces all existing tags. Setting a tag with Property "description" also updates the video's Description field.
         *
         * @var list<MetaTag>|Undefined
         */
        public array|Undefined $metaTags = Undefined::Value,
    ) {}

    public function toArray(): array
    {
        $data = [];

        if (!$this->title instanceof Undefined) {
            $data['title'] = $this->title;
        }

        if (!$this->collectionId instanceof Undefined) {
            $data['collectionId'] = $this->collectionId;
        }

        if (!$this->chapters instanceof Undefined) {
            $data['chapters'] = array_map(static fn(Chapter $item): array => $item->toArray(), $this->chapters);
        }

        if (!$this->moments instanceof Undefined) {
            $data['moments'] = array_map(static fn(Moment $item): array => $item->toArray(), $this->moments);
        }

        if (!$this->metaTags instanceof Undefined) {
            $data['metaTags'] = array_map(static fn(MetaTag $item): array => $item->toArray(), $this->metaTags);
        }

        return $data;
    }
}
