<?php

declare(strict_types=1);

// This file is generated by tools/generate.php from resources/specs/stream.json. Do not edit.

namespace GoSuccess\Bunny\Stream\Model;

use GoSuccess\Bunny\Model\Cast;
use GoSuccess\Bunny\Model\ResponseModel;

/** Schema: VideoHeatmapModel */
final readonly class VideoHeatmap implements ResponseModel
{
    public function __construct(
        /**
         * Timeline heatmap as segment-index to intensity (0–100). Keys represent consecutive segments from the start of the video; values are normalized so 100 equals the most‑watched segment. Missing segments imply 0.
         *
         * @var array<array-key, int>
         */
        public array $heatmap = [],
    ) {}

    public static function fromArray(array $data): static
    {
        return new self(
            heatmap: Cast::mapOf($data['heatmap'] ?? null, Cast::int(...)),
        );
    }
}
