<?php

declare(strict_types=1);

// This file is generated by tools/generate.php from resources/specs/stream.json. Do not edit.

namespace GoSuccess\Bunny\Stream\Model;

use GoSuccess\Bunny\Model\Cast;
use GoSuccess\Bunny\Model\ResponseModel;

/** Schema: VideoResolutionsInfoModel */
final readonly class VideoResolutionsInfo implements ResponseModel
{
    public function __construct(
        /** The GUID of the video. */
        public ?string $videoId = null,
        /** The ID of the video library. */
        public int $videoLibraryId = 0,
        /**
         * Resolutions currently ready to stream for this video.
         *
         * @var list<string>
         */
        public array $availableResolutions = [],
        /**
         * Resolutions the video library is configured to encode; may not all exist yet for this video.
         *
         * @var list<string>
         */
        public array $configuredResolutions = [],
        /**
         * Resolutions declared in the video's HLS master playlist.
         *
         * @var list<ResolutionReference>
         */
        public array $playlistResolutions = [],
        /**
         * Resolutions found as folders in object storage; can diverge from PlaylistResolutions.
         *
         * @var list<ResolutionReference>
         */
        public array $storageResolutions = [],
        /**
         * Resolutions found as MP4 fallback files in object storage.
         *
         * @var list<ResolutionReference>
         */
        public array $mp4Resolutions = [],
        /**
         * All storage objects found for this video.
         *
         * @var list<VideoStorageObject>
         */
        public array $storageObjects = [],
        /**
         * Storage folders using the legacy "{width}x{height}" naming, populated only when HasBothOldAndNewResolutionFormat is true.
         *
         * @var list<VideoStorageObject>
         */
        public array $oldResolutions = [],
        /**
         * True when storage contains both the legacy "{width}x{height}" folder naming and the current "{height}p" naming for the same video — can happen when a codec was added via API rather than a full re-encode.
         */
        public bool $hasBothOldAndNewResolutionFormat = false,
        /** Whether the original uploaded source file is present in storage. */
        public bool $hasOriginal = false,
    ) {}

    public static function fromArray(array $data): static
    {
        return new self(
            videoId: Cast::string($data['videoId'] ?? null),
            videoLibraryId: Cast::int($data['videoLibraryId'] ?? null) ?? 0,
            availableResolutions: Cast::listOf($data['availableResolutions'] ?? null, Cast::string(...)),
            configuredResolutions: Cast::listOf($data['configuredResolutions'] ?? null, Cast::string(...)),
            playlistResolutions: Cast::modelList(ResolutionReference::class, $data['playlistResolutions'] ?? null),
            storageResolutions: Cast::modelList(ResolutionReference::class, $data['storageResolutions'] ?? null),
            mp4Resolutions: Cast::modelList(ResolutionReference::class, $data['mp4Resolutions'] ?? null),
            storageObjects: Cast::modelList(VideoStorageObject::class, $data['storageObjects'] ?? null),
            oldResolutions: Cast::modelList(VideoStorageObject::class, $data['oldResolutions'] ?? null),
            hasBothOldAndNewResolutionFormat: Cast::bool($data['hasBothOldAndNewResolutionFormat'] ?? null) ?? false,
            hasOriginal: Cast::bool($data['hasOriginal'] ?? null) ?? false,
        );
    }
}
