<?php

declare(strict_types=1);

// This file is generated by tools/generate.php from resources/specs/stream.json. Do not edit.

namespace GoSuccess\Bunny\Stream\Model;

use GoSuccess\Bunny\Model\Cast;
use GoSuccess\Bunny\Model\ResponseModel;

/** Schema: VideoStatisticsModel */
final readonly class VideoStatistics implements ResponseModel
{
    public function __construct(
        /**
         * Shows the number of playback starts over time, with each data point representing the count of view starts in the corresponding UTC interval (hourly or daily). It is available at both the library level (aggregated across all videos) and the video level (for a single video). A playback start is counted once per viewer session per video and empty intervals are shown as zero.
         *
         * @var array<array-key, int>
         */
        public array $viewsChart = [],
        /**
         * Shows the cumulative time viewers spent watching over time, with each data point representing total watch time in the corresponding UTC interval (hourly or daily). It is available at both the library level (aggregated across all videos) and the video level (for a single video). Rewatches and repeated visits add to the total and empty intervals are shown as zero.
         *
         * @var array<array-key, int>
         */
        public array $watchTimeChart = [],
        /**
         * Shows the total number of playback starts by country for the selected time range. It is available at both the library level (aggregated across all videos) and the video level (for a single video). Each country’s value reflects unique playback starts per viewer session based on IP geolocation at playback start.
         *
         * @var array<array-key, int>
         */
        public array $countryViewCounts = [],
        /**
         * Shows the total watch time by country for the selected time range. It is available at both the library level (aggregated across all videos) and the video level (for a single video). Values reflect cumulative viewing time (rewatches and repeated visits add to the total) based on IP geolocation at playback start.
         *
         * @var array<array-key, int>
         */
        public array $countryWatchTime = [],
        /**
         * Indicates how engaging a specific video is on a 0–100 scale based on viewing duration and viewing patterns; higher values reflect stronger viewer retention. Reported at the video level only and may be unavailable when there isn’t enough viewing data.
         */
        public int $engagementScore = 0,
    ) {}

    public static function fromArray(array $data): static
    {
        return new self(
            viewsChart: Cast::mapOf($data['viewsChart'] ?? null, Cast::int(...)),
            watchTimeChart: Cast::mapOf($data['watchTimeChart'] ?? null, Cast::int(...)),
            countryViewCounts: Cast::mapOf($data['countryViewCounts'] ?? null, Cast::int(...)),
            countryWatchTime: Cast::mapOf($data['countryWatchTime'] ?? null, Cast::int(...)),
            engagementScore: Cast::int($data['engagementScore'] ?? null) ?? 0,
        );
    }
}
