<?php

declare(strict_types=1);

// This file is generated by tools/generate.php from resources/specs/edge-scripting.json. Do not edit.

namespace GoSuccess\Bunny\EdgeScripting\Model;

use GoSuccess\Bunny\Model\Cast;
use GoSuccess\Bunny\Model\RequestModel;
use GoSuccess\Bunny\Model\ResponseModel;
use GoSuccess\Bunny\Model\Undefined;

/** Schema: DeployConfigurationModel */
final readonly class DeployConfiguration implements RequestModel, ResponseModel
{
    public ?string $branch;

    public ?string $installCommand;

    public ?string $buildCommand;

    public ?string $entryFile;

    public bool $createWorkflow;

    /**
     * Payload keys the caller provided; toArray() sends exactly these.
     *
     * @var array<string, true>
     */
    private array $provided;

    public function __construct(
        string|Undefined|null $branch = Undefined::Value,
        string|Undefined|null $installCommand = Undefined::Value,
        string|Undefined|null $buildCommand = Undefined::Value,
        string|Undefined|null $entryFile = Undefined::Value,
        bool|Undefined $createWorkflow = Undefined::Value,
    ) {
        $this->branch = $branch instanceof Undefined ? null : $branch;
        $this->installCommand = $installCommand instanceof Undefined ? null : $installCommand;
        $this->buildCommand = $buildCommand instanceof Undefined ? null : $buildCommand;
        $this->entryFile = $entryFile instanceof Undefined ? null : $entryFile;
        $this->createWorkflow = $createWorkflow instanceof Undefined ? false : $createWorkflow;
        $this->provided = array_filter([
            'Branch' => !$branch instanceof Undefined,
            'InstallCommand' => !$installCommand instanceof Undefined,
            'BuildCommand' => !$buildCommand instanceof Undefined,
            'EntryFile' => !$entryFile instanceof Undefined,
            'CreateWorkflow' => !$createWorkflow instanceof Undefined,
        ]);
    }

    public static function fromArray(array $data): static
    {
        return new self(
            branch: Cast::string($data['Branch'] ?? null) ?? Undefined::Value,
            installCommand: Cast::string($data['InstallCommand'] ?? null) ?? Undefined::Value,
            buildCommand: Cast::string($data['BuildCommand'] ?? null) ?? Undefined::Value,
            entryFile: Cast::string($data['EntryFile'] ?? null) ?? Undefined::Value,
            createWorkflow: Cast::bool($data['CreateWorkflow'] ?? null) ?? Undefined::Value,
        );
    }

    public function toArray(): array
    {
        $data = [];

        if (isset($this->provided['Branch'])) {
            $data['Branch'] = $this->branch;
        }

        if (isset($this->provided['InstallCommand'])) {
            $data['InstallCommand'] = $this->installCommand;
        }

        if (isset($this->provided['BuildCommand'])) {
            $data['BuildCommand'] = $this->buildCommand;
        }

        if (isset($this->provided['EntryFile'])) {
            $data['EntryFile'] = $this->entryFile;
        }

        if (isset($this->provided['CreateWorkflow'])) {
            $data['CreateWorkflow'] = $this->createWorkflow;
        }

        return $data;
    }
}
