<?php

declare(strict_types=1);

// This file is generated by tools/generate.php from resources/specs/edge-scripting.json. Do not edit.

namespace GoSuccess\Bunny\EdgeScripting\Model;

use DateTimeImmutable;
use GoSuccess\Bunny\EdgeScripting\Enum\EdgeScriptReleaseStatus;
use GoSuccess\Bunny\Model\Cast;
use GoSuccess\Bunny\Model\ResponseModel;

/** Schema: EdgeScriptReleaseModel */
final readonly class EdgeScriptRelease implements ResponseModel
{
    public function __construct(
        public int $id = 0,
        public bool $deleted = false,
        public ?string $code = null,
        public ?string $uuid = null,
        public ?string $note = null,
        public ?string $author = null,
        public ?string $authorEmail = null,
        public ?string $commitSha = null,
        /**
         * 0 = Archived
         * 1 = Live
         */
        public ?EdgeScriptReleaseStatus $status = null,
        public ?DateTimeImmutable $dateReleased = null,
        public ?DateTimeImmutable $datePublished = null,
    ) {}

    public static function fromArray(array $data): static
    {
        return new self(
            id: Cast::int($data['Id'] ?? null) ?? 0,
            deleted: Cast::bool($data['Deleted'] ?? null) ?? false,
            code: Cast::string($data['Code'] ?? null),
            uuid: Cast::string($data['Uuid'] ?? null),
            note: Cast::string($data['Note'] ?? null),
            author: Cast::string($data['Author'] ?? null),
            authorEmail: Cast::string($data['AuthorEmail'] ?? null),
            commitSha: Cast::string($data['CommitSha'] ?? null),
            status: Cast::intEnum(EdgeScriptReleaseStatus::class, $data['Status'] ?? null),
            dateReleased: Cast::dateTime($data['DateReleased'] ?? null),
            datePublished: Cast::dateTime($data['DatePublished'] ?? null),
        );
    }
}
