<?php

declare(strict_types=1);

// This file is generated by tools/generate.php from resources/specs/edge-scripting.json. Do not edit.

namespace GoSuccess\Bunny\EdgeScripting\Model;

use DateTimeImmutable;
use GoSuccess\Bunny\Model\Cast;
use GoSuccess\Bunny\Model\ResponseModel;

/** Schema: EdgeScriptCodeModel */
final readonly class EdgeScriptCode implements ResponseModel
{
    public function __construct(
        public ?string $code = null,
        public ?DateTimeImmutable $lastModified = null,
    ) {}

    public static function fromArray(array $data): static
    {
        return new self(
            code: Cast::string($data['Code'] ?? null),
            lastModified: Cast::dateTime($data['LastModified'] ?? null),
        );
    }
}
