<?php

declare(strict_types=1);

// This file is generated by tools/generate.php from resources/specs/edge-scripting.json. Do not edit.

namespace GoSuccess\Bunny\EdgeScripting\Model;

use DateTimeImmutable;
use GoSuccess\Bunny\EdgeScripting\Enum\EdgeScriptType;
use GoSuccess\Bunny\Model\Cast;
use GoSuccess\Bunny\Model\ResponseModel;

/** Schema: EdgeScriptModel */
final readonly class EdgeScript implements ResponseModel
{
    public function __construct(
        public int $id = 0,
        public ?string $name = null,
        public ?DateTimeImmutable $lastModified = null,
        /**
         * 0 = DNS
         * 1 = CDN
         * 2 = Middleware
         */
        public ?EdgeScriptType $scriptType = null,
        public int $currentReleaseId = 0,
        /** @var list<EdgeScriptVariable> */
        public array $edgeScriptVariables = [],
        public bool $deleted = false,
        /** @var list<LinkedPullZone> */
        public array $linkedPullZones = [],
        public ?SourceCodeIntegration $integration = null,
        public ?string $defaultHostname = null,
        public ?string $systemHostname = null,
        public ?string $deploymentKey = null,
        public ?int $repositoryId = null,
        public ?int $integrationId = null,
        public float $monthlyCost = 0.0,
        public int $monthlyRequestCount = 0,
        public int $monthlyCpuTime = 0,
    ) {}

    public static function fromArray(array $data): static
    {
        return new self(
            id: Cast::int($data['Id'] ?? null) ?? 0,
            name: Cast::string($data['Name'] ?? null),
            lastModified: Cast::dateTime($data['LastModified'] ?? null),
            scriptType: Cast::intEnum(EdgeScriptType::class, $data['ScriptType'] ?? null),
            currentReleaseId: Cast::int($data['CurrentReleaseId'] ?? null) ?? 0,
            edgeScriptVariables: Cast::modelList(EdgeScriptVariable::class, $data['EdgeScriptVariables'] ?? null),
            deleted: Cast::bool($data['Deleted'] ?? null) ?? false,
            linkedPullZones: Cast::modelList(LinkedPullZone::class, $data['LinkedPullZones'] ?? null),
            integration: Cast::model(SourceCodeIntegration::class, $data['Integration'] ?? null),
            defaultHostname: Cast::string($data['DefaultHostname'] ?? null),
            systemHostname: Cast::string($data['SystemHostname'] ?? null),
            deploymentKey: Cast::string($data['DeploymentKey'] ?? null),
            repositoryId: Cast::int($data['RepositoryId'] ?? null),
            integrationId: Cast::int($data['IntegrationId'] ?? null),
            monthlyCost: Cast::float($data['MonthlyCost'] ?? null) ?? 0.0,
            monthlyRequestCount: Cast::int($data['MonthlyRequestCount'] ?? null) ?? 0,
            monthlyCpuTime: Cast::int($data['MonthlyCpuTime'] ?? null) ?? 0,
        );
    }
}
