<?php

declare(strict_types=1);

// This file is generated by tools/generate.php from resources/specs/edge-scripting.json. Do not edit.

namespace GoSuccess\Bunny\EdgeScripting\Model;

use GoSuccess\Bunny\Model\Cast;
use GoSuccess\Bunny\Model\ResponseModel;

/** Schema: EdgeScriptVariableModel */
final readonly class EdgeScriptVariable implements ResponseModel
{
    public function __construct(
        public int $id = 0,
        public ?string $name = null,
        public bool $required = false,
        public ?string $defaultValue = null,
    ) {}

    public static function fromArray(array $data): static
    {
        return new self(
            id: Cast::int($data['Id'] ?? null) ?? 0,
            name: Cast::string($data['Name'] ?? null),
            required: Cast::bool($data['Required'] ?? null) ?? false,
            defaultValue: Cast::string($data['DefaultValue'] ?? null),
        );
    }
}
