<?php

declare(strict_types=1);

// This file is generated by tools/generate.php from resources/specs/edge-scripting.json. Do not edit.

namespace GoSuccess\Bunny\EdgeScripting\Model;

use GoSuccess\Bunny\Model\Cast;
use GoSuccess\Bunny\Model\ResponseModel;

/** Schema: EdgeScriptStatisticsModel */
final readonly class EdgeScriptStatistics implements ResponseModel
{
    public function __construct(
        public int $totalRequestsServed = 0,
        public float $totalCpuUsed = 0.0,
        public float $totalMonthlyCost = 0.0,
        public float $averageCpuTimePerExecution = 0.0,
        /** @var array<array-key, float> */
        public array $requestsServedChart = [],
        /** @var array<array-key, float> */
        public array $averageCpuTimeChart = [],
        /** @var array<array-key, float> */
        public array $totalCpuTimeChart = [],
    ) {}

    public static function fromArray(array $data): static
    {
        return new self(
            totalRequestsServed: Cast::int($data['TotalRequestsServed'] ?? null) ?? 0,
            totalCpuUsed: Cast::float($data['TotalCpuUsed'] ?? null) ?? 0.0,
            totalMonthlyCost: Cast::float($data['TotalMonthlyCost'] ?? null) ?? 0.0,
            averageCpuTimePerExecution: Cast::float($data['AverageCpuTimePerExecution'] ?? null) ?? 0.0,
            requestsServedChart: Cast::mapOf($data['RequestsServedChart'] ?? null, Cast::float(...)),
            averageCpuTimeChart: Cast::mapOf($data['AverageCpuTimeChart'] ?? null, Cast::float(...)),
            totalCpuTimeChart: Cast::mapOf($data['TotalCpuTimeChart'] ?? null, Cast::float(...)),
        );
    }
}
