<?php

declare(strict_types=1);

// This file is generated by tools/generate.php from resources/specs/edge-scripting.json. Do not edit.

namespace GoSuccess\Bunny\EdgeScripting\Model;

use GoSuccess\Bunny\Model\Cast;
use GoSuccess\Bunny\Model\ResponseModel;

/** Schema: LinkedPullZone */
final readonly class LinkedPullZone implements ResponseModel
{
    public function __construct(
        public int $id = 0,
        public ?string $pullZoneName = null,
        public ?string $defaultHostname = null,
    ) {}

    public static function fromArray(array $data): static
    {
        return new self(
            id: Cast::int($data['Id'] ?? null) ?? 0,
            pullZoneName: Cast::string($data['PullZoneName'] ?? null),
            defaultHostname: Cast::string($data['DefaultHostname'] ?? null),
        );
    }
}
