<?php

declare(strict_types=1);

// This file is generated by tools/generate.php from resources/specs/edge-scripting.json. Do not edit.

namespace GoSuccess\Bunny\EdgeScripting\Model;

use GoSuccess\Bunny\Model\Cast;
use GoSuccess\Bunny\Model\RequestModel;
use GoSuccess\Bunny\Model\ResponseModel;
use GoSuccess\Bunny\Model\Undefined;

/** Schema: SourceCodeRepositorySettingsModel */
final readonly class SourceCodeRepositorySettings implements RequestModel, ResponseModel
{
    public ?int $id;

    public ?string $name;

    public bool $private;

    public ?string $templateUrl;

    /**
     * Payload keys the caller provided; toArray() sends exactly these.
     *
     * @var array<string, true>
     */
    private array $provided;

    public function __construct(
        int|Undefined|null $id = Undefined::Value,
        string|Undefined|null $name = Undefined::Value,
        bool|Undefined $private = Undefined::Value,
        string|Undefined|null $templateUrl = Undefined::Value,
    ) {
        $this->id = $id instanceof Undefined ? null : $id;
        $this->name = $name instanceof Undefined ? null : $name;
        $this->private = $private instanceof Undefined ? false : $private;
        $this->templateUrl = $templateUrl instanceof Undefined ? null : $templateUrl;
        $this->provided = array_filter([
            'Id' => !$id instanceof Undefined,
            'Name' => !$name instanceof Undefined,
            'Private' => !$private instanceof Undefined,
            'TemplateUrl' => !$templateUrl instanceof Undefined,
        ]);
    }

    public static function fromArray(array $data): static
    {
        return new self(
            id: Cast::int($data['Id'] ?? null) ?? Undefined::Value,
            name: Cast::string($data['Name'] ?? null) ?? Undefined::Value,
            private: Cast::bool($data['Private'] ?? null) ?? Undefined::Value,
            templateUrl: Cast::string($data['TemplateUrl'] ?? null) ?? Undefined::Value,
        );
    }

    public function toArray(): array
    {
        $data = [];

        if (isset($this->provided['Id'])) {
            $data['Id'] = $this->id;
        }

        if (isset($this->provided['Name'])) {
            $data['Name'] = $this->name;
        }

        if (isset($this->provided['Private'])) {
            $data['Private'] = $this->private;
        }

        if (isset($this->provided['TemplateUrl'])) {
            $data['TemplateUrl'] = $this->templateUrl;
        }

        return $data;
    }
}
