<?php

declare(strict_types=1);

// This file is generated by tools/generate.php from resources/specs/shield.json. Do not edit.

namespace GoSuccess\Bunny\Shield\Enum;

/** Schema: AccessListAction */
enum AccessListAction: int
{
    case None = 0;
    case Allow = 1;
    case Block = 2;
    case Challenge = 3;
    case Log = 4;
    case Bypass = 5;
}
