<?php

declare(strict_types=1);

// This file is generated by tools/generate.php from resources/specs/shield.json. Do not edit.

namespace GoSuccess\Bunny\Shield\Enum;

/** Schema: BotCategoryAction */
enum BotCategoryAction: int
{
    case None = 0;
    case Block = 1;
    case Allow = 2;
}
