<?php

declare(strict_types=1);

// This file is generated by tools/generate.php from resources/specs/shield.json. Do not edit.

namespace GoSuccess\Bunny\Shield\Enum;

/** Schema: DDoSShieldSensitivity */
enum DdosSensitivity: int
{
    case Off = 0;
    case Low = 1;
    case Medium = 2;
    case High = 3;
    case Challenge = 4;
}
