<?php

declare(strict_types=1);

// This file is generated by tools/generate.php from resources/specs/shield.json. Do not edit.

namespace GoSuccess\Bunny\Shield\Enum;

/** Schema: MetricsOverviewResolution */
enum MetricsOverviewResolution: int
{
    case Auto = 0;
    case TwoMinutes = 1;
    case TenMinutes = 2;
    case Hourly = 3;
    case Daily = 4;
    case Weekly = 5;
    case Monthly = 6;
}
