<?php

declare(strict_types=1);

// This file is generated by tools/generate.php from resources/specs/shield.json. Do not edit.

namespace GoSuccess\Bunny\Shield\Enum;

/** Schema: WafRatelimitCounterKeyType */
enum RateLimitCounterKey: int
{
    case IP = 0;
    case Host = 1;
    case Country = 2;
    case City = 3;
    case ASN = 4;
    case Organization = 5;
    case JA4 = 6;
    case IP_JA4 = 7;
}
