<?php

declare(strict_types=1);

// This file is generated by tools/generate.php from resources/specs/shield.json. Do not edit.

namespace GoSuccess\Bunny\Shield\Enum;

/** Schema: ShieldPlanType */
enum ShieldPlanType: int
{
    case Basic = 0;
    case Advanced = 1;
    case Business = 2;
    case Enterprise = 3;
}
