<?php

declare(strict_types=1);

// This file is generated by tools/generate.php from resources/specs/shield.json. Do not edit.

namespace GoSuccess\Bunny\Shield\Enum;

/** Schema: UnmatchedPathAction */
enum UnmatchedPathAction: int
{
    case Block = 0;
    case Log = 1;
    case Ignore = 2;
}
