<?php

declare(strict_types=1);

// This file is generated by tools/generate.php from resources/specs/shield.json. Do not edit.

namespace GoSuccess\Bunny\Shield\Enum;

/** Schema: WafRuleActionType */
enum WafRuleActionType: int
{
    case Block = 1;
    case Log = 2;
    case Challenge = 3;
    case Allow = 4;
    case Bypass = 5;
}
