<?php

declare(strict_types=1);

// This file is generated by tools/generate.php from resources/specs/core.json. Do not edit.

namespace GoSuccess\Bunny\Core\Enum;

/** Schema: AcceleratedStatus */
enum AcceleratedStatus: int
{
    case None = 0;
    case Pending = 1;
    case Processing = 2;
    case Completed = 3;
    case Failed = 4;
}
