<?php

declare(strict_types=1);

// This file is generated by tools/generate.php from resources/specs/core.json. Do not edit.

namespace GoSuccess\Bunny\Core\Enum;

/** Schema: DnsZoneScanJobStatus */
enum DnsRecordScanStatus: int
{
    case Pending = 0;
    case InProgress = 1;
    case Completed = 2;
    case Failed = 3;
}
