<?php

declare(strict_types=1);

// This file is generated by tools/generate.php from resources/specs/core.json. Do not edit.

namespace GoSuccess\Bunny\Core\Enum;

/** Schema: DrmVersion */
enum DrmVersion: int
{
    case Basic = 0;
    case Enterprise = 1;
    case BasicV2 = 2;
}
