<?php

declare(strict_types=1);

// This file is generated by tools/generate.php from resources/specs/core.json. Do not edit.

namespace GoSuccess\Bunny\Core\Enum;

/** Schema: TriggerTypes */
enum EdgeRuleTriggerType: int
{
    case Url = 0;
    case RequestHeader = 1;
    case ResponseHeader = 2;
    case UrlExtension = 3;
    case CountryCode = 4;
    case RemoteIP = 5;
    case UrlQueryString = 6;
    case RandomChance = 7;
    case StatusCode = 8;
    case RequestMethod = 9;
    case CookieValue = 10;
    case CountryStateCode = 11;
    case OriginRetryAttemptCount = 12;
    case OriginConnectionError = 13;
}
