<?php

declare(strict_types=1);

// This file is generated by tools/generate.php from resources/specs/core.json. Do not edit.

namespace GoSuccess\Bunny\Core\Enum;

/** Schema: EdgeRuleActionType */
enum EdgeRuleActionType: int
{
    case ForceSSL = 0;
    case Redirect = 1;
    case OriginUrl = 2;
    case OverrideCacheTime = 3;
    case BlockRequest = 4;
    case SetResponseHeader = 5;
    case SetRequestHeader = 6;
    case ForceDownload = 7;
    case DisableTokenAuthentication = 8;
    case EnableTokenAuthentication = 9;
    case OverrideCacheTimePublic = 10;
    case IgnoreQueryString = 11;
    case DisableOptimizer = 12;
    case ForceCompression = 13;
    case SetStatusCode = 14;
    case BypassPermaCache = 15;
    case OverrideBrowserCacheTime = 16;
    case OriginStorage = 17;
    case SetNetworkRateLimit = 18;
    case SetConnectionLimit = 19;
    case SetRequestsPerSecondLimit = 20;
    case RunEdgeScript = 21;
    case OriginMagicContainers = 22;
    case DisableWAF = 23;
    case RetryOrigin = 24;
    case OverrideBrowserCacheResponseHeader = 25;
    case RemoveBrowserCacheResponseHeader = 26;
    case DisableShieldChallenge = 27;
    case DisableShield = 28;
    case DisableShieldBotDetection = 29;
    case BypassAwsS3Authentication = 30;
    case DisableShieldAccessLists = 31;
    case DisableShieldRateLimiting = 32;
    case EnableRequestCoalescing = 33;
    case DisableRequestCoalescing = 34;
    case StripCookiesClientToOrigin = 37;
}
