<?php

declare(strict_types=1);

// This file is generated by tools/generate.php from resources/specs/core.json. Do not edit.

namespace GoSuccess\Bunny\Core\Enum;

/** Schema: ExecutionPhase */
enum ExecutionPhase: int
{
    case Cache = 0;
    case LoadBalancer = 1;
    case PreCache = 2;
}
