<?php

declare(strict_types=1);

// This file is generated by tools/generate.php from resources/specs/core.json. Do not edit.

namespace GoSuccess\Bunny\Core\Enum;

/** Schema: IpFamilyPolicy */
enum IpFamilyPolicy: int
{
    case IPv4Only = 0;
    case DualStack = 1;
    case DualStackPreferIPv6 = 2;
    case IPv6Only = 3;
}
