<?php

declare(strict_types=1);

// This file is generated by tools/generate.php from resources/specs/core.json. Do not edit.

namespace GoSuccess\Bunny\Core\Enum;

/** Schema: PermaCacheType */
enum PermaCacheType: int
{
    case Automatic = 0;
    case Manual = 1;
}
