<?php

declare(strict_types=1);

// This file is generated by tools/generate.php from resources/specs/core.json. Do not edit.

namespace GoSuccess\Bunny\Core\Enum;

/** Schema: PullZoneType */
enum PullZoneType: int
{
    case Premium = 0;
    case Volume = 1;
}
