<?php

declare(strict_types=1);

// This file is generated by tools/generate.php from resources/specs/core.json. Do not edit.

namespace GoSuccess\Bunny\Core\Enum;

/** Schema: PullZoneLogForwarderProtocolType */
enum PullZoneLogForwarderProtocolType: int
{
    case UDP = 0;
    case TCP = 1;
    case TCPEncrypted = 2;
    case DataDog = 3;
}
