<?php

declare(strict_types=1);

// This file is generated by tools/generate.php from resources/specs/core.json. Do not edit.

namespace GoSuccess\Bunny\Core\Enum;

/** Schema: StickySessionType */
enum StickySessionType: int
{
    case Off = 0;
    case On = 1;
}
