<?php

declare(strict_types=1);

// This file is generated by tools/generate.php from resources/specs/core.json. Do not edit.

namespace GoSuccess\Bunny\Core\Enum;

/** Schema: StorageZoneS3Type */
enum StorageZoneS3Type: int
{
    case NotSupported = 0;
    case Supported = 1;
}
