<?php

declare(strict_types=1);

// This file is generated by tools/generate.php from resources/specs/core.json. Do not edit.

namespace GoSuccess\Bunny\Core\Enum;

/** Schema: StorageZoneTier */
enum StorageZoneTier: int
{
    case Standard = 0;
    case Edge = 1;
}
