<?php

declare(strict_types=1);

// This file is generated by tools/generate.php from resources/specs/core.json. Do not edit.

namespace GoSuccess\Bunny\Core\Enum;

/** Schema: TlsSecurityLevelType */
enum TlsSecurityLevelType: int
{
    case Legacy = 0;
    case Compatible = 1;
    case ModernOnly = 2;
}
