<?php

declare(strict_types=1);

// This file is generated by tools/generate.php from resources/specs/core.json. Do not edit.

namespace GoSuccess\Bunny\Core\Enum;

/** Schema: TriggerMatchingTypes */
enum TriggerMatchingType: int
{
    case MatchAny = 0;
    case MatchAll = 1;
    case MatchNone = 2;
}
