<?php

declare(strict_types=1);

// This file is generated by tools/generate.php from resources/specs/core.json. Do not edit.

namespace GoSuccess\Bunny\Core\Enum;

/** Schema: WidevineMinClientSecurityLevel */
enum WidevineMinClientSecurityLevel: int
{
    case None = 0;
    case L1 = 1;
    case L2 = 2;
    case L3 = 3;
}
