<?php

declare(strict_types=1);

// This file is generated by tools/generate.php from resources/specs/stream.json. Do not edit.

namespace GoSuccess\Bunny\Stream\Enum;

/** Schema: Severity */
enum TranscodingSeverity: int
{
    /** Shouldn't be used */
    case Undefined = 0;

    /** An info message to the user, shouldn't break anythying */
    case Information = 1;

    /** A warning message, for example that the transcoded video may break when playing */
    case Warning = 2;

    /** An error, meaning that the video will most likely not be playable */
    case Error = 3;
}
