<?php

declare(strict_types=1);

// This file is generated by tools/generate.php from resources/specs/magic-containers.json. Do not edit.

namespace GoSuccess\Bunny\MagicContainers\Enum;

/** Schema: DeploymentStatus */
enum DeploymentStatus: string
{
    case Unknown = 'unknown';
    case Active = 'active';
    case Progressing = 'progressing';
    case Inactive = 'inactive';
    case Failing = 'failing';
}
