<?php

declare(strict_types=1);

// This file is generated by tools/generate.php from resources/specs/magic-containers.json. Do not edit.

namespace GoSuccess\Bunny\MagicContainers\Enum;

/** Schema: EndpointType */
enum EndpointType: string
{
    case Cdn = 'cdn';
    case Anycast = 'anycast';
    case PublicIp = 'publicIp';
}
