<?php

declare(strict_types=1);

// This file is generated by tools/generate.php from resources/specs/magic-containers.json. Do not edit.

namespace GoSuccess\Bunny\MagicContainers\Enum;

/** Schema: RegionProvisioningType */
enum RegionProvisioningType: string
{
    case Static = 'static';
    case Dynamic = 'dynamic';
}
