<?php

declare(strict_types=1);

// This file is generated by tools/generate.php from resources/specs/logging.json. Do not edit.

namespace GoSuccess\Bunny\Logging\Resource;

use DateTimeInterface;
use GoSuccess\Bunny\Http\Method;
use GoSuccess\Bunny\Logging\Model\LogEntry;
use GoSuccess\Bunny\Logging\Pagination;
use GoSuccess\Bunny\Logging\Resource\Handwritten\LogOperations;
use GoSuccess\Bunny\Model\Cast;
use GoSuccess\Bunny\Pagination\Page;
use GoSuccess\Bunny\Pagination\Paginator;
use GoSuccess\Bunny\Resource\AbstractResource;

/** Raw CDN request logs of the last 3 days. */
final class LogResource extends AbstractResource
{
    use LogOperations;

    /**
     * Query CDN access logs for a pull zone.
     *
     * Authenticate with either an `Authorization` bearer JWT or an `AccessKey` header.
     * Filter pushdown happens in ClickHouse where possible; `country` and free-text
     * `search` are applied in-process after fetch.
     *
     * The time range must lie within the last 3 days. bunny.net allows 30 requests per 10 seconds and pull zone.
     *
     * `GET /v2/pullzones/{pullZoneId}/logs`
     *
     * @param int                    $pullZoneId
     * @param DateTimeInterface|null $from                Inclusive start of the time range (UTC). Defaults to `To - 24h`. Must fall within the 3-day log retention window. The total range (`To - From`) cannot exceed 3 days.
     * @param DateTimeInterface|null $to                  Exclusive end of the time range (UTC). Defaults to `now`.
     * @param string|null            $status              Comma-separated list of HTTP status filters. Each entry can be an exact code (e.g. `200`, `404`) or a status class (e.g. `2xx`, `5xx`). Multiple entries are combined with OR.
     * @param string|null            $cacheStatus         Comma-separated list of cache statuses to match exactly (e.g. `HIT,MISS,EXPIRED`).
     * @param string|null            $country             ISO 3166 alpha-2 country code (e.g. `EE`). Multiple values can be comma-separated.
     * @param string|null            $edgeLocation        Edge location / server zone (exact match).
     * @param string|null            $remoteIp            Client IP address filter (IPv4 or IPv6). The match width adapts to the zone's IP anonymization setting so the filter can never reveal information beyond what the API returns: exact match when anonymization is disabled, /24 (IPv4) or /64 (IPv6) when last-octet anonymization is enabled, and ignored when full anonymization is enabled.
     * @param string|null            $urlContains         Case-insensitive substring match against the request URL (host + path).
     * @param string|null            $userAgentContains   Case-insensitive substring match against the User-Agent header.
     * @param string|null            $refererContains     Case-insensitive substring match against the Referer header.
     * @param string|null            $search              Free-text, case-insensitive token search. Tokens are space-separated; a row matches if ANY token appears in ANY of the searched columns: cache status, request ID, edge location, host, path, user agent, referer, and (for zones with extended logging) content range. Remote IP, country code, and the authorization header are not searched. use the dedicated filters for those, or note that the authorization header is encrypted at rest. Limited to 16 tokens of at most 128 characters each.
     * @param string|null            $requestId           Exact request ID (UUID) to look up a single log entry.
     * @param bool|null              $includeOriginShield Include origin-shield (edge → shield) requests. Defaults to `false` to match v1.
     * @param int                    $limit               The number of items per page.
     * @param int                    $offset              The number of items to skip.
     * @param string|null            $order               Sort order by timestamp: `asc` or `desc` (default).
     *
     * @return Page<LogEntry>
     */
    public function list(
        int $pullZoneId,
        ?DateTimeInterface $from = null,
        ?DateTimeInterface $to = null,
        ?string $status = null,
        ?string $cacheStatus = null,
        ?string $country = null,
        ?string $edgeLocation = null,
        ?string $remoteIp = null,
        ?string $urlContains = null,
        ?string $userAgentContains = null,
        ?string $refererContains = null,
        ?string $search = null,
        ?string $requestId = null,
        ?bool $includeOriginShield = null,
        int $limit = 100,
        int $offset = 0,
        ?string $order = null,
    ): Page {
        $data = self::expectObject($this->connection->json(Method::Get, "v2/pullzones/{$pullZoneId}/logs", [
            'from' => $from,
            'to' => $to,
            'status' => $status,
            'cacheStatus' => $cacheStatus,
            'country' => $country,
            'edgeLocation' => $edgeLocation,
            'remoteIp' => $remoteIp,
            'urlContains' => $urlContains,
            'userAgentContains' => $userAgentContains,
            'refererContains' => $refererContains,
            'search' => $search,
            'requestId' => $requestId,
            'includeOriginShield' => $includeOriginShield,
            'limit' => $limit,
            'offset' => $offset,
            'order' => $order,
        ]));

        return Pagination::offset($data, Cast::modelList(LogEntry::class, $data['data'] ?? null));
    }

    /**
     * Iterate lazily over every item of list(), across all pages.
     *
     * The time range must lie within the last 3 days. bunny.net allows 30 requests per 10 seconds and pull zone.
     *
     * `GET /v2/pullzones/{pullZoneId}/logs`
     *
     * @param int                    $pullZoneId
     * @param DateTimeInterface|null $from                Inclusive start of the time range (UTC). Defaults to `To - 24h`. Must fall within the 3-day log retention window. The total range (`To - From`) cannot exceed 3 days.
     * @param DateTimeInterface|null $to                  Exclusive end of the time range (UTC). Defaults to `now`.
     * @param string|null            $status              Comma-separated list of HTTP status filters. Each entry can be an exact code (e.g. `200`, `404`) or a status class (e.g. `2xx`, `5xx`). Multiple entries are combined with OR.
     * @param string|null            $cacheStatus         Comma-separated list of cache statuses to match exactly (e.g. `HIT,MISS,EXPIRED`).
     * @param string|null            $country             ISO 3166 alpha-2 country code (e.g. `EE`). Multiple values can be comma-separated.
     * @param string|null            $edgeLocation        Edge location / server zone (exact match).
     * @param string|null            $remoteIp            Client IP address filter (IPv4 or IPv6). The match width adapts to the zone's IP anonymization setting so the filter can never reveal information beyond what the API returns: exact match when anonymization is disabled, /24 (IPv4) or /64 (IPv6) when last-octet anonymization is enabled, and ignored when full anonymization is enabled.
     * @param string|null            $urlContains         Case-insensitive substring match against the request URL (host + path).
     * @param string|null            $userAgentContains   Case-insensitive substring match against the User-Agent header.
     * @param string|null            $refererContains     Case-insensitive substring match against the Referer header.
     * @param string|null            $search              Free-text, case-insensitive token search. Tokens are space-separated; a row matches if ANY token appears in ANY of the searched columns: cache status, request ID, edge location, host, path, user agent, referer, and (for zones with extended logging) content range. Remote IP, country code, and the authorization header are not searched. use the dedicated filters for those, or note that the authorization header is encrypted at rest. Limited to 16 tokens of at most 128 characters each.
     * @param string|null            $requestId           Exact request ID (UUID) to look up a single log entry.
     * @param bool|null              $includeOriginShield Include origin-shield (edge → shield) requests. Defaults to `false` to match v1.
     * @param string|null            $order               Sort order by timestamp: `asc` or `desc` (default).
     * @param int                    $limit               The number of items per page.
     *
     * @return Paginator<LogEntry>
     */
    public function all(
        int $pullZoneId,
        ?DateTimeInterface $from = null,
        ?DateTimeInterface $to = null,
        ?string $status = null,
        ?string $cacheStatus = null,
        ?string $country = null,
        ?string $edgeLocation = null,
        ?string $remoteIp = null,
        ?string $urlContains = null,
        ?string $userAgentContains = null,
        ?string $refererContains = null,
        ?string $search = null,
        ?string $requestId = null,
        ?bool $includeOriginShield = null,
        ?string $order = null,
        int $limit = 1000,
    ): Paginator {
        return new Paginator(fn(int|string|null $position): Page => $this->list(
            pullZoneId: $pullZoneId,
            from: $from,
            to: $to,
            status: $status,
            cacheStatus: $cacheStatus,
            country: $country,
            edgeLocation: $edgeLocation,
            remoteIp: $remoteIp,
            urlContains: $urlContains,
            userAgentContains: $userAgentContains,
            refererContains: $refererContains,
            search: $search,
            requestId: $requestId,
            includeOriginShield: $includeOriginShield,
            limit: $limit,
            offset: \is_int($position) ? $position : 0,
            order: $order,
        ));
    }
}
