<?php

declare(strict_types=1);

// This file is generated by tools/generate.php from resources/specs/magic-containers.json. Do not edit.

namespace GoSuccess\Bunny\MagicContainers\Model;

use GoSuccess\Bunny\MagicContainers\Enum\ImagePullPolicy;
use GoSuccess\Bunny\Model\RequestModel;
use GoSuccess\Bunny\Model\Undefined;

/** Schema: AddContainerRequest */
final readonly class AddContainerRequest implements RequestModel
{
    public function __construct(
        public string $name,
        public string $imageName,
        public string $imageNamespace,
        public string $imageTag,
        public string $imageRegistryId,
        public string|Undefined|null $image = Undefined::Value,
        public string|Undefined|null $imageDigest = Undefined::Value,
        public ImagePullPolicy|Undefined $imagePullPolicy = Undefined::Value,
        public ContainerEntryPoint|Undefined $entryPoint = Undefined::Value,
        public ContainerProbes|Undefined $probes = Undefined::Value,
        /** @var list<EnvironmentVariable>|Undefined */
        public array|Undefined $environmentVariables = Undefined::Value,
        /** @var list<EndpointRequest>|Undefined */
        public array|Undefined $endpoints = Undefined::Value,
        /** @var list<VolumeMountRequest>|Undefined */
        public array|Undefined $volumeMounts = Undefined::Value,
    ) {}

    public function toArray(): array
    {
        $data = [];
        $data['name'] = $this->name;
        $data['imageName'] = $this->imageName;
        $data['imageNamespace'] = $this->imageNamespace;
        $data['imageTag'] = $this->imageTag;
        $data['imageRegistryId'] = $this->imageRegistryId;

        if (!$this->image instanceof Undefined) {
            $data['image'] = $this->image;
        }

        if (!$this->imageDigest instanceof Undefined) {
            $data['imageDigest'] = $this->imageDigest;
        }

        if (!$this->imagePullPolicy instanceof Undefined) {
            $data['imagePullPolicy'] = $this->imagePullPolicy->value;
        }

        if (!$this->entryPoint instanceof Undefined) {
            $data['entryPoint'] = $this->entryPoint->toArray();
        }

        if (!$this->probes instanceof Undefined) {
            $data['probes'] = $this->probes->toArray();
        }

        if (!$this->environmentVariables instanceof Undefined) {
            $data['environmentVariables'] = array_map(static fn(EnvironmentVariable $item): array => $item->toArray(), $this->environmentVariables);
        }

        if (!$this->endpoints instanceof Undefined) {
            $data['endpoints'] = array_map(static fn(EndpointRequest $item): array => $item->toArray(), $this->endpoints);
        }

        if (!$this->volumeMounts instanceof Undefined) {
            $data['volumeMounts'] = array_map(static fn(VolumeMountRequest $item): array => $item->toArray(), $this->volumeMounts);
        }

        return $data;
    }
}
