<?php

declare(strict_types=1);

// This file is generated by tools/generate.php from resources/specs/magic-containers.json. Do not edit.

namespace GoSuccess\Bunny\MagicContainers\Model;

use GoSuccess\Bunny\Model\Cast;
use GoSuccess\Bunny\Model\RequestModel;
use GoSuccess\Bunny\Model\ResponseModel;
use GoSuccess\Bunny\Model\Undefined;

/** Schema: AutoscalingSettings */
final readonly class AutoscalingSettings implements RequestModel, ResponseModel
{
    public int $min;

    public int $max;

    /**
     * Payload keys the caller provided; toArray() sends exactly these.
     *
     * @var array<string, true>
     */
    private array $provided;

    public function __construct(
        int|Undefined $min = Undefined::Value,
        int|Undefined $max = Undefined::Value,
    ) {
        $this->min = $min instanceof Undefined ? 0 : $min;
        $this->max = $max instanceof Undefined ? 0 : $max;
        $this->provided = array_filter([
            'min' => !$min instanceof Undefined,
            'max' => !$max instanceof Undefined,
        ]);
    }

    public static function fromArray(array $data): static
    {
        return new self(
            min: Cast::int($data['min'] ?? null) ?? Undefined::Value,
            max: Cast::int($data['max'] ?? null) ?? Undefined::Value,
        );
    }

    public function toArray(): array
    {
        $data = [];

        if (isset($this->provided['min'])) {
            $data['min'] = $this->min;
        }

        if (isset($this->provided['max'])) {
            $data['max'] = $this->max;
        }

        return $data;
    }
}
