<?php

declare(strict_types=1);

// This file is generated by tools/generate.php from resources/specs/magic-containers.json. Do not edit.

namespace GoSuccess\Bunny\MagicContainers\Model;

use GoSuccess\Bunny\Model\Cast;
use GoSuccess\Bunny\Model\ResponseModel;

/** Schema: ContainerInstance */
final readonly class ContainerInstance implements ResponseModel
{
    public function __construct(
        public string $id = '',
        public string $templateId = '',
        public string $podId = '',
        public string $nodeIpAddress = '',
    ) {}

    public static function fromArray(array $data): static
    {
        return new self(
            id: Cast::string($data['id'] ?? null) ?? '',
            templateId: Cast::string($data['templateId'] ?? null) ?? '',
            podId: Cast::string($data['podId'] ?? null) ?? '',
            nodeIpAddress: Cast::string($data['nodeIpAddress'] ?? null) ?? '',
        );
    }
}
