<?php

declare(strict_types=1);

// This file is generated by tools/generate.php from resources/specs/magic-containers.json. Do not edit.

namespace GoSuccess\Bunny\MagicContainers\Model;

use GoSuccess\Bunny\Model\Cast;
use GoSuccess\Bunny\Model\ResponseModel;

/** Schema: ContainerConfigSuggestions */
final readonly class ContainerConfigSuggestions implements ResponseModel
{
    public function __construct(
        /** @var list<EndpointRequest> */
        public array $endpointSuggestions = [],
        /** @var list<EnvironmentVariableSuggestion> */
        public array $environmentVariablesSuggestions = [],
        /** @var list<VolumeSuggestion> */
        public array $volumeSuggestions = [],
        public ?string $appName = null,
        public ?string $description = null,
        public ?string $instructions = null,
        public ?string $registryUrl = null,
    ) {}

    public static function fromArray(array $data): static
    {
        return new self(
            endpointSuggestions: Cast::modelList(EndpointRequest::class, $data['endpointSuggestions'] ?? null),
            environmentVariablesSuggestions: Cast::modelList(EnvironmentVariableSuggestion::class, $data['environmentVariablesSuggestions'] ?? null),
            volumeSuggestions: Cast::modelList(VolumeSuggestion::class, $data['volumeSuggestions'] ?? null),
            appName: Cast::string($data['appName'] ?? null),
            description: Cast::string($data['description'] ?? null),
            instructions: Cast::string($data['instructions'] ?? null),
            registryUrl: Cast::string($data['registryUrl'] ?? null),
        );
    }
}
