<?php

declare(strict_types=1);

// This file is generated by tools/generate.php from resources/specs/magic-containers.json. Do not edit.

namespace GoSuccess\Bunny\MagicContainers\Model;

use GoSuccess\Bunny\MagicContainers\Enum\ImagePullPolicy;
use GoSuccess\Bunny\Model\Cast;
use GoSuccess\Bunny\Model\ResponseModel;

/**
 * Container template model
 *
 * Schema: ContainerTemplate
 */
final readonly class ContainerTemplate implements ResponseModel
{
    public function __construct(
        public string $id = '',
        public string $name = '',
        public string $packageId = '',
        public string $image = '',
        public string $imageName = '',
        public string $imageNamespace = '',
        public string $imageTag = '',
        public string $imageRegistryId = '',
        public string $imageDigest = '',
        public ?ImagePullPolicy $imagePullPolicy = null,
        public ContainerEntryPoint $entryPoint = new ContainerEntryPoint(),
        public ContainerProbes $probes = new ContainerProbes(),
        /** @var list<EnvironmentVariable> */
        public array $environmentVariables = [],
        /** @var list<ContainerEndpoint> */
        public array $endpoints = [],
        /** @var list<ContainerVolumeMount> */
        public array $volumeMounts = [],
    ) {}

    public static function fromArray(array $data): static
    {
        return new self(
            id: Cast::string($data['id'] ?? null) ?? '',
            name: Cast::string($data['name'] ?? null) ?? '',
            packageId: Cast::string($data['packageId'] ?? null) ?? '',
            image: Cast::string($data['image'] ?? null) ?? '',
            imageName: Cast::string($data['imageName'] ?? null) ?? '',
            imageNamespace: Cast::string($data['imageNamespace'] ?? null) ?? '',
            imageTag: Cast::string($data['imageTag'] ?? null) ?? '',
            imageRegistryId: Cast::string($data['imageRegistryId'] ?? null) ?? '',
            imageDigest: Cast::string($data['imageDigest'] ?? null) ?? '',
            imagePullPolicy: Cast::stringEnum(ImagePullPolicy::class, $data['imagePullPolicy'] ?? null),
            entryPoint: Cast::model(ContainerEntryPoint::class, $data['entryPoint'] ?? null) ?? new ContainerEntryPoint(),
            probes: Cast::model(ContainerProbes::class, $data['probes'] ?? null) ?? new ContainerProbes(),
            environmentVariables: Cast::modelList(EnvironmentVariable::class, $data['environmentVariables'] ?? null),
            endpoints: Cast::modelList(ContainerEndpoint::class, $data['endpoints'] ?? null),
            volumeMounts: Cast::modelList(ContainerVolumeMount::class, $data['volumeMounts'] ?? null),
        );
    }
}
