<?php

declare(strict_types=1);

// This file is generated by tools/generate.php from resources/specs/magic-containers.json. Do not edit.

namespace GoSuccess\Bunny\MagicContainers\Model;

use GoSuccess\Bunny\Model\Cast;
use GoSuccess\Bunny\Model\RequestModel;
use GoSuccess\Bunny\Model\ResponseModel;
use GoSuccess\Bunny\Model\Undefined;

/** Schema: ContainerProbes */
final readonly class ContainerProbes implements RequestModel, ResponseModel
{
    public ContainerProbe $startup;

    public ContainerProbe $readiness;

    public ContainerProbe $liveness;

    /**
     * Payload keys the caller provided; toArray() sends exactly these.
     *
     * @var array<string, true>
     */
    private array $provided;

    public function __construct(
        ContainerProbe|Undefined $startup = Undefined::Value,
        ContainerProbe|Undefined $readiness = Undefined::Value,
        ContainerProbe|Undefined $liveness = Undefined::Value,
    ) {
        $this->startup = $startup instanceof Undefined ? new ContainerProbe() : $startup;
        $this->readiness = $readiness instanceof Undefined ? new ContainerProbe() : $readiness;
        $this->liveness = $liveness instanceof Undefined ? new ContainerProbe() : $liveness;
        $this->provided = array_filter([
            'startup' => !$startup instanceof Undefined,
            'readiness' => !$readiness instanceof Undefined,
            'liveness' => !$liveness instanceof Undefined,
        ]);
    }

    public static function fromArray(array $data): static
    {
        return new self(
            startup: Cast::model(ContainerProbe::class, $data['startup'] ?? null) ?? Undefined::Value,
            readiness: Cast::model(ContainerProbe::class, $data['readiness'] ?? null) ?? Undefined::Value,
            liveness: Cast::model(ContainerProbe::class, $data['liveness'] ?? null) ?? Undefined::Value,
        );
    }

    public function toArray(): array
    {
        $data = [];

        if (isset($this->provided['startup'])) {
            $data['startup'] = $this->startup->toArray();
        }

        if (isset($this->provided['readiness'])) {
            $data['readiness'] = $this->readiness->toArray();
        }

        if (isset($this->provided['liveness'])) {
            $data['liveness'] = $this->liveness->toArray();
        }

        return $data;
    }
}
