<?php

declare(strict_types=1);

// This file is generated by tools/generate.php from resources/specs/magic-containers.json. Do not edit.

namespace GoSuccess\Bunny\MagicContainers\Model;

use GoSuccess\Bunny\MagicContainers\Enum\RegistryType;
use GoSuccess\Bunny\Model\RequestModel;
use GoSuccess\Bunny\Model\Undefined;

/** Schema: ContainerRegistryRequest */
final readonly class ContainerRegistryRequest implements RequestModel
{
    public function __construct(
        /** Container registry display name */
        public string $displayName,
        public RegistryType|Undefined $type = Undefined::Value,
        /** Password credentials for container registry */
        public Credentials|Undefined $passwordCredentials = Undefined::Value,
    ) {}

    public function toArray(): array
    {
        $data = [];
        $data['displayName'] = $this->displayName;

        if (!$this->type instanceof Undefined) {
            $data['type'] = $this->type->value;
        }

        if (!$this->passwordCredentials instanceof Undefined) {
            $data['passwordCredentials'] = $this->passwordCredentials->toArray();
        }

        return $data;
    }
}
