<?php

declare(strict_types=1);

// This file is generated by tools/generate.php from resources/specs/magic-containers.json. Do not edit.

namespace GoSuccess\Bunny\MagicContainers\Model;

use GoSuccess\Bunny\Model\Cast;
use GoSuccess\Bunny\Model\RequestModel;
use GoSuccess\Bunny\Model\ResponseModel;
use GoSuccess\Bunny\Model\Undefined;

/** Schema: ContainerEntryPoint */
final readonly class ContainerEntryPoint implements RequestModel, ResponseModel
{
    public ?string $command;

    /** @var list<string> */
    public array $commandArray;

    public ?string $arguments;

    /** @var list<string> */
    public array $argumentsArray;

    public ?string $workingDirectory;

    /**
     * Payload keys the caller provided; toArray() sends exactly these.
     *
     * @var array<string, true>
     */
    private array $provided;

    /**
     * @param list<string>|Undefined $commandArray
     * @param list<string>|Undefined $argumentsArray
     */
    public function __construct(
        string|Undefined|null $command = Undefined::Value,
        array|Undefined $commandArray = Undefined::Value,
        string|Undefined|null $arguments = Undefined::Value,
        array|Undefined $argumentsArray = Undefined::Value,
        string|Undefined|null $workingDirectory = Undefined::Value,
    ) {
        $this->command = $command instanceof Undefined ? null : $command;
        $this->commandArray = $commandArray instanceof Undefined ? [] : $commandArray;
        $this->arguments = $arguments instanceof Undefined ? null : $arguments;
        $this->argumentsArray = $argumentsArray instanceof Undefined ? [] : $argumentsArray;
        $this->workingDirectory = $workingDirectory instanceof Undefined ? null : $workingDirectory;
        $this->provided = array_filter([
            'command' => !$command instanceof Undefined,
            'commandArray' => !$commandArray instanceof Undefined,
            'arguments' => !$arguments instanceof Undefined,
            'argumentsArray' => !$argumentsArray instanceof Undefined,
            'workingDirectory' => !$workingDirectory instanceof Undefined,
        ]);
    }

    public static function fromArray(array $data): static
    {
        return new self(
            command: Cast::string($data['command'] ?? null) ?? Undefined::Value,
            commandArray: Cast::listOf($data['commandArray'] ?? null, Cast::string(...)) ?: Undefined::Value,
            arguments: Cast::string($data['arguments'] ?? null) ?? Undefined::Value,
            argumentsArray: Cast::listOf($data['argumentsArray'] ?? null, Cast::string(...)) ?: Undefined::Value,
            workingDirectory: Cast::string($data['workingDirectory'] ?? null) ?? Undefined::Value,
        );
    }

    public function toArray(): array
    {
        $data = [];

        if (isset($this->provided['command'])) {
            $data['command'] = $this->command;
        }

        if (isset($this->provided['commandArray'])) {
            $data['commandArray'] = $this->commandArray;
        }

        if (isset($this->provided['arguments'])) {
            $data['arguments'] = $this->arguments;
        }

        if (isset($this->provided['argumentsArray'])) {
            $data['argumentsArray'] = $this->argumentsArray;
        }

        if (isset($this->provided['workingDirectory'])) {
            $data['workingDirectory'] = $this->workingDirectory;
        }

        return $data;
    }
}
