<?php

declare(strict_types=1);

// This file is generated by tools/generate.php from resources/specs/magic-containers.json. Do not edit.

namespace GoSuccess\Bunny\MagicContainers\Model;

use GoSuccess\Bunny\Model\Cast;
use GoSuccess\Bunny\Model\ResponseModel;

/** Schema: ContainerImageTag */
final readonly class ContainerImageTag implements ResponseModel
{
    public function __construct(
        public string $name = '',
    ) {}

    public static function fromArray(array $data): static
    {
        return new self(
            name: Cast::string($data['name'] ?? null) ?? '',
        );
    }
}
