<?php

declare(strict_types=1);

// This file is generated by tools/generate.php from resources/specs/magic-containers.json. Do not edit.

namespace GoSuccess\Bunny\MagicContainers\Model;

use GoSuccess\Bunny\MagicContainers\Enum\EndpointType;
use GoSuccess\Bunny\Model\Cast;
use GoSuccess\Bunny\Model\ResponseModel;

/**
 * Display endpoint model
 *
 * Schema: DisplayEndpoint
 */
final readonly class DisplayEndpoint implements ResponseModel
{
    public function __construct(
        public string $id = '',
        public string $address = '',
        public ?EndpointType $type = null,
    ) {}

    public static function fromArray(array $data): static
    {
        return new self(
            id: Cast::string($data['id'] ?? null) ?? '',
            address: Cast::string($data['address'] ?? null) ?? '',
            type: Cast::stringEnum(EndpointType::class, $data['type'] ?? null),
        );
    }
}
