<?php

declare(strict_types=1);

// This file is generated by tools/generate.php from resources/specs/magic-containers.json. Do not edit.

namespace GoSuccess\Bunny\MagicContainers\Model;

use GoSuccess\Bunny\Model\Cast;
use GoSuccess\Bunny\Model\RequestModel;
use GoSuccess\Bunny\Model\ResponseModel;
use GoSuccess\Bunny\Model\Undefined;

/** Schema: EndpointRequest */
final readonly class EndpointRequest implements RequestModel, ResponseModel
{
    public string $displayName;

    public ?CdnEndpointRequest $cdn;

    public ?AnycastEndpointRequest $anycast;

    /** The settings of a public IP endpoint. */
    public ?InternalIpEndpointRequest $internalIp;

    /**
     * Payload keys the caller provided; toArray() sends exactly these.
     *
     * @var array<string, true>
     */
    private array $provided;

    public function __construct(
        string|Undefined $displayName = Undefined::Value,
        CdnEndpointRequest|Undefined|null $cdn = Undefined::Value,
        AnycastEndpointRequest|Undefined|null $anycast = Undefined::Value,
        InternalIpEndpointRequest|Undefined|null $internalIp = Undefined::Value,
    ) {
        $this->displayName = $displayName instanceof Undefined ? '' : $displayName;
        $this->cdn = $cdn instanceof Undefined ? null : $cdn;
        $this->anycast = $anycast instanceof Undefined ? null : $anycast;
        $this->internalIp = $internalIp instanceof Undefined ? null : $internalIp;
        $this->provided = array_filter([
            'displayName' => !$displayName instanceof Undefined,
            'cdn' => !$cdn instanceof Undefined,
            'anycast' => !$anycast instanceof Undefined,
            'internalIp' => !$internalIp instanceof Undefined,
        ]);
    }

    public static function fromArray(array $data): static
    {
        return new self(
            displayName: Cast::string($data['displayName'] ?? null) ?? Undefined::Value,
            cdn: Cast::model(CdnEndpointRequest::class, $data['cdn'] ?? null) ?? Undefined::Value,
            anycast: Cast::model(AnycastEndpointRequest::class, $data['anycast'] ?? null) ?? Undefined::Value,
            internalIp: Cast::model(InternalIpEndpointRequest::class, $data['internalIp'] ?? null) ?? Undefined::Value,
        );
    }

    public function toArray(): array
    {
        $data = [];

        if (isset($this->provided['displayName'])) {
            $data['displayName'] = $this->displayName;
        }

        if (isset($this->provided['cdn'])) {
            $data['cdn'] = $this->cdn?->toArray();
        }

        if (isset($this->provided['anycast'])) {
            $data['anycast'] = $this->anycast?->toArray();
        }

        if (isset($this->provided['internalIp'])) {
            $data['internalIp'] = $this->internalIp?->toArray();
        }

        return $data;
    }
}
