<?php

declare(strict_types=1);

// This file is generated by tools/generate.php from resources/specs/magic-containers.json. Do not edit.

namespace GoSuccess\Bunny\MagicContainers\Model;

use GoSuccess\Bunny\MagicContainers\Enum\Protocol;
use GoSuccess\Bunny\Model\Cast;
use GoSuccess\Bunny\Model\ResponseModel;

/** Schema: EndpointPortMapping */
final readonly class EndpointPortMapping implements ResponseModel
{
    public function __construct(
        public int $containerPort = 0,
        public int $exposedPort = 0,
        /** @var list<Protocol> */
        public array $protocols = [],
    ) {}

    public static function fromArray(array $data): static
    {
        return new self(
            containerPort: Cast::int($data['containerPort'] ?? null) ?? 0,
            exposedPort: Cast::int($data['exposedPort'] ?? null) ?? 0,
            protocols: Cast::listOf($data['protocols'] ?? null, static fn(mixed $value): ?Protocol => Cast::stringEnum(Protocol::class, $value)),
        );
    }
}
