<?php

declare(strict_types=1);

// This file is generated by tools/generate.php from resources/specs/magic-containers.json. Do not edit.

namespace GoSuccess\Bunny\MagicContainers\Model;

use GoSuccess\Bunny\Model\Cast;
use GoSuccess\Bunny\Model\ResponseModel;

/** Schema: EndpointStickySession */
final readonly class EndpointStickySession implements ResponseModel
{
    public function __construct(
        public bool $enabled = false,
        /** @var list<string> */
        public array $sessionHeaders = [],
        public string $cookieName = '',
    ) {}

    public static function fromArray(array $data): static
    {
        return new self(
            enabled: Cast::bool($data['enabled'] ?? null) ?? false,
            sessionHeaders: Cast::listOf($data['sessionHeaders'] ?? null, Cast::string(...)),
            cookieName: Cast::string($data['cookieName'] ?? null) ?? '',
        );
    }
}
