<?php

declare(strict_types=1);

// This file is generated by tools/generate.php from resources/specs/magic-containers.json. Do not edit.

namespace GoSuccess\Bunny\MagicContainers\Model;

use GoSuccess\Bunny\Model\Cast;
use GoSuccess\Bunny\Model\RequestModel;
use GoSuccess\Bunny\Model\ResponseModel;
use GoSuccess\Bunny\Model\Undefined;

/** Schema: GrpcProbeRequestDetails */
final readonly class GrpcProbeRequestDetails implements RequestModel, ResponseModel
{
    public int $portNumber;

    /** If this is not specified, the default behavior is to probe the server's overall health status. */
    public ?string $serviceName;

    /**
     * Payload keys the caller provided; toArray() sends exactly these.
     *
     * @var array<string, true>
     */
    private array $provided;

    public function __construct(
        int|Undefined $portNumber = Undefined::Value,
        string|Undefined|null $serviceName = Undefined::Value,
    ) {
        $this->portNumber = $portNumber instanceof Undefined ? 0 : $portNumber;
        $this->serviceName = $serviceName instanceof Undefined ? null : $serviceName;
        $this->provided = array_filter([
            'portNumber' => !$portNumber instanceof Undefined,
            'serviceName' => !$serviceName instanceof Undefined,
        ]);
    }

    public static function fromArray(array $data): static
    {
        return new self(
            portNumber: Cast::int($data['portNumber'] ?? null) ?? Undefined::Value,
            serviceName: Cast::string($data['serviceName'] ?? null) ?? Undefined::Value,
        );
    }

    public function toArray(): array
    {
        $data = [];

        if (isset($this->provided['portNumber'])) {
            $data['portNumber'] = $this->portNumber;
        }

        if (isset($this->provided['serviceName'])) {
            $data['serviceName'] = $this->serviceName;
        }

        return $data;
    }
}
