<?php

declare(strict_types=1);

// This file is generated by tools/generate.php from resources/specs/magic-containers.json. Do not edit.

namespace GoSuccess\Bunny\MagicContainers\Model;

use GoSuccess\Bunny\Model\Cast;
use GoSuccess\Bunny\Model\ResponseModel;

/** Schema: ImageTagInfo */
final readonly class ImageTagInfo implements ResponseModel
{
    public function __construct(
        public string $imageNamespace = '',
        public string $image = '',
        public string $tag = '',
        public string $digest = '',
    ) {}

    public static function fromArray(array $data): static
    {
        return new self(
            imageNamespace: Cast::string($data['imageNamespace'] ?? null) ?? '',
            image: Cast::string($data['image'] ?? null) ?? '',
            tag: Cast::string($data['tag'] ?? null) ?? '',
            digest: Cast::string($data['digest'] ?? null) ?? '',
        );
    }
}
