<?php

declare(strict_types=1);

// This file is generated by tools/generate.php from resources/specs/magic-containers.json. Do not edit.

namespace GoSuccess\Bunny\MagicContainers\Model;

use GoSuccess\Bunny\MagicContainers\Enum\Grade;
use GoSuccess\Bunny\Model\Cast;
use GoSuccess\Bunny\Model\ResponseModel;

/**
 * Status grade model
 *
 * Schema: Int32StatusIndicator
 */
final readonly class Int32StatusIndicator implements ResponseModel
{
    public function __construct(
        public int $indicator = 0,
        public ?Grade $statusGrade = null,
    ) {}

    public static function fromArray(array $data): static
    {
        return new self(
            indicator: Cast::int($data['indicator'] ?? null) ?? 0,
            statusGrade: Cast::stringEnum(Grade::class, $data['statusGrade'] ?? null),
        );
    }
}
