<?php

declare(strict_types=1);

// This file is generated by tools/generate.php from resources/specs/magic-containers.json. Do not edit.

namespace GoSuccess\Bunny\MagicContainers\Model;

use GoSuccess\Bunny\Model\Cast;
use GoSuccess\Bunny\Model\ResponseModel;

/**
 * What one instance of the application may use. The same for every instance, so it is stated once.
 *
 * Schema: OverviewLimits
 */
final readonly class OverviewLimits implements ResponseModel
{
    public function __construct(
        public ?float $cpuCores = null,
        public ?float $ramBytes = null,
        public ?float $outboundBandwidthBytesPerSecond = null,
    ) {}

    public static function fromArray(array $data): static
    {
        return new self(
            cpuCores: Cast::float($data['cpuCores'] ?? null),
            ramBytes: Cast::float($data['ramBytes'] ?? null),
            outboundBandwidthBytesPerSecond: Cast::float($data['outboundBandwidthBytesPerSecond'] ?? null),
        );
    }
}
