<?php

declare(strict_types=1);

// This file is generated by tools/generate.php from resources/specs/magic-containers.json. Do not edit.

namespace GoSuccess\Bunny\MagicContainers\Model;

use GoSuccess\Bunny\MagicContainers\Enum\ContainerStatus;
use GoSuccess\Bunny\Model\Cast;
use GoSuccess\Bunny\Model\ResponseModel;

/**
 * Overview container model
 *
 * Schema: OverviewContainer
 */
final readonly class OverviewContainer implements ResponseModel
{
    public function __construct(
        public string $id = '',
        public string $name = '',
        public float $cpuUsage = 0.0,
        public float $ramUsage = 0.0,
        public string $reason = '',
        public string $message = '',
        public ?ContainerStatus $status = null,
        public ?string $image = null,
        public ?string $imageDisplay = null,
        public ?int $numberOfRestarts = null,
        public ?int $exitCode = null,
    ) {}

    public static function fromArray(array $data): static
    {
        return new self(
            id: Cast::string($data['id'] ?? null) ?? '',
            name: Cast::string($data['name'] ?? null) ?? '',
            cpuUsage: Cast::float($data['cpuUsage'] ?? null) ?? 0.0,
            ramUsage: Cast::float($data['ramUsage'] ?? null) ?? 0.0,
            reason: Cast::string($data['reason'] ?? null) ?? '',
            message: Cast::string($data['message'] ?? null) ?? '',
            status: Cast::stringEnum(ContainerStatus::class, $data['status'] ?? null),
            image: Cast::string($data['image'] ?? null),
            imageDisplay: Cast::string($data['imageDisplay'] ?? null),
            numberOfRestarts: Cast::int($data['numberOfRestarts'] ?? null),
            exitCode: Cast::int($data['exitCode'] ?? null),
        );
    }
}
