<?php

declare(strict_types=1);

// This file is generated by tools/generate.php from resources/specs/magic-containers.json. Do not edit.

namespace GoSuccess\Bunny\MagicContainers\Model;

use GoSuccess\Bunny\MagicContainers\Enum\ApplicationRuntimeType;
use GoSuccess\Bunny\Model\RequestModel;
use GoSuccess\Bunny\Model\Undefined;

/** Schema: PatchApplicationRequest */
final readonly class PatchApplicationRequest implements RequestModel
{
    public function __construct(
        public string|Undefined|null $name = Undefined::Value,
        public ApplicationRuntimeType|Undefined $runtimeType = Undefined::Value,
        public AutoscalingSettings|Undefined $autoScaling = Undefined::Value,
        public UpdateRegionSettingsRequest|Undefined $regionSettings = Undefined::Value,
        /** @var list<ContainerRequest>|Undefined */
        public array|Undefined $containerTemplates = Undefined::Value,
        /** @var list<VolumeRequest>|Undefined */
        public array|Undefined $volumes = Undefined::Value,
    ) {}

    public function toArray(): array
    {
        $data = [];

        if (!$this->name instanceof Undefined) {
            $data['name'] = $this->name;
        }

        if (!$this->runtimeType instanceof Undefined) {
            $data['runtimeType'] = $this->runtimeType->value;
        }

        if (!$this->autoScaling instanceof Undefined) {
            $data['autoScaling'] = $this->autoScaling->toArray();
        }

        if (!$this->regionSettings instanceof Undefined) {
            $data['regionSettings'] = $this->regionSettings->toArray();
        }

        if (!$this->containerTemplates instanceof Undefined) {
            $data['containerTemplates'] = array_map(static fn(ContainerRequest $item): array => $item->toArray(), $this->containerTemplates);
        }

        if (!$this->volumes instanceof Undefined) {
            $data['volumes'] = array_map(static fn(VolumeRequest $item): array => $item->toArray(), $this->volumes);
        }

        return $data;
    }
}
