<?php

declare(strict_types=1);

// This file is generated by tools/generate.php from resources/specs/magic-containers.json. Do not edit.

namespace GoSuccess\Bunny\MagicContainers\Model;

use GoSuccess\Bunny\MagicContainers\Enum\ImagePullPolicy;
use GoSuccess\Bunny\Model\RequestModel;
use GoSuccess\Bunny\Model\Undefined;

/** Schema: PatchContainerRequest */
final readonly class PatchContainerRequest implements RequestModel
{
    public function __construct(
        public string|Undefined|null $name = Undefined::Value,
        public string|Undefined|null $image = Undefined::Value,
        public string|Undefined|null $imageName = Undefined::Value,
        public string|Undefined|null $imageNamespace = Undefined::Value,
        public string|Undefined|null $imageTag = Undefined::Value,
        public string|Undefined|null $imageDigest = Undefined::Value,
        public string|Undefined|null $imageRegistryId = Undefined::Value,
        public ImagePullPolicy|Undefined $imagePullPolicy = Undefined::Value,
        public ContainerEntryPoint|Undefined $entryPoint = Undefined::Value,
        public ContainerProbes|Undefined $probes = Undefined::Value,
        /** @var list<EnvironmentVariable>|Undefined */
        public array|Undefined $environmentVariables = Undefined::Value,
        /** @var list<EndpointRequest>|Undefined */
        public array|Undefined $endpoints = Undefined::Value,
        /** @var list<VolumeMountRequest>|Undefined */
        public array|Undefined $volumeMounts = Undefined::Value,
    ) {}

    public function toArray(): array
    {
        $data = [];

        if (!$this->name instanceof Undefined) {
            $data['name'] = $this->name;
        }

        if (!$this->image instanceof Undefined) {
            $data['image'] = $this->image;
        }

        if (!$this->imageName instanceof Undefined) {
            $data['imageName'] = $this->imageName;
        }

        if (!$this->imageNamespace instanceof Undefined) {
            $data['imageNamespace'] = $this->imageNamespace;
        }

        if (!$this->imageTag instanceof Undefined) {
            $data['imageTag'] = $this->imageTag;
        }

        if (!$this->imageDigest instanceof Undefined) {
            $data['imageDigest'] = $this->imageDigest;
        }

        if (!$this->imageRegistryId instanceof Undefined) {
            $data['imageRegistryId'] = $this->imageRegistryId;
        }

        if (!$this->imagePullPolicy instanceof Undefined) {
            $data['imagePullPolicy'] = $this->imagePullPolicy->value;
        }

        if (!$this->entryPoint instanceof Undefined) {
            $data['entryPoint'] = $this->entryPoint->toArray();
        }

        if (!$this->probes instanceof Undefined) {
            $data['probes'] = $this->probes->toArray();
        }

        if (!$this->environmentVariables instanceof Undefined) {
            $data['environmentVariables'] = array_map(static fn(EnvironmentVariable $item): array => $item->toArray(), $this->environmentVariables);
        }

        if (!$this->endpoints instanceof Undefined) {
            $data['endpoints'] = array_map(static fn(EndpointRequest $item): array => $item->toArray(), $this->endpoints);
        }

        if (!$this->volumeMounts instanceof Undefined) {
            $data['volumeMounts'] = array_map(static fn(VolumeMountRequest $item): array => $item->toArray(), $this->volumeMounts);
        }

        return $data;
    }
}
