<?php

declare(strict_types=1);

// This file is generated by tools/generate.php from resources/specs/magic-containers.json. Do not edit.

namespace GoSuccess\Bunny\MagicContainers\Model;

use GoSuccess\Bunny\MagicContainers\Enum\RemoveContainerRegistryResponseStatus;
use GoSuccess\Bunny\Model\Cast;
use GoSuccess\Bunny\Model\ResponseModel;

/** Schema: RemoveContainerRegistryResult */
final readonly class RemoveContainerRegistryResult implements ResponseModel
{
    public function __construct(
        public ?RemoveContainerRegistryResponseStatus $status = null,
        /** @var list<string> */
        public array $applications = [],
    ) {}

    public static function fromArray(array $data): static
    {
        return new self(
            status: Cast::stringEnum(RemoveContainerRegistryResponseStatus::class, $data['status'] ?? null),
            applications: Cast::listOf($data['applications'] ?? null, Cast::string(...)),
        );
    }
}
