<?php

declare(strict_types=1);

// This file is generated by tools/generate.php from resources/specs/magic-containers.json. Do not edit.

namespace GoSuccess\Bunny\MagicContainers\Model;

use GoSuccess\Bunny\Model\Cast;
use GoSuccess\Bunny\Model\RequestModel;
use GoSuccess\Bunny\Model\ResponseModel;
use GoSuccess\Bunny\Model\Undefined;

/** Schema: RepositorySettings */
final readonly class RepositorySettings implements RequestModel, ResponseModel
{
    public ?string $templateRepository;

    public ?string $repositoryName;

    public ?string $owner;

    /**
     * Payload keys the caller provided; toArray() sends exactly these.
     *
     * @var array<string, true>
     */
    private array $provided;

    public function __construct(
        string|Undefined|null $templateRepository = Undefined::Value,
        string|Undefined|null $repositoryName = Undefined::Value,
        string|Undefined|null $owner = Undefined::Value,
    ) {
        $this->templateRepository = $templateRepository instanceof Undefined ? null : $templateRepository;
        $this->repositoryName = $repositoryName instanceof Undefined ? null : $repositoryName;
        $this->owner = $owner instanceof Undefined ? null : $owner;
        $this->provided = array_filter([
            'templateRepository' => !$templateRepository instanceof Undefined,
            'repositoryName' => !$repositoryName instanceof Undefined,
            'owner' => !$owner instanceof Undefined,
        ]);
    }

    public static function fromArray(array $data): static
    {
        return new self(
            templateRepository: Cast::string($data['templateRepository'] ?? null) ?? Undefined::Value,
            repositoryName: Cast::string($data['repositoryName'] ?? null) ?? Undefined::Value,
            owner: Cast::string($data['owner'] ?? null) ?? Undefined::Value,
        );
    }

    public function toArray(): array
    {
        $data = [];

        if (isset($this->provided['templateRepository'])) {
            $data['templateRepository'] = $this->templateRepository;
        }

        if (isset($this->provided['repositoryName'])) {
            $data['repositoryName'] = $this->repositoryName;
        }

        if (isset($this->provided['owner'])) {
            $data['owner'] = $this->owner;
        }

        return $data;
    }
}
