<?php

declare(strict_types=1);

// This file is generated by tools/generate.php from resources/specs/magic-containers.json. Do not edit.

namespace GoSuccess\Bunny\MagicContainers\Model;

use GoSuccess\Bunny\MagicContainers\Enum\SavedContainerRegistryStatus;
use GoSuccess\Bunny\Model\Cast;
use GoSuccess\Bunny\Model\ResponseModel;

/** Schema: SaveContainerRegistryResult */
final readonly class SaveContainerRegistryResult implements ResponseModel
{
    public function __construct(
        public ?int $id = null,
        public ?string $error = null,
        public ?SavedContainerRegistryStatus $status = null,
    ) {}

    public static function fromArray(array $data): static
    {
        return new self(
            id: Cast::int($data['id'] ?? null),
            error: Cast::string($data['error'] ?? null),
            status: Cast::stringEnum(SavedContainerRegistryStatus::class, $data['status'] ?? null),
        );
    }
}
