<?php

declare(strict_types=1);

// This file is generated by tools/generate.php from resources/specs/magic-containers.json. Do not edit.

namespace GoSuccess\Bunny\MagicContainers\Model;

use GoSuccess\Bunny\Model\Cast;
use GoSuccess\Bunny\Model\ResponseModel;

/** Schema: Statistics */
final readonly class Statistics implements ResponseModel
{
    public function __construct(
        /** @var array<array-key, float> */
        public array $targetLatencyChart = [],
        /** @var array<array-key, int> */
        public array $activeRegionsChart = [],
        /** @var array<array-key, float> */
        public array $latencyChart = [],
        /** @var array<array-key, int> */
        public array $instancesChart = [],
        /** @var array<array-key, float> */
        public array $cpuUsageChart = [],
        /** @var array<array-key, float> */
        public array $ramUsageChart = [],
        /** @var array<array-key, float> */
        public array $trafficChart = [],
        /** @var array<array-key, array<array-key, float>> */
        public array $volumesSplitUsageChart = [],
        /** @var array<array-key, array<array-key, float>> */
        public array $volumesSplitCapacityChart = [],
        /** @var array<array-key, float> */
        public array $volumesUsageChart = [],
        /** @var array<array-key, float> */
        public array $volumesCapacityChart = [],
    ) {}

    public static function fromArray(array $data): static
    {
        return new self(
            targetLatencyChart: Cast::mapOf($data['targetLatencyChart'] ?? null, Cast::float(...)),
            activeRegionsChart: Cast::mapOf($data['activeRegionsChart'] ?? null, Cast::int(...)),
            latencyChart: Cast::mapOf($data['latencyChart'] ?? null, Cast::float(...)),
            instancesChart: Cast::mapOf($data['instancesChart'] ?? null, Cast::int(...)),
            cpuUsageChart: Cast::mapOf($data['cpuUsageChart'] ?? null, Cast::float(...)),
            ramUsageChart: Cast::mapOf($data['ramUsageChart'] ?? null, Cast::float(...)),
            trafficChart: Cast::mapOf($data['trafficChart'] ?? null, Cast::float(...)),
            volumesSplitUsageChart: Cast::mapOf($data['volumesSplitUsageChart'] ?? null, static fn(mixed $value): array => Cast::mapOf($value, Cast::float(...))),
            volumesSplitCapacityChart: Cast::mapOf($data['volumesSplitCapacityChart'] ?? null, static fn(mixed $value): array => Cast::mapOf($value, Cast::float(...))),
            volumesUsageChart: Cast::mapOf($data['volumesUsageChart'] ?? null, Cast::float(...)),
            volumesCapacityChart: Cast::mapOf($data['volumesCapacityChart'] ?? null, Cast::float(...)),
        );
    }
}
