<?php

declare(strict_types=1);

// This file is generated by tools/generate.php from resources/specs/magic-containers.json. Do not edit.

namespace GoSuccess\Bunny\MagicContainers\Model;

use GoSuccess\Bunny\Model\Cast;
use GoSuccess\Bunny\Model\RequestModel;
use GoSuccess\Bunny\Model\ResponseModel;
use GoSuccess\Bunny\Model\Undefined;

/** Schema: StickySessionSettings */
final readonly class StickySessionSettings implements RequestModel, ResponseModel
{
    public bool $enabled;

    /** @var list<string> */
    public array $sessionHeaders;

    public string $cookieName;

    /**
     * Payload keys the caller provided; toArray() sends exactly these.
     *
     * @var array<string, true>
     */
    private array $provided;

    /** @param list<string>|Undefined $sessionHeaders */
    public function __construct(
        bool|Undefined $enabled = Undefined::Value,
        array|Undefined $sessionHeaders = Undefined::Value,
        string|Undefined $cookieName = Undefined::Value,
    ) {
        $this->enabled = $enabled instanceof Undefined ? false : $enabled;
        $this->sessionHeaders = $sessionHeaders instanceof Undefined ? [] : $sessionHeaders;
        $this->cookieName = $cookieName instanceof Undefined ? '' : $cookieName;
        $this->provided = array_filter([
            'enabled' => !$enabled instanceof Undefined,
            'sessionHeaders' => !$sessionHeaders instanceof Undefined,
            'cookieName' => !$cookieName instanceof Undefined,
        ]);
    }

    public static function fromArray(array $data): static
    {
        return new self(
            enabled: Cast::bool($data['enabled'] ?? null) ?? Undefined::Value,
            sessionHeaders: Cast::listOf($data['sessionHeaders'] ?? null, Cast::string(...)) ?: Undefined::Value,
            cookieName: Cast::string($data['cookieName'] ?? null) ?? Undefined::Value,
        );
    }

    public function toArray(): array
    {
        $data = [];

        if (isset($this->provided['enabled'])) {
            $data['enabled'] = $this->enabled;
        }

        if (isset($this->provided['sessionHeaders'])) {
            $data['sessionHeaders'] = $this->sessionHeaders;
        }

        if (isset($this->provided['cookieName'])) {
            $data['cookieName'] = $this->cookieName;
        }

        return $data;
    }
}
