<?php

declare(strict_types=1);

// This file is generated by tools/generate.php from resources/specs/magic-containers.json. Do not edit.

namespace GoSuccess\Bunny\MagicContainers\Model;

use GoSuccess\Bunny\Model\Json;
use GoSuccess\Bunny\Model\RequestModel;
use GoSuccess\Bunny\Model\Undefined;

/** Schema: UpdateRegionSettingsRequest */
final readonly class UpdateRegionSettingsRequest implements RequestModel
{
    public function __construct(
        /** @var list<string>|Undefined */
        public array|Undefined $allowedRegionIds = Undefined::Value,
        /** @var list<string>|Undefined */
        public array|Undefined $requiredRegionIds = Undefined::Value,
        public int|Undefined|null $maxAllowedRegions = Undefined::Value,
        /** @var array<array-key, string>|Undefined */
        public array|Undefined $nodeSelectors = Undefined::Value,
    ) {}

    public function toArray(): array
    {
        $data = [];

        if (!$this->allowedRegionIds instanceof Undefined) {
            $data['allowedRegionIds'] = $this->allowedRegionIds;
        }

        if (!$this->requiredRegionIds instanceof Undefined) {
            $data['requiredRegionIds'] = $this->requiredRegionIds;
        }

        if (!$this->maxAllowedRegions instanceof Undefined) {
            $data['maxAllowedRegions'] = $this->maxAllowedRegions;
        }

        if (!$this->nodeSelectors instanceof Undefined) {
            $data['nodeSelectors'] = Json::map($this->nodeSelectors);
        }

        return $data;
    }
}
