<?php

declare(strict_types=1);

// This file is generated by tools/generate.php from resources/specs/magic-containers.json. Do not edit.

namespace GoSuccess\Bunny\MagicContainers\Model;

use GoSuccess\Bunny\MagicContainers\Enum\ApplicationStatus;
use GoSuccess\Bunny\Model\Cast;
use GoSuccess\Bunny\Model\ResponseModel;

/** Schema: UsageSummary */
final readonly class UsageSummary implements ResponseModel
{
    public function __construct(
        public float $averageLatency = 0.0,
        public float $currentLatency = 0.0,
        public float $totalVolumeSizeInGb = 0.0,
        public float $monthlyCost = 0.0,
        /** @var array<array-key, float> */
        public array $latencyChart = [],
        public ?ApplicationStatus $status = null,
    ) {}

    public static function fromArray(array $data): static
    {
        return new self(
            averageLatency: Cast::float($data['averageLatency'] ?? null) ?? 0.0,
            currentLatency: Cast::float($data['currentLatency'] ?? null) ?? 0.0,
            totalVolumeSizeInGb: Cast::float($data['totalVolumeSizeInGb'] ?? null) ?? 0.0,
            monthlyCost: Cast::float($data['monthlyCost'] ?? null) ?? 0.0,
            latencyChart: Cast::mapOf($data['latencyChart'] ?? null, Cast::float(...)),
            status: Cast::stringEnum(ApplicationStatus::class, $data['status'] ?? null),
        );
    }
}
