<?php

declare(strict_types=1);

// This file is generated by tools/generate.php from resources/specs/magic-containers.json. Do not edit.

namespace GoSuccess\Bunny\MagicContainers\Model;

use GoSuccess\Bunny\Model\Cast;
use GoSuccess\Bunny\Model\ResponseModel;

/**
 * Volume list item model
 *
 * Schema: VolumeInList
 */
final readonly class VolumeInList implements ResponseModel
{
    public function __construct(
        public string $name = '',
        public string $id = '',
        public float $size = 0.0,
        public float $totalUsage = 0.0,
        public int $totalInstancesCount = 0,
        public int $attachedInstancesCount = 0,
        public int $containersCount = 0,
        /** @var list<VolumeInstance> */
        public array $volumeInstances = [],
    ) {}

    public static function fromArray(array $data): static
    {
        return new self(
            name: Cast::string($data['name'] ?? null) ?? '',
            id: Cast::string($data['id'] ?? null) ?? '',
            size: Cast::float($data['size'] ?? null) ?? 0.0,
            totalUsage: Cast::float($data['totalUsage'] ?? null) ?? 0.0,
            totalInstancesCount: Cast::int($data['totalInstancesCount'] ?? null) ?? 0,
            attachedInstancesCount: Cast::int($data['attachedInstancesCount'] ?? null) ?? 0,
            containersCount: Cast::int($data['containersCount'] ?? null) ?? 0,
            volumeInstances: Cast::modelList(VolumeInstance::class, $data['volumeInstances'] ?? null),
        );
    }
}
