<?php

declare(strict_types=1);

// This file is generated by tools/generate.php from resources/specs/magic-containers.json. Do not edit.

namespace GoSuccess\Bunny\MagicContainers\Model;

use GoSuccess\Bunny\MagicContainers\Enum\VolumeStatus;
use GoSuccess\Bunny\Model\Cast;
use GoSuccess\Bunny\Model\ResponseModel;

/**
 * Volume instance model
 *
 * Schema: VolumeInstance
 */
final readonly class VolumeInstance implements ResponseModel
{
    public function __construct(
        public string $id = '',
        /** @var list<string> */
        public array $attachedPods = [],
        /** @var list<string> */
        public array $attachedContainers = [],
        public string $region = '',
        public ?VolumeStatus $status = null,
        public float $size = 0.0,
        public float $usage = 0.0,
        public string $set = '',
    ) {}

    public static function fromArray(array $data): static
    {
        return new self(
            id: Cast::string($data['id'] ?? null) ?? '',
            attachedPods: Cast::listOf($data['attachedPods'] ?? null, Cast::string(...)),
            attachedContainers: Cast::listOf($data['attachedContainers'] ?? null, Cast::string(...)),
            region: Cast::string($data['region'] ?? null) ?? '',
            status: Cast::stringEnum(VolumeStatus::class, $data['status'] ?? null),
            size: Cast::float($data['size'] ?? null) ?? 0.0,
            usage: Cast::float($data['usage'] ?? null) ?? 0.0,
            set: Cast::string($data['set'] ?? null) ?? '',
        );
    }
}
