<?php

declare(strict_types=1);

// This file is generated by tools/generate.php from resources/specs/magic-containers.json. Do not edit.

namespace GoSuccess\Bunny\MagicContainers\Model;

use GoSuccess\Bunny\Model\Cast;
use GoSuccess\Bunny\Model\ResponseModel;

/** Schema: VolumeTemplate */
final readonly class VolumeTemplate implements ResponseModel
{
    public function __construct(
        public string $name = '',
        public float $size = 0.0,
    ) {}

    public static function fromArray(array $data): static
    {
        return new self(
            name: Cast::string($data['name'] ?? null) ?? '',
            size: Cast::float($data['size'] ?? null) ?? 0.0,
        );
    }
}
