<?php

declare(strict_types=1);

// This file is generated by tools/generate.php from resources/specs/magic-containers.json. Do not edit.

namespace GoSuccess\Bunny\MagicContainers\Model;

use GoSuccess\Bunny\Model\Cast;
use GoSuccess\Bunny\Model\ResponseModel;

/** Schema: VolumeSuggestion */
final readonly class VolumeSuggestion implements ResponseModel
{
    public function __construct(
        public string $containerPath = '',
        public string $suggestedVolumeName = '',
    ) {}

    public static function fromArray(array $data): static
    {
        return new self(
            containerPath: Cast::string($data['containerPath'] ?? null) ?? '',
            suggestedVolumeName: Cast::string($data['suggestedVolumeName'] ?? null) ?? '',
        );
    }
}
