<?php

declare(strict_types=1);

// This file is generated by tools/generate.php from resources/specs/magic-containers.json. Do not edit.

namespace GoSuccess\Bunny\MagicContainers\Model;

use GoSuccess\Bunny\Model\RequestModel;

/** Schema: VolumeRequest */
final readonly class VolumeRequest implements RequestModel
{
    public function __construct(
        public string $name,
        public int $size,
    ) {}

    public function toArray(): array
    {
        $data = [];
        $data['name'] = $this->name;
        $data['size'] = $this->size;

        return $data;
    }
}
