<?php

declare(strict_types=1);

// This file is generated by tools/generate.php from resources/specs/magic-containers.json. Do not edit.

namespace GoSuccess\Bunny\MagicContainers;

use GoSuccess\Bunny\ClientOptions;
use GoSuccess\Bunny\Http\Connection;
use GoSuccess\Bunny\Http\CurlHttpClient;
use GoSuccess\Bunny\Http\HttpClient;
use GoSuccess\Bunny\MagicContainers\Resource\ApplicationResource;
use GoSuccess\Bunny\MagicContainers\Resource\ContainerResource;
use GoSuccess\Bunny\MagicContainers\Resource\EndpointResource;
use GoSuccess\Bunny\MagicContainers\Resource\LimitResource;
use GoSuccess\Bunny\MagicContainers\Resource\LogForwardingResource;
use GoSuccess\Bunny\MagicContainers\Resource\NodeResource;
use GoSuccess\Bunny\MagicContainers\Resource\PodResource;
use GoSuccess\Bunny\MagicContainers\Resource\RegionResource;
use GoSuccess\Bunny\MagicContainers\Resource\RegistryResource;
use GoSuccess\Bunny\MagicContainers\Resource\VolumeResource;
use GoSuccess\Bunny\RateLimit\NullRateLimiter;
use GoSuccess\Bunny\RateLimit\RateLimiter;
use SensitiveParameter;

/**
 * Client for the bunny.net Magic Containers API (`https://api.bunny.net/mc`).
 *
 * Resources are created on first access, so unused ones cost nothing.
 */
final class MagicContainersClient
{
    public const string DEFAULT_BASE_URI = 'https://api.bunny.net/mc';

    /** Applications: their deployment, settings, statistics and costs. */
    public private(set) ApplicationResource $apps {
        get => $this->apps ??= new ApplicationResource($this->connection);
    }

    /** The container templates of applications. */
    public private(set) ContainerResource $containers {
        get => $this->containers ??= new ContainerResource($this->connection);
    }

    /** The endpoints that expose containers through the CDN or anycast IPs. */
    public private(set) EndpointResource $endpoints {
        get => $this->endpoints ??= new EndpointResource($this->connection);
    }

    /** The persistent volumes of applications. */
    public private(set) VolumeResource $volumes {
        get => $this->volumes ??= new VolumeResource($this->connection);
    }

    /** The running instances of applications. */
    public private(set) PodResource $pods {
        get => $this->pods ??= new PodResource($this->connection);
    }

    /** Container registries and the images they hold. */
    public private(set) RegistryResource $registries {
        get => $this->registries ??= new RegistryResource($this->connection);
    }

    /** The regions applications can run in. */
    public private(set) RegionResource $regions {
        get => $this->regions ??= new RegionResource($this->connection);
    }

    /** The IP addresses of the Magic Containers nodes, e.g. for allowlists. */
    public private(set) NodeResource $nodes {
        get => $this->nodes ??= new NodeResource($this->connection);
    }

    /** The limits of the account. */
    public private(set) LimitResource $limits {
        get => $this->limits ??= new LimitResource($this->connection);
    }

    /** Forwarding of application logs to syslog endpoints. */
    public private(set) LogForwardingResource $logForwarding {
        get => $this->logForwarding ??= new LogForwardingResource($this->connection);
    }

    private readonly Connection $connection;

    /**
     * @param string          $apiKey      The account API key (bunny.net dashboard → Account settings → API key).
     * @param ClientOptions   $options     Timeouts, retries and user agent.
     * @param HttpClient|null $httpClient  Custom transport; defaults to the built-in cURL transport.
     * @param RateLimiter     $rateLimiter Client-side throttling; disabled by default.
     * @param string          $baseUri     Base URI of the API.
     */
    public function __construct(
        #[SensitiveParameter]
        string $apiKey,
        ClientOptions $options = new ClientOptions(),
        ?HttpClient $httpClient = null,
        RateLimiter $rateLimiter = new NullRateLimiter(),
        string $baseUri = self::DEFAULT_BASE_URI,
    ) {
        $this->connection = new Connection(
            $baseUri,
            $apiKey,
            $options,
            $httpClient ?? new CurlHttpClient($options->timeout, $options->connectTimeout),
            $rateLimiter,
        );
    }
}
