<?php

declare(strict_types=1);

// This file is generated by tools/generate.php from resources/specs/magic-containers.json. Do not edit.

namespace GoSuccess\Bunny\MagicContainers\Resource;

use GoSuccess\Bunny\Http\Method;
use GoSuccess\Bunny\MagicContainers\Model\AddContainerRequest;
use GoSuccess\Bunny\MagicContainers\Model\ContainerTemplate;
use GoSuccess\Bunny\MagicContainers\Model\PatchContainerRequest;
use GoSuccess\Bunny\Resource\AbstractResource;

/** The container templates of applications. */
final class ContainerResource extends AbstractResource
{
    /**
     * Get Container Template
     *
     * Gets a container template within an application.
     *
     * `GET /apps/{appId}/containers/{containerId}`
     *
     * @param string $appId       The ID of the application
     * @param string $containerId The ID of the container template
     */
    public function get(string $appId, string $containerId): ContainerTemplate
    {
        $data = $this->connection->json(Method::Get, "apps/{$this->segment($appId)}/containers/{$this->segment($containerId)}");

        return self::toModel(ContainerTemplate::class, $data);
    }

    /**
     * Add Container Template
     *
     * Adds a new container template to an application.
     *
     * `POST /apps/{appId}/containers`
     *
     * @param string              $appId     The ID of the application
     * @param AddContainerRequest $container
     */
    public function create(string $appId, AddContainerRequest $container): ContainerTemplate
    {
        $data = $this->connection->json(Method::Post, "apps/{$this->segment($appId)}/containers", body: $container->toArray());

        return self::toModel(ContainerTemplate::class, $data);
    }

    /**
     * Patch Container Template
     *
     * Partially updates a container template within an application. Only provided fields will be updated; existing fields not included in the request will remain unchanged.
     *
     * `PATCH /apps/{appId}/containers/{containerId}`
     *
     * @param string                $appId       The ID of the application
     * @param string                $containerId The ID of the container template to update
     * @param PatchContainerRequest $changes
     */
    public function patch(string $appId, string $containerId, PatchContainerRequest $changes): ContainerTemplate
    {
        $data = $this->connection->json(Method::Patch, "apps/{$this->segment($appId)}/containers/{$this->segment($containerId)}", body: $changes->toArray());

        return self::toModel(ContainerTemplate::class, $data);
    }

    /**
     * Delete Container Template
     *
     * Deletes a container template from an application.
     *
     * `DELETE /apps/{appId}/containers/{containerId}`
     *
     * @param string $appId       The ID of the application
     * @param string $containerId The ID of the container template to delete
     */
    public function delete(string $appId, string $containerId): void
    {
        $this->connection->json(Method::Delete, "apps/{$this->segment($appId)}/containers/{$this->segment($containerId)}");
    }

    /**
     * Set Container Environment Variables
     *
     * Replaces all environment variables for a container template. All existing environment variables will be removed and replaced with the provided set.
     *
     * `PUT /apps/{appId}/containers/{containerId}/env`
     *
     * @param string                   $appId       The ID of the application
     * @param string                   $containerId The ID of the container template
     * @param array<array-key, string> $variables
     */
    public function setEnvironmentVariables(string $appId, string $containerId, array $variables): ContainerTemplate
    {
        $data = $this->connection->json(Method::Put, "apps/{$this->segment($appId)}/containers/{$this->segment($containerId)}/env", body: $variables);

        return self::toModel(ContainerTemplate::class, $data);
    }
}
