<?php

declare(strict_types=1);

// This file is generated by tools/generate.php from resources/specs/magic-containers.json. Do not edit.

namespace GoSuccess\Bunny\MagicContainers\Resource;

use GoSuccess\Bunny\Http\Method;
use GoSuccess\Bunny\MagicContainers\Model\EndpointListItem;
use GoSuccess\Bunny\MagicContainers\Model\EndpointRequest;
use GoSuccess\Bunny\Model\Cast;
use GoSuccess\Bunny\Resource\AbstractResource;

/** The endpoints that expose containers through the CDN or anycast IPs. */
final class EndpointResource extends AbstractResource
{
    /**
     * List application endpoints
     *
     * List endpoints from all containers for given application
     *
     * `GET /apps/{appId}/endpoints`
     *
     * @param string $appId The ID of the application
     *
     * @return list<EndpointListItem>
     */
    public function list(string $appId): array
    {
        $data = $this->connection->json(Method::Get, "apps/{$this->segment($appId)}/endpoints");

        return Cast::modelList(EndpointListItem::class, self::expectObject($data)['items'] ?? null);
    }

    /**
     * Add application endpoint
     *
     * Add CDN or Anycast endpoint to a container of given application.
     *
     * `POST /apps/{appId}/containers/{containerId}/endpoints`
     *
     * @param string          $appId       The ID of the application
     * @param string          $containerId The ID of the container template
     * @param EndpointRequest $endpoint
     */
    public function create(string $appId, string $containerId, EndpointRequest $endpoint): string
    {
        $data = $this->connection->json(Method::Post, "apps/{$this->segment($appId)}/containers/{$this->segment($containerId)}/endpoints", body: $endpoint->toArray());

        return Cast::string(self::expectObject($data)['id'] ?? null) ?? '';
    }

    /**
     * Update Application Endpoint
     *
     * Update an existing endpoint for given application
     *
     * `PUT /apps/{appId}/endpoints/{endpointId}`
     *
     * @param string          $appId      The ID of the application
     * @param string          $endpointId The display name of the endpoint to update
     * @param EndpointRequest $endpoint
     */
    public function update(string $appId, string $endpointId, EndpointRequest $endpoint): void
    {
        $this->connection->json(Method::Put, "apps/{$this->segment($appId)}/endpoints/{$this->segment($endpointId)}", body: $endpoint->toArray());
    }

    /**
     * Delete application endpoint
     *
     * Delete endpoint of a container for given application.
     *
     * `DELETE /apps/{appId}/endpoints/{endpointId}`
     *
     * @param string $appId      The ID of the application
     * @param string $endpointId The ID of the endpoint to delete
     */
    public function delete(string $appId, string $endpointId): void
    {
        $this->connection->json(Method::Delete, "apps/{$this->segment($appId)}/endpoints/{$this->segment($endpointId)}");
    }
}
