<?php

declare(strict_types=1);

// This file is generated by tools/generate.php from resources/specs/magic-containers.json. Do not edit.

namespace GoSuccess\Bunny\MagicContainers\Resource;

use GoSuccess\Bunny\Http\Method;
use GoSuccess\Bunny\MagicContainers\Model\UserLimits;
use GoSuccess\Bunny\Resource\AbstractResource;

/** The limits of the account. */
final class LimitResource extends AbstractResource
{
    /**
     * Get User Limits
     *
     * Retrieves the current resource limits and usage for the authenticated user, including application counts and instance limits.
     *
     * `GET /limits`
     */
    public function get(): UserLimits
    {
        $data = $this->connection->json(Method::Get, 'limits');

        return self::toModel(UserLimits::class, $data);
    }
}
