<?php

declare(strict_types=1);

// This file is generated by tools/generate.php from resources/specs/magic-containers.json. Do not edit.

namespace GoSuccess\Bunny\MagicContainers\Resource;

use GoSuccess\Bunny\Http\Method;
use GoSuccess\Bunny\Resource\AbstractResource;

/** The running instances of applications. */
final class PodResource extends AbstractResource
{
    /**
     * Recreate Pod
     *
     * Recreate a pod, deleting previous one.
     *
     * `POST /apps/{appId}/pods/{podId}/recreate`
     *
     * @param string $appId
     * @param string $podId
     */
    public function recreate(string $appId, string $podId): void
    {
        $this->connection->json(Method::Post, "apps/{$this->segment($appId)}/pods/{$this->segment($podId)}/recreate");
    }
}
