<?php

declare(strict_types=1);

// This file is generated by tools/generate.php from resources/specs/magic-containers.json. Do not edit.

namespace GoSuccess\Bunny\MagicContainers\Resource;

use GoSuccess\Bunny\Http\Method;
use GoSuccess\Bunny\MagicContainers\Model\Region;
use GoSuccess\Bunny\MagicContainers\Pagination;
use GoSuccess\Bunny\Model\Cast;
use GoSuccess\Bunny\Pagination\Page;
use GoSuccess\Bunny\Pagination\Paginator;
use GoSuccess\Bunny\Resource\AbstractResource;

/** The regions applications can run in. */
final class RegionResource extends AbstractResource
{
    /**
     * List Regions
     *
     * Lists all available regions where applications can be deployed, including their anycast support and capacity status.
     *
     * `GET /regions`
     *
     * @param string|null $nextCursor The position returned by the previous page; null for the first page.
     * @param int         $limit      The number of items per page.
     *
     * @return Page<Region>
     */
    public function list(?string $nextCursor = null, int $limit = 100): Page
    {
        $data = self::expectObject($this->connection->json(Method::Get, 'regions', [
            'nextCursor' => $nextCursor,
            'limit' => $limit,
        ]));

        return Pagination::cursor($data, Cast::modelList(Region::class, $data['items'] ?? null), $nextCursor);
    }

    /**
     * Iterate lazily over every item of list(), across all pages.
     *
     * `GET /regions`
     *
     * @param int $limit The number of items per page.
     *
     * @return Paginator<Region>
     */
    public function all(int $limit = 1000): Paginator
    {
        return new Paginator(fn(int|string|null $position): Page => $this->list(
            nextCursor: \is_string($position) ? $position : null,
            limit: $limit,
        ));
    }

    /**
     * Get Optimal Base Region
     *
     * Returns the optimal base region for deployment based on the user's CDN server token location.
     *
     * `GET /regions/optimal`
     *
     * @param string|null $cdnServerToken
     */
    public function optimal(?string $cdnServerToken = null): Region
    {
        $data = $this->connection->json(Method::Get, 'regions/optimal', [
            'cdnServerToken' => $cdnServerToken,
        ]);

        return self::toModel(Region::class, self::expectObject($data)['region'] ?? null);
    }
}
