<?php

declare(strict_types=1);

// This file is generated by tools/generate.php from resources/specs/shield.json. Do not edit.

namespace GoSuccess\Bunny\Shield\Model;

use GoSuccess\Bunny\Model\Cast;
use GoSuccess\Bunny\Model\ResponseModel;
use GoSuccess\Bunny\Shield\Enum\AccessListAction;

/**
 * Request model for updating an access list configuration.
 *
 * Schema: UpdateAccessListConfigurationRequest
 */
final readonly class AccessListConfiguration implements ResponseModel
{
    public function __construct(
        /** Whether the access list should be enabled or disabled. If null, the current state is preserved. */
        public ?bool $isEnabled = null,
        /**
         * 0 = None
         * 1 = Allow
         * 2 = Block
         * 3 = Challenge
         * 4 = Log
         * 5 = Bypass
         */
        public ?AccessListAction $action = null,
    ) {}

    public static function fromArray(array $data): static
    {
        return new self(
            isEnabled: Cast::bool($data['isEnabled'] ?? null),
            action: Cast::intEnum(AccessListAction::class, $data['action'] ?? null),
        );
    }
}
