<?php

declare(strict_types=1);

// This file is generated by tools/generate.php from resources/specs/shield.json. Do not edit.

namespace GoSuccess\Bunny\Shield\Model;

use DateTimeImmutable;
use GoSuccess\Bunny\Model\Cast;
use GoSuccess\Bunny\Model\ResponseModel;
use GoSuccess\Bunny\Shield\Enum\ApiGuardianRateLimitType;
use GoSuccess\Bunny\Shield\Enum\RateLimitTimeframe;

/**
 * Detailed view of a single API Guardian endpoint, including its validation settings,
 * authentication requirements, and rate limiting configuration.
 *
 * Schema: ApiGuardianEndpointDetails
 */
final readonly class ApiGuardianEndpoint implements ResponseModel
{
    public function __construct(
        public int $apiGuardianEndpointId = 0,
        public int $shieldZoneId = 0,
        /** The HTTP method (e.g. "GET", "POST"). */
        public ?string $requestMethod = null,
        /** The OAS path template (e.g. "/pets/{petId}"). */
        public ?string $requestPath = null,
        /** Whether inbound request bodies are validated against the OAS request body schema. */
        public bool $validateRequestBodySchema = false,
        /** Whether outbound response bodies are validated against the OAS response schema. */
        public bool $validateResponseBodySchema = false,
        /** Whether authentication credentials are enforced. */
        public bool $validateAuthorization = false,
        /** Whether this endpoint is active. Disabled endpoints are not enforced. */
        public bool $isEnabled = false,
        /**
         * Authentication schemes required by this endpoint, derived from the OAS security requirements.
         * Null when the endpoint has no security requirements.
         *
         * @var list<AuthSchemeDetails>
         */
        public array $authSchemes = [],
        /** The request body schema rendered as YAML for display purposes. Null if no request body is defined. */
        public ?string $requestBodySchemaYaml = null,
        /**
         * Response body schemas keyed by HTTP status code, rendered as YAML. Null if no response schemas are defined.
         *
         * @var array<array-key, string>
         */
        public array $responseBodySchemasYaml = [],
        /** All parameters defined in the OAS operation, grouped by location (path, query, header, cookie). */
        public ?ApiGuardianParameters $availableParameters = null,
        /**
         * Parameters selected for XSS/SQLi injection detection, grouped by location.
         * Null if not configured. Subset of BunnyNet.Shield.Api.Services.Shield.ApiGuardian.Models.ApiGuardianEndpointDetails.AvailableParameters.
         */
        public ?ApiGuardianParameters $injectionDetectionParameters = null,
        /** Whether XSS detection is enabled for the selected parameters. */
        public bool $detectParameterXss = false,
        /** Whether SQL injection detection is enabled for the selected parameters. */
        public bool $detectParameterSqli = false,
        /** Whether per-endpoint rate limiting is active. */
        public bool $rateLimitingEnabled = false,
        public ?ApiGuardianRateLimitType $rateLimitingType = null,
        /** Maximum number of requests allowed within the rate limiting timeframe before blocking. */
        public int $rateLimitingRequestCount = 0,
        /**
         * 1 = PerSecond
         * 10 = PerTenSeconds
         * 60 = PerOneMinute
         * 300 = PerFiveMinutes
         * 900 = PerFifteenMinutes
         * 3600 = PerOneHour
         */
        public ?RateLimitTimeframe $rateLimitingTimeframe = null,
        public ?DateTimeImmutable $createdAt = null,
        public ?DateTimeImmutable $updatedAt = null,
    ) {}

    public static function fromArray(array $data): static
    {
        return new self(
            apiGuardianEndpointId: Cast::int($data['apiGuardianEndpointId'] ?? null) ?? 0,
            shieldZoneId: Cast::int($data['shieldZoneId'] ?? null) ?? 0,
            requestMethod: Cast::string($data['requestMethod'] ?? null),
            requestPath: Cast::string($data['requestPath'] ?? null),
            validateRequestBodySchema: Cast::bool($data['validateRequestBodySchema'] ?? null) ?? false,
            validateResponseBodySchema: Cast::bool($data['validateResponseBodySchema'] ?? null) ?? false,
            validateAuthorization: Cast::bool($data['validateAuthorization'] ?? null) ?? false,
            isEnabled: Cast::bool($data['isEnabled'] ?? null) ?? false,
            authSchemes: Cast::modelList(AuthSchemeDetails::class, $data['authSchemes'] ?? null),
            requestBodySchemaYaml: Cast::string($data['requestBodySchemaYaml'] ?? null),
            responseBodySchemasYaml: Cast::mapOf($data['responseBodySchemasYaml'] ?? null, Cast::string(...)),
            availableParameters: Cast::model(ApiGuardianParameters::class, $data['availableParameters'] ?? null),
            injectionDetectionParameters: Cast::model(ApiGuardianParameters::class, $data['injectionDetectionParameters'] ?? null),
            detectParameterXss: Cast::bool($data['detectParameterXss'] ?? null) ?? false,
            detectParameterSqli: Cast::bool($data['detectParameterSqli'] ?? null) ?? false,
            rateLimitingEnabled: Cast::bool($data['rateLimitingEnabled'] ?? null) ?? false,
            rateLimitingType: Cast::stringEnum(ApiGuardianRateLimitType::class, $data['rateLimitingType'] ?? null),
            rateLimitingRequestCount: Cast::int($data['rateLimitingRequestCount'] ?? null) ?? 0,
            rateLimitingTimeframe: Cast::intEnum(RateLimitTimeframe::class, $data['rateLimitingTimeframe'] ?? null),
            createdAt: Cast::dateTime($data['createdAt'] ?? null),
            updatedAt: Cast::dateTime($data['updatedAt'] ?? null),
        );
    }
}
