<?php

declare(strict_types=1);

// This file is generated by tools/generate.php from resources/specs/shield.json. Do not edit.

namespace GoSuccess\Bunny\Shield\Model;

use GoSuccess\Bunny\Model\Cast;
use GoSuccess\Bunny\Model\ResponseModel;

/** Schema: ApiGuardianEndpointActivity */
final readonly class ApiGuardianCounts implements ResponseModel
{
    public function __construct(
        public int $blockedRequests = 0,
        public int $loggedRequests = 0,
        public int $rateLimited = 0,
        public int $requestsInspected = 0,
        public int $failedRequestValidation = 0,
        public int $failedAuthenticationEnforcement = 0,
    ) {}

    public static function fromArray(array $data): static
    {
        return new self(
            blockedRequests: Cast::int($data['blockedRequests'] ?? null) ?? 0,
            loggedRequests: Cast::int($data['loggedRequests'] ?? null) ?? 0,
            rateLimited: Cast::int($data['rateLimited'] ?? null) ?? 0,
            requestsInspected: Cast::int($data['requestsInspected'] ?? null) ?? 0,
            failedRequestValidation: Cast::int($data['failedRequestValidation'] ?? null) ?? 0,
            failedAuthenticationEnforcement: Cast::int($data['failedAuthenticationEnforcement'] ?? null) ?? 0,
        );
    }
}
