<?php

declare(strict_types=1);

// This file is generated by tools/generate.php from resources/specs/shield.json. Do not edit.

namespace GoSuccess\Bunny\Shield\Model;

use GoSuccess\Bunny\Model\Cast;
use GoSuccess\Bunny\Model\ResponseModel;

/**
 * The full API Guardian state for a shield zone: global configuration and all endpoints.
 *
 * Schema: ApiGuardianConfigurationResponse
 */
final readonly class ApiGuardian implements ResponseModel
{
    public function __construct(
        /** Global API Guardian configuration for a shield zone. */
        public ApiGuardianConfiguration $configuration = new ApiGuardianConfiguration(),
        /**
         * All endpoints discovered from the uploaded OpenAPI specification.
         *
         * @var list<ApiGuardianEndpoint>
         */
        public array $endpoints = [],
    ) {}

    public static function fromArray(array $data): static
    {
        return new self(
            configuration: Cast::model(ApiGuardianConfiguration::class, $data['configuration'] ?? null) ?? new ApiGuardianConfiguration(),
            endpoints: Cast::modelList(ApiGuardianEndpoint::class, $data['endpoints'] ?? null),
        );
    }
}
