<?php

declare(strict_types=1);

// This file is generated by tools/generate.php from resources/specs/shield.json. Do not edit.

namespace GoSuccess\Bunny\Shield\Model;

use GoSuccess\Bunny\Model\Cast;
use GoSuccess\Bunny\Model\ResponseModel;
use GoSuccess\Bunny\Shield\Enum\AuthLocation;
use GoSuccess\Bunny\Shield\Enum\AuthSchemeType;

/**
 * Describes a single authentication scheme required by an endpoint,
 * as extracted from the OpenAPI specification's securitySchemes.
 *
 * Schema: AuthSchemeDetails
 */
final readonly class AuthSchemeDetails implements ResponseModel
{
    public function __construct(
        /** The OpenAPI security scheme reference name (e.g. "bearerAuth", "apiKey"). */
        public ?string $schemeName = null,
        /** The type of security scheme as defined in the OpenAPI specification. */
        public ?AuthSchemeType $schemeType = null,
        /** Where an authentication credential is transmitted in the HTTP request. */
        public ?AuthLocation $location = null,
        /**
         * The name of the header, query parameter, or cookie that carries the credential
         * (e.g. "Authorization", "X-API-Key").
         */
        public ?string $credentialName = null,
        /** For HTTP auth schemes, the scheme name (e.g. "bearer", "basic"). Null for non-HTTP schemes. */
        public ?string $httpScheme = null,
    ) {}

    public static function fromArray(array $data): static
    {
        return new self(
            schemeName: Cast::string($data['schemeName'] ?? null),
            schemeType: Cast::stringEnum(AuthSchemeType::class, $data['schemeType'] ?? null),
            location: Cast::stringEnum(AuthLocation::class, $data['location'] ?? null),
            credentialName: Cast::string($data['credentialName'] ?? null),
            httpScheme: Cast::string($data['httpScheme'] ?? null),
        );
    }
}
