<?php

declare(strict_types=1);

// This file is generated by tools/generate.php from resources/specs/shield.json. Do not edit.

namespace GoSuccess\Bunny\Shield\Model;

use GoSuccess\Bunny\Model\Cast;
use GoSuccess\Bunny\Model\ResponseModel;
use GoSuccess\Bunny\Shield\Enum\BotCategory;
use GoSuccess\Bunny\Shield\Enum\BotCategoryAction;

/** Schema: BotCategoryDetails */
final readonly class BotCategorySetting implements ResponseModel
{
    public function __construct(
        /**
         * 0 = None
         * 1 = SEO
         * 2 = AIScraper
         * 3 = AITool
         * 4 = Tool
         * 5 = Ads
         * 6 = Preview
         * 7 = Social
         * 255 = System
         */
        public ?BotCategory $category = null,
        /**
         * 0 = None
         * 1 = Block
         * 2 = Allow
         */
        public ?BotCategoryAction $action = null,
    ) {}

    public static function fromArray(array $data): static
    {
        return new self(
            category: Cast::intEnum(BotCategory::class, $data['category'] ?? null),
            action: Cast::intEnum(BotCategoryAction::class, $data['action'] ?? null),
        );
    }
}
