<?php

declare(strict_types=1);

// This file is generated by tools/generate.php from resources/specs/shield.json. Do not edit.

namespace GoSuccess\Bunny\Shield\Model;

use GoSuccess\Bunny\Model\Cast;
use GoSuccess\Bunny\Model\ResponseModel;

/** Schema: BotDetectionData */
final readonly class BotDetectionCounts implements ResponseModel
{
    public function __construct(
        public int $loggedRequests = 0,
        public int $challengedRequests = 0,
    ) {}

    public static function fromArray(array $data): static
    {
        return new self(
            loggedRequests: Cast::int($data['loggedRequests'] ?? null) ?? 0,
            challengedRequests: Cast::int($data['challengedRequests'] ?? null) ?? 0,
        );
    }
}
