<?php

declare(strict_types=1);

// This file is generated by tools/generate.php from resources/specs/shield.json. Do not edit.

namespace GoSuccess\Bunny\Shield\Model;

use GoSuccess\Bunny\Model\Cast;
use GoSuccess\Bunny\Model\ResponseModel;

/** Schema: CustomWafRule */
final readonly class CustomRule implements ResponseModel
{
    public function __construct(
        public int $id = 0,
        public int $shieldZoneId = 0,
        public ?string $userId = null,
        public ?string $ruleName = null,
        public ?string $ruleDescription = null,
        public ?string $ruleJson = null,
        public CustomRuleConfiguration $ruleConfiguration = new CustomRuleConfiguration(),
    ) {}

    public static function fromArray(array $data): static
    {
        return new self(
            id: Cast::int($data['id'] ?? null) ?? 0,
            shieldZoneId: Cast::int($data['shieldZoneId'] ?? null) ?? 0,
            userId: Cast::string($data['userId'] ?? null),
            ruleName: Cast::string($data['ruleName'] ?? null),
            ruleDescription: Cast::string($data['ruleDescription'] ?? null),
            ruleJson: Cast::string($data['ruleJson'] ?? null),
            ruleConfiguration: Cast::model(CustomRuleConfiguration::class, $data['ruleConfiguration'] ?? null) ?? new CustomRuleConfiguration(),
        );
    }
}
