<?php

declare(strict_types=1);

// This file is generated by tools/generate.php from resources/specs/shield.json. Do not edit.

namespace GoSuccess\Bunny\Shield\Model;

use GoSuccess\Bunny\Model\Cast;
use GoSuccess\Bunny\Model\ResponseModel;
use GoSuccess\Bunny\Shield\Enum\MetricsOverviewResolution;

/** Schema: ShieldOverviewMetricsData */
final readonly class DetailedMetrics implements ResponseModel
{
    public function __construct(
        public MetricSeries $waf = new MetricSeries(),
        public MetricSeries $ddos = new MetricSeries(),
        public MetricSeries $rateLimit = new MetricSeries(),
        public MetricSeries $accessLists = new MetricSeries(),
        public MetricSeries $botDetection = new MetricSeries(),
        public MetricSeries $uploadScanning = new MetricSeries(),
        public MetricSeries $apiGuardian = new MetricSeries(),
        public int $totalCleanRequestsLimit = 0,
        public int $totalBillableRequestsThisMonth = 0,
        /**
         * 0 = Auto
         * 1 = TwoMinutes
         * 2 = TenMinutes
         * 3 = Hourly
         * 4 = Daily
         * 5 = Weekly
         * 6 = Monthly
         */
        public ?MetricsOverviewResolution $resolution = null,
    ) {}

    public static function fromArray(array $data): static
    {
        return new self(
            waf: Cast::model(MetricSeries::class, $data['waf'] ?? null) ?? new MetricSeries(),
            ddos: Cast::model(MetricSeries::class, $data['ddos'] ?? null) ?? new MetricSeries(),
            rateLimit: Cast::model(MetricSeries::class, $data['rateLimit'] ?? null) ?? new MetricSeries(),
            accessLists: Cast::model(MetricSeries::class, $data['accessLists'] ?? null) ?? new MetricSeries(),
            botDetection: Cast::model(MetricSeries::class, $data['botDetection'] ?? null) ?? new MetricSeries(),
            uploadScanning: Cast::model(MetricSeries::class, $data['uploadScanning'] ?? null) ?? new MetricSeries(),
            apiGuardian: Cast::model(MetricSeries::class, $data['apiGuardian'] ?? null) ?? new MetricSeries(),
            totalCleanRequestsLimit: Cast::int($data['totalCleanRequestsLimit'] ?? null) ?? 0,
            totalBillableRequestsThisMonth: Cast::int($data['totalBillableRequestsThisMonth'] ?? null) ?? 0,
            resolution: Cast::intEnum(MetricsOverviewResolution::class, $data['resolution'] ?? null),
        );
    }
}
