<?php

declare(strict_types=1);

// This file is generated by tools/generate.php from resources/specs/shield.json. Do not edit.

namespace GoSuccess\Bunny\Shield\Model;

use GoSuccess\Bunny\Model\Cast;
use GoSuccess\Bunny\Model\ResponseModel;

/**
 * An aggregated group of events (returned when the search request specifies groupBy).
 *
 * Schema: EventGroup
 */
final readonly class EventLogGroup implements ResponseModel
{
    public function __construct(
        /**
         * The group key: each requested groupBy dimension mapped to its value.
         *
         * @var array<array-key, string>
         */
        public array $key = [],
        /** Number of events in the group. */
        public int $count = 0,
        /** Earliest event time in the group (Unix time in milliseconds, UTC). */
        public int $firstSeen = 0,
        /** Most recent event time in the group (Unix time in milliseconds, UTC). */
        public int $lastSeen = 0,
        /**
         * Context aggregates for the group: country, asn, per-action counts (blocked/challenged/logged),
         * and features/ruleIds touched. Counts are numbers; features/ruleIds are comma-joined strings.
         *
         * @var array<array-key, mixed>|null
         */
        public ?array $context = null,
        /**
         * Per-group event counts bucketed across the requested window (mini time histogram), present only
         * when the request set `buckets`. Bucket i covers [from + i*width, from + (i+1)*width).
         *
         * @var list<int>
         */
        public array $sparkline = [],
    ) {}

    public static function fromArray(array $data): static
    {
        return new self(
            key: Cast::mapOf($data['key'] ?? null, Cast::string(...)),
            count: Cast::int($data['count'] ?? null) ?? 0,
            firstSeen: Cast::int($data['firstSeen'] ?? null) ?? 0,
            lastSeen: Cast::int($data['lastSeen'] ?? null) ?? 0,
            context: Cast::object($data['context'] ?? null),
            sparkline: Cast::listOf($data['sparkline'] ?? null, Cast::int(...)),
        );
    }
}
