<?php

declare(strict_types=1);

// This file is generated by tools/generate.php from resources/specs/shield.json. Do not edit.

namespace GoSuccess\Bunny\Shield\Model;

use GoSuccess\Bunny\Model\Cast;
use GoSuccess\Bunny\Model\ResponseModel;

/**
 * A single event returned in a flat (ungrouped) search.
 *
 * Schema: EventRow
 */
final readonly class EventLogRow implements ResponseModel
{
    public function __construct(
        /** Unique event identifier. */
        public ?string $logId = null,
        /** Event time as Unix time in milliseconds (UTC). */
        public int $timestamp = 0,
        /** The full request context for the event (JSON object). */
        public mixed $log = null,
        /**
         * Resolved dimension values for the event (e.g. ip, ruleId, url, ja4).
         *
         * @var array<array-key, string>
         */
        public array $fields = [],
    ) {}

    public static function fromArray(array $data): static
    {
        return new self(
            logId: Cast::string($data['logId'] ?? null),
            timestamp: Cast::int($data['timestamp'] ?? null) ?? 0,
            log: $data['log'] ?? null,
            fields: Cast::mapOf($data['fields'] ?? null, Cast::string(...)),
        );
    }
}
