<?php

declare(strict_types=1);

// This file is generated by tools/generate.php from resources/specs/shield.json. Do not edit.

namespace GoSuccess\Bunny\Shield\Model;

use DateTimeImmutable;
use GoSuccess\Bunny\Model\Cast;
use GoSuccess\Bunny\Model\ResponseModel;
use GoSuccess\Bunny\Shield\Enum\ShieldPlanType;

/** Schema: OverageSegment */
final readonly class OverageSegment implements ResponseModel
{
    public function __construct(
        public ?DateTimeImmutable $periodStart = null,
        public ?DateTimeImmutable $periodEnd = null,
        /**
         * 0 = Basic
         * 1 = Advanced
         * 2 = Business
         * 3 = Enterprise
         */
        public ?ShieldPlanType $planType = null,
        public int $overageAllowance = 0,
        public int $overage = 0,
    ) {}

    public static function fromArray(array $data): static
    {
        return new self(
            periodStart: Cast::dateTime($data['periodStart'] ?? null),
            periodEnd: Cast::dateTime($data['periodEnd'] ?? null),
            planType: Cast::intEnum(ShieldPlanType::class, $data['planType'] ?? null),
            overageAllowance: Cast::int($data['overageAllowance'] ?? null) ?? 0,
            overage: Cast::int($data['overage'] ?? null) ?? 0,
        );
    }
}
