<?php

declare(strict_types=1);

// This file is generated by tools/generate.php from resources/specs/shield.json. Do not edit.

namespace GoSuccess\Bunny\Shield\Model;

use GoSuccess\Bunny\Model\Cast;
use GoSuccess\Bunny\Model\Json;
use GoSuccess\Bunny\Model\RequestModel;
use GoSuccess\Bunny\Model\ResponseModel;
use GoSuccess\Bunny\Model\Undefined;
use GoSuccess\Bunny\Shield\Enum\RateLimitAction;
use GoSuccess\Bunny\Shield\Enum\RateLimitBlockTime;
use GoSuccess\Bunny\Shield\Enum\RateLimitCounterKey;
use GoSuccess\Bunny\Shield\Enum\RateLimitTimeframe;
use GoSuccess\Bunny\Shield\Enum\WafRuleOperatorType;
use GoSuccess\Bunny\Shield\Enum\WafRuleSeverityType;
use GoSuccess\Bunny\Shield\Enum\WafRuleTransformationType;

/** Schema: CreateWafRateLimitRuleModel */
final readonly class RateLimitRuleConfiguration implements RequestModel, ResponseModel
{
    /**
     * 1 = RateLimit
     * 2 = Log
     * 3 = Challenge
     */
    public ?RateLimitAction $actionType;

    /** @var array<array-key, string> */
    public array $variableTypes;

    /**
     * 0 = BEGINSWITH
     * 1 = ENDSWITH
     * 2 = CONTAINS
     * 3 = CONTAINSWORD
     * 4 = STRMATCH
     * 5 = EQ
     * 6 = GE
     * 7 = GT
     * 8 = LE
     * 9 = LT
     * 12 = WITHIN
     * 14 = RX
     * 15 = STREQ
     * 17 = DETECTSQLI
     * 18 = DETECTXSS
     */
    public ?WafRuleOperatorType $operatorType;

    /**
     * 0 = NOTICE
     * 1 = WARNING
     * 2 = CRITICAL
     */
    public ?WafRuleSeverityType $severityType;

    /** @var list<WafRuleTransformationType> */
    public array $transformationTypes;

    public ?string $value;

    public ?bool $isNegated;

    public ?bool $isRegexVariable;

    public int $requestCount;

    /**
     * 0 = IP
     * 1 = Host
     * 2 = Country
     * 3 = City
     * 4 = ASN
     * 5 = Organization
     * 6 = JA4
     * 7 = IP_JA4
     */
    public ?RateLimitCounterKey $counterKeyType;

    /**
     * 1 = PerSecond
     * 10 = PerTenSeconds
     * 60 = PerOneMinute
     * 300 = PerFiveMinutes
     * 900 = PerFifteenMinutes
     * 3600 = PerOneHour
     */
    public ?RateLimitTimeframe $timeframe;

    /**
     * 30 = ForThirtySeconds
     * 60 = ForOneMinute
     * 300 = ForFiveMinutes
     * 900 = ForFifteenMinutes
     * 1800 = ForThirtyMinutes
     * 3600 = ForOneHour
     */
    public ?RateLimitBlockTime $blockTime;

    /** @var list<ChainedRuleCondition> */
    public array $chainedRuleConditions;

    /**
     * Payload keys the caller provided; toArray() sends exactly these.
     *
     * @var array<string, true>
     */
    private array $provided;

    /**
     * @param array<array-key, string>|Undefined $variableTypes
     * @param list<WafRuleTransformationType>|Undefined $transformationTypes
     * @param list<ChainedRuleCondition>|Undefined $chainedRuleConditions
     */
    public function __construct(
        RateLimitAction|Undefined $actionType = Undefined::Value,
        array|Undefined $variableTypes = Undefined::Value,
        WafRuleOperatorType|Undefined $operatorType = Undefined::Value,
        WafRuleSeverityType|Undefined $severityType = Undefined::Value,
        array|Undefined $transformationTypes = Undefined::Value,
        string|Undefined|null $value = Undefined::Value,
        bool|Undefined|null $isNegated = Undefined::Value,
        bool|Undefined|null $isRegexVariable = Undefined::Value,
        int|Undefined $requestCount = Undefined::Value,
        RateLimitCounterKey|Undefined $counterKeyType = Undefined::Value,
        RateLimitTimeframe|Undefined $timeframe = Undefined::Value,
        RateLimitBlockTime|Undefined $blockTime = Undefined::Value,
        array|Undefined $chainedRuleConditions = Undefined::Value,
    ) {
        $this->actionType = $actionType instanceof Undefined ? null : $actionType;
        $this->variableTypes = $variableTypes instanceof Undefined ? [] : $variableTypes;
        $this->operatorType = $operatorType instanceof Undefined ? null : $operatorType;
        $this->severityType = $severityType instanceof Undefined ? null : $severityType;
        $this->transformationTypes = $transformationTypes instanceof Undefined ? [] : $transformationTypes;
        $this->value = $value instanceof Undefined ? null : $value;
        $this->isNegated = $isNegated instanceof Undefined ? null : $isNegated;
        $this->isRegexVariable = $isRegexVariable instanceof Undefined ? null : $isRegexVariable;
        $this->requestCount = $requestCount instanceof Undefined ? 0 : $requestCount;
        $this->counterKeyType = $counterKeyType instanceof Undefined ? null : $counterKeyType;
        $this->timeframe = $timeframe instanceof Undefined ? null : $timeframe;
        $this->blockTime = $blockTime instanceof Undefined ? null : $blockTime;
        $this->chainedRuleConditions = $chainedRuleConditions instanceof Undefined ? [] : $chainedRuleConditions;
        $this->provided = array_filter([
            'actionType' => !$actionType instanceof Undefined,
            'variableTypes' => !$variableTypes instanceof Undefined,
            'operatorType' => !$operatorType instanceof Undefined,
            'severityType' => !$severityType instanceof Undefined,
            'transformationTypes' => !$transformationTypes instanceof Undefined,
            'value' => !$value instanceof Undefined,
            'isNegated' => !$isNegated instanceof Undefined,
            'isRegexVariable' => !$isRegexVariable instanceof Undefined,
            'requestCount' => !$requestCount instanceof Undefined,
            'counterKeyType' => !$counterKeyType instanceof Undefined,
            'timeframe' => !$timeframe instanceof Undefined,
            'blockTime' => !$blockTime instanceof Undefined,
            'chainedRuleConditions' => !$chainedRuleConditions instanceof Undefined,
        ]);
    }

    public static function fromArray(array $data): static
    {
        return new self(
            actionType: Cast::intEnum(RateLimitAction::class, $data['actionType'] ?? null) ?? Undefined::Value,
            variableTypes: Cast::mapOf($data['variableTypes'] ?? null, Cast::string(...)) ?: Undefined::Value,
            operatorType: Cast::intEnum(WafRuleOperatorType::class, $data['operatorType'] ?? null) ?? Undefined::Value,
            severityType: Cast::intEnum(WafRuleSeverityType::class, $data['severityType'] ?? null) ?? Undefined::Value,
            transformationTypes: Cast::listOf($data['transformationTypes'] ?? null, static fn(mixed $value): ?WafRuleTransformationType => Cast::intEnum(WafRuleTransformationType::class, $value)) ?: Undefined::Value,
            value: Cast::string($data['value'] ?? null) ?? Undefined::Value,
            isNegated: Cast::bool($data['isNegated'] ?? null) ?? Undefined::Value,
            isRegexVariable: Cast::bool($data['isRegexVariable'] ?? null) ?? Undefined::Value,
            requestCount: Cast::int($data['requestCount'] ?? null) ?? Undefined::Value,
            counterKeyType: Cast::intEnum(RateLimitCounterKey::class, $data['counterKeyType'] ?? null) ?? Undefined::Value,
            timeframe: Cast::intEnum(RateLimitTimeframe::class, $data['timeframe'] ?? null) ?? Undefined::Value,
            blockTime: Cast::intEnum(RateLimitBlockTime::class, $data['blockTime'] ?? null) ?? Undefined::Value,
            chainedRuleConditions: Cast::modelList(ChainedRuleCondition::class, $data['chainedRuleConditions'] ?? null) ?: Undefined::Value,
        );
    }

    public function toArray(): array
    {
        $data = [];

        if (isset($this->provided['actionType'])) {
            $data['actionType'] = $this->actionType?->value;
        }

        if (isset($this->provided['variableTypes'])) {
            $data['variableTypes'] = Json::map($this->variableTypes);
        }

        if (isset($this->provided['operatorType'])) {
            $data['operatorType'] = $this->operatorType?->value;
        }

        if (isset($this->provided['severityType'])) {
            $data['severityType'] = $this->severityType?->value;
        }

        if (isset($this->provided['transformationTypes'])) {
            $data['transformationTypes'] = array_map(static fn(WafRuleTransformationType $item): int => $item->value, $this->transformationTypes);
        }

        if (isset($this->provided['value'])) {
            $data['value'] = $this->value;
        }

        if (isset($this->provided['isNegated'])) {
            $data['isNegated'] = $this->isNegated;
        }

        if (isset($this->provided['isRegexVariable'])) {
            $data['isRegexVariable'] = $this->isRegexVariable;
        }

        if (isset($this->provided['requestCount'])) {
            $data['requestCount'] = $this->requestCount;
        }

        if (isset($this->provided['counterKeyType'])) {
            $data['counterKeyType'] = $this->counterKeyType?->value;
        }

        if (isset($this->provided['timeframe'])) {
            $data['timeframe'] = $this->timeframe?->value;
        }

        if (isset($this->provided['blockTime'])) {
            $data['blockTime'] = $this->blockTime?->value;
        }

        if (isset($this->provided['chainedRuleConditions'])) {
            $data['chainedRuleConditions'] = array_map(static fn(ChainedRuleCondition $item): array => $item->toArray(), $this->chainedRuleConditions);
        }

        return $data;
    }
}
