<?php

declare(strict_types=1);

// This file is generated by tools/generate.php from resources/specs/shield.json. Do not edit.

namespace GoSuccess\Bunny\Shield\Model;

use GoSuccess\Bunny\Model\Cast;
use GoSuccess\Bunny\Model\ResponseModel;

/** Schema: RatelimitMetrics */
final readonly class RateLimitRuleMetrics implements ResponseModel
{
    public function __construct(
        public RateLimitRuleCounts $overview = new RateLimitRuleCounts(),
        /** @var array<array-key, RateLimitRuleCounts> */
        public array $ratelimitOverviewPastTwentyEightDays = [],
    ) {}

    public static function fromArray(array $data): static
    {
        return new self(
            overview: Cast::model(RateLimitRuleCounts::class, $data['overview'] ?? null) ?? new RateLimitRuleCounts(),
            ratelimitOverviewPastTwentyEightDays: Cast::mapOf($data['ratelimitOverviewPastTwentyEightDays'] ?? null, static fn(mixed $value): ?RateLimitRuleCounts => Cast::model(RateLimitRuleCounts::class, $value)),
        );
    }
}
