<?php

declare(strict_types=1);

// This file is generated by tools/generate.php from resources/specs/shield.json. Do not edit.

namespace GoSuccess\Bunny\Shield\Model;

use GoSuccess\Bunny\Model\Cast;
use GoSuccess\Bunny\Model\ResponseModel;
use GoSuccess\Bunny\Shield\Enum\BotDetectionExecutionMode;
use GoSuccess\Bunny\Shield\Enum\UploadScanningScannerMode;

/** Schema: ShieldZoneDefaults */
final readonly class ShieldZoneDefaults implements ResponseModel
{
    public function __construct(
        public ShieldZoneSettings $shieldZone = new ShieldZoneSettings(),
        /**
         * 0 = LogOnly
         * 1 = Challenge
         */
        public ?BotDetectionExecutionMode $botDetectionExecutionMode = null,
        /**
         * 0 = Disabled
         * 1 = Log
         * 2 = Block
         */
        public ?UploadScanningScannerMode $csamScanningMode = null,
        /**
         * 0 = Disabled
         * 1 = Log
         * 2 = Block
         */
        public ?UploadScanningScannerMode $antivirusScanningMode = null,
        /** @var list<SuggestedAccessList> */
        public array $accessLists = [],
    ) {}

    public static function fromArray(array $data): static
    {
        return new self(
            shieldZone: Cast::model(ShieldZoneSettings::class, $data['shieldZone'] ?? null) ?? new ShieldZoneSettings(),
            botDetectionExecutionMode: Cast::intEnum(BotDetectionExecutionMode::class, $data['botDetectionExecutionMode'] ?? null),
            csamScanningMode: Cast::intEnum(UploadScanningScannerMode::class, $data['csamScanningMode'] ?? null),
            antivirusScanningMode: Cast::intEnum(UploadScanningScannerMode::class, $data['antivirusScanningMode'] ?? null),
            accessLists: Cast::modelList(SuggestedAccessList::class, $data['accessLists'] ?? null),
        );
    }
}
