<?php

declare(strict_types=1);

// This file is generated by tools/generate.php from resources/specs/shield.json. Do not edit.

namespace GoSuccess\Bunny\Shield\Model;

use GoSuccess\Bunny\Model\Cast;
use GoSuccess\Bunny\Model\ResponseModel;

/** Schema: UpdateShieldZoneRequest */
final readonly class ShieldZoneUpdate implements ResponseModel
{
    public function __construct(
        public ShieldZoneSettings $shieldZone = new ShieldZoneSettings(),
        public int $shieldZoneId = 0,
    ) {}

    public static function fromArray(array $data): static
    {
        return new self(
            shieldZone: Cast::model(ShieldZoneSettings::class, $data['shieldZone'] ?? null) ?? new ShieldZoneSettings(),
            shieldZoneId: Cast::int($data['shieldZoneId'] ?? null) ?? 0,
        );
    }
}
