<?php

declare(strict_types=1);

// This file is generated by tools/generate.php from resources/specs/shield.json. Do not edit.

namespace GoSuccess\Bunny\Shield\Model;

use DateTimeImmutable;
use DateTimeInterface;
use GoSuccess\Bunny\Model\Cast;
use GoSuccess\Bunny\Model\Json;
use GoSuccess\Bunny\Model\RequestModel;
use GoSuccess\Bunny\Model\ResponseModel;
use GoSuccess\Bunny\Model\Undefined;
use GoSuccess\Bunny\Shield\Enum\DdosSensitivity;
use GoSuccess\Bunny\Shield\Enum\ShieldPlanType;
use GoSuccess\Bunny\Shield\Enum\WafExecutionMode;
use GoSuccess\Bunny\Shield\Enum\WafPayloadLimitAction;

/** Schema: ShieldZoneRequest */
final readonly class ShieldZoneSettings implements RequestModel, ResponseModel
{
    public int $shieldZoneId;

    /** @deprecated */
    public ?bool $premiumPlan;

    /**
     * 0 = Basic
     * 1 = Advanced
     * 2 = Business
     * 3 = Enterprise
     */
    public ?ShieldPlanType $planType;

    public ?bool $learningMode;

    public ?DateTimeImmutable $learningModeUntil;

    public ?bool $wafEnabled;

    /**
     * 0 = Log
     * 1 = Block
     */
    public ?WafExecutionMode $wafExecutionMode;

    /** @var list<string> */
    public array $wafDisabledRules;

    /** @var list<string> */
    public array $wafLogOnlyRules;

    /** @var list<int> */
    public array $wafCustomRuleOrder;

    public ?bool $wafRequestHeaderLoggingEnabled;

    public ?bool $requestBodyLoggingEnabled;

    /** @var list<string> */
    public array $wafRequestIgnoredHeaders;

    public ?bool $wafRealtimeThreatIntelligenceEnabled;

    public ?int $wafProfileId;

    /** @var list<ZoneWafEngineSetting> */
    public array $wafEngineConfig;

    /**
     * 0 = Block
     * 1 = Log
     * 2 = Ignore
     */
    public ?WafPayloadLimitAction $wafRequestBodyLimitAction;

    /**
     * 0 = Block
     * 1 = Log
     * 2 = Ignore
     */
    public ?WafPayloadLimitAction $wafResponseBodyLimitAction;

    /**
     * 0 = Off
     * 1 = Low
     * 2 = Medium
     * 3 = High
     * 4 = Challenge
     */
    public ?DdosSensitivity $dDoSShieldSensitivity;

    public ?int $dDoSChallengeWindow;

    public ?bool $whitelabelResponsePages;

    /**
     * Payload keys the caller provided; toArray() sends exactly these.
     *
     * @var array<string, true>
     */
    private array $provided;

    /**
     * @param list<string>|Undefined $wafDisabledRules
     * @param list<string>|Undefined $wafLogOnlyRules
     * @param list<int>|Undefined $wafCustomRuleOrder
     * @param list<string>|Undefined $wafRequestIgnoredHeaders
     * @param list<ZoneWafEngineSetting>|Undefined $wafEngineConfig
     */
    public function __construct(
        int|Undefined $shieldZoneId = Undefined::Value,
        bool|Undefined|null $premiumPlan = Undefined::Value,
        ShieldPlanType|Undefined $planType = Undefined::Value,
        bool|Undefined|null $learningMode = Undefined::Value,
        DateTimeInterface|Undefined|null $learningModeUntil = Undefined::Value,
        bool|Undefined|null $wafEnabled = Undefined::Value,
        WafExecutionMode|Undefined $wafExecutionMode = Undefined::Value,
        array|Undefined $wafDisabledRules = Undefined::Value,
        array|Undefined $wafLogOnlyRules = Undefined::Value,
        array|Undefined $wafCustomRuleOrder = Undefined::Value,
        bool|Undefined|null $wafRequestHeaderLoggingEnabled = Undefined::Value,
        bool|Undefined|null $requestBodyLoggingEnabled = Undefined::Value,
        array|Undefined $wafRequestIgnoredHeaders = Undefined::Value,
        bool|Undefined|null $wafRealtimeThreatIntelligenceEnabled = Undefined::Value,
        int|Undefined|null $wafProfileId = Undefined::Value,
        array|Undefined $wafEngineConfig = Undefined::Value,
        WafPayloadLimitAction|Undefined $wafRequestBodyLimitAction = Undefined::Value,
        WafPayloadLimitAction|Undefined $wafResponseBodyLimitAction = Undefined::Value,
        DdosSensitivity|Undefined $dDoSShieldSensitivity = Undefined::Value,
        int|Undefined|null $dDoSChallengeWindow = Undefined::Value,
        bool|Undefined|null $whitelabelResponsePages = Undefined::Value,
    ) {
        $this->shieldZoneId = $shieldZoneId instanceof Undefined ? 0 : $shieldZoneId;
        $this->premiumPlan = $premiumPlan instanceof Undefined ? null : $premiumPlan;
        $this->planType = $planType instanceof Undefined ? null : $planType;
        $this->learningMode = $learningMode instanceof Undefined ? null : $learningMode;
        $this->learningModeUntil = $learningModeUntil instanceof Undefined ? null : ($learningModeUntil === null ? null : DateTimeImmutable::createFromInterface($learningModeUntil));
        $this->wafEnabled = $wafEnabled instanceof Undefined ? null : $wafEnabled;
        $this->wafExecutionMode = $wafExecutionMode instanceof Undefined ? null : $wafExecutionMode;
        $this->wafDisabledRules = $wafDisabledRules instanceof Undefined ? [] : $wafDisabledRules;
        $this->wafLogOnlyRules = $wafLogOnlyRules instanceof Undefined ? [] : $wafLogOnlyRules;
        $this->wafCustomRuleOrder = $wafCustomRuleOrder instanceof Undefined ? [] : $wafCustomRuleOrder;
        $this->wafRequestHeaderLoggingEnabled = $wafRequestHeaderLoggingEnabled instanceof Undefined ? null : $wafRequestHeaderLoggingEnabled;
        $this->requestBodyLoggingEnabled = $requestBodyLoggingEnabled instanceof Undefined ? null : $requestBodyLoggingEnabled;
        $this->wafRequestIgnoredHeaders = $wafRequestIgnoredHeaders instanceof Undefined ? [] : $wafRequestIgnoredHeaders;
        $this->wafRealtimeThreatIntelligenceEnabled = $wafRealtimeThreatIntelligenceEnabled instanceof Undefined ? null : $wafRealtimeThreatIntelligenceEnabled;
        $this->wafProfileId = $wafProfileId instanceof Undefined ? null : $wafProfileId;
        $this->wafEngineConfig = $wafEngineConfig instanceof Undefined ? [] : $wafEngineConfig;
        $this->wafRequestBodyLimitAction = $wafRequestBodyLimitAction instanceof Undefined ? null : $wafRequestBodyLimitAction;
        $this->wafResponseBodyLimitAction = $wafResponseBodyLimitAction instanceof Undefined ? null : $wafResponseBodyLimitAction;
        $this->dDoSShieldSensitivity = $dDoSShieldSensitivity instanceof Undefined ? null : $dDoSShieldSensitivity;
        $this->dDoSChallengeWindow = $dDoSChallengeWindow instanceof Undefined ? null : $dDoSChallengeWindow;
        $this->whitelabelResponsePages = $whitelabelResponsePages instanceof Undefined ? null : $whitelabelResponsePages;
        $this->provided = array_filter([
            'shieldZoneId' => !$shieldZoneId instanceof Undefined,
            'premiumPlan' => !$premiumPlan instanceof Undefined,
            'planType' => !$planType instanceof Undefined,
            'learningMode' => !$learningMode instanceof Undefined,
            'learningModeUntil' => !$learningModeUntil instanceof Undefined,
            'wafEnabled' => !$wafEnabled instanceof Undefined,
            'wafExecutionMode' => !$wafExecutionMode instanceof Undefined,
            'wafDisabledRules' => !$wafDisabledRules instanceof Undefined,
            'wafLogOnlyRules' => !$wafLogOnlyRules instanceof Undefined,
            'wafCustomRuleOrder' => !$wafCustomRuleOrder instanceof Undefined,
            'wafRequestHeaderLoggingEnabled' => !$wafRequestHeaderLoggingEnabled instanceof Undefined,
            'requestBodyLoggingEnabled' => !$requestBodyLoggingEnabled instanceof Undefined,
            'wafRequestIgnoredHeaders' => !$wafRequestIgnoredHeaders instanceof Undefined,
            'wafRealtimeThreatIntelligenceEnabled' => !$wafRealtimeThreatIntelligenceEnabled instanceof Undefined,
            'wafProfileId' => !$wafProfileId instanceof Undefined,
            'wafEngineConfig' => !$wafEngineConfig instanceof Undefined,
            'wafRequestBodyLimitAction' => !$wafRequestBodyLimitAction instanceof Undefined,
            'wafResponseBodyLimitAction' => !$wafResponseBodyLimitAction instanceof Undefined,
            'dDoSShieldSensitivity' => !$dDoSShieldSensitivity instanceof Undefined,
            'dDoSChallengeWindow' => !$dDoSChallengeWindow instanceof Undefined,
            'whitelabelResponsePages' => !$whitelabelResponsePages instanceof Undefined,
        ]);
    }

    public static function fromArray(array $data): static
    {
        return new self(
            shieldZoneId: Cast::int($data['shieldZoneId'] ?? null) ?? Undefined::Value,
            premiumPlan: Cast::bool($data['premiumPlan'] ?? null) ?? Undefined::Value,
            planType: Cast::intEnum(ShieldPlanType::class, $data['planType'] ?? null) ?? Undefined::Value,
            learningMode: Cast::bool($data['learningMode'] ?? null) ?? Undefined::Value,
            learningModeUntil: Cast::dateTime($data['learningModeUntil'] ?? null) ?? Undefined::Value,
            wafEnabled: Cast::bool($data['wafEnabled'] ?? null) ?? Undefined::Value,
            wafExecutionMode: Cast::intEnum(WafExecutionMode::class, $data['wafExecutionMode'] ?? null) ?? Undefined::Value,
            wafDisabledRules: Cast::listOf($data['wafDisabledRules'] ?? null, Cast::string(...)) ?: Undefined::Value,
            wafLogOnlyRules: Cast::listOf($data['wafLogOnlyRules'] ?? null, Cast::string(...)) ?: Undefined::Value,
            wafCustomRuleOrder: Cast::listOf($data['wafCustomRuleOrder'] ?? null, Cast::int(...)) ?: Undefined::Value,
            wafRequestHeaderLoggingEnabled: Cast::bool($data['wafRequestHeaderLoggingEnabled'] ?? null) ?? Undefined::Value,
            requestBodyLoggingEnabled: Cast::bool($data['requestBodyLoggingEnabled'] ?? null) ?? Undefined::Value,
            wafRequestIgnoredHeaders: Cast::listOf($data['wafRequestIgnoredHeaders'] ?? null, Cast::string(...)) ?: Undefined::Value,
            wafRealtimeThreatIntelligenceEnabled: Cast::bool($data['wafRealtimeThreatIntelligenceEnabled'] ?? null) ?? Undefined::Value,
            wafProfileId: Cast::int($data['wafProfileId'] ?? null) ?? Undefined::Value,
            wafEngineConfig: Cast::modelList(ZoneWafEngineSetting::class, $data['wafEngineConfig'] ?? null) ?: Undefined::Value,
            wafRequestBodyLimitAction: Cast::intEnum(WafPayloadLimitAction::class, $data['wafRequestBodyLimitAction'] ?? null) ?? Undefined::Value,
            wafResponseBodyLimitAction: Cast::intEnum(WafPayloadLimitAction::class, $data['wafResponseBodyLimitAction'] ?? null) ?? Undefined::Value,
            dDoSShieldSensitivity: Cast::intEnum(DdosSensitivity::class, $data['dDoSShieldSensitivity'] ?? null) ?? Undefined::Value,
            dDoSChallengeWindow: Cast::int($data['dDoSChallengeWindow'] ?? null) ?? Undefined::Value,
            whitelabelResponsePages: Cast::bool($data['whitelabelResponsePages'] ?? null) ?? Undefined::Value,
        );
    }

    public function toArray(): array
    {
        $data = [];

        if (isset($this->provided['shieldZoneId'])) {
            $data['shieldZoneId'] = $this->shieldZoneId;
        }

        if (isset($this->provided['premiumPlan'])) {
            $data['premiumPlan'] = $this->premiumPlan;
        }

        if (isset($this->provided['planType'])) {
            $data['planType'] = $this->planType?->value;
        }

        if (isset($this->provided['learningMode'])) {
            $data['learningMode'] = $this->learningMode;
        }

        if (isset($this->provided['learningModeUntil'])) {
            $data['learningModeUntil'] = $this->learningModeUntil === null ? null : Json::date($this->learningModeUntil);
        }

        if (isset($this->provided['wafEnabled'])) {
            $data['wafEnabled'] = $this->wafEnabled;
        }

        if (isset($this->provided['wafExecutionMode'])) {
            $data['wafExecutionMode'] = $this->wafExecutionMode?->value;
        }

        if (isset($this->provided['wafDisabledRules'])) {
            $data['wafDisabledRules'] = $this->wafDisabledRules;
        }

        if (isset($this->provided['wafLogOnlyRules'])) {
            $data['wafLogOnlyRules'] = $this->wafLogOnlyRules;
        }

        if (isset($this->provided['wafCustomRuleOrder'])) {
            $data['wafCustomRuleOrder'] = $this->wafCustomRuleOrder;
        }

        if (isset($this->provided['wafRequestHeaderLoggingEnabled'])) {
            $data['wafRequestHeaderLoggingEnabled'] = $this->wafRequestHeaderLoggingEnabled;
        }

        if (isset($this->provided['requestBodyLoggingEnabled'])) {
            $data['requestBodyLoggingEnabled'] = $this->requestBodyLoggingEnabled;
        }

        if (isset($this->provided['wafRequestIgnoredHeaders'])) {
            $data['wafRequestIgnoredHeaders'] = $this->wafRequestIgnoredHeaders;
        }

        if (isset($this->provided['wafRealtimeThreatIntelligenceEnabled'])) {
            $data['wafRealtimeThreatIntelligenceEnabled'] = $this->wafRealtimeThreatIntelligenceEnabled;
        }

        if (isset($this->provided['wafProfileId'])) {
            $data['wafProfileId'] = $this->wafProfileId;
        }

        if (isset($this->provided['wafEngineConfig'])) {
            $data['wafEngineConfig'] = array_map(static fn(ZoneWafEngineSetting $item): array => $item->toArray(), $this->wafEngineConfig);
        }

        if (isset($this->provided['wafRequestBodyLimitAction'])) {
            $data['wafRequestBodyLimitAction'] = $this->wafRequestBodyLimitAction?->value;
        }

        if (isset($this->provided['wafResponseBodyLimitAction'])) {
            $data['wafResponseBodyLimitAction'] = $this->wafResponseBodyLimitAction?->value;
        }

        if (isset($this->provided['dDoSShieldSensitivity'])) {
            $data['dDoSShieldSensitivity'] = $this->dDoSShieldSensitivity?->value;
        }

        if (isset($this->provided['dDoSChallengeWindow'])) {
            $data['dDoSChallengeWindow'] = $this->dDoSChallengeWindow;
        }

        if (isset($this->provided['whitelabelResponsePages'])) {
            $data['whitelabelResponsePages'] = $this->whitelabelResponsePages;
        }

        return $data;
    }
}
