<?php

declare(strict_types=1);

// This file is generated by tools/generate.php from resources/specs/shield.json. Do not edit.

namespace GoSuccess\Bunny\Shield\Model;

use GoSuccess\Bunny\Model\Cast;
use GoSuccess\Bunny\Model\ResponseModel;
use GoSuccess\Bunny\Shield\Enum\AccessListAction;
use GoSuccess\Bunny\Shield\Enum\ShieldPlanType;

/** Schema: SuggestedAccessList */
final readonly class SuggestedAccessList implements ResponseModel
{
    public function __construct(
        public int $listId = 0,
        public ?string $name = null,
        public ?string $description = null,
        /**
         * 0 = Basic
         * 1 = Advanced
         * 2 = Business
         * 3 = Enterprise
         */
        public ?ShieldPlanType $requiredPlan = null,
        /**
         * 0 = None
         * 1 = Allow
         * 2 = Block
         * 3 = Challenge
         * 4 = Log
         * 5 = Bypass
         */
        public ?AccessListAction $action = null,
    ) {}

    public static function fromArray(array $data): static
    {
        return new self(
            listId: Cast::int($data['listId'] ?? null) ?? 0,
            name: Cast::string($data['name'] ?? null),
            description: Cast::string($data['description'] ?? null),
            requiredPlan: Cast::intEnum(ShieldPlanType::class, $data['requiredPlan'] ?? null),
            action: Cast::intEnum(AccessListAction::class, $data['action'] ?? null),
        );
    }
}
