<?php

declare(strict_types=1);

// This file is generated by tools/generate.php from resources/specs/shield.json. Do not edit.

namespace GoSuccess\Bunny\Shield\Model;

use GoSuccess\Bunny\Model\Cast;
use GoSuccess\Bunny\Model\ResponseModel;

/** Schema: TriggeredRuleRecommendationResponse */
final readonly class TriggeredRuleRecommendation implements ResponseModel
{
    public function __construct(
        public int $shieldZoneId = 0,
        public ?string $ruleId = null,
        public bool $success = false,
        public ?string $recommendation = null,
    ) {}

    public static function fromArray(array $data): static
    {
        return new self(
            shieldZoneId: Cast::int($data['shieldZoneId'] ?? null) ?? 0,
            ruleId: Cast::string($data['ruleId'] ?? null),
            success: Cast::bool($data['success'] ?? null) ?? false,
            recommendation: Cast::string($data['recommendation'] ?? null),
        );
    }
}
