<?php

declare(strict_types=1);

// This file is generated by tools/generate.php from resources/specs/shield.json. Do not edit.

namespace GoSuccess\Bunny\Shield\Model;

use GoSuccess\Bunny\Model\Cast;
use GoSuccess\Bunny\Model\ResponseModel;

/** Schema: GetTriggeredRulesResponse */
final readonly class TriggeredRules implements ResponseModel
{
    public function __construct(
        /** @var list<TriggeredRule> */
        public array $triggeredRules = [],
        public int $totalTriggeredRules = 0,
    ) {}

    public static function fromArray(array $data): static
    {
        return new self(
            triggeredRules: Cast::modelList(TriggeredRule::class, $data['triggeredRules'] ?? null),
            totalTriggeredRules: Cast::int($data['totalTriggeredRules'] ?? null) ?? 0,
        );
    }
}
