<?php

declare(strict_types=1);

// This file is generated by tools/generate.php from resources/specs/shield.json. Do not edit.

namespace GoSuccess\Bunny\Shield\Model;

use GoSuccess\Bunny\Model\Cast;
use GoSuccess\Bunny\Model\ResponseModel;

/** Schema: TriggeredRuleItem */
final readonly class TriggeredRule implements ResponseModel
{
    public function __construct(
        public ?string $ruleId = null,
        public ?string $ruleDescription = null,
        /** @var array<array-key, int> */
        public array $topTargetedUrls = [],
        public int $totalTriggeredRequests = 0,
        /** @var list<EventLog> */
        public array $ruleLogs = [],
    ) {}

    public static function fromArray(array $data): static
    {
        return new self(
            ruleId: Cast::string($data['ruleId'] ?? null),
            ruleDescription: Cast::string($data['ruleDescription'] ?? null),
            topTargetedUrls: Cast::mapOf($data['topTargetedUrls'] ?? null, Cast::int(...)),
            totalTriggeredRequests: Cast::int($data['totalTriggeredRequests'] ?? null) ?? 0,
            ruleLogs: Cast::modelList(EventLog::class, $data['ruleLogs'] ?? null),
        );
    }
}
