<?php

declare(strict_types=1);

// This file is generated by tools/generate.php from resources/specs/shield.json. Do not edit.

namespace GoSuccess\Bunny\Shield\Model;

use GoSuccess\Bunny\Model\Cast;
use GoSuccess\Bunny\Model\ResponseModel;

/** Schema: UploadScanning */
final readonly class UploadScanningCounts implements ResponseModel
{
    public function __construct(
        public int $loggedRequests = 0,
        public int $blockedRequests = 0,
        public int $filesScanned = 0,
    ) {}

    public static function fromArray(array $data): static
    {
        return new self(
            loggedRequests: Cast::int($data['loggedRequests'] ?? null) ?? 0,
            blockedRequests: Cast::int($data['blockedRequests'] ?? null) ?? 0,
            filesScanned: Cast::int($data['filesScanned'] ?? null) ?? 0,
        );
    }
}
