<?php

declare(strict_types=1);

// This file is generated by tools/generate.php from resources/specs/shield.json. Do not edit.

namespace GoSuccess\Bunny\Shield\Model;

use GoSuccess\Bunny\Model\Cast;
use GoSuccess\Bunny\Model\ResponseModel;
use GoSuccess\Bunny\Shield\Enum\UploadScanningScannerMode;

/** Schema: UploadScanningConfigurationState */
final readonly class UploadScanningConfiguration implements ResponseModel
{
    public function __construct(
        public int $shieldZoneId = 0,
        public bool $isEnabled = false,
        /**
         * 0 = Disabled
         * 1 = Log
         * 2 = Block
         */
        public ?UploadScanningScannerMode $csamScanningMode = null,
        /**
         * 0 = Disabled
         * 1 = Log
         * 2 = Block
         */
        public ?UploadScanningScannerMode $antivirusScanningMode = null,
    ) {}

    public static function fromArray(array $data): static
    {
        return new self(
            shieldZoneId: Cast::int($data['shieldZoneId'] ?? null) ?? 0,
            isEnabled: Cast::bool($data['isEnabled'] ?? null) ?? false,
            csamScanningMode: Cast::intEnum(UploadScanningScannerMode::class, $data['csamScanningMode'] ?? null),
            antivirusScanningMode: Cast::intEnum(UploadScanningScannerMode::class, $data['antivirusScanningMode'] ?? null),
        );
    }
}
