<?php

declare(strict_types=1);

// This file is generated by tools/generate.php from resources/specs/shield.json. Do not edit.

namespace GoSuccess\Bunny\Shield\Model;

use GoSuccess\Bunny\Model\Cast;
use GoSuccess\Bunny\Model\ResponseModel;

/** Schema: WafMappedEnumList */
final readonly class WafEnum implements ResponseModel
{
    public function __construct(
        public ?string $enumName = null,
        /** @var list<WafEnumValue> */
        public array $enumValues = [],
    ) {}

    public static function fromArray(array $data): static
    {
        return new self(
            enumName: Cast::string($data['enumName'] ?? null),
            enumValues: Cast::modelList(WafEnumValue::class, $data['enumValues'] ?? null),
        );
    }
}
