<?php

declare(strict_types=1);

// This file is generated by tools/generate.php from resources/specs/shield.json. Do not edit.

namespace GoSuccess\Bunny\Shield\Model;

use GoSuccess\Bunny\Model\Cast;
use GoSuccess\Bunny\Model\ResponseModel;

/** Schema: WafMappedEnum */
final readonly class WafEnumValue implements ResponseModel
{
    public function __construct(
        public ?bool $optionalInput = null,
        public bool $isPremium = false,
        public ?string $name = null,
        public int $value = 0,
        public WafSupportedValues $supportedValues = new WafSupportedValues(),
        public WafRecommendedOperator $recommendedOperator = new WafRecommendedOperator(),
    ) {}

    public static function fromArray(array $data): static
    {
        return new self(
            optionalInput: Cast::bool($data['optionalInput'] ?? null),
            isPremium: Cast::bool($data['isPremium'] ?? null) ?? false,
            name: Cast::string($data['name'] ?? null),
            value: Cast::int($data['value'] ?? null) ?? 0,
            supportedValues: Cast::model(WafSupportedValues::class, $data['supportedValues'] ?? null) ?? new WafSupportedValues(),
            recommendedOperator: Cast::model(WafRecommendedOperator::class, $data['recommendedOperator'] ?? null) ?? new WafRecommendedOperator(),
        );
    }
}
