<?php

declare(strict_types=1);

// This file is generated by tools/generate.php from resources/specs/shield.json. Do not edit.

namespace GoSuccess\Bunny\Shield\Model;

use GoSuccess\Bunny\Model\Cast;
use GoSuccess\Bunny\Model\ResponseModel;

/** Schema: WafRuleGroupModel */
final readonly class WafRuleGroup implements ResponseModel
{
    public function __construct(
        public int $id = 0,
        public ?string $name = null,
        public ?string $code = null,
        public ?string $fileName = null,
        public ?string $mainGroup = null,
        public ?string $ruleset = null,
        public ?string $description = null,
        /** @var list<WafRule> */
        public array $rules = [],
    ) {}

    public static function fromArray(array $data): static
    {
        return new self(
            id: Cast::int($data['id'] ?? null) ?? 0,
            name: Cast::string($data['name'] ?? null),
            code: Cast::string($data['code'] ?? null),
            fileName: Cast::string($data['fileName'] ?? null),
            mainGroup: Cast::string($data['mainGroup'] ?? null),
            ruleset: Cast::string($data['ruleset'] ?? null),
            description: Cast::string($data['description'] ?? null),
            rules: Cast::modelList(WafRule::class, $data['rules'] ?? null),
        );
    }
}
