<?php

declare(strict_types=1);

// This file is generated by tools/generate.php from resources/specs/shield.json. Do not edit.

namespace GoSuccess\Bunny\Shield\Model;

use GoSuccess\Bunny\Model\Cast;
use GoSuccess\Bunny\Model\ResponseModel;

/** Schema: WafRuleMetrics */
final readonly class WafRuleMetrics implements ResponseModel
{
    public function __construct(
        public int $totalTriggers = 0,
        public int $blockedRequests = 0,
        public int $loggedRequests = 0,
        public int $challengedRequests = 0,
        /** @var array<array-key, WafRuleCounts> */
        public array $overviewPastTwentyEightDays = [],
    ) {}

    public static function fromArray(array $data): static
    {
        return new self(
            totalTriggers: Cast::int($data['totalTriggers'] ?? null) ?? 0,
            blockedRequests: Cast::int($data['blockedRequests'] ?? null) ?? 0,
            loggedRequests: Cast::int($data['loggedRequests'] ?? null) ?? 0,
            challengedRequests: Cast::int($data['challengedRequests'] ?? null) ?? 0,
            overviewPastTwentyEightDays: Cast::mapOf($data['overviewPastTwentyEightDays'] ?? null, static fn(mixed $value): ?WafRuleCounts => Cast::model(WafRuleCounts::class, $value)),
        );
    }
}
