<?php

declare(strict_types=1);

// This file is generated by tools/generate.php from resources/specs/shield.json. Do not edit.

namespace GoSuccess\Bunny\Shield\Model;

use GoSuccess\Bunny\Model\Cast;
use GoSuccess\Bunny\Model\ResponseModel;
use GoSuccess\Bunny\Shield\Enum\WafRuleOperatorType;

/** Schema: WafRecommendedOperator */
final readonly class WafRecommendedOperator implements ResponseModel
{
    public function __construct(
        /**
         * 0 = BEGINSWITH
         * 1 = ENDSWITH
         * 2 = CONTAINS
         * 3 = CONTAINSWORD
         * 4 = STRMATCH
         * 5 = EQ
         * 6 = GE
         * 7 = GT
         * 8 = LE
         * 9 = LT
         * 12 = WITHIN
         * 14 = RX
         * 15 = STREQ
         * 17 = DETECTSQLI
         * 18 = DETECTXSS
         */
        public ?WafRuleOperatorType $operator = null,
        /** @var list<string> */
        public array $values = [],
    ) {}

    public static function fromArray(array $data): static
    {
        return new self(
            operator: Cast::intEnum(WafRuleOperatorType::class, $data['operator'] ?? null),
            values: Cast::listOf($data['values'] ?? null, Cast::string(...)),
        );
    }
}
