<?php

declare(strict_types=1);

// This file is generated by tools/generate.php from resources/specs/shield.json. Do not edit.

namespace GoSuccess\Bunny\Shield\Model;

use GoSuccess\Bunny\Model\Cast;
use GoSuccess\Bunny\Model\ResponseModel;

/** Schema: WafSupportedValues */
final readonly class WafSupportedValues implements ResponseModel
{
    public function __construct(
        /** @var list<string> */
        public array $values = [],
        public bool $editable = false,
    ) {}

    public static function fromArray(array $data): static
    {
        return new self(
            values: Cast::listOf($data['values'] ?? null, Cast::string(...)),
            editable: Cast::bool($data['editable'] ?? null) ?? false,
        );
    }
}
