<?php

declare(strict_types=1);

// This file is generated by tools/generate.php from resources/specs/shield.json. Do not edit.

namespace GoSuccess\Bunny\Shield\Model;

use GoSuccess\Bunny\Model\Cast;
use GoSuccess\Bunny\Model\ResponseModel;

/** Schema: ShieldZoneMetrics */
final readonly class ZoneMetrics implements ResponseModel
{
    public function __construct(
        public OverviewCounts $overview = new OverviewCounts(),
        public WafCounts $waf = new WafCounts(),
        /** @var array<array-key, OverviewCounts> */
        public array $overviewPastTwentyEightDays = [],
        public DdosCounts $dDoS = new DdosCounts(),
        /** @var array<array-key, DdosCounts> */
        public array $dDoSOverviewPastTwentyEightDays = [],
        public RateLimitCounts $ratelimit = new RateLimitCounts(),
        /** @var array<array-key, RateLimitCounts> */
        public array $ratelimitOverviewPastTwentyEightDays = [],
        public BotDetectionCounts $botDetection = new BotDetectionCounts(),
        /** @var array<array-key, BotDetectionCounts> */
        public array $botDetectionOverviewPastTwentyEightDays = [],
        public AccessListCounts $accessList = new AccessListCounts(),
        /** @var array<array-key, AccessListCounts> */
        public array $accessListOverviewPastTwentyEightDays = [],
        /** @var array<array-key, UploadScanningCounts> */
        public array $uploadScanningOverviewPastTwentyEightDays = [],
        public ApiGuardianCounts $apiGuardian = new ApiGuardianCounts(),
        /** @var array<array-key, ApiGuardianCounts> */
        public array $apiGuardianOverviewPastTwentyEightDays = [],
        public int $totalCleanRequestsLimit = 0,
        public int $totalBillableRequests = 0,
        public UploadScanningCounts $uploadScanning = new UploadScanningCounts(),
    ) {}

    public static function fromArray(array $data): static
    {
        return new self(
            overview: Cast::model(OverviewCounts::class, $data['overview'] ?? null) ?? new OverviewCounts(),
            waf: Cast::model(WafCounts::class, $data['waf'] ?? null) ?? new WafCounts(),
            overviewPastTwentyEightDays: Cast::mapOf($data['overviewPastTwentyEightDays'] ?? null, static fn(mixed $value): ?OverviewCounts => Cast::model(OverviewCounts::class, $value)),
            dDoS: Cast::model(DdosCounts::class, $data['dDoS'] ?? null) ?? new DdosCounts(),
            dDoSOverviewPastTwentyEightDays: Cast::mapOf($data['dDoSOverviewPastTwentyEightDays'] ?? null, static fn(mixed $value): ?DdosCounts => Cast::model(DdosCounts::class, $value)),
            ratelimit: Cast::model(RateLimitCounts::class, $data['ratelimit'] ?? null) ?? new RateLimitCounts(),
            ratelimitOverviewPastTwentyEightDays: Cast::mapOf($data['ratelimitOverviewPastTwentyEightDays'] ?? null, static fn(mixed $value): ?RateLimitCounts => Cast::model(RateLimitCounts::class, $value)),
            botDetection: Cast::model(BotDetectionCounts::class, $data['botDetection'] ?? null) ?? new BotDetectionCounts(),
            botDetectionOverviewPastTwentyEightDays: Cast::mapOf($data['botDetectionOverviewPastTwentyEightDays'] ?? null, static fn(mixed $value): ?BotDetectionCounts => Cast::model(BotDetectionCounts::class, $value)),
            accessList: Cast::model(AccessListCounts::class, $data['accessList'] ?? null) ?? new AccessListCounts(),
            accessListOverviewPastTwentyEightDays: Cast::mapOf($data['accessListOverviewPastTwentyEightDays'] ?? null, static fn(mixed $value): ?AccessListCounts => Cast::model(AccessListCounts::class, $value)),
            uploadScanningOverviewPastTwentyEightDays: Cast::mapOf($data['uploadScanningOverviewPastTwentyEightDays'] ?? null, static fn(mixed $value): ?UploadScanningCounts => Cast::model(UploadScanningCounts::class, $value)),
            apiGuardian: Cast::model(ApiGuardianCounts::class, $data['apiGuardian'] ?? null) ?? new ApiGuardianCounts(),
            apiGuardianOverviewPastTwentyEightDays: Cast::mapOf($data['apiGuardianOverviewPastTwentyEightDays'] ?? null, static fn(mixed $value): ?ApiGuardianCounts => Cast::model(ApiGuardianCounts::class, $value)),
            totalCleanRequestsLimit: Cast::int($data['totalCleanRequestsLimit'] ?? null) ?? 0,
            totalBillableRequests: Cast::int($data['totalBillableRequests'] ?? null) ?? 0,
            uploadScanning: Cast::model(UploadScanningCounts::class, $data['uploadScanning'] ?? null) ?? new UploadScanningCounts(),
        );
    }
}
