<?php

declare(strict_types=1);

// This file is generated by tools/generate.php from resources/specs/shield.json. Do not edit.

namespace GoSuccess\Bunny\Shield\Model;

use GoSuccess\Bunny\Model\Cast;
use GoSuccess\Bunny\Model\ResponseModel;

/** Schema: ShieldZoneRatelimitMetrics */
final readonly class ZoneRateLimitMetrics implements ResponseModel
{
    public function __construct(
        public int $ratelimitId = 0,
        public ZoneRateLimitCounts $overview = new ZoneRateLimitCounts(),
        /** @var array<array-key, ZoneRateLimitCounts> */
        public array $ratelimitOverviewPastTwentyEightDays = [],
    ) {}

    public static function fromArray(array $data): static
    {
        return new self(
            ratelimitId: Cast::int($data['ratelimitId'] ?? null) ?? 0,
            overview: Cast::model(ZoneRateLimitCounts::class, $data['overview'] ?? null) ?? new ZoneRateLimitCounts(),
            ratelimitOverviewPastTwentyEightDays: Cast::mapOf($data['ratelimitOverviewPastTwentyEightDays'] ?? null, static fn(mixed $value): ?ZoneRateLimitCounts => Cast::model(ZoneRateLimitCounts::class, $value)),
        );
    }
}
