<?php

declare(strict_types=1);

// This file is generated by tools/generate.php from resources/specs/stream.json. Do not edit.

namespace GoSuccess\Bunny\Stream;

use GoSuccess\Bunny\ClientOptions;
use GoSuccess\Bunny\Http\Connection;
use GoSuccess\Bunny\Http\CurlHttpClient;
use GoSuccess\Bunny\Http\HttpClient;
use GoSuccess\Bunny\RateLimit\NullRateLimiter;
use GoSuccess\Bunny\RateLimit\RateLimiter;
use GoSuccess\Bunny\Stream\Resource\CollectionResource;
use GoSuccess\Bunny\Stream\Resource\StatisticsResource;
use GoSuccess\Bunny\Stream\Resource\VideoResource;
use SensitiveParameter;

/**
 * Client for the bunny.net Stream API (`https://video.bunnycdn.com`).
 *
 * Resources are created on first access, so unused ones cost nothing.
 */
final class StreamClient
{
    public const string DEFAULT_BASE_URI = 'https://video.bunnycdn.com';

    /** Videos of the library: uploads, metadata, captions, thumbnails, encoding and playback data. */
    public private(set) VideoResource $videos {
        get => $this->videos ??= new VideoResource($this->connection, $this->libraryId);
    }

    /** Collections that group the videos of the library. */
    public private(set) CollectionResource $collections {
        get => $this->collections ??= new CollectionResource($this->connection, $this->libraryId);
    }

    /** View and watch time statistics of the library or of one video. */
    public private(set) StatisticsResource $statistics {
        get => $this->statistics ??= new StatisticsResource($this->connection, $this->libraryId);
    }

    private readonly Connection $connection;

    /**
     * @param int             $libraryId   The ID of the video library.
     * @param string          $apiKey      The API key of the video library (dashboard → Stream → library → API), not the account API key.
     * @param ClientOptions   $options     Timeouts, retries and user agent.
     * @param HttpClient|null $httpClient  Custom transport; defaults to the built-in cURL transport.
     * @param RateLimiter     $rateLimiter Client-side throttling; disabled by default.
     * @param string          $baseUri     Base URI of the API.
     */
    public function __construct(
        public readonly int $libraryId,
        #[SensitiveParameter]
        string $apiKey,
        ClientOptions $options = new ClientOptions(),
        ?HttpClient $httpClient = null,
        RateLimiter $rateLimiter = new NullRateLimiter(),
        string $baseUri = self::DEFAULT_BASE_URI,
    ) {
        $this->connection = new Connection(
            $baseUri,
            $apiKey,
            $options,
            $httpClient ?? new CurlHttpClient($options->timeout, $options->connectTimeout),
            $rateLimiter,
        );
    }
}
