<?php

declare(strict_types=1);

// This file is generated by tools/generate.php from resources/specs/shield.json. Do not edit.

namespace GoSuccess\Bunny\Shield\Resource;

use GoSuccess\Bunny\Http\Method;
use GoSuccess\Bunny\Model\Cast;
use GoSuccess\Bunny\Resource\AbstractResource;
use GoSuccess\Bunny\Shield\Enum\AccessListAction;
use GoSuccess\Bunny\Shield\Enum\AccessListType;
use GoSuccess\Bunny\Shield\Model\AccessListConfiguration;
use GoSuccess\Bunny\Shield\Model\AccessListOverview;
use GoSuccess\Bunny\Shield\Model\CustomAccessList;

/** Managed and custom access lists of Shield zones. */
final class AccessListResource extends AbstractResource
{
    /**
     * Get all Access Lists available for a Shield Zone
     *
     * `GET /shield/shield-zone/{shieldZoneId}/access-lists`
     *
     * @param int $shieldZoneId The ID of the Shield Zone to which the Access Lists belong.
     */
    public function list(int $shieldZoneId): AccessListOverview
    {
        $data = $this->connection->json(Method::Get, "shield/shield-zone/{$shieldZoneId}/access-lists");

        return self::toModel(AccessListOverview::class, $data);
    }

    /**
     * Get the specified Custom Access List associated with a Shield Zone
     *
     * `GET /shield/shield-zone/{shieldZoneId}/access-lists/{id}`
     *
     * @param int $shieldZoneId The ID of the Shield Zone to which the Custom Access List belongs.
     * @param int $id           The ID of the Custom Access List to retrieve.
     */
    public function get(int $shieldZoneId, int $id): CustomAccessList
    {
        $data = $this->connection->json(Method::Get, "shield/shield-zone/{$shieldZoneId}/access-lists/{$id}");

        return self::toModel(CustomAccessList::class, self::expectObject($data)['data'] ?? null);
    }

    /**
     * Create a new Custom Access List associated with a Shield Zone
     *
     * A new list starts disabled, with the action Log. Enable it and choose its action with configure(), which takes the configurationId that list() reports for the list, not the ID returned here.
     *
     * `POST /shield/shield-zone/{shieldZoneId}/access-lists`
     *
     * @param int            $shieldZoneId The ID of the Shield Zone to which the Custom Access List will be associated.
     * @param string|null    $name         The display name for the new access list.
     * @param AccessListType $type         0 = IP 1 = CIDR 2 = ASN 3 = Country 4 = Organization 5 = JA4
     * @param string|null    $content      The initial content for the access list with entries separated by newlines.
     * @param string|null    $description  Optional description of the access list's purpose or contents.
     * @param string|null    $checksum     SHA-256 checksum of the content for integrity verification. If null, it will be automatically calculated.
     */
    public function create(
        int $shieldZoneId,
        ?string $name,
        AccessListType $type,
        ?string $content,
        ?string $description = null,
        ?string $checksum = null,
    ): CustomAccessList {
        $body = [
            'name' => $name,
            'type' => $type->value,
            'content' => $content,
        ];

        if ($description !== null) {
            $body['description'] = $description;
        }

        if ($checksum !== null) {
            $body['checksum'] = $checksum;
        }

        $data = $this->connection->json(Method::Post, "shield/shield-zone/{$shieldZoneId}/access-lists", body: $body);

        return self::toModel(CustomAccessList::class, self::expectObject($data)['data'] ?? null);
    }

    /**
     * Update the specified Custom Access List associated with a Shield Zone
     *
     * `PATCH /shield/shield-zone/{shieldZoneId}/access-lists/{id}`
     *
     * @param int         $shieldZoneId The ID of the Shield Zone to which the Custom Access List belongs.
     * @param int         $id           The ID of the Custom Access List to update.
     * @param string|null $name         The new display name for the access list. If null, the current name is preserved.
     * @param string|null $content      The new content for the access list with entries separated by newlines. If null, the current content is preserved.
     * @param string|null $checksum     SHA-256 checksum of the new content for integrity verification. If null, it will be automatically calculated.
     */
    public function update(
        int $shieldZoneId,
        int $id,
        ?string $name = null,
        ?string $content = null,
        ?string $checksum = null,
    ): CustomAccessList {
        $body = [];

        if ($name !== null) {
            $body['name'] = $name;
        }

        if ($content !== null) {
            $body['content'] = $content;
        }

        if ($checksum !== null) {
            $body['checksum'] = $checksum;
        }

        $data = $this->connection->json(Method::Patch, "shield/shield-zone/{$shieldZoneId}/access-lists/{$id}", body: $body);

        return self::toModel(CustomAccessList::class, self::expectObject($data)['data'] ?? null);
    }

    /**
     * Delete the specified Custom Access List associated with a Shield Zone
     *
     * `DELETE /shield/shield-zone/{shieldZoneId}/access-lists/{id}`
     *
     * @param int $shieldZoneId The ID of the Shield Zone to which the Custom Access List belongs.
     * @param int $id           The ID of the Custom Access List to delete.
     */
    public function delete(int $shieldZoneId, int $id): void
    {
        $this->connection->json(Method::Delete, "shield/shield-zone/{$shieldZoneId}/access-lists/{$id}");
    }

    /**
     * Update Access List Configuration for a Shield Zone
     *
     * Takes the configuration ID that list() reports as configurationId for every managed and custom list; it differs from the list ID that create() and get() return.
     *
     * `PATCH /shield/shield-zone/{shieldZoneId}/access-lists/configurations/{id}`
     *
     * @param int                   $shieldZoneId The ID of the Shield Zone to which the Access List Configuration belongs.
     * @param int                   $id           The ID of the Access List Configuration to update.
     * @param bool|null             $isEnabled    Whether the access list should be enabled or disabled. If null, the current state is preserved.
     * @param AccessListAction|null $action       0 = None 1 = Allow 2 = Block 3 = Challenge 4 = Log 5 = Bypass
     */
    public function configure(
        int $shieldZoneId,
        int $id,
        ?bool $isEnabled = null,
        ?AccessListAction $action = null,
    ): AccessListConfiguration {
        $body = [];

        if ($isEnabled !== null) {
            $body['isEnabled'] = $isEnabled;
        }

        if ($action !== null) {
            $body['action'] = $action->value;
        }

        $data = $this->connection->json(Method::Patch, "shield/shield-zone/{$shieldZoneId}/access-lists/configurations/{$id}", body: $body);

        return self::toModel(AccessListConfiguration::class, self::expectObject($data)['data'] ?? null);
    }

    /**
     * Get all Access Lists API enumeration types and their values
     *
     * `GET /shield/shield-zone/{shieldZoneId}/access-lists/enums`
     *
     * @param int $shieldZoneId
     *
     * @return array<array-key, array<array-key, string>>
     */
    public function enums(int $shieldZoneId): array
    {
        $data = $this->connection->json(Method::Get, "shield/shield-zone/{$shieldZoneId}/access-lists/enums");

        return Cast::mapOf($data, static fn(mixed $value): array => Cast::mapOf($value, Cast::string(...)));
    }
}
