<?php

declare(strict_types=1);

// This file is generated by tools/generate.php from resources/specs/shield.json. Do not edit.

namespace GoSuccess\Bunny\Shield\Resource;

use GoSuccess\Bunny\Http\Method;
use GoSuccess\Bunny\Model\Cast;
use GoSuccess\Bunny\Resource\AbstractResource;
use GoSuccess\Bunny\Shield\Enum\BotCategorizationAction;
use GoSuccess\Bunny\Shield\Enum\BotCategory;
use GoSuccess\Bunny\Shield\Enum\BotCategoryAction;
use GoSuccess\Bunny\Shield\Enum\BotDetectionExecutionMode;
use GoSuccess\Bunny\Shield\Model\BotCategorization;
use GoSuccess\Bunny\Shield\Model\BotCategorizationGroup;
use GoSuccess\Bunny\Shield\Model\BotCategorySetting;
use GoSuccess\Bunny\Shield\Model\BotDetectionConfiguration;
use GoSuccess\Bunny\Shield\Model\BrowserFingerprintConfiguration;
use GoSuccess\Bunny\Shield\Model\IpAddressConfiguration;
use GoSuccess\Bunny\Shield\Model\RequestIntegrityConfiguration;

/** Bot detection and the handling of known bots and bot categories. */
final class BotDetectionResource extends AbstractResource
{
    /**
     * Your current Bot Detection configuration
     *
     * `GET /shield/shield-zone/{shieldZoneId}/bot-detection`
     *
     * @param int $shieldZoneId
     */
    public function get(int $shieldZoneId): BotDetectionConfiguration
    {
        $data = $this->connection->json(Method::Get, "shield/shield-zone/{$shieldZoneId}/bot-detection");

        return self::toModel(BotDetectionConfiguration::class, self::expectObject($data)['data'] ?? null);
    }

    /**
     * Update your current Bot Detection configuration
     *
     * `PATCH /shield/shield-zone/{shieldZoneId}/bot-detection`
     *
     * @param int                                  $shieldZoneId
     * @param BotDetectionExecutionMode|null       $executionMode      0 = LogOnly 1 = Challenge
     * @param RequestIntegrityConfiguration|null   $requestIntegrity
     * @param IpAddressConfiguration|null          $ipAddress
     * @param BrowserFingerprintConfiguration|null $browserFingerprint
     */
    public function update(
        int $shieldZoneId,
        ?BotDetectionExecutionMode $executionMode = null,
        ?RequestIntegrityConfiguration $requestIntegrity = null,
        ?IpAddressConfiguration $ipAddress = null,
        ?BrowserFingerprintConfiguration $browserFingerprint = null,
    ): BotDetectionConfiguration {
        $body = [
            'shieldZoneId' => $shieldZoneId,
        ];

        if ($executionMode !== null) {
            $body['executionMode'] = $executionMode->value;
        }

        if ($requestIntegrity !== null) {
            $body['requestIntegrity'] = $requestIntegrity->toArray();
        }

        if ($ipAddress !== null) {
            $body['ipAddress'] = $ipAddress->toArray();
        }

        if ($browserFingerprint !== null) {
            $body['browserFingerprint'] = $browserFingerprint->toArray();
        }

        $data = $this->connection->json(Method::Patch, "shield/shield-zone/{$shieldZoneId}/bot-detection", body: $body);

        return self::toModel(BotDetectionConfiguration::class, self::expectObject($data)['data'] ?? null);
    }

    /**
     * List bots available for explicit allow/block configuration on this Shield Zone, grouped by category.
     *
     * `GET /shield/shield-zone/{shieldZoneId}/bot-categorization`
     *
     * @param int $shieldZoneId
     *
     * @return list<BotCategorizationGroup>
     */
    public function categorization(int $shieldZoneId): array
    {
        $data = $this->connection->json(Method::Get, "shield/shield-zone/{$shieldZoneId}/bot-categorization");

        return Cast::modelList(BotCategorizationGroup::class, self::expectObject($data)['categories'] ?? null);
    }

    /**
     * Set or clear the action applied to a categorised bot for this Shield Zone.
     *
     * `PUT /shield/shield-zone/{shieldZoneId}/bot-categorization/bots/{botId}`
     *
     * @param int                     $shieldZoneId
     * @param int                     $botId
     * @param BotCategorizationAction $action       0 = None 1 = Block 2 = Allow 3 = Ignore
     */
    public function setBotAction(int $shieldZoneId, int $botId, BotCategorizationAction $action): BotCategorization
    {
        $body = [
            'action' => $action->value,
        ];

        $data = $this->connection->json(Method::Put, "shield/shield-zone/{$shieldZoneId}/bot-categorization/bots/{$botId}", body: $body);

        return self::toModel(BotCategorization::class, self::expectObject($data)['data'] ?? null);
    }

    /**
     * Set or clear the action applied to every bot in a category for this Shield Zone.
     *
     * `PUT /shield/shield-zone/{shieldZoneId}/bot-categorization/categories/{category}`
     *
     * @param int               $shieldZoneId
     * @param BotCategory       $category     0 = None 1 = SEO 2 = AIScraper 3 = AITool 4 = Tool 5 = Ads 6 = Preview 7 = Social 255 = System
     * @param BotCategoryAction $action       0 = None 1 = Block 2 = Allow
     */
    public function setCategoryAction(int $shieldZoneId, BotCategory $category, BotCategoryAction $action): BotCategorySetting
    {
        $body = [
            'action' => $action->value,
        ];

        $data = $this->connection->json(Method::Put, "shield/shield-zone/{$shieldZoneId}/bot-categorization/categories/{$this->segment($category)}", body: $body);

        return self::toModel(BotCategorySetting::class, self::expectObject($data)['data'] ?? null);
    }
}
