<?php

declare(strict_types=1);

// This file is generated by tools/generate.php from resources/specs/shield.json. Do not edit.

namespace GoSuccess\Bunny\Shield\Resource;

use GoSuccess\Bunny\Resource\AbstractResource;
use GoSuccess\Bunny\Shield\Resource\Handwritten\CustomPageOperations;

/** Custom HTML pages shown to blocked, challenged or rate-limited visitors. */
final class CustomPageResource extends AbstractResource
{
    use CustomPageOperations;
}
