<?php

declare(strict_types=1);

// This file is generated by tools/generate.php from resources/specs/shield.json. Do not edit.

namespace GoSuccess\Bunny\Shield\Resource;

use GoSuccess\Bunny\Http\Method;
use GoSuccess\Bunny\Model\Cast;
use GoSuccess\Bunny\Pagination\Page;
use GoSuccess\Bunny\Pagination\Paginator;
use GoSuccess\Bunny\Resource\AbstractResource;
use GoSuccess\Bunny\Shield\Model\CustomRule;
use GoSuccess\Bunny\Shield\Model\CustomRuleConfiguration;
use GoSuccess\Bunny\Shield\Pagination;

/** Custom WAF rules of Shield zones. */
final class CustomRuleResource extends AbstractResource
{
    /**
     * Retrieve custom WAF rules configured for the specified Shield Zone
     *
     * `GET /shield/waf/custom-rules/{shieldZoneId}`
     *
     * @param int $shieldZoneId The ID of the Shield Zone associated with the Custom WAF Rules.
     * @param int $page         The page to return, starting at 1.
     * @param int $perPage      The number of items per page.
     *
     * @return Page<CustomRule>
     */
    public function list(int $shieldZoneId, int $page = 1, int $perPage = 100): Page
    {
        $data = self::expectObject($this->connection->json(Method::Get, "shield/waf/custom-rules/{$shieldZoneId}", [
            'page' => $page,
            'perPage' => $perPage,
        ]));

        return Pagination::page($data, Cast::modelList(CustomRule::class, $data['data'] ?? null));
    }

    /**
     * Iterate lazily over every item of list(), across all pages.
     *
     * `GET /shield/waf/custom-rules/{shieldZoneId}`
     *
     * @param int $shieldZoneId The ID of the Shield Zone associated with the Custom WAF Rules.
     * @param int $perPage      The number of items per page.
     *
     * @return Paginator<CustomRule>
     */
    public function all(int $shieldZoneId, int $perPage = 1000): Paginator
    {
        return new Paginator(fn(int|string|null $position): Page => $this->list(
            shieldZoneId: $shieldZoneId,
            page: \is_int($position) ? $position : 1,
            perPage: $perPage,
        ));
    }

    /**
     * Retrieve a specific custom WAF rule
     *
     * `GET /shield/waf/custom-rule/{id}`
     *
     * @param int $id The ID of the Custom WAF Rule.
     */
    public function get(int $id): CustomRule
    {
        $data = $this->connection->json(Method::Get, "shield/waf/custom-rule/{$id}");

        return self::toModel(CustomRule::class, $data);
    }

    /**
     * Create a new custom WAF rule
     *
     * `POST /shield/waf/custom-rule`
     *
     * @param int                          $shieldZoneId
     * @param string|null                  $ruleName
     * @param string|null                  $ruleDescription
     * @param CustomRuleConfiguration|null $ruleConfiguration
     */
    public function create(
        int $shieldZoneId,
        ?string $ruleName = null,
        ?string $ruleDescription = null,
        ?CustomRuleConfiguration $ruleConfiguration = null,
    ): CustomRule {
        $body = [
            'shieldZoneId' => $shieldZoneId,
        ];

        if ($ruleName !== null) {
            $body['ruleName'] = $ruleName;
        }

        if ($ruleDescription !== null) {
            $body['ruleDescription'] = $ruleDescription;
        }

        if ($ruleConfiguration !== null) {
            $body['ruleConfiguration'] = $ruleConfiguration->toArray();
        }

        $data = $this->connection->json(Method::Post, 'shield/waf/custom-rule', body: $body);

        return self::toModel(CustomRule::class, $data);
    }

    /**
     * Update an existing custom WAF rule
     *
     * `PATCH /shield/waf/custom-rule/{id}`
     *
     * @param int                          $id                The ID of the Custom WAF Rule you would like to update.
     * @param string|null                  $ruleName
     * @param string|null                  $ruleDescription
     * @param CustomRuleConfiguration|null $ruleConfiguration
     */
    public function update(
        int $id,
        ?string $ruleName = null,
        ?string $ruleDescription = null,
        ?CustomRuleConfiguration $ruleConfiguration = null,
    ): CustomRule {
        $body = [];

        if ($ruleName !== null) {
            $body['ruleName'] = $ruleName;
        }

        if ($ruleDescription !== null) {
            $body['ruleDescription'] = $ruleDescription;
        }

        if ($ruleConfiguration !== null) {
            $body['ruleConfiguration'] = $ruleConfiguration->toArray();
        }

        $data = $this->connection->json(Method::Patch, "shield/waf/custom-rule/{$id}", body: $body);

        return self::toModel(CustomRule::class, $data);
    }

    /**
     * Update an existing custom WAF rule
     *
     * `PUT /shield/waf/custom-rule/{id}`
     *
     * @param int                          $id                The ID of the Custom WAF Rule you would like to update.
     * @param string|null                  $ruleName
     * @param string|null                  $ruleDescription
     * @param CustomRuleConfiguration|null $ruleConfiguration
     */
    public function replace(
        int $id,
        ?string $ruleName = null,
        ?string $ruleDescription = null,
        ?CustomRuleConfiguration $ruleConfiguration = null,
    ): CustomRule {
        $body = [];

        if ($ruleName !== null) {
            $body['ruleName'] = $ruleName;
        }

        if ($ruleDescription !== null) {
            $body['ruleDescription'] = $ruleDescription;
        }

        if ($ruleConfiguration !== null) {
            $body['ruleConfiguration'] = $ruleConfiguration->toArray();
        }

        $data = $this->connection->json(Method::Put, "shield/waf/custom-rule/{$id}", body: $body);

        return self::toModel(CustomRule::class, $data);
    }

    /**
     * Delete a custom WAF rule
     *
     * `DELETE /shield/waf/custom-rule/{id}`
     *
     * @param int $id The ID of the Custom WAF Rule that should be deleted.
     */
    public function delete(int $id): void
    {
        $this->connection->json(Method::Delete, "shield/waf/custom-rule/{$id}");
    }
}
