<?php

declare(strict_types=1);

// This file is generated by tools/generate.php from resources/specs/shield.json. Do not edit.

namespace GoSuccess\Bunny\Shield\Resource;

use GoSuccess\Bunny\Resource\AbstractResource;
use GoSuccess\Bunny\Shield\Resource\Handwritten\EventLogOperations;

/** Event logs of the requests Shield acted on. */
final class EventLogResource extends AbstractResource
{
    use EventLogOperations;
}
