<?php

declare(strict_types=1);

// This file is generated by tools/generate.php from resources/specs/shield.json. Do not edit.

namespace GoSuccess\Bunny\Shield\Resource;

use DateTimeInterface;
use GoSuccess\Bunny\Http\Method;
use GoSuccess\Bunny\Model\Cast;
use GoSuccess\Bunny\Resource\AbstractResource;
use GoSuccess\Bunny\Shield\Enum\MetricsOverviewResolution;
use GoSuccess\Bunny\Shield\Model\ApiGuardianEndpointMetrics;
use GoSuccess\Bunny\Shield\Model\ApiGuardianMetrics;
use GoSuccess\Bunny\Shield\Model\BotDetectionMetrics;
use GoSuccess\Bunny\Shield\Model\DetailedMetrics;
use GoSuccess\Bunny\Shield\Model\MonthlyOverages;
use GoSuccess\Bunny\Shield\Model\RateLimitRuleMetrics;
use GoSuccess\Bunny\Shield\Model\UploadScanningMetrics;
use GoSuccess\Bunny\Shield\Model\WafRuleMetrics;
use GoSuccess\Bunny\Shield\Model\ZoneMetrics;
use GoSuccess\Bunny\Shield\Model\ZoneRateLimitMetrics;

/** Request metrics and billing overages of Shield zones. */
final class MetricsResource extends AbstractResource
{
    /**
     * Get an overview of metrics for the specified Shield Zone
     *
     * `GET /shield/metrics/overview/{shieldZoneId}`
     *
     * @param int $shieldZoneId The ID of the Shield Zone.
     */
    public function overview(int $shieldZoneId): ZoneMetrics
    {
        $data = $this->connection->json(Method::Get, "shield/metrics/overview/{$shieldZoneId}");

        return self::toModel(ZoneMetrics::class, self::expectObject($data)['data'] ?? null);
    }

    /**
     * Get a detailed metrics overview for the specified Shield Zone within the selected time range and resolution
     *
     * `GET /shield/metrics/overview/{shieldZoneId}/detailed`
     *
     * @param int                            $shieldZoneId The ID of the Shield Zone.
     * @param DateTimeInterface|null         $startDate
     * @param DateTimeInterface|null         $endDate
     * @param MetricsOverviewResolution|null $resolution   0 = Auto 1 = TwoMinutes 2 = TenMinutes 3 = Hourly 4 = Daily 5 = Weekly 6 = Monthly
     */
    public function detailed(
        int $shieldZoneId,
        ?DateTimeInterface $startDate = null,
        ?DateTimeInterface $endDate = null,
        ?MetricsOverviewResolution $resolution = null,
    ): DetailedMetrics {
        $data = $this->connection->json(Method::Get, "shield/metrics/overview/{$shieldZoneId}/detailed", [
            'StartDate' => $startDate,
            'EndDate' => $endDate,
            'Resolution' => $resolution,
        ]);

        return self::toModel(DetailedMetrics::class, self::expectObject($data)['data'] ?? null);
    }

    /**
     * Get the overage breakdown for the specified Shield Zone for a given month, segmented by billing plan changes
     *
     * The API answers 404 for a month without billing data of the zone, e.g. before the zone existed.
     *
     * `GET /shield/metrics/overages/{shieldZoneId}`
     *
     * @param int $shieldZoneId The ID of the Shield Zone.
     * @param int $year         The calendar year to query.
     * @param int $month        The calendar month (1-12) to query.
     */
    public function overages(int $shieldZoneId, int $year, int $month): MonthlyOverages
    {
        $data = $this->connection->json(Method::Get, "shield/metrics/overages/{$shieldZoneId}", [
            'year' => $year,
            'month' => $month,
        ]);

        return self::toModel(MonthlyOverages::class, $data);
    }

    /**
     * Get aggregated rate limit metrics for the specified Shield Zone
     *
     * `GET /shield/metrics/rate-limits/{shieldZoneId}`
     *
     * @param int $shieldZoneId The ID of the Shield Zone.
     *
     * @return list<ZoneRateLimitMetrics>
     */
    public function rateLimits(int $shieldZoneId): array
    {
        $data = $this->connection->json(Method::Get, "shield/metrics/rate-limits/{$shieldZoneId}");

        return Cast::modelList(ZoneRateLimitMetrics::class, self::expectObject($data)['data'] ?? null);
    }

    /**
     * Get detailed metrics for the specified Rate Limit
     *
     * `GET /shield/metrics/rate-limit/{id}`
     *
     * @param int $id The ID of the Rate limit.
     */
    public function rateLimit(int $id): RateLimitRuleMetrics
    {
        $data = $this->connection->json(Method::Get, "shield/metrics/rate-limit/{$id}");

        return self::toModel(RateLimitRuleMetrics::class, self::expectObject($data)['data'] ?? null);
    }

    /**
     * Get metrics for a specific WAF Rule within the specified Shield Zone
     *
     * `GET /shield/metrics/shield-zone/{shieldZoneId}/waf-rule/{ruleId}`
     *
     * @param int    $shieldZoneId The ID of the Shield Zone.
     * @param string $ruleId       The ID of the WAF Rule.
     */
    public function wafRule(int $shieldZoneId, string $ruleId): WafRuleMetrics
    {
        $data = $this->connection->json(Method::Get, "shield/metrics/shield-zone/{$shieldZoneId}/waf-rule/{$this->segment($ruleId)}");

        return self::toModel(WafRuleMetrics::class, self::expectObject($data)['data'] ?? null);
    }

    /**
     * Get bot detection metrics for the specified Shield Zone
     *
     * `GET /shield/metrics/shield-zone/{shieldZoneId}/bot-detection`
     *
     * @param int $shieldZoneId The ID of the Shield Zone.
     */
    public function botDetection(int $shieldZoneId): BotDetectionMetrics
    {
        $data = $this->connection->json(Method::Get, "shield/metrics/shield-zone/{$shieldZoneId}/bot-detection");

        return self::toModel(BotDetectionMetrics::class, self::expectObject($data)['data'] ?? null);
    }

    /**
     * Get upload scanning metrics for the specified Shield Zone
     *
     * `GET /shield/metrics/shield-zone/{shieldZoneId}/upload-scanning`
     *
     * @param int $shieldZoneId The ID of the Shield Zone.
     */
    public function uploadScanning(int $shieldZoneId): UploadScanningMetrics
    {
        $data = $this->connection->json(Method::Get, "shield/metrics/shield-zone/{$shieldZoneId}/upload-scanning");

        return self::toModel(UploadScanningMetrics::class, self::expectObject($data)['data'] ?? null);
    }

    /**
     * Get API Guardian metrics for the specified Shield Zone
     *
     * `GET /shield/metrics/shield-zone/{shieldZoneId}/api-guardian`
     *
     * @param int $shieldZoneId The ID of the Shield Zone.
     */
    public function apiGuardian(int $shieldZoneId): ApiGuardianMetrics
    {
        $data = $this->connection->json(Method::Get, "shield/metrics/shield-zone/{$shieldZoneId}/api-guardian");

        return self::toModel(ApiGuardianMetrics::class, self::expectObject($data)['data'] ?? null);
    }

    /**
     * Get metrics for a specific API Guardian endpoint within the specified Shield Zone
     *
     * `GET /shield/metrics/shield-zone/{shieldZoneId}/api-guardian/endpoint/{endpointId}`
     *
     * @param int $shieldZoneId The ID of the Shield Zone.
     * @param int $endpointId   The ID of the API Guardian Endpoint.
     */
    public function apiGuardianEndpoint(int $shieldZoneId, int $endpointId): ApiGuardianEndpointMetrics
    {
        $data = $this->connection->json(Method::Get, "shield/metrics/shield-zone/{$shieldZoneId}/api-guardian/endpoint/{$endpointId}");

        return self::toModel(ApiGuardianEndpointMetrics::class, self::expectObject($data)['data'] ?? null);
    }
}
